/*
 Highcharts JS v8.0.4 (2020-04-02)

 Annotations module

 (c) 2009-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(f){"object"===typeof module&&module.exports?(f["default"]=f,module.exports=f):"function"===typeof define&&define.amd?define("highcharts/modules/annotations",["highcharts"],function(l){f(l);f.Highcharts=l;return f}):f("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(f){function l(d,b,f,k){d.hasOwnProperty(b)||(d[b]=k.apply(null,f))}f=f?f._modules:{};l(f,"annotations/eventEmitterMixin.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,b){var f=b.addEvent,k=b.fireEvent,
r=b.inArray,p=b.objectEach,c=b.pick,z=b.removeEvent;return{addEvents:function(){var a=this,g=function(e){f(e,"mousedown",function(h){a.onMouseDown(h)})};g(this.graphic.element);(a.labels||[]).forEach(function(e){e.options.useHTML&&g(e.graphic.text.element)});p(a.options.events,function(e,h){var g=function(g){"click"===h&&a.cancelClick||e.call(a,a.chart.pointer.normalize(g),a.target)};if(-1===r(h,a.nonDOMEvents||[]))a.graphic.on(h,g);else f(a,h,g)});if(a.options.draggable&&(f(a,"drag",a.onDrag),!a.graphic.renderer.styledMode)){var c=
{cursor:{x:"ew-resize",y:"ns-resize",xy:"move"}[a.options.draggable]};a.graphic.css(c);(a.labels||[]).forEach(function(e){e.options.useHTML&&e.graphic.text.css(c)})}a.isUpdating||k(a,"add")},removeDocEvents:function(){this.removeDrag&&(this.removeDrag=this.removeDrag());this.removeMouseUp&&(this.removeMouseUp=this.removeMouseUp())},onMouseDown:function(a){var g=this,b=g.chart.pointer;a.preventDefault&&a.preventDefault();if(2!==a.button){a=b.normalize(a);var e=a.chartX;var h=a.chartY;g.cancelClick=
!1;g.chart.hasDraggedAnnotation=!0;g.removeDrag=f(d.doc,"mousemove",function(a){g.hasDragged=!0;a=b.normalize(a);a.prevChartX=e;a.prevChartY=h;k(g,"drag",a);e=a.chartX;h=a.chartY});g.removeMouseUp=f(d.doc,"mouseup",function(a){g.cancelClick=g.hasDragged;g.hasDragged=!1;g.chart.hasDraggedAnnotation=!1;k(c(g.target,g),"afterUpdate");g.onMouseUp(a)})}},onMouseUp:function(a){var g=this.chart;a=this.target||this;var c=g.options.annotations;g=g.annotations.indexOf(a);this.removeDocEvents();c[g]=a.options},
onDrag:function(a){if(this.chart.isInsidePlot(a.chartX-this.chart.plotLeft,a.chartY-this.chart.plotTop)){var g=this.mouseMoveToTranslation(a);"x"===this.options.draggable&&(g.y=0);"y"===this.options.draggable&&(g.x=0);this.points.length?this.translate(g.x,g.y):(this.shapes.forEach(function(a){a.translate(g.x,g.y)}),this.labels.forEach(function(a){a.translate(g.x,g.y)}));this.redraw(!1)}},mouseMoveToRadians:function(a,g,c){var e=a.prevChartY-c,h=a.prevChartX-g;c=a.chartY-c;a=a.chartX-g;this.chart.inverted&&
(g=h,h=e,e=g,g=a,a=c,c=g);return Math.atan2(c,a)-Math.atan2(e,h)},mouseMoveToTranslation:function(a){var g=a.chartX-a.prevChartX;a=a.chartY-a.prevChartY;if(this.chart.inverted){var c=a;a=g;g=c}return{x:g,y:a}},mouseMoveToScale:function(a,g,c){g=(a.chartX-g||1)/(a.prevChartX-g||1);a=(a.chartY-c||1)/(a.prevChartY-c||1);this.chart.inverted&&(c=a,a=g,g=c);return{x:g,y:a}},destroy:function(){this.removeDocEvents();z(this);this.hcEvents=null}}});l(f,"annotations/ControlPoint.js",[f["parts/Utilities.js"],
f["annotations/eventEmitterMixin.js"]],function(d,b){var f=d.extend,k=d.merge,r=d.pick;d=function(b,c,d,a){this.chart=b;this.target=c;this.options=d;this.index=r(d.index,a)};f(d.prototype,b);d.prototype.nonDOMEvents=["drag"];d.prototype.setVisibility=function(b){this.graphic.attr("visibility",b?"visible":"hidden");this.options.visible=b};d.prototype.render=function(){var b=this.chart,c=this.options;this.graphic=b.renderer.symbol(c.symbol,0,0,c.width,c.height).add(b.controlPointsGroup).css(c.style);
this.setVisibility(c.visible);this.addEvents()};d.prototype.redraw=function(b){this.graphic[b?"animate":"attr"](this.options.positioner.call(this,this.target))};d.prototype.destroy=function(){b.destroy.call(this);this.graphic&&(this.graphic=this.graphic.destroy());this.options=this.target=this.chart=null};d.prototype.update=function(b){var c=this.chart,d=this.target,a=this.index;b=k(!0,this.options,b);this.destroy();this.constructor(c,d,b,a);this.render(c.controlPointsGroup);this.redraw()};return d});
l(f,"annotations/MockPoint.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,b){var f=b.defined,k=b.extend,r=b.fireEvent,p=function(c,b,a){this.series={visible:!0,chart:c,getPlotBox:d.Series.prototype.getPlotBox};this.target=b||null;this.options=a;this.applyOptions(this.getOptions())};p.fromPoint=function(c){return new p(c.series.chart,null,{x:c.x,y:c.y,xAxis:c.series.xAxis,yAxis:c.series.yAxis})};p.pointToPixels=function(c,b){var a=c.series,g=a.chart,d=c.plotX,e=c.plotY;g.inverted&&
(c.mock?(d=c.plotY,e=c.plotX):(d=g.plotWidth-c.plotY,e=g.plotHeight-c.plotX));a&&!b&&(c=a.getPlotBox(),d+=c.translateX,e+=c.translateY);return{x:d,y:e}};p.pointToOptions=function(c){return{x:c.x,y:c.y,xAxis:c.series.xAxis,yAxis:c.series.yAxis}};k(p.prototype,{mock:!0,hasDynamicOptions:function(){return"function"===typeof this.options},getOptions:function(){return this.hasDynamicOptions()?this.options(this.target):this.options},applyOptions:function(c){this.command=c.command;this.setAxis(c,"x");this.setAxis(c,
"y");this.refresh()},setAxis:function(c,b){b+="Axis";c=c[b];var a=this.series.chart;this.series[b]=c instanceof d.Axis?c:f(c)?a[b][c]||a.get(c):null},toAnchor:function(){var c=[this.plotX,this.plotY,0,0];this.series.chart.inverted&&(c[0]=this.plotY,c[1]=this.plotX);return c},getLabelConfig:function(){return{x:this.x,y:this.y,point:this}},isInsidePlot:function(){var c=this.plotX,b=this.plotY,a=this.series.xAxis,g=this.series.yAxis,d={x:c,y:b,isInsidePlot:!0};a&&(d.isInsidePlot=f(c)&&0<=c&&c<=a.len);
g&&(d.isInsidePlot=d.isInsidePlot&&f(b)&&0<=b&&b<=g.len);r(this.series.chart,"afterIsInsidePlot",d);return d.isInsidePlot},refresh:function(){var c=this.series,b=c.xAxis;c=c.yAxis;var a=this.getOptions();b?(this.x=a.x,this.plotX=b.toPixels(a.x,!0)):(this.x=null,this.plotX=a.x);c?(this.y=a.y,this.plotY=c.toPixels(a.y,!0)):(this.y=null,this.plotY=a.y);this.isInside=this.isInsidePlot()},translate:function(c,b,a,g){this.hasDynamicOptions()||(this.plotX+=a,this.plotY+=g,this.refreshOptions())},scale:function(c,
b,a,g){if(!this.hasDynamicOptions()){var d=this.plotY*g;this.plotX=(1-a)*c+this.plotX*a;this.plotY=(1-g)*b+d;this.refreshOptions()}},rotate:function(c,b,a){if(!this.hasDynamicOptions()){var g=Math.cos(a);a=Math.sin(a);var d=this.plotX,e=this.plotY;d-=c;e-=b;this.plotX=d*g-e*a+c;this.plotY=d*a+e*g+b;this.refreshOptions()}},refreshOptions:function(){var c=this.series,b=c.xAxis;c=c.yAxis;this.x=this.options.x=b?this.options.x=b.toValue(this.plotX,!0):this.plotX;this.y=this.options.y=c?c.toValue(this.plotY,
!0):this.plotY}});return p});l(f,"annotations/controllable/controllableMixin.js",[f["parts/Utilities.js"],f["annotations/ControlPoint.js"],f["annotations/MockPoint.js"],f["parts/Tooltip.js"]],function(d,b,f,k){var r=d.isObject,p=d.isString,c=d.merge,A=d.splat;return{init:function(a,g,b){this.annotation=a;this.chart=a.chart;this.options=g;this.points=[];this.controlPoints=[];this.index=b;this.linkPoints();this.addControlPoints()},attr:function(){this.graphic.attr.apply(this.graphic,arguments)},getPointsOptions:function(){var a=
this.options;return a.points||a.point&&A(a.point)},attrsFromOptions:function(a){var g=this.constructor.attrsMap,b={},e,h=this.chart.styledMode;for(e in a){var c=g[e];!c||h&&-1!==["fill","stroke","stroke-width"].indexOf(c)||(b[c]=a[e])}return b},anchor:function(a){var g=a.series.getPlotBox();a=a.mock?a.toAnchor():k.prototype.getAnchor.call({chart:a.series.chart},a);a={x:a[0]+(this.options.x||0),y:a[1]+(this.options.y||0),height:a[2]||0,width:a[3]||0};return{relativePosition:a,absolutePosition:c(a,
{x:a.x+g.translateX,y:a.y+g.translateY})}},point:function(a,g){if(a&&a.series)return a;g&&null!==g.series||(r(a)?g=new f(this.chart,this,a):p(a)?g=this.chart.get(a)||null:"function"===typeof a&&(g=a.call(g,this),g=g.series?g:new f(this.chart,this,a)));return g},linkPoints:function(){var a=this.getPointsOptions(),g=this.points,b=a&&a.length||0,e;for(e=0;e<b;e++){var h=this.point(a[e],g[e]);if(!h){g.length=0;return}h.mock&&h.refresh();g[e]=h}return g},addControlPoints:function(){var a=this.options.controlPoints;
(a||[]).forEach(function(g,d){g=c(this.options.controlPointOptions,g);g.index||(g.index=d);a[d]=g;this.controlPoints.push(new b(this.chart,this,g))},this)},shouldBeDrawn:function(){return!!this.points.length},render:function(a){this.controlPoints.forEach(function(a){a.render()})},redraw:function(a){this.controlPoints.forEach(function(g){g.redraw(a)})},transform:function(a,g,b,e,h){if(this.chart.inverted){var c=g;g=b;b=c}this.points.forEach(function(c,m){this.transformPoint(a,g,b,e,h,m)},this)},transformPoint:function(a,
g,b,e,h,c){var m=this.points[c];m.mock||(m=this.points[c]=f.fromPoint(m));m[a](g,b,e,h)},translate:function(a,b){this.transform("translate",null,null,a,b)},translatePoint:function(a,b,c){this.transformPoint("translate",null,null,a,b,c)},translateShape:function(a,b){var c=this.annotation.chart,e=this.annotation.userOptions,h=c.annotations.indexOf(this.annotation);c=c.options.annotations[h];this.translatePoint(a,b,0);c[this.collection][this.index].point=this.options.point;e[this.collection][this.index].point=
this.options.point},rotate:function(a,b,c){this.transform("rotate",a,b,c)},scale:function(a,b,c,e){this.transform("scale",a,b,c,e)},setControlPointsVisibility:function(a){this.controlPoints.forEach(function(b){b.setVisibility(a)})},destroy:function(){this.graphic&&(this.graphic=this.graphic.destroy());this.tracker&&(this.tracker=this.tracker.destroy());this.controlPoints.forEach(function(a){a.destroy()});this.options=this.controlPoints=this.points=this.chart=null;this.annotation&&(this.annotation=
null)},update:function(a){var b=this.annotation;a=c(!0,this.options,a);var d=this.graphic.parentGroup;this.destroy();this.constructor(b,a);this.render(d);this.redraw()}}});l(f,"annotations/controllable/markerMixin.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,b){var f=b.addEvent,k=b.defined,r=b.merge,p=b.objectEach,c=b.uniqueKey,z={arrow:{tagName:"marker",render:!1,id:"arrow",refY:5,refX:9,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 0 L 10 5 L 0 10 Z",strokeWidth:0}]},
"reverse-arrow":{tagName:"marker",render:!1,id:"reverse-arrow",refY:5,refX:1,markerWidth:10,markerHeight:10,children:[{tagName:"path",d:"M 0 5 L 10 0 L 10 10 Z",strokeWidth:0}]}};d.SVGRenderer.prototype.addMarker=function(a,b){var c={id:a},e={stroke:b.color||"none",fill:b.color||"rgba(0, 0, 0, 0.75)"};c.children=b.children.map(function(a){return r(e,a)});b=this.definition(r(!0,{markerWidth:20,markerHeight:20,refX:0,refY:0,orient:"auto"},b,c));b.id=a;return b};b=function(a){return function(b){this.attr(a,
"url(#"+b+")")}};b={markerEndSetter:b("marker-end"),markerStartSetter:b("marker-start"),setItemMarkers:function(a){var b=a.options,d=a.chart,e=d.options.defs,h=b.fill,m=k(h)&&"none"!==h?h:b.stroke;["markerStart","markerEnd"].forEach(function(h){var g=b[h],q;if(g){for(q in e){var f=e[q];if(g===f.id&&"marker"===f.tagName){var n=f;break}}n&&(g=a[h]=d.renderer.addMarker((b.id||c())+"-"+n.id,r(n,{color:m})),a.attr(h,g.attr("id")))}})}};f(d.Chart,"afterGetContainer",function(){this.options.defs=r(z,this.options.defs||
{});p(this.options.defs,function(a){"marker"===a.tagName&&!1!==a.render&&this.renderer.addMarker(a.id,a)},this)});return b});l(f,"annotations/controllable/ControllablePath.js",[f["parts/Globals.js"],f["parts/Utilities.js"],f["annotations/controllable/controllableMixin.js"],f["annotations/controllable/markerMixin.js"]],function(d,b,f,k){var r=b.extend;b=b.merge;var p="rgba(192,192,192,"+(d.svg?.0001:.002)+")";d=function(b,d,a){this.init(b,d,a);this.collection="shapes"};d.attrsMap={dashStyle:"dashstyle",
strokeWidth:"stroke-width",stroke:"stroke",fill:"fill",zIndex:"zIndex"};b(!0,d.prototype,f,{type:"path",setMarkers:k.setItemMarkers,toD:function(){var b=this.options.d;if(b)return"function"===typeof b?b.call(this):b;var d=this.points,a=d.length,g=a,f=d[0],e=g&&this.anchor(f).absolutePosition,h=0,m=2;for(b=e&&["M",e.x,e.y];++h<a&&g;)f=d[h],g=f.command||"L",e=this.anchor(f).absolutePosition,"Z"===g?b[++m]=g:(g!==d[h-1].command&&(b[++m]=g),b[++m]=e.x,b[++m]=e.y),g=f.series.visible;return g?this.chart.renderer.crispLine(b,
this.graphic.strokeWidth()):null},shouldBeDrawn:function(){return f.shouldBeDrawn.call(this)||!!this.options.d},render:function(b){var c=this.options,a=this.attrsFromOptions(c);this.graphic=this.annotation.chart.renderer.path(["M",0,0]).attr(a).add(b);c.className&&this.graphic.addClass(c.className);this.tracker=this.annotation.chart.renderer.path(["M",0,0]).addClass("highcharts-tracker-line").attr({zIndex:2}).add(b);this.annotation.chart.styledMode||this.tracker.attr({"stroke-linejoin":"round",stroke:p,
fill:p,"stroke-width":this.graphic.strokeWidth()+2*c.snap});f.render.call(this);r(this.graphic,{markerStartSetter:k.markerStartSetter,markerEndSetter:k.markerEndSetter});this.setMarkers(this)},redraw:function(b){var c=this.toD(),a=b?"animate":"attr";c?(this.graphic[a]({d:c}),this.tracker[a]({d:c})):(this.graphic.attr({d:"M 0 -9000000000"}),this.tracker.attr({d:"M 0 -9000000000"}));this.graphic.placed=this.tracker.placed=!!c;f.redraw.call(this,b)}});return d});l(f,"annotations/controllable/ControllableRect.js",
[f["parts/Utilities.js"],f["annotations/controllable/controllableMixin.js"],f["annotations/controllable/ControllablePath.js"]],function(d,b,f){d=d.merge;var k=function(b,d,c){this.init(b,d,c);this.collection="shapes"};k.attrsMap=d(f.attrsMap,{width:"width",height:"height"});d(!0,k.prototype,b,{type:"rect",translate:b.translateShape,render:function(d){var f=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.rect(0,-9E9,0,0).attr(f).add(d);b.render.call(this)},redraw:function(d){var f=
this.anchor(this.points[0]).absolutePosition;if(f)this.graphic[d?"animate":"attr"]({x:f.x,y:f.y,width:this.options.width,height:this.options.height});else this.attr({x:0,y:-9E9});this.graphic.placed=!!f;b.redraw.call(this,d)}});return k});l(f,"annotations/controllable/ControllableCircle.js",[f["parts/Utilities.js"],f["annotations/controllable/controllableMixin.js"],f["annotations/controllable/ControllablePath.js"]],function(d,b,f){d=d.merge;var k=function(b,d,c){this.init(b,d,c);this.collection="shapes"};
k.attrsMap=d(f.attrsMap,{r:"r"});d(!0,k.prototype,b,{type:"circle",translate:b.translateShape,render:function(d){var f=this.attrsFromOptions(this.options);this.graphic=this.annotation.chart.renderer.circle(0,-9E9,0).attr(f).add(d);b.render.call(this)},redraw:function(d){var f=this.anchor(this.points[0]).absolutePosition;if(f)this.graphic[d?"animate":"attr"]({x:f.x,y:f.y,r:this.options.r});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!f;b.redraw.call(this,d)},setRadius:function(b){this.options.r=
b}});return k});l(f,"annotations/controllable/ControllableLabel.js",[f["parts/Globals.js"],f["parts/Utilities.js"],f["annotations/controllable/controllableMixin.js"],f["annotations/MockPoint.js"],f["parts/Tooltip.js"]],function(d,b,f,k,r){var p=b.extend,c=b.format,A=b.isNumber,a=b.merge,g=b.pick,l=function(a,h,b){this.init(a,h,b);this.collection="labels"};l.shapesWithoutBackground=["connector"];l.alignedPosition=function(a,b){var h=a.align,e=a.verticalAlign,c=(b.x||0)+(a.x||0),d=(b.y||0)+(a.y||0),
g,n;"right"===h?g=1:"center"===h&&(g=2);g&&(c+=(b.width-(a.width||0))/g);"bottom"===e?n=1:"middle"===e&&(n=2);n&&(d+=(b.height-(a.height||0))/n);return{x:Math.round(c),y:Math.round(d)}};l.justifiedOptions=function(a,b,c,d){var e=c.align,h=c.verticalAlign,g=b.box?0:b.padding||0,n=b.getBBox();b={align:e,verticalAlign:h,x:c.x,y:c.y,width:b.width,height:b.height};c=d.x-a.plotLeft;var f=d.y-a.plotTop;d=c+g;0>d&&("right"===e?b.align="left":b.x=-d);d=c+n.width-g;d>a.plotWidth&&("left"===e?b.align="right":
b.x=a.plotWidth-d);d=f+g;0>d&&("bottom"===h?b.verticalAlign="top":b.y=-d);d=f+n.height-g;d>a.plotHeight&&("top"===h?b.verticalAlign="bottom":b.y=a.plotHeight-d);return b};l.attrsMap={backgroundColor:"fill",borderColor:"stroke",borderWidth:"stroke-width",zIndex:"zIndex",borderRadius:"r",padding:"padding"};a(!0,l.prototype,f,{translatePoint:function(a,b){f.translatePoint.call(this,a,b,0)},translate:function(a,b){var e=this.annotation.chart,h=this.annotation.userOptions,c=e.annotations.indexOf(this.annotation);
c=e.options.annotations[c];e.inverted&&(e=a,a=b,b=e);this.options.x+=a;this.options.y+=b;c[this.collection][this.index].x=this.options.x;c[this.collection][this.index].y=this.options.y;h[this.collection][this.index].x=this.options.x;h[this.collection][this.index].y=this.options.y},render:function(a){var b=this.options,e=this.attrsFromOptions(b),c=b.style;this.graphic=this.annotation.chart.renderer.label("",0,-9999,b.shape,null,null,b.useHTML,null,"annotation-label").attr(e).add(a);this.annotation.chart.styledMode||
("contrast"===c.color&&(c.color=this.annotation.chart.renderer.getContrast(-1<l.shapesWithoutBackground.indexOf(b.shape)?"#FFFFFF":b.backgroundColor)),this.graphic.css(b.style).shadow(b.shadow));b.className&&this.graphic.addClass(b.className);this.graphic.labelrank=b.labelrank;f.render.call(this)},redraw:function(b){var a=this.options,e=this.text||a.format||a.text,d=this.graphic,g=this.points[0];d.attr({text:e?c(e,g.getLabelConfig(),this.annotation.chart):a.formatter.call(g,this)});a=this.anchor(g);
(e=this.position(a))?(d.alignAttr=e,e.anchorX=a.absolutePosition.x,e.anchorY=a.absolutePosition.y,d[b?"animate":"attr"](e)):d.attr({x:0,y:-9999});d.placed=!!e;f.redraw.call(this,b)},anchor:function(){var a=f.anchor.apply(this,arguments),b=this.options.x||0,c=this.options.y||0;a.absolutePosition.x-=b;a.absolutePosition.y-=c;a.relativePosition.x-=b;a.relativePosition.y-=c;return a},position:function(a){var b=this.graphic,e=this.annotation.chart,c=this.points[0],d=this.options,f=a.absolutePosition,v=
a.relativePosition;if(a=c.series.visible&&k.prototype.isInsidePlot.call(c)){if(d.distance)var n=r.prototype.getPosition.call({chart:e,distance:g(d.distance,16)},b.width,b.height,{plotX:v.x,plotY:v.y,negative:c.negative,ttBelow:c.ttBelow,h:v.height||v.width});else d.positioner?n=d.positioner.call(this):(c={x:f.x,y:f.y,width:0,height:0},n=l.alignedPosition(p(d,{width:b.width,height:b.height}),c),"justify"===this.options.overflow&&(n=l.alignedPosition(l.justifiedOptions(e,b,d,n),c)));d.crop&&(d=n.x-
e.plotLeft,c=n.y-e.plotTop,a=e.isInsidePlot(d,c)&&e.isInsidePlot(d+b.width,c+b.height))}return a?n:null}});d.SVGRenderer.prototype.symbols.connector=function(a,b,c,d,g){var e=g&&g.anchorX;g=g&&g.anchorY;var h=c/2;if(A(e)&&A(g)){var n=["M",e,g];var f=b-g;0>f&&(f=-d-f);f<c&&(h=e<a+c/2?f:c-f);g>b+d?n.push("L",a+h,b+d):g<b?n.push("L",a+h,b):e<a?n.push("L",a,b+d/2):e>a+c&&n.push("L",a+c,b+d/2)}return n||[]};return l});l(f,"annotations/controllable/ControllableImage.js",[f["parts/Utilities.js"],f["annotations/controllable/controllableMixin.js"],
f["annotations/controllable/ControllableLabel.js"]],function(d,b,f){d=d.merge;var k=function(b,d,c){this.init(b,d,c);this.collection="shapes"};k.attrsMap={width:"width",height:"height",zIndex:"zIndex"};d(!0,k.prototype,b,{type:"image",translate:b.translateShape,render:function(d){var f=this.attrsFromOptions(this.options),c=this.options;this.graphic=this.annotation.chart.renderer.image(c.src,0,-9E9,c.width,c.height).attr(f).add(d);this.graphic.width=c.width;this.graphic.height=c.height;b.render.call(this)},
redraw:function(d){var k=this.anchor(this.points[0]);if(k=f.prototype.position.call(this,k))this.graphic[d?"animate":"attr"]({x:k.x,y:k.y});else this.graphic.attr({x:0,y:-9E9});this.graphic.placed=!!k;b.redraw.call(this,d)}});return k});l(f,"annotations/annotations.src.js",[f["parts/Globals.js"],f["parts/Utilities.js"],f["annotations/controllable/controllableMixin.js"],f["annotations/controllable/ControllableRect.js"],f["annotations/controllable/ControllableCircle.js"],f["annotations/controllable/ControllablePath.js"],
f["annotations/controllable/ControllableImage.js"],f["annotations/controllable/ControllableLabel.js"],f["annotations/eventEmitterMixin.js"],f["annotations/MockPoint.js"],f["annotations/ControlPoint.js"]],function(d,b,f,k,l,p,c,z,a,g,B){var e=b.addEvent,h=b.defined,m=b.destroyObjectProperties,q=b.erase,w=b.extend,u=b.find,v=b.fireEvent,n=b.merge,C=b.pick,x=b.splat;b=b.wrap;var y=d.Chart.prototype,t=d.Annotation=function(a,b){this.chart=a;this.points=[];this.controlPoints=[];this.coll="annotations";
this.labels=[];this.shapes=[];this.options=n(this.defaultOptions,b);this.userOptions=b;b=this.getLabelsAndShapesOptions(this.options,b);this.options.labels=b.labels;this.options.shapes=b.shapes;this.init(a,this.options)};n(!0,t.prototype,f,a,{nonDOMEvents:["add","afterUpdate","drag","remove"],defaultOptions:{visible:!0,draggable:"xy",labelOptions:{align:"center",allowOverlap:!1,backgroundColor:"rgba(0, 0, 0, 0.75)",borderColor:"black",borderRadius:3,borderWidth:1,className:"",crop:!1,formatter:function(){return h(this.y)?
this.y:"Annotation label"},overflow:"justify",padding:5,shadow:!1,shape:"callout",style:{fontSize:"11px",fontWeight:"normal",color:"contrast"},useHTML:!1,verticalAlign:"bottom",x:0,y:-16},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1,fill:"rgba(0, 0, 0, 0.75)",r:0,snap:2},controlPointOptions:{symbol:"circle",width:10,height:10,style:{stroke:"black","stroke-width":2,fill:"white"},visible:!1,events:{}},events:{},zIndex:6},init:function(){this.linkPoints();this.addControlPoints();this.addShapes();
this.addLabels();this.addClipPaths();this.setLabelCollector()},getLabelsAndShapesOptions:function(a,b){var c={};["labels","shapes"].forEach(function(e){a[e]&&(c[e]=x(b[e]).map(function(b,c){return n(a[e][c],b)}))});return c},addShapes:function(){(this.options.shapes||[]).forEach(function(a,b){a=this.initShape(a,b);n(!0,this.options.shapes[b],a.options)},this)},addLabels:function(){(this.options.labels||[]).forEach(function(a,b){a=this.initLabel(a,b);n(!0,this.options.labels[b],a.options)},this)},
addClipPaths:function(){this.setClipAxes();this.clipXAxis&&this.clipYAxis&&(this.clipRect=this.chart.renderer.clipRect(this.getClipBox()))},setClipAxes:function(){var a=this.chart.xAxis,b=this.chart.yAxis,c=(this.options.labels||[]).concat(this.options.shapes||[]).reduce(function(c,e){return[a[e&&e.point&&e.point.xAxis]||c[0],b[e&&e.point&&e.point.yAxis]||c[1]]},[]);this.clipXAxis=c[0];this.clipYAxis=c[1]},getClipBox:function(){return{x:this.clipXAxis.left,y:this.clipYAxis.top,width:this.clipXAxis.width,
height:this.clipYAxis.height}},setLabelCollector:function(){var a=this;a.labelCollector=function(){return a.labels.reduce(function(a,b){b.options.allowOverlap||a.push(b.graphic);return a},[])};a.chart.labelCollectors.push(a.labelCollector)},setOptions:function(a){this.options=n(this.defaultOptions,a)},redraw:function(a){this.linkPoints();this.graphic||this.render();this.clipRect&&this.clipRect.animate(this.getClipBox());this.redrawItems(this.shapes,a);this.redrawItems(this.labels,a);f.redraw.call(this,
a)},redrawItems:function(a,b){for(var c=a.length;c--;)this.redrawItem(a[c],b)},renderItems:function(a){for(var b=a.length;b--;)this.renderItem(a[b])},render:function(){var a=this.chart.renderer;this.graphic=a.g("annotation").attr({zIndex:this.options.zIndex,visibility:this.options.visible?"visible":"hidden"}).add();this.shapesGroup=a.g("annotation-shapes").add(this.graphic).clip(this.chart.plotBoxClip);this.labelsGroup=a.g("annotation-labels").attr({translateX:0,translateY:0}).add(this.graphic);this.clipRect&&
this.graphic.clip(this.clipRect);this.renderItems(this.shapes);this.renderItems(this.labels);this.addEvents();f.render.call(this)},setVisibility:function(a){var b=this.options;a=C(a,!b.visible);this.graphic.attr("visibility",a?"visible":"hidden");a||this.setControlPointsVisibility(!1);b.visible=a},setControlPointsVisibility:function(a){var b=function(b){b.setControlPointsVisibility(a)};f.setControlPointsVisibility.call(this,a);this.shapes.forEach(b);this.labels.forEach(b)},destroy:function(){var b=
this.chart,c=function(a){a.destroy()};this.labels.forEach(c);this.shapes.forEach(c);this.clipYAxis=this.clipXAxis=null;q(b.labelCollectors,this.labelCollector);a.destroy.call(this);f.destroy.call(this);m(this,b)},remove:function(){return this.chart.removeAnnotation(this)},update:function(a){var b=this.chart,c=this.getLabelsAndShapesOptions(this.userOptions,a),e=b.annotations.indexOf(this);a=n(!0,this.userOptions,a);a.labels=c.labels;a.shapes=c.shapes;this.destroy();this.constructor(b,a);b.options.annotations[e]=
a;this.isUpdating=!0;this.redraw();this.isUpdating=!1;v(this,"afterUpdate")},initShape:function(a,b){a=n(this.options.shapeOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new t.shapesMap[a.type](this,a,b);b.itemType="shape";this.shapes.push(b);return b},initLabel:function(a,b){a=n(this.options.labelOptions,{controlPointOptions:this.options.controlPointOptions},a);b=new z(this,a,b);b.itemType="label";this.labels.push(b);return b},redrawItem:function(a,b){a.linkPoints();a.shouldBeDrawn()?
(a.graphic||this.renderItem(a),a.redraw(C(b,!0)&&a.graphic.placed),a.points.length&&this.adjustVisibility(a)):this.destroyItem(a)},adjustVisibility:function(a){var b=!1,c=a.graphic;a.points.forEach(function(a){!1!==a.series.visible&&!1!==a.visible&&(b=!0)});b?"hidden"===c.visibility&&c.show():c.hide()},destroyItem:function(a){q(this[a.itemType+"s"],a);a.destroy()},renderItem:function(a){a.render("label"===a.itemType?this.labelsGroup:this.shapesGroup)}});t.shapesMap={rect:k,circle:l,path:p,image:c};
t.types={};t.MockPoint=g;t.ControlPoint=B;d.extendAnnotation=function(a,b,c,e){b=b||t;n(!0,a.prototype,b.prototype,c);a.prototype.defaultOptions=n(a.prototype.defaultOptions,e||{})};w(y,{initAnnotation:function(a){a=new (t.types[a.type]||t)(this,a);this.annotations.push(a);return a},addAnnotation:function(a,b){a=this.initAnnotation(a);this.options.annotations.push(a.options);C(b,!0)&&a.redraw();return a},removeAnnotation:function(a){var b=this.annotations,c="annotations"===a.coll?a:u(b,function(b){return b.options.id===
a});c&&(v(c,"remove"),q(this.options.annotations,c.options),q(b,c),c.destroy())},drawAnnotations:function(){this.plotBoxClip.attr(this.plotBox);this.annotations.forEach(function(a){a.redraw()})}});y.collectionsWithUpdate.push("annotations");y.collectionsWithInit.annotations=[y.addAnnotation];y.callbacks.push(function(a){a.annotations=[];a.options.annotations||(a.options.annotations=[]);a.plotBoxClip=this.renderer.clipRect(this.plotBox);a.controlPointsGroup=a.renderer.g("control-points").attr({zIndex:99}).clip(a.plotBoxClip).add();
a.options.annotations.forEach(function(b,c){b=a.initAnnotation(b);a.options.annotations[c]=b.options});a.drawAnnotations();e(a,"redraw",a.drawAnnotations);e(a,"destroy",function(){a.plotBoxClip.destroy();a.controlPointsGroup.destroy()})});b(d.Pointer.prototype,"onContainerMouseDown",function(a){this.chart.hasDraggedAnnotation||a.apply(this,Array.prototype.slice.call(arguments,1))})});l(f,"mixins/navigation.js",[],function(){return{initUpdate:function(d){d.navigation||(d.navigation={updates:[],update:function(b,
d){this.updates.forEach(function(f){f.update.call(f.context,b,d)})}})},addUpdate:function(d,b){b.navigation||this.initUpdate(b);b.navigation.updates.push({update:d,context:b})}}});l(f,"annotations/navigationBindings.js",[f["parts/Globals.js"],f["parts/Utilities.js"],f["mixins/navigation.js"]],function(d,b,f){function k(b){var c=b.prototype.defaultOptions.events&&b.prototype.defaultOptions.events.click;m(!0,b.prototype.defaultOptions.events,{click:function(b){var e=this,d=e.chart.navigationBindings,
h=d.activeAnnotation;c&&c.click.call(e,b);h!==e?(d.deselectAnnotation(),d.activeAnnotation=e,e.setControlPointsVisibility(!0),a(d,"showPopup",{annotation:e,formType:"annotation-toolbar",options:d.annotationToFields(e),onSubmit:function(a){var b={};"remove"===a.actionType?(d.activeAnnotation=!1,d.chart.removeAnnotation(e)):(d.fieldsToOptions(a.fields,b),d.deselectAnnotation(),a=b.typeOptions,"measure"===e.options.type&&(a.crosshairY.enabled=0!==a.crosshairY.strokeWidth,a.crosshairX.enabled=0!==a.crosshairX.strokeWidth),
e.update(b))}})):(d.deselectAnnotation(),a(d,"closePopup"));b.activeAnnotation=!0}})}var l=b.addEvent,p=b.attr,c=b.extend,A=b.format,a=b.fireEvent,g=b.isArray,B=b.isFunction,e=b.isNumber,h=b.isObject,m=b.merge,q=b.objectEach,w=b.pick,u=d.doc,v=d.win;d.NavigationBindings=function(a,b){this.chart=a;this.options=b;this.eventsToUnbind=[];this.container=u.getElementsByClassName(this.options.bindingsClassName)};d.NavigationBindings.annotationsEditable={nestedOptions:{labelOptions:["style","format","backgroundColor"],
labels:["style"],label:["style"],style:["fontSize","color"],background:["fill","strokeWidth","stroke"],innerBackground:["fill","strokeWidth","stroke"],outerBackground:["fill","strokeWidth","stroke"],shapeOptions:["fill","strokeWidth","stroke"],shapes:["fill","strokeWidth","stroke"],line:["strokeWidth","stroke"],backgroundColors:[!0],connector:["fill","strokeWidth","stroke"],crosshairX:["strokeWidth","stroke"],crosshairY:["strokeWidth","stroke"]},circle:["shapes"],verticalLine:[],label:["labelOptions"],
measure:["background","crosshairY","crosshairX"],fibonacci:[],tunnel:["background","line","height"],pitchfork:["innerBackground","outerBackground"],rect:["shapes"],crookedLine:[]};d.NavigationBindings.annotationsNonEditable={rectangle:["crosshairX","crosshairY","label"]};c(d.NavigationBindings.prototype,{initEvents:function(){var a=this,b=a.chart,c=a.container,e=a.options;a.boundClassNames={};q(e.bindings,function(b){a.boundClassNames[b.className]=b});[].forEach.call(c,function(b){a.eventsToUnbind.push(l(b,
"click",function(b){var e=a.getButtonEvents(c,b);e&&a.bindingsButtonClick(e.button,e.events,b)}))});q(e.events||{},function(b,c){B(b)&&a.eventsToUnbind.push(l(a,c,b))});a.eventsToUnbind.push(l(b.container,"click",function(c){!b.cancelClick&&b.isInsidePlot(c.chartX-b.plotLeft,c.chartY-b.plotTop)&&a.bindingsChartClick(this,c)}));a.eventsToUnbind.push(l(b.container,"mousemove",function(b){a.bindingsContainerMouseMove(this,b)}))},initUpdate:function(){var a=this;f.addUpdate(function(b){a.update(b)},this.chart)},
bindingsButtonClick:function(b,c,e){var d=this.chart;this.selectedButtonElement&&(a(this,"deselectButton",{button:this.selectedButtonElement}),this.nextEvent&&(this.currentUserDetails&&"annotations"===this.currentUserDetails.coll&&d.removeAnnotation(this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1));this.selectedButton=c;this.selectedButtonElement=b;a(this,"selectButton",{button:b});c.init&&c.init.call(this,b,e);(c.start||c.steps)&&d.renderer.boxWrapper.addClass("highcharts-draw-mode")},
bindingsChartClick:function(b,c){b=this.chart;var e=this.selectedButton;b=b.renderer.boxWrapper;var d;if(d=this.activeAnnotation&&!c.activeAnnotation&&c.target.parentNode){a:{d=c.target;var h=v.Element.prototype,f=h.matches||h.msMatchesSelector||h.webkitMatchesSelector,g=null;if(h.closest)g=h.closest.call(d,".highcharts-popup");else{do{if(f.call(d,".highcharts-popup"))break a;d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType)}d=g}d=!d}d&&(a(this,"closePopup"),this.deselectAnnotation());
e&&e.start&&(this.nextEvent?(this.nextEvent(c,this.currentUserDetails),this.steps&&(this.stepIndex++,e.steps[this.stepIndex]?this.mouseMoveEvent=this.nextEvent=e.steps[this.stepIndex]:(a(this,"deselectButton",{button:this.selectedButtonElement}),b.removeClass("highcharts-draw-mode"),e.end&&e.end.call(this,c,this.currentUserDetails),this.mouseMoveEvent=this.nextEvent=!1,this.selectedButton=null))):(this.currentUserDetails=e.start.call(this,c),e.steps?(this.stepIndex=0,this.steps=!0,this.mouseMoveEvent=
this.nextEvent=e.steps[this.stepIndex]):(a(this,"deselectButton",{button:this.selectedButtonElement}),b.removeClass("highcharts-draw-mode"),this.steps=!1,this.selectedButton=null,e.end&&e.end.call(this,c,this.currentUserDetails))))},bindingsContainerMouseMove:function(a,b){this.mouseMoveEvent&&this.mouseMoveEvent(b,this.currentUserDetails)},fieldsToOptions:function(a,b){q(a,function(a,c){var d=parseFloat(a),h=c.split("."),f=b,g=h.length-1;!e(d)||a.match(/px/g)||c.match(/format/g)||(a=d);""!==a&&"undefined"!==
a&&h.forEach(function(b,c){var e=w(h[c+1],"");g===c?f[b]=a:(f[b]||(f[b]=e.match(/\d/g)?[]:{}),f=f[b])})});return b},deselectAnnotation:function(){this.activeAnnotation&&(this.activeAnnotation.setControlPointsVisibility(!1),this.activeAnnotation=!1)},annotationToFields:function(a){function b(c,e,d,m){if(d&&-1===k.indexOf(e)&&(0<=(d.indexOf&&d.indexOf(e))||d[e]||!0===d))if(g(c))m[e]=[],c.forEach(function(a,c){h(a)?(m[e][c]={},q(a,function(a,d){b(a,d,f[e],m[e][c])})):b(a,0,f[e],m[e])});else if(h(c)){var x=
{};g(m)?(m.push(x),x[e]={},x=x[e]):m[e]=x;q(c,function(a,c){b(a,c,0===e?d:f[e],x)})}else"format"===e?m[e]=[A(c,a.labels[0].points[0]).toString(),"text"]:g(m)?m.push([c,n(c)]):m[e]=[c,n(c)]}var c=a.options,e=d.NavigationBindings.annotationsEditable,f=e.nestedOptions,n=this.utils.getFieldType,m=w(c.type,c.shapes&&c.shapes[0]&&c.shapes[0].type,c.labels&&c.labels[0]&&c.labels[0].itemType,"label"),k=d.NavigationBindings.annotationsNonEditable[c.langKey]||[],u={langKey:c.langKey,type:m};q(c,function(a,
d){"typeOptions"===d?(u[d]={},q(c[d],function(a,c){b(a,c,f,u[d],!0)})):b(a,d,e[m],u)});return u},getClickedClassNames:function(a,b){var c=b.target;b=[];for(var e;c&&((e=p(c,"class"))&&(b=b.concat(e.split(" ").map(function(a){return[a,c]}))),c=c.parentNode,c!==a););return b},getButtonEvents:function(a,b){var c=this,e;this.getClickedClassNames(a,b).forEach(function(a){c.boundClassNames[a[0]]&&!e&&(e={events:c.boundClassNames[a[0]],button:a[1]})});return e},update:function(a){this.options=m(!0,this.options,
a);this.removeEvents();this.initEvents()},removeEvents:function(){this.eventsToUnbind.forEach(function(a){a()})},destroy:function(){this.removeEvents()},utils:{updateRectSize:function(a,b){var c=b.chart,e=b.options.typeOptions,d=c.pointer.getCoordinates(a);a=d.xAxis[0].value-e.point.x;e=e.point.y-d.yAxis[0].value;b.update({typeOptions:{background:{width:c.inverted?e:a,height:c.inverted?a:e}}})},getFieldType:function(a){return{string:"text",number:"number","boolean":"checkbox"}[typeof a]}}});d.Chart.prototype.initNavigationBindings=
function(){var a=this.options;a&&a.navigation&&a.navigation.bindings&&(this.navigationBindings=new d.NavigationBindings(this,a.navigation),this.navigationBindings.initEvents(),this.navigationBindings.initUpdate())};l(d.Chart,"load",function(){this.initNavigationBindings()});l(d.Chart,"destroy",function(){this.navigationBindings&&this.navigationBindings.destroy()});l(d.NavigationBindings,"deselectButton",function(){this.selectedButtonElement=null});l(d.Annotation,"remove",function(){this.chart.navigationBindings&&
this.chart.navigationBindings.deselectAnnotation()});d.Annotation&&(k(d.Annotation),q(d.Annotation.types,function(a){k(a)}));d.setOptions({lang:{navigation:{popup:{simpleShapes:"Simple shapes",lines:"Lines",circle:"Circle",rectangle:"Rectangle",label:"Label",shapeOptions:"Shape options",typeOptions:"Details",fill:"Fill",format:"Text",strokeWidth:"Line width",stroke:"Line color",title:"Title",name:"Name",labelOptions:"Label options",labels:"Labels",backgroundColor:"Background color",backgroundColors:"Background colors",
borderColor:"Border color",borderRadius:"Border radius",borderWidth:"Border width",style:"Style",padding:"Padding",fontSize:"Font size",color:"Color",height:"Height",shapes:"Shape options"}}},navigation:{bindingsClassName:"highcharts-bindings-container",bindings:{circleAnnotation:{className:"highcharts-circle-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;return this.chart.addAnnotation(m({langKey:"circle",shapes:[{type:"circle",point:{xAxis:0,
yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},r:5,controlPoints:[{positioner:function(a){var b=d.Annotation.MockPoint.pointToPixels(a.points[0]);a=a.options.r;return{x:b.x+a*Math.cos(Math.PI/4)-this.graphic.width/2,y:b.y+a*Math.sin(Math.PI/4)-this.graphic.height/2}},events:{drag:function(a,b){var c=b.annotation;a=this.mouseMoveToTranslation(a);b.setRadius(Math.max(b.options.r+a.y/Math.sin(Math.PI/4),5));c.options.shapes[0]=c.userOptions.shapes[0]=b.options;b.redraw(!1)}}}]}]},b.annotationsOptions,
b.bindings.circleAnnotation.annotationsOptions))},steps:[function(a,b){var c=b.options.shapes[0].point,e=this.chart.xAxis[0].toPixels(c.x);c=this.chart.yAxis[0].toPixels(c.y);var d=this.chart.inverted;b.update({shapes:[{r:Math.max(Math.sqrt(Math.pow(d?c-a.chartX:e-a.chartX,2)+Math.pow(d?e-a.chartY:c-a.chartY,2)),5)}]})}]},rectangleAnnotation:{className:"highcharts-rectangle-annotation",start:function(a){var b=this.chart.pointer.getCoordinates(a),c=this.chart.options.navigation,e=b.xAxis[0].value;
b=b.yAxis[0].value;return this.chart.addAnnotation(m({langKey:"rectangle",shapes:[{type:"path",points:[{xAxis:0,yAxis:0,x:e,y:b},{xAxis:0,yAxis:0,x:e,y:b},{xAxis:0,yAxis:0,x:e,y:b},{xAxis:0,yAxis:0,x:e,y:b}]}],controlPoints:[{positioner:function(a){a=d.Annotation.MockPoint.pointToPixels(a.shapes[0].points[2]);return{x:a.x-4,y:a.y-4}},events:{drag:function(b){var c=this.chart.pointer.getCoordinates(a),e=c.xAxis[0].value;c=c.yAxis[0].value;var d=b.options.shapes[0].points;d[1].x=e;d[2].x=e;d[2].y=c;
d[3].y=c;b.options.shapes[0].points=d;b.redraw(!1)}}}]},c.annotationsOptions,c.bindings.rectangleAnnotation.annotationsOptions))},steps:[function(a,b){var c=b.options.shapes[0].points,e=this.chart.pointer.getCoordinates(a);a=e.xAxis[0].value;e=e.yAxis[0].value;c[1].x=a;c[2].x=a;c[2].y=e;c[3].y=e;b.update({shapes:[{points:c}]})}]},labelAnnotation:{className:"highcharts-label-annotation",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;return this.chart.addAnnotation(m({langKey:"label",
labelOptions:{format:"{y:.2f}"},labels:[{point:{xAxis:0,yAxis:0,x:a.xAxis[0].value,y:a.yAxis[0].value},overflow:"none",crop:!0,controlPoints:[{symbol:"triangle-down",positioner:function(a){if(!a.graphic.placed)return{x:0,y:-9E7};a=d.Annotation.MockPoint.pointToPixels(a.points[0]);return{x:a.x-this.graphic.width/2,y:a.y-this.graphic.height/2}},events:{drag:function(a,b){a=this.mouseMoveToTranslation(a);b.translatePoint(a.x,a.y);b.annotation.labels[0].options=b.options;b.redraw(!1)}}},{symbol:"square",
positioner:function(a){return a.graphic.placed?{x:a.graphic.alignAttr.x-this.graphic.width/2,y:a.graphic.alignAttr.y-this.graphic.height/2}:{x:0,y:-9E7}},events:{drag:function(a,b){a=this.mouseMoveToTranslation(a);b.translate(a.x,a.y);b.annotation.labels[0].options=b.options;b.redraw(!1)}}}]}]},b.annotationsOptions,b.bindings.labelAnnotation.annotationsOptions))}}},events:{},annotationsOptions:{}}})});l(f,"annotations/popup.js",[f["parts/Globals.js"],f["parts/Utilities.js"]],function(d,b){var f=b.addEvent,
k=b.createElement,l=b.defined,p=b.isArray,c=b.isObject,z=b.isString,a=b.objectEach,g=b.pick;b=b.wrap;var B=/\d/g;b(d.Pointer.prototype,"onContainerMouseDown",function(a,b){var c=b.target&&b.target.className;z(c)&&0<=c.indexOf("highcharts-popup-field")||a.apply(this,Array.prototype.slice.call(arguments,1))});d.Popup=function(a,b){this.init(a,b)};d.Popup.prototype={init:function(a,b){this.container=k("div",{className:"highcharts-popup"},null,a);this.lang=this.getLangpack();this.iconsURL=b;this.addCloseBtn()},
addCloseBtn:function(){var a=this;var b=k("div",{className:"highcharts-popup-close"},null,this.container);b.style["background-image"]="url("+this.iconsURL+"close.svg)";["click","touchstart"].forEach(function(c){f(b,c,function(){a.closePopup()})})},addColsContainer:function(a){var b=k("div",{className:"highcharts-popup-lhs-col"},null,a);a=k("div",{className:"highcharts-popup-rhs-col"},null,a);k("div",{className:"highcharts-popup-rhs-col-wrapper"},null,a);return{lhsCol:b,rhsCol:a}},addInput:function(a,
b,c,d){var e=a.split(".");e=e[e.length-1];var f=this.lang;b="highcharts-"+b+"-"+e;b.match(B)||k("label",{innerHTML:f[e]||e,htmlFor:b},null,c);k("input",{name:b,value:d[0],type:d[1],className:"highcharts-popup-field"},null,c).setAttribute("highcharts-data-name",a)},addButton:function(a,b,c,d,g){var e=this,h=this.closePopup,m=this.getFields;var q=k("button",{innerHTML:b},null,a);["click","touchstart"].forEach(function(a){f(q,a,function(){h.call(e);return d(m(g,c))})});return q},getFields:function(a,
b){var c=a.querySelectorAll("input"),e=a.querySelectorAll("#highcharts-select-series > option:checked")[0];a=a.querySelectorAll("#highcharts-select-volume > option:checked")[0];var d,f;var g={actionType:b,linkedTo:e&&e.getAttribute("value"),fields:{}};[].forEach.call(c,function(a){f=a.getAttribute("highcharts-data-name");(d=a.getAttribute("highcharts-data-series-id"))?g.seriesId=a.value:f?g.fields[f]=a.value:g.type=a.value});a&&(g.fields["params.volumeSeriesID"]=a.getAttribute("value"));return g},
showPopup:function(){var a=this.container,b=a.querySelectorAll(".highcharts-popup-close")[0];a.innerHTML="";0<=a.className.indexOf("highcharts-annotation-toolbar")&&(a.classList.remove("highcharts-annotation-toolbar"),a.removeAttribute("style"));a.appendChild(b);a.style.display="block"},closePopup:function(){this.popup.container.style.display="none"},showForm:function(a,b,c,d){this.popup=b.navigationBindings.popup;this.showPopup();"indicators"===a&&this.indicators.addForm.call(this,b,c,d);"annotation-toolbar"===
a&&this.annotations.addToolbar.call(this,b,c,d);"annotation-edit"===a&&this.annotations.addForm.call(this,b,c,d);"flag"===a&&this.annotations.addForm.call(this,b,c,d,!0)},getLangpack:function(){return d.getOptions().lang.navigation.popup},annotations:{addToolbar:function(a,b,c){var e=this,d=this.lang,f=this.popup.container,h=this.showForm;-1===f.className.indexOf("highcharts-annotation-toolbar")&&(f.className+=" highcharts-annotation-toolbar");f.style.top=a.plotTop+10+"px";k("span",{innerHTML:g(d[b.langKey]||
b.langKey,b.shapes&&b.shapes[0].type)},null,f);var m=this.addButton(f,d.removeButton||"remove","remove",c,f);m.className+=" highcharts-annotation-remove-button";m.style["background-image"]="url("+this.iconsURL+"destroy.svg)";m=this.addButton(f,d.editButton||"edit","edit",function(){h.call(e,"annotation-edit",a,b,c)},f);m.className+=" highcharts-annotation-edit-button";m.style["background-image"]="url("+this.iconsURL+"edit.svg)"},addForm:function(a,b,c,d){var e=this.popup.container,f=this.lang;k("h2",
{innerHTML:f[b.langKey]||b.langKey,className:"highcharts-popup-main-title"},null,e);var g=k("div",{className:"highcharts-popup-lhs-col highcharts-popup-lhs-full"},null,e);var h=k("div",{className:"highcharts-popup-bottom-row"},null,e);this.annotations.addFormFields.call(this,g,a,"",b,[],!0);this.addButton(h,d?f.addButton||"add":f.saveButton||"save",d?"add":"save",c,e)},addFormFields:function(b,d,f,g,l,u){var e=this,h=this.annotations.addFormFields,m=this.addInput,q=this.lang,w,t;a(g,function(a,g){w=
""!==f?f+"."+g:g;c(a)&&(!p(a)||p(a)&&c(a[0])?(t=q[g]||g,t.match(B)||l.push([!0,t,b]),h.call(e,b,d,w,a,l,!1)):l.push([e,w,"annotation",b,a]))});u&&(l=l.sort(function(a){return a[1].match(/format/g)?-1:1}),l.forEach(function(a){!0===a[0]?k("span",{className:"highcharts-annotation-title",innerHTML:a[1]},null,a[2]):m.apply(a[0],a.splice(1))}))}},indicators:{addForm:function(a,b,c){var d=this.indicators,e=this.lang;this.tabs.init.call(this,a);b=this.popup.container.querySelectorAll(".highcharts-tab-item-content");
this.addColsContainer(b[0]);d.addIndicatorList.call(this,a,b[0],"add");var f=b[0].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(f,e.addButton||"add","add",c,f);this.addColsContainer(b[1]);d.addIndicatorList.call(this,a,b[1],"edit");f=b[1].querySelectorAll(".highcharts-popup-rhs-col")[0];this.addButton(f,e.saveButton||"save","edit",c,f);this.addButton(f,e.removeButton||"remove","remove",c,f)},addIndicatorList:function(b,c,d){var e=this,g=c.querySelectorAll(".highcharts-popup-lhs-col")[0];
c=c.querySelectorAll(".highcharts-popup-rhs-col")[0];var h="edit"===d,m=h?b.series:b.options.plotOptions,l=this.indicators.addFormFields,p;var r=k("ul",{className:"highcharts-indicator-list"},null,g);var y=c.querySelectorAll(".highcharts-popup-rhs-col-wrapper")[0];a(m,function(a,c){var d=a.options;if(a.params||d&&d.params){var g=e.indicators.getNameType(a,c),q=g.type;p=k("li",{className:"highcharts-indicator-list",innerHTML:g.name},null,r);["click","touchstart"].forEach(function(c){f(p,c,function(){l.call(e,
b,h?a:m[q],g.type,y);h&&a.options&&k("input",{type:"hidden",name:"highcharts-id-"+q,value:a.options.id},null,y).setAttribute("highcharts-data-series-id",a.options.id)})})}});0<r.childNodes.length&&r.childNodes[0].click()},getNameType:function(a,b){var c=a.options,e=d.seriesTypes;e=e[b]&&e[b].prototype.nameBase||b.toUpperCase();c&&c.type&&(b=a.options.type,e=a.name);return{name:e,type:b}},listAllSeries:function(a,b,c,d,f){a="highcharts-"+b+"-type-"+a;var e;k("label",{innerHTML:this.lang[b]||b,htmlFor:a},
null,d);var g=k("select",{name:a,className:"highcharts-popup-field"},null,d);g.setAttribute("id","highcharts-select-"+b);c.series.forEach(function(a){e=a.options;!e.params&&e.id&&"highcharts-navigator-series"!==e.id&&k("option",{innerHTML:e.name||e.id,value:e.id},null,g)});l(f)&&(g.value=f)},addFormFields:function(a,b,c,d){var e=b.params||b.options.params,f=this.indicators.getNameType;d.innerHTML="";k("h3",{className:"highcharts-indicator-title",innerHTML:f(b,c).name},null,d);k("input",{type:"hidden",
name:"highcharts-type-"+c,value:c},null,d);this.indicators.listAllSeries.call(this,c,"series",a,d,b.linkedParent&&e.volumeSeriesID);e.volumeSeriesID&&this.indicators.listAllSeries.call(this,c,"volume",a,d,b.linkedParent&&b.linkedParent.options.id);this.indicators.addParamInputs.call(this,a,"params",e,c,d)},addParamInputs:function(b,d,f,g,k){var e=this,h=this.indicators.addParamInputs,m=this.addInput,l;a(f,function(a,f){l=d+"."+f;c(a)?h.call(e,b,l,a,g,k):"params.volumeSeriesID"!==l&&m.call(e,l,g,k,
[a,"text"])})},getAmount:function(){var b=0;a(this.series,function(a){var c=a.options;(a.params||c&&c.params)&&b++});return b}},tabs:{init:function(a){var b=this.tabs;a=this.indicators.getAmount.call(a);var c=b.addMenuItem.call(this,"add");b.addMenuItem.call(this,"edit",a);b.addContentItem.call(this,"add");b.addContentItem.call(this,"edit");b.switchTabs.call(this,a);b.selectTab.call(this,c,0)},addMenuItem:function(a,b){var c=this.popup.container,d="highcharts-tab-item",e=this.lang;0===b&&(d+=" highcharts-tab-disabled");
b=k("span",{innerHTML:e[a+"Button"]||a,className:d},null,c);b.setAttribute("highcharts-data-tab-type",a);return b},addContentItem:function(){return k("div",{className:"highcharts-tab-item-content"},null,this.popup.container)},switchTabs:function(a){var b=this,c;this.popup.container.querySelectorAll(".highcharts-tab-item").forEach(function(d,e){c=d.getAttribute("highcharts-data-tab-type");"edit"===c&&0===a||["click","touchstart"].forEach(function(a){f(d,a,function(){b.tabs.deselectAll.call(b);b.tabs.selectTab.call(b,
this,e)})})})},selectTab:function(a,b){var c=this.popup.container.querySelectorAll(".highcharts-tab-item-content");a.className+=" highcharts-tab-item-active";c[b].className+=" highcharts-tab-item-show"},deselectAll:function(){var a=this.popup.container,b=a.querySelectorAll(".highcharts-tab-item");a=a.querySelectorAll(".highcharts-tab-item-content");var c;for(c=0;c<b.length;c++)b[c].classList.remove("highcharts-tab-item-active"),a[c].classList.remove("highcharts-tab-item-show")}}};f(d.NavigationBindings,
"showPopup",function(a){this.popup||(this.popup=new d.Popup(this.chart.container,this.chart.options.navigation.iconsURL||this.chart.options.stockTools&&this.chart.options.stockTools.gui.iconsURL||"https://code.highcharts.com/8.0.4/gfx/stock-icons/"));this.popup.showForm(a.formType,this.chart,a.options,a.onSubmit)});f(d.NavigationBindings,"closePopup",function(){this.popup&&this.popup.closePopup()})});l(f,"masters/modules/annotations.src.js",[],function(){})});
//# sourceMappingURL=annotations.js.map