/*
 Highcharts JS v8.0.4 (2020-04-02)

 (c) 2009-2019 Sebastian Bochan, Rafal Sebestjanski

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/dumbbell",["highcharts"],function(h){b(h);b.Highcharts=h;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function h(b,c,h,f){b.hasOwnProperty(c)||(b[c]=f.apply(null,h))}b=b?b._modules:{};h(b,"modules/dumbbell.src.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,c){var h=c.extend,f=c.pick;c=c.seriesType;
var p=b.seriesTypes,t=b.Series.prototype,m=p.arearange.prototype,r=p.column.prototype,n=m.pointClass.prototype;c("dumbbell","arearange",{trackByArea:!1,fillColor:"none",lineWidth:0,pointRange:1,connectorWidth:1,stickyTracking:!1,groupPadding:.2,pointPadding:.1,lowColor:"#333333",states:{hover:{lineWidthPlus:0,connectorWidthPlus:1,halo:!1}}},{trackerGroups:["group","markerGroup","dataLabelsGroup"],drawTracker:b.TrackerMixin.drawTrackerPoint,drawGraph:b.noop,crispConnector:function(a,b){a[1]===a[4]&&
(a[1]=a[4]=Math.floor(a[1])+b%2/2);a[2]===a[5]&&(a[2]=a[5]=Math.floor(a[2])+b%2/2);return a},crispCol:r.crispCol,getConnectorAttribs:function(a){var b=this.chart,e=a.options,g=this.options,d=this.xAxis,k=this.yAxis,c=f(e.connectorWidth,g.connectorWidth),m=f(e.connectorColor,g.connectorColor,e.color,a.zone?a.zone.color:void 0,a.color),p=f(g.states&&g.states.hover&&g.states.hover.connectorWidthPlus,1),n=f(e.dashStyle,g.dashStyle),q=f(a.plotLow,a.plotY),l=k.toPixels(g.threshold||0,!0);l=f(a.plotHigh,
b.inverted?k.len-l:l);a.state&&(c+=p);0>q?q=0:q>=k.len&&(q=k.len);0>l?l=0:l>=k.len&&(l=k.len);if(0>a.plotX||a.plotX>d.len)c=0;a.upperGraphic&&(d={y:a.y,zone:a.zone},a.y=a.high,a.zone=a.zone?a.getZone():void 0,m=f(e.connectorColor,g.connectorColor,e.color,a.zone?a.zone.color:void 0,a.color),h(a,d));a={d:this.crispConnector(["M",a.plotX,q,"L",a.plotX,l],c)};b.styledMode||(a.stroke=m,a["stroke-width"]=c,n&&(a.dashstyle=n));return a},drawConnector:function(a){var b=f(this.options.animationLimit,250);
b=a.connector&&this.chart.pointCount<b?"animate":"attr";a.connector||(a.connector=this.chart.renderer.path().addClass("highcharts-lollipop-stem").attr({zIndex:-1}).add(this.markerGroup));a.connector[b](this.getConnectorAttribs(a))},getColumnMetrics:function(){var a=r.getColumnMetrics.apply(this,arguments);a.offset+=a.width/2;return a},translatePoint:m.translate,setShapeArgs:p.columnrange.prototype.translate,translate:function(){this.setShapeArgs.apply(this);this.translatePoint.apply(this,arguments);
this.points.forEach(function(a){var b=a.shapeArgs,e=a.pointWidth;a.plotX=b.x;b.x=a.plotX-e/2;a.tooltipPos=null});this.columnMetrics.offset-=this.columnMetrics.width/2},seriesDrawPoints:m.drawPoints,drawPoints:function(){var a=this.chart,b=this.points.length,e=this.lowColor=this.options.lowColor,g=0;for(this.seriesDrawPoints.apply(this,arguments);g<b;){var d=this.points[g];this.drawConnector(d);d.upperGraphic&&(d.upperGraphic.element.point=d,d.upperGraphic.addClass("highcharts-lollipop-high"));d.connector.element.point=
d;if(d.lowerGraphic){var c=d.zone&&d.zone.color;c=f(d.options.lowColor,e,d.options.color,c,d.color,this.color);a.styledMode||d.lowerGraphic.attr({fill:c});d.lowerGraphic.addClass("highcharts-lollipop-low")}g++}},markerAttribs:function(){var a=m.markerAttribs.apply(this,arguments);a.x=Math.floor(a.x);a.y=Math.floor(a.y);return a},pointAttribs:function(a,b){var e=t.pointAttribs.apply(this,arguments);"hover"===b&&delete e.fill;return e}},{destroyElements:n.destroyElements,isValid:n.isValid,pointSetState:n.setState,
setState:function(){var a=this.series,b=a.chart,e=a.options.marker,c=this.options,d=f(c.lowColor,a.options.lowColor,c.color,this.zone&&this.zone.color,this.color,a.color),k="attr";this.pointSetState.apply(this,arguments);this.state||(k="animate",this.lowerGraphic&&!b.styledMode&&(this.lowerGraphic.attr({fill:d}),this.upperGraphic&&(b={y:this.y,zone:this.zone},this.y=this.high,this.zone=this.zone?this.getZone():void 0,e=f(this.marker?this.marker.fillColor:void 0,e?e.fillColor:void 0,c.color,this.zone?
this.zone.color:void 0,this.color),this.upperGraphic.attr({fill:e}),h(this,b))));this.connector[k](a.getConnectorAttribs(this))}});""});h(b,"masters/modules/dumbbell.src.js",[],function(){})});
//# sourceMappingURL=dumbbell.js.map