/*
 Highcharts Gantt JS v8.0.4 (2020-04-02)

 Gantt series

 (c) 2016-2019 Lars A. V. Cabrera

 License: www.highcharts.com/license
*/
(function(n){"object"===typeof module&&module.exports?(n["default"]=n,module.exports=n):"function"===typeof define&&define.amd?define("highcharts/modules/gantt",["highcharts"],function(G){n(G);n.Highcharts=G;return n}):n("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(n){function G(v,a,m,t){v.hasOwnProperty(a)||(v[a]=t.apply(null,m))}n=n?n._modules:{};G(n,"parts-gantt/CurrentDateIndicator.js",[n["parts/Globals.js"],n["parts/Utilities.js"],n["parts/PlotLineOrBand.js"]],function(v,a,m){var t=
a.addEvent,r=a.merge;a=a.wrap;var w={currentDateIndicator:!0,color:"#ccd6eb",width:2,label:{format:"%a, %b %d %Y, %H:%M",formatter:function(a,m){return v.dateFormat(m,a)},rotation:0,style:{fontSize:"10px"}}};t(v.Axis,"afterSetOptions",function(){var a=this.options,m=a.currentDateIndicator;m&&(m="object"===typeof m?r(w,m):r(w),m.value=new Date,a.plotLines||(a.plotLines=[]),a.plotLines.push(m))});t(m,"render",function(){this.label&&this.label.attr({text:this.getLabelText(this.options.label)})});a(m.prototype,
"getLabelText",function(a,m){var x=this.options;return x.currentDateIndicator&&x.label&&"function"===typeof x.label.formatter?(x.value=new Date,x.label.formatter.call(this,x.value,x.label.format)):a.call(this,m)})});G(n,"parts-gantt/GridAxis.js",[n["parts/Globals.js"],n["parts/Tick.js"],n["parts/Utilities.js"]],function(v,a,m){var t=m.addEvent,r=m.defined,w=m.erase,K=m.find,E=m.isArray,x=m.isNumber,e=m.merge,k=m.pick,p=m.timeUnits,u=m.wrap,F=v.dateFormat,D=function(c){return m.isObject(c,!0)},C=v.Chart,
g=v.Axis,f=function(c){var b=c.options;b.labels||(b.labels={});b.labels.align=k(b.labels.align,"center");c.categories||(b.showLastLabel=!1);c.labelRotation=0;b.labels.rotation=0},A={top:0,right:1,bottom:2,left:3,0:"top",1:"right",2:"bottom",3:"left"};g.prototype.isOuterAxis=function(){var c=this,b=c.columnIndex,l=c.linkedParent&&c.linkedParent.columns||c.columns,d=b?c.linkedParent:c,f=-1,A=0;c.chart[c.coll].forEach(function(b,l){b.side!==c.side||b.options.isInternal||(A=l,b===d&&(f=l))});return A===
f&&(x(b)?l.length===b:!0)};g.prototype.getMaxLabelDimensions=function(c,b){var l={width:0,height:0};b.forEach(function(b){b=c[b];if(D(b)){var d=D(b.label)?b.label:{};b=d.getBBox?d.getBBox().height:0;d.textStr&&!x(d.textPxLength)&&(d.textPxLength=d.getBBox().width);d=x(d.textPxLength)?Math.round(d.textPxLength):0;l.height=Math.max(b,l.height);l.width=Math.max(d,l.width)}});return l};v.dateFormats.W=function(c){c=new this.Date(c);var b=(this.get("Day",c)+6)%7,l=new this.Date(c.valueOf());this.set("Date",
l,this.get("Date",c)-b+3);b=new this.Date(this.get("FullYear",l),0,1);4!==this.get("Day",b)&&(this.set("Month",c,0),this.set("Date",c,1+(11-this.get("Day",b))%7));return(1+Math.floor((l.valueOf()-b.valueOf())/6048E5)).toString()};v.dateFormats.E=function(c){return F("%a",c,!0).charAt(0)};t(a,"afterGetLabelPosition",function(c){var b=this.label,l=this.axis,d=l.reversed,f=l.chart,g=l.options,B=g&&D(g.grid)?g.grid:{};g=l.options.labels;var z=g.align,h=A[l.side],q=c.tickmarkOffset,y=l.tickPositions,H=
this.pos-q;y=x(y[c.index+1])?y[c.index+1]-q:l.max+q;var I=l.tickSize("tick",!0);q=E(I)?I[0]:0;I=I&&I[1]/2;if(!0===B.enabled){if("top"===h){B=l.top+l.offset;var e=B-q}else"bottom"===h?(e=f.chartHeight-l.bottom+l.offset,B=e+q):(B=l.top+l.len-l.translate(d?y:H),e=l.top+l.len-l.translate(d?H:y));"right"===h?(h=f.chartWidth-l.right+l.offset,d=h+q):"left"===h?(d=l.left+l.offset,h=d-q):(h=Math.round(l.left+l.translate(d?y:H))-I,d=Math.round(l.left+l.translate(d?H:y))-I);this.slotWidth=d-h;c.pos.x="left"===
z?h:"right"===z?d:h+(d-h)/2;c.pos.y=e+(B-e)/2;f=f.renderer.fontMetrics(g.style.fontSize,b.element);b=b.getBBox().height;g.useHTML?c.pos.y+=f.b+-(b/2):(b=Math.round(b/f.h),c.pos.y+=(f.b-(f.h-f.f))/2+-((b-1)*f.h/2));c.pos.x+=l.horiz&&g.x||0}});t(g,"afterTickSize",function(c){var b=g.defaultLeftAxisOptions,l=this.horiz,d=this.options.grid;d=void 0===d?{}:d;var f=this.maxLabelDimensions;d.enabled&&(b=2*Math.abs(b.labels.x),l=l?d.cellHeight||b+f.height:b+f.width,E(c.tickSize)?c.tickSize[0]=l:c.tickSize=
[l])});t(g,"afterGetTitlePosition",function(c){var b=this.options;if(!0===(b&&D(b.grid)?b.grid:{}).enabled){var l=this.axisTitle,d=l&&l.getBBox().width,f=this.horiz,g=this.left,B=this.top,z=this.width,h=this.height,q=b.title;b=this.opposite;var y=this.offset,H=this.tickSize()||[0],I=q.x||0,e=q.y||0,p=k(q.margin,f?5:10);l=this.chart.renderer.fontMetrics(q.style&&q.style.fontSize,l).f;H=(f?B+h:g)+H[0]/2*(b?-1:1)*(f?1:-1)+(this.side===A.bottom?l:0);c.titlePosition.x=f?g-d/2-p+I:H+(b?z:0)+y+I;c.titlePosition.y=
f?H-(b?h:0)+(b?l:-l)/2+y+e:B-p+e}});u(g.prototype,"unsquish",function(c){var b=this.options;return!0===(b&&D(b.grid)?b.grid:{}).enabled&&this.categories?this.tickInterval:c.apply(this,Array.prototype.slice.call(arguments,1))});t(g,"afterSetOptions",function(c){var b=this.options;c=c.userOptions;var l=b&&D(b.grid)?b.grid:{};if(!0===l.enabled){var d=e(!0,{className:"highcharts-grid-axis "+(c.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},
week:{list:["Week %W","W%W"]},month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},c);"xAxis"===this.coll&&(r(c.linkedTo)&&!r(c.tickPixelInterval)&&(d.tickPixelInterval=350),r(c.tickPixelInterval)||!r(c.linkedTo)||r(c.tickPositioner)||r(c.tickInterval)||(d.tickPositioner=
function(b,c){var l=this.linkedParent&&this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(l){var f,h=d.units;for(f=0;f<h.length;f++)if(h[f][0]===l.unitName){var q=f;break}if(h[q+1]){var y=h[q+1][0];var H=(h[q+1][1]||[1])[0]}else"year"===l.unitName&&(y="year",H=10*l.count);l=p[y];this.tickInterval=l*H;return this.getTimeTicks({unitRange:l,count:H,unitName:y},b,c,this.options.startOfWeek)}}));e(!0,this.options,d);this.horiz&&(b.minPadding=k(c.minPadding,0),b.maxPadding=k(c.maxPadding,
0));x(b.grid.borderWidth)&&(b.tickWidth=b.lineWidth=l.borderWidth)}});t(g,"afterSetAxisTranslation",function(){var c=this.options,b=c&&D(c.grid)?c.grid:{},l=this.tickPositions&&this.tickPositions.info,d=this.userOptions.labels||{};this.horiz&&(!0===b.enabled&&this.series.forEach(function(b){b.options.pointRange=0}),l&&(!1===c.dateTimeLabelFormats[l.unitName].range||1<l.count)&&!r(d.align)&&(c.labels.align="left",r(d.x)||(c.labels.x=3)))});t(g,"trimTicks",function(){var c=this.options,b=c&&D(c.grid)?
c.grid:{},l=this.categories,d=this.tickPositions,f=d[0],g=d[d.length-1],B=this.linkedParent&&this.linkedParent.min||this.min,z=this.linkedParent&&this.linkedParent.max||this.max,h=this.tickInterval;!0!==b.enabled||l||!this.horiz&&!this.isLinked||(f<B&&f+h>B&&!c.startOnTick&&(d[0]=B),g>z&&g-h<z&&!c.endOnTick&&(d[d.length-1]=z))});t(g,"afterRender",function(){var c=this.options,b=c&&D(c.grid)?c.grid:{},l=this.chart.renderer;if(!0===b.enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,
this.tickPositions);this.rightWall&&this.rightWall.destroy();if(this.isOuterAxis()&&this.axisLine){var d=c.lineWidth;if(d){var f=this.getLinePath(d);var g=f.indexOf("M")+1;var B=f.indexOf("L")+1;b=f.indexOf("M")+2;var z=f.indexOf("L")+2;var h=(this.tickSize("tick")[0]-1)*(this.side===A.top||this.side===A.left?-1:1);this.horiz?(f[b]+=h,f[z]+=h):(f[g]+=h,f[B]+=h);this.axisLineExtra?this.axisLineExtra.animate({d:f}):(this.axisLineExtra=l.path(f).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),
l.styledMode||this.axisLineExtra.attr({stroke:c.lineColor,"stroke-width":d}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(this.columns||[]).forEach(function(b){b.render()})}});var d={afterGetOffset:function(){(this.columns||[]).forEach(function(c){c.getOffset()})},afterInit:function(){var c=this.chart,b=this.userOptions,d=this.options;d=d&&D(d.grid)?d.grid:{};d.enabled&&(f(this),u(this,"labelFormatter",function(b){var c=this.axis,h=c.tickPositions,q=this.value,d=(c.isLinked?c.linkedParent:c).series[0],
l=q===h[0];h=q===h[h.length-1];d=d&&K(d.options.data,function(b){return b[c.isXAxis?"x":"y"]===q});this.isFirst=l;this.isLast=h;this.point=d;return b.call(this)}));if(d.columns)for(var A=this.columns=[],k=this.columnIndex=0;++k<d.columns.length;){var p=e(b,d.columns[d.columns.length-k-1],{linkedTo:0,type:"category"});delete p.grid.columns;p=new g(this.chart,p,!0);p.isColumn=!0;p.columnIndex=k;w(c.axes,p);w(c[this.coll],p);A.push(p)}},afterSetOptions:function(c){c=(c=c.userOptions)&&D(c.grid)?c.grid:
{};var b=c.columns;c.enabled&&b&&e(!0,this.options,b[b.length-1])},afterSetScale:function(){(this.columns||[]).forEach(function(c){c.setScale()})},destroy:function(c){(this.columns||[]).forEach(function(b){b.destroy(c.keepEvents)})},init:function(c){var b=(c=c.userOptions)&&D(c.grid)?c.grid:{};b.enabled&&r(b.borderColor)&&(c.tickColor=c.lineColor=b.borderColor)}};Object.keys(d).forEach(function(c){t(g,c,d[c])});t(C,"afterSetChartSize",function(){this.axes.forEach(function(c){(c.columns||[]).forEach(function(b){b.setAxisSize();
b.setAxisTranslation()})})})});G(n,"modules/static-scale.src.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(v,a){var m=a.addEvent,t=a.defined,r=a.isNumber,w=a.pick;a=v.Chart;m(v.Axis,"afterSetOptions",function(){var a=this.chart.options&&this.chart.options.chart;!this.horiz&&r(this.options.staticScale)&&(!a.height||a.scrollablePlotArea&&a.scrollablePlotArea.minHeight)&&(this.staticScale=this.options.staticScale)});a.prototype.adjustHeight=function(){"adjustHeight"!==this.redrawTrigger&&
((this.axes||[]).forEach(function(a){var m=a.chart,x=!!m.initiatedScale&&m.options.animation,e=a.options.staticScale;if(a.staticScale&&t(a.min)){var k=w(a.brokenAxis&&a.brokenAxis.unitLength,a.max+a.tickInterval-a.min)*e;k=Math.max(k,e);e=k-m.plotHeight;1<=Math.abs(e)&&(m.plotHeight=k,m.redrawTrigger="adjustHeight",m.setSize(void 0,m.chartHeight+e,x));a.series.forEach(function(e){(e=e.sharedClipKey&&m[e.sharedClipKey])&&e.attr({height:m.plotHeight})})}}),this.initiatedScale=!0);this.redrawTrigger=
null};m(a,"render",a.prototype.adjustHeight)});G(n,"mixins/tree-series.js",[n["parts/Color.js"],n["parts/Utilities.js"]],function(v,a){var m=a.extend,t=a.isArray,r=a.isNumber,w=a.isObject,n=a.merge,E=a.pick;return{getColor:function(a,e){var k=e.index,p=e.mapOptionsToLevel,u=e.parentColor,m=e.parentColorIndex,D=e.series,C=e.colors,g=e.siblings,f=D.points,A=D.chart.options.chart,d;if(a){f=f[a.i];a=p[a.level]||{};if(p=f&&a.colorByPoint){var c=f.index%(C?C.length:A.colorCount);var b=C&&C[c]}if(!D.chart.styledMode){C=
f&&f.options.color;A=a&&a.color;if(d=u)d=(d=a&&a.colorVariation)&&"brightness"===d.key?v.parse(u).brighten(k/g*d.to).get():u;d=E(C,A,b,d,D.color)}var l=E(f&&f.options.colorIndex,a&&a.colorIndex,c,m,e.colorIndex)}return{color:d,colorIndex:l}},getLevelOptions:function(a){var e=null;if(w(a)){e={};var k=r(a.from)?a.from:1;var p=a.levels;var u={};var F=w(a.defaults)?a.defaults:{};t(p)&&(u=p.reduce(function(e,a){if(w(a)&&r(a.level)){var g=n({},a);var f="boolean"===typeof g.levelIsConstant?g.levelIsConstant:
F.levelIsConstant;delete g.levelIsConstant;delete g.level;a=a.level+(f?0:k-1);w(e[a])?m(e[a],g):e[a]=g}return e},{}));p=r(a.to)?a.to:1;for(a=0;a<=p;a++)e[a]=n({},F,w(u[a])?u[a]:{})}return e},setTreeValues:function p(e,a){var k=a.before,F=a.idRoot,D=a.mapIdToNode[F],C=a.points[e.i],g=C&&C.options||{},f=0,A=[];m(e,{levelDynamic:e.level-(("boolean"===typeof a.levelIsConstant?a.levelIsConstant:1)?0:D.level),name:E(C&&C.name,""),visible:F===e.id||("boolean"===typeof a.visible?a.visible:!1)});"function"===
typeof k&&(e=k(e,a));e.children.forEach(function(d,c){var b=m({},a);m(b,{index:c,siblings:e.children.length,visible:e.visible});d=p(d,b);A.push(d);d.visible&&(f+=d.val)});e.visible=0<f||e.visible;k=E(g.value,f);m(e,{children:A,childrenTotal:f,isLeaf:e.visible&&!f,val:k});return e},updateRootId:function(e){if(w(e)){var a=w(e.options)?e.options:{};a=E(e.rootNode,a.rootId,"");w(e.userOptions)&&(e.userOptions.rootId=a);e.rootNode=a}return a}}});G(n,"parts-gantt/Tree.js",[n["parts/Utilities.js"]],function(v){var a=
v.extend,m=v.isNumber,t=v.pick,r=function(a,m){var x=a.reduce(function(a,k){var e=t(k.parent,"");"undefined"===typeof a[e]&&(a[e]=[]);a[e].push(k);return a},{});Object.keys(x).forEach(function(a,k){var e=x[a];""!==a&&-1===m.indexOf(a)&&(e.forEach(function(a){k[""].push(a)}),delete k[a])});return x},w=function(r,v,x,e,k,p){var u=0,F=0,D=p&&p.after,C=p&&p.before;v={data:e,depth:x-1,id:r,level:x,parent:v};var g,f;"function"===typeof C&&C(v,p);C=(k[r]||[]).map(function(a){var d=w(a.id,r,x+1,a,k,p),c=
a.start;a=!0===a.milestone?c:a.end;g=!m(g)||c<g?c:g;f=!m(f)||a>f?a:f;u=u+1+d.descendants;F=Math.max(d.height+1,F);return d});e&&(e.start=t(e.start,g),e.end=t(e.end,f));a(v,{children:C,descendants:u,height:F});"function"===typeof D&&D(v,p);return v};return{getListOfParents:r,getNode:w,getTree:function(a,m){var x=a.map(function(a){return a.id});a=r(a,x);return w("",null,1,null,a,m)}}});G(n,"modules/broken-axis.src.js",[n["parts/Axis.js"],n["parts/Globals.js"],n["parts/Utilities.js"],n["parts/Stacking.js"]],
function(v,a,m,t){var r=m.addEvent,w=m.find,n=m.fireEvent,E=m.isArray,x=m.isNumber,e=m.pick,k=a.Series,p=function(){function a(a){this.hasBreaks=!1;this.axis=a}a.isInBreak=function(a,e){var k=a.repeat||Infinity,g=a.from,f=a.to-a.from;e=e>=g?(e-g)%k:k-(g-e)%k;return a.inclusive?e<=f:e<f&&0!==e};a.lin2Val=function(e){var k=this.brokenAxis;k=k&&k.breakArray;if(!k)return e;var p;for(p=0;p<k.length;p++){var g=k[p];if(g.from>=e)break;else g.to<e?e+=g.len:a.isInBreak(g,e)&&(e+=g.len)}return e};a.val2Lin=
function(e){var k=this.brokenAxis;k=k&&k.breakArray;if(!k)return e;var p=e,g;for(g=0;g<k.length;g++){var f=k[g];if(f.to<=e)p-=f.len;else if(f.from>=e)break;else if(a.isInBreak(f,e)){p-=e-f.from;break}}return p};a.prototype.findBreakAt=function(a,e){return w(e,function(e){return e.from<a&&a<e.to})};a.prototype.isInAnyBreak=function(k,p){var u=this.axis,g=u.options.breaks,f=g&&g.length,A;if(f){for(;f--;)if(a.isInBreak(g[f],k)){var d=!0;A||(A=e(g[f].showPoints,!u.isXAxis))}var c=d&&p?d&&!A:d}return c};
a.prototype.setBreaks=function(k,p){var u=this,g=u.axis,f=E(k)&&!!k.length;g.isDirty=u.hasBreaks!==f;u.hasBreaks=f;g.options.breaks=g.userOptions.breaks=k;g.forceRedraw=!0;g.series.forEach(function(f){f.isDirty=!0});f||g.val2lin!==a.val2Lin||(delete g.val2lin,delete g.lin2val);f&&(g.userOptions.ordinal=!1,g.lin2val=a.lin2Val,g.val2lin=a.val2Lin,g.setExtremes=function(f,d,c,b,l){if(u.hasBreaks){for(var a,e=this.options.breaks;a=u.findBreakAt(f,e);)f=a.to;for(;a=u.findBreakAt(d,e);)d=a.from;d<f&&(d=
f)}v.prototype.setExtremes.call(this,f,d,c,b,l)},g.setAxisTranslation=function(f){v.prototype.setAxisTranslation.call(this,f);u.unitLength=null;if(u.hasBreaks){f=g.options.breaks||[];var d=[],c=[],b=0,l,k=g.userMin||g.min,p=g.userMax||g.max,A=e(g.pointRangePadding,0),B;f.forEach(function(b){l=b.repeat||Infinity;a.isInBreak(b,k)&&(k+=b.to%l-k%l);a.isInBreak(b,p)&&(p-=p%l-b.from%l)});f.forEach(function(b){h=b.from;for(l=b.repeat||Infinity;h-l>k;)h-=l;for(;h<k;)h+=l;for(B=h;B<p;B+=l)d.push({value:B,
move:"in"}),d.push({value:B+(b.to-b.from),move:"out",size:b.breakSize})});d.sort(function(b,h){return b.value===h.value?("in"===b.move?0:1)-("in"===h.move?0:1):b.value-h.value});var z=0;var h=k;d.forEach(function(d){z+="in"===d.move?1:-1;1===z&&"in"===d.move&&(h=d.value);0===z&&(c.push({from:h,to:d.value,len:d.value-h-(d.size||0)}),b+=d.value-h-(d.size||0))});g.breakArray=u.breakArray=c;u.unitLength=p-k-b+A;n(g,"afterBreaks");g.staticScale?g.transA=g.staticScale:u.unitLength&&(g.transA*=(p-g.min+
A)/u.unitLength);A&&(g.minPixelPadding=g.transA*g.minPointOffset);g.min=k;g.max=p}});e(p,!0)&&g.chart.redraw()};return a}();a=function(){function a(){}a.compose=function(a,u){a.keepProps.push("brokenAxis");var m=k.prototype;m.drawBreaks=function(a,f){var k=this,d=k.points,c,b,l,g;if(a&&a.brokenAxis&&a.brokenAxis.hasBreaks){var p=a.brokenAxis;f.forEach(function(f){c=p&&p.breakArray||[];b=a.isXAxis?a.min:e(k.options.threshold,a.min);d.forEach(function(d){g=e(d["stack"+f.toUpperCase()],d[f]);c.forEach(function(c){if(x(b)&&
x(g)){l=!1;if(b<c.from&&g>c.to||b>c.from&&g<c.from)l="pointBreak";else if(b<c.from&&g>c.from&&g<c.to||b>c.from&&g>c.to&&g<c.from)l="pointInBreak";l&&n(a,l,{point:d,brk:c})}})})})}};m.gappedPath=function(){var a=this.currentDataGrouping,f=a&&a.gapSize;a=this.options.gapSize;var e=this.points.slice(),d=e.length-1,c=this.yAxis,b;if(a&&0<d)for("value"!==this.options.gapUnit&&(a*=this.basePointRange),f&&f>a&&f>=this.basePointRange&&(a=f),b=void 0;d--;)b&&!1!==b.visible||(b=e[d+1]),f=e[d],!1!==b.visible&&
!1!==f.visible&&(b.x-f.x>a&&(b=(f.x+b.x)/2,e.splice(d+1,0,{isNull:!0,x:b}),this.options.stacking&&(b=c.stacks[this.stackKey][b]=new t(c,c.options.stackLabels,!1,b,this.stack),b.total=0)),b=f);return this.getGraphPath(e)};r(a,"init",function(){this.brokenAxis||(this.brokenAxis=new p(this))});r(a,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,!1)});r(a,"afterSetTickPositions",function(){var a=this.brokenAxis;if(a&&a.hasBreaks){var f=this.tickPositions,
e=this.tickPositions.info,d=[],c;for(c=0;c<f.length;c++)a.isInAnyBreak(f[c])||d.push(f[c]);this.tickPositions=d;this.tickPositions.info=e}});r(a,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});r(u,"afterGeneratePoints",function(){var a=this.options.connectNulls,f=this.points,e=this.xAxis,d=this.yAxis;if(this.isDirty)for(var c=f.length;c--;){var b=f[c],l=!(null===b.y&&!1===a)&&(e&&e.brokenAxis&&e.brokenAxis.isInAnyBreak(b.x,!0)||d&&d.brokenAxis&&
d.brokenAxis.isInAnyBreak(b.y,!0));b.visible=l?!1:!1!==b.options.visible}});r(u,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,e(this.pointArrayMap,["y"]))})};return a}();a.compose(v,k);return a});G(n,"parts-gantt/TreeGrid.js",[n["parts/Globals.js"],n["mixins/tree-series.js"],n["parts/Tick.js"],n["parts-gantt/Tree.js"],n["parts/Utilities.js"]],function(v,a,m,t,r){var w=r.addEvent,n=r.defined,E=r.fireEvent,x=r.extend,e=r.isNumber,k=r.isString,p=r.merge,u=r.pick,
F=r.wrap,D=function(b){return Array.prototype.slice.call(b,1)},C=r.find,g=a.getLevelOptions,f=function(b){return r.isObject(b,!0)};v=v.Axis;a=function(b,c){var h;for(h in c)if(Object.hasOwnProperty.call(c,h)){var d=c[h];F(b,h,d)}};var A=function(b,c){var h=b.collapseStart;b=b.collapseEnd;b>=c&&(h-=.5);return{from:h,to:b,showPoints:!1}},d=function(b){return Object.keys(b.mapOfPosToGridNode).reduce(function(c,h){h=+h;!(b.min<=h&&b.max>=h)||b.brokenAxis&&b.brokenAxis.isInAnyBreak(h)||c.push(h);return c},
[])},c=function(b,c){var h=b.options.breaks||[],d=A(c,b.max);return h.some(function(b){return b.from===d.from&&b.to===d.to})},b=function(b,c){var h=b.options.breaks||[];b=A(c,b.max);h.push(b);return h},l=function(b,c){var h=b.options.breaks||[],d=A(c,b.max);return h.reduce(function(b,c){c.to===d.to&&c.from===d.from||b.push(c);return b},[])},O=function(b,c){var h=b.labelIcon,d=!h,l=c.renderer,f=c.xy,a=c.options,z=a.width,k=a.height,g=f.x-z/2-a.padding;f=f.y-k/2;var p=c.collapsed?90:180,O=c.show&&e(f);
d&&(b.labelIcon=h=l.path(l.symbols[a.type](a.x,a.y,z,k)).addClass("highcharts-label-icon").add(c.group));O||h.attr({y:-9999});l.styledMode||h.attr({"stroke-width":1,fill:u(c.color,"#666666")}).css({cursor:"pointer",stroke:a.lineColor,strokeWidth:a.lineWidth});h[d?"attr":"animate"]({translateX:g,translateY:f,rotation:p})},J=function(b,c,h){var d=[],l=[],a={},z={},e=-1,g="boolean"===typeof c?c:!1;b=t.getTree(b,{after:function(b){b=z[b.pos];var c=0,h=0;b.children.forEach(function(b){h+=b.descendants+
1;c=Math.max(b.height+1,c)});b.descendants=h;b.height=c;b.collapsed&&l.push(b)},before:function(b){var c=f(b.data)?b.data:{},h=k(c.name)?c.name:"",l=a[b.parent];l=f(l)?z[l.pos]:null;var q=function(b){return b.name===h},y;g&&f(l)&&(y=C(l.children,q))?(q=y.pos,y.nodes.push(b)):q=e++;z[q]||(z[q]=y={depth:l?l.depth+1:0,name:h,nodes:[b],children:[],pos:q},-1!==q&&d.push(h),f(l)&&l.children.push(y));k(b.id)&&(a[b.id]=b);!0===c.collapsed&&(y.collapsed=!0);b.pos=q}});z=function(b,c){var h=function(b,d,l){var q=
d+(-1===d?0:c-1),a=(q-d)/2,y=d+a;b.nodes.forEach(function(b){var c=b.data;f(c)&&(c.y=d+c.seriesIndex,delete c.seriesIndex);b.pos=y});l[y]=b;b.pos=y;b.tickmarkOffset=a+.5;b.collapseStart=q+.5;b.children.forEach(function(b){h(b,q+1,l);q=b.collapseEnd-.5});b.collapseEnd=q+.5;return l};return h(b["-1"],-1,{})}(z,h);return{categories:d,mapOfIdToNode:a,mapOfPosToGridNode:z,collapsedNodes:l,tree:b}},P=function(c){c.target.axes.filter(function(b){return"treegrid"===b.options.type}).forEach(function(d){var h=
d.options||{},l=h.labels,a,e=h.uniqueNames,z=0;if(!d.mapOfPosToGridNode||d.series.some(function(b){return!b.hasRendered||b.isDirtyData||b.isDirty})){h=d.series.reduce(function(b,c){c.visible&&(c.options.data.forEach(function(c){f(c)&&(c.seriesIndex=z,b.push(c))}),!0===e&&z++);return b},[]);var k=J(h,e,!0===e?z:1);d.categories=k.categories;d.mapOfPosToGridNode=k.mapOfPosToGridNode;d.hasNames=!0;d.tree=k.tree;d.series.forEach(function(b){var c=b.options.data.map(function(b){return f(b)?p(b):b});b.visible&&
b.setData(c,!1)});d.mapOptionsToLevel=g({defaults:l,from:1,levels:l.levels,to:d.tree.height});"beforeRender"===c.type&&(a=w(d,"foundExtremes",function(){k.collapsedNodes.forEach(function(c){c=b(d,c);d.brokenAxis&&d.brokenAxis.setBreaks(c,!1)});a()}))}})};a(v.prototype,{init:function(b,c,h){var d="treegrid"===h.type;d&&(w(c,"beforeRender",P),w(c,"beforeRedraw",P),h=p({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",x:-5,y:-5,
height:10,width:10,padding:5}},uniqueNames:!1},h,{reversed:!0,grid:{columns:void 0}}));b.apply(this,[c,h]);d&&(this.hasNames=!0,this.options.showLastLabel=!0)},getMaxLabelDimensions:function(b){var c=this.options,h=c&&c.labels;c=h&&e(h.indentation)?c.labels.indentation:0;h=b.apply(this,D(arguments));if("treegrid"===this.options.type&&this.mapOfPosToGridNode){var d=this.mapOfPosToGridNode[-1].height;h.width+=c*(d-1)}return h},generateTick:function(b,c){var h=f(this.mapOptionsToLevel)?this.mapOptionsToLevel:
{},d=this.ticks,l=d[c],a;if("treegrid"===this.options.type){var e=this.mapOfPosToGridNode[c];(h=h[e.depth])&&(a={labels:h});l?(l.parameters.category=e.name,l.options=a,l.addLabel()):d[c]=new m(this,c,null,void 0,{category:e.name,tickmarkOffset:e.tickmarkOffset,options:a})}else b.apply(this,D(arguments))},setTickInterval:function(b){var c=this.options;"treegrid"===c.type?(this.min=u(this.userMin,c.min,this.dataMin),this.max=u(this.userMax,c.max,this.dataMax),E(this,"foundExtremes"),this.setAxisTranslation(!0),
this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?d(this):[]):b.apply(this,D(arguments))}});a(m.prototype,{getLabelPosition:function(b,c,h,d,l,a,k,g,p){var q=u(this.options&&this.options.labels,a);a=this.pos;var y=this.axis,z="treegrid"===y.options.type;b=b.apply(this,[c,h,d,l,q,k,g,p]);z&&(c=q&&f(q.symbol)?q.symbol:{},q=q&&e(q.indentation)?q.indentation:0,a=(a=(y=y.mapOfPosToGridNode)&&y[a])&&a.depth||1,b.x+=c.width+2*c.padding+(a-1)*q);return b},renderLabel:function(b){var d=
this,h=d.pos,l=d.axis,a=d.label,e=l.mapOfPosToGridNode,k=l.options,g=u(d.options&&d.options.labels,k&&k.labels),p=g&&f(g.symbol)?g.symbol:{},A=(e=e&&e[h])&&e.depth;k="treegrid"===k.type;var J=!(!a||!a.element),m=-1<l.tickPositions.indexOf(h);h=l.chart.styledMode;k&&e&&J&&a.addClass("highcharts-treegrid-node-level-"+A);b.apply(d,D(arguments));k&&e&&J&&0<e.descendants&&(l=c(l,e),O(d,{color:!h&&a.styles.color,collapsed:l,group:a.parentGroup,options:p,renderer:a.renderer,show:m,xy:a.xy}),p="highcharts-treegrid-node-"+
(l?"expanded":"collapsed"),a.addClass("highcharts-treegrid-node-"+(l?"collapsed":"expanded")).removeClass(p),h||a.css({cursor:"pointer"}),[a,d.labelIcon].forEach(function(b){b.attachedTreeGridEvents||(w(b.element,"mouseover",function(){a.addClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:"underline"})}),w(b.element,"mouseout",function(){var b=n(g.style)?g.style:{};a.removeClass("highcharts-treegrid-node-active");a.renderer.styledMode||a.css({textDecoration:b.textDecoration})}),
w(b.element,"click",function(){d.toggleCollapse()}),b.attachedTreeGridEvents=!0)}))}});x(m.prototype,{collapse:function(c){var d=this.axis,h=d.brokenAxis;d=b(d,d.mapOfPosToGridNode[this.pos]);h&&h.setBreaks(d,u(c,!0))},expand:function(b){var c=this.axis,d=c.brokenAxis;c=l(c,c.mapOfPosToGridNode[this.pos]);d&&d.setBreaks(c,u(b,!0))},toggleCollapse:function(d){var a=this.axis,h=a.brokenAxis,f=a.mapOfPosToGridNode[this.pos];a=c(a,f)?l(a,f):b(a,f);h&&h.setBreaks(a,u(d,!0))}});v.prototype.utils={getNode:t.getNode}});
G(n,"parts-gantt/PathfinderAlgorithms.js",[n["parts/Utilities.js"]],function(v){function a(a,e,u){u=u||0;var k=a.length-1;e-=1e-7;for(var p,m;u<=k;)if(p=k+u>>1,m=e-a[p].xMin,0<m)u=p+1;else if(0>m)k=p-1;else return p;return 0<u?u-1:0}function m(e,p){for(var k=a(e,p.x+1)+1;k--;){var m;if(m=e[k].xMax>=p.x)m=e[k],m=p.x<=m.xMax&&p.x>=m.xMin&&p.y<=m.yMax&&p.y>=m.yMin;if(m)return k}return-1}function t(a){var e=[];if(a.length){e.push("M",a[0].start.x,a[0].start.y);for(var k=0;k<a.length;++k)e.push("L",a[k].end.x,
a[k].end.y)}return e}function r(a,e){a.yMin=x(a.yMin,e.yMin);a.yMax=E(a.yMax,e.yMax);a.xMin=x(a.xMin,e.xMin);a.xMax=E(a.xMax,e.xMax)}var n=v.extend,K=v.pick,E=Math.min,x=Math.max,e=Math.abs;return{straight:function(a,e){return{path:["M",a.x,a.y,"L",e.x,e.y],obstacles:[{start:a,end:e}]}},simpleConnect:n(function(a,p,u){function k(b,c,d,a,f){b={x:b.x,y:b.y};b[c]=d[a||c]+(f||0);return b}function x(b,c,d){var a=e(c[d]-b[d+"Min"])>e(c[d]-b[d+"Max"]);return k(c,d,b,d+(a?"Max":"Min"),a?1:-1)}var r=[],g=
K(u.startDirectionX,e(p.x-a.x)>e(p.y-a.y))?"x":"y",f=u.chartObstacles,A=m(f,a);u=m(f,p);if(-1<u){var d=f[u];u=x(d,p,g);d={start:u,end:p};var c=u}else c=p;-1<A&&(f=f[A],u=x(f,a,g),r.push({start:a,end:u}),u[g]>=a[g]===u[g]>=c[g]&&(g="y"===g?"x":"y",p=a[g]<p[g],r.push({start:u,end:k(u,g,f,g+(p?"Max":"Min"),p?1:-1)}),g="y"===g?"x":"y"));a=r.length?r[r.length-1].end:a;u=k(a,g,c);r.push({start:a,end:u});g=k(u,"y"===g?"x":"y",c);r.push({start:u,end:g});r.push(d);return{path:t(r),obstacles:r}},{requiresObstacles:!0}),
fastAvoid:n(function(k,p,u){function n(b,c,d){var h,l=b.x<c.x?1:-1;if(b.x<c.x){var f=b;var q=c}else f=c,q=b;if(b.y<c.y){var e=b;var y=c}else e=c,y=b;for(h=0>l?E(a(B,q.x),B.length-1):0;B[h]&&(0<l&&B[h].xMin<=q.x||0>l&&B[h].xMax>=f.x);){if(B[h].xMin<=q.x&&B[h].xMax>=f.x&&B[h].yMin<=y.y&&B[h].yMax>=e.y)return d?{y:b.y,x:b.x<c.x?B[h].xMin-1:B[h].xMax+1,obstacle:B[h]}:{x:b.x,y:b.y<c.y?B[h].yMin-1:B[h].yMax+1,obstacle:B[h]};h+=l}return c}function v(b,c,d,h,a){var l=a.soft,f=a.hard,q=h?"x":"y",y={x:c.x,
y:c.y},g={x:c.x,y:c.y};a=b[q+"Max"]>=l[q+"Max"];l=b[q+"Min"]<=l[q+"Min"];var k=b[q+"Max"]>=f[q+"Max"];f=b[q+"Min"]<=f[q+"Min"];var p=e(b[q+"Min"]-c[q]),z=e(b[q+"Max"]-c[q]);d=10>e(p-z)?c[q]<d[q]:z<p;g[q]=b[q+"Min"];y[q]=b[q+"Max"];b=n(c,g,h)[q]!==g[q];c=n(c,y,h)[q]!==y[q];d=b?c?d:!0:c?!1:d;d=l?a?d:!0:a?!1:d;return f?k?d:!0:k?!1:d}function w(b,d,h){if(b.x===d.x&&b.y===d.y)return[];var a=h?"x":"y",f=u.obstacleOptions.margin;var q={soft:{xMin:l,xMax:O,yMin:J,yMax:P},hard:u.hardBounds};var e=m(B,b);if(-1<
e){e=B[e];q=v(e,b,d,h,q);r(e,u.hardBounds);var y=h?{y:b.y,x:e[q?"xMax":"xMin"]+(q?1:-1)}:{x:b.x,y:e[q?"yMax":"yMin"]+(q?1:-1)};var g=m(B,y);-1<g&&(g=B[g],r(g,u.hardBounds),y[a]=q?x(e[a+"Max"]-f+1,(g[a+"Min"]+e[a+"Max"])/2):E(e[a+"Min"]+f-1,(g[a+"Max"]+e[a+"Min"])/2),b.x===y.x&&b.y===y.y?(c&&(y[a]=q?x(e[a+"Max"],g[a+"Max"])+1:E(e[a+"Min"],g[a+"Min"])-1),c=!c):c=!1);b=[{start:b,end:y}]}else a=n(b,{x:h?d.x:b.x,y:h?b.y:d.y},h),b=[{start:b,end:{x:a.x,y:a.y}}],a[h?"x":"y"]!==d[h?"x":"y"]&&(q=v(a.obstacle,
a,d,!h,q),r(a.obstacle,u.hardBounds),q={x:h?a.x:a.obstacle[q?"xMax":"xMin"]+(q?1:-1),y:h?a.obstacle[q?"yMax":"yMin"]+(q?1:-1):a.y},h=!h,b=b.concat(w({x:a.x,y:a.y},q,h)));return b=b.concat(w(b[b.length-1].end,d,!h))}function g(b,c,d){var h=E(b.xMax-c.x,c.x-b.xMin)<E(b.yMax-c.y,c.y-b.yMin);d=v(b,c,d,h,{soft:u.hardBounds,hard:u.hardBounds});return h?{y:c.y,x:b[d?"xMax":"xMin"]+(d?1:-1)}:{x:c.x,y:b[d?"yMax":"yMin"]+(d?1:-1)}}var f=K(u.startDirectionX,e(p.x-k.x)>e(p.y-k.y)),A=f?"x":"y",d=[],c=!1,b=u.obstacleMetrics,
l=E(k.x,p.x)-b.maxWidth-10,O=x(k.x,p.x)+b.maxWidth+10,J=E(k.y,p.y)-b.maxHeight-10,P=x(k.y,p.y)+b.maxHeight+10,B=u.chartObstacles;var z=a(B,l);b=a(B,O);B=B.slice(z,b+1);if(-1<(b=m(B,p))){var h=g(B[b],p,k);d.push({end:p,start:h});p=h}for(;-1<(b=m(B,p));)z=0>p[A]-k[A],h={x:p.x,y:p.y},h[A]=B[b][z?A+"Max":A+"Min"]+(z?1:-1),d.push({end:p,start:h}),p=h;k=w(k,p,f);k=k.concat(d.reverse());return{path:t(k),obstacles:k}},{requiresObstacles:!0})}});G(n,"parts-gantt/ArrowSymbols.js",[n["parts/Globals.js"]],function(n){n.SVGRenderer.prototype.symbols.arrow=
function(a,m,n,r){return["M",a,m+r/2,"L",a+n,m,"L",a,m+r/2,"L",a+n,m+r]};n.SVGRenderer.prototype.symbols["arrow-half"]=function(a,m,t,r){return n.SVGRenderer.prototype.symbols.arrow(a,m,t/2,r)};n.SVGRenderer.prototype.symbols["triangle-left"]=function(a,m,n,r){return["M",a+n,m,"L",a,m+r/2,"L",a+n,m+r,"Z"]};n.SVGRenderer.prototype.symbols["arrow-filled"]=n.SVGRenderer.prototype.symbols["triangle-left"];n.SVGRenderer.prototype.symbols["triangle-left-half"]=function(a,m,t,r){return n.SVGRenderer.prototype.symbols["triangle-left"](a,
m,t/2,r)};n.SVGRenderer.prototype.symbols["arrow-filled-half"]=n.SVGRenderer.prototype.symbols["triangle-left-half"]});G(n,"parts-gantt/Pathfinder.js",[n["parts/Globals.js"],n["parts/Point.js"],n["parts/Utilities.js"],n["parts-gantt/PathfinderAlgorithms.js"]],function(n,a,m,t){function r(c){var b=c.shapeArgs;return b?{xMin:b.x,xMax:b.x+b.width,yMin:b.y,yMax:b.y+b.height}:(b=c.graphic&&c.graphic.getBBox())?{xMin:c.plotX-b.width/2,xMax:c.plotX+b.width/2,yMin:c.plotY-b.height/2,yMax:c.plotY+b.height/
2}:null}function w(c){for(var b=c.length,a=0,f,e,g=[],k=function(b,c,a){a=C(a,10);var h=b.yMax+a>c.yMin-a&&b.yMin-a<c.yMax+a,l=b.xMax+a>c.xMin-a&&b.xMin-a<c.xMax+a,f=h?b.xMin>c.xMax?b.xMin-c.xMax:c.xMin-b.xMax:Infinity,q=l?b.yMin>c.yMax?b.yMin-c.yMax:c.yMin-b.yMax:Infinity;return l&&h?a?k(b,c,Math.floor(a/2)):Infinity:d(f,q)};a<b;++a)for(f=a+1;f<b;++f)e=k(c[a],c[f]),80>e&&g.push(e);g.push(80);return A(Math.floor(g.sort(function(b,c){return b-c})[Math.floor(g.length/10)]/2-1),1)}function v(c,b,d){this.init(c,
b,d)}function E(c){this.init(c)}function x(c){if(c.options.pathfinder||c.series.reduce(function(b,c){c.options&&F(!0,c.options.connectors=c.options.connectors||{},c.options.pathfinder);return b||c.options&&c.options.pathfinder},!1))F(!0,c.options.connectors=c.options.connectors||{},c.options.pathfinder),p('WARNING: Pathfinder options have been renamed. Use "chart.connectors" or "series.connectors" instead.')}"";var e=m.addEvent,k=m.defined,p=m.error,u=m.extend,F=m.merge,D=m.objectEach,C=m.pick,g=
m.splat,f=n.deg2rad,A=Math.max,d=Math.min;u(n.defaultOptions,{connectors:{type:"straight",lineWidth:1,marker:{enabled:!1,align:"center",verticalAlign:"middle",inside:!1,lineWidth:1},startMarker:{symbol:"diamond"},endMarker:{symbol:"arrow-filled"}}});v.prototype={init:function(c,b,d){this.fromPoint=c;this.toPoint=b;this.options=d;this.chart=c.series.chart;this.pathfinder=this.chart.pathfinder},renderPath:function(c,b,d){var a=this.chart,l=a.styledMode,f=a.pathfinder,e=!a.options.chart.forExport&&!1!==
d,g=this.graphics&&this.graphics.path;f.group||(f.group=a.renderer.g().addClass("highcharts-pathfinder-group").attr({zIndex:-1}).add(a.seriesGroup));f.group.translate(a.plotLeft,a.plotTop);g&&g.renderer||(g=a.renderer.path().add(f.group),l||g.attr({opacity:0}));g.attr(b);c={d:c};l||(c.opacity=1);g[e?"animate":"attr"](c,d);this.graphics=this.graphics||{};this.graphics.path=g},addMarker:function(c,b,d){var a=this.fromPoint.series.chart,l=a.pathfinder;a=a.renderer;var e="start"===c?this.fromPoint:this.toPoint,
g=e.getPathfinderAnchorPoint(b);if(b.enabled){d="start"===c?{x:d[4],y:d[5]}:{x:d[d.length-5],y:d[d.length-4]};d=e.getRadiansToVector(d,g);g=e.getMarkerVector(d,b.radius,g);d=-d/f;if(b.width&&b.height){var k=b.width;var h=b.height}else k=h=2*b.radius;this.graphics=this.graphics||{};g={x:g.x-k/2,y:g.y-h/2,width:k,height:h,rotation:d,rotationOriginX:g.x,rotationOriginY:g.y};this.graphics[c]?this.graphics[c].animate(g):(this.graphics[c]=a.symbol(b.symbol).addClass("highcharts-point-connecting-path-"+
c+"-marker").attr(g).add(l.group),a.styledMode||this.graphics[c].attr({fill:b.color||this.fromPoint.color,stroke:b.lineColor,"stroke-width":b.lineWidth,opacity:0}).animate({opacity:1},e.series.options.animation))}},getPath:function(c){var b=this.pathfinder,d=this.chart,a=b.algorithms[c.type],f=b.chartObstacles;if("function"!==typeof a)p('"'+c.type+'" is not a Pathfinder algorithm.');else return a.requiresObstacles&&!f&&(f=b.chartObstacles=b.getChartObstacles(c),d.options.connectors.algorithmMargin=
c.algorithmMargin,b.chartObstacleMetrics=b.getObstacleMetrics(f)),a(this.fromPoint.getPathfinderAnchorPoint(c.startMarker),this.toPoint.getPathfinderAnchorPoint(c.endMarker),F({chartObstacles:f,lineObstacles:b.lineObstacles||[],obstacleMetrics:b.chartObstacleMetrics,hardBounds:{xMin:0,xMax:d.plotWidth,yMin:0,yMax:d.plotHeight},obstacleOptions:{margin:c.algorithmMargin},startDirectionX:b.getAlgorithmStartDirection(c.startMarker)},c))},render:function(){var c=this.fromPoint,b=c.series,a=b.chart,f=a.pathfinder,
e=F(a.options.connectors,b.options.connectors,c.options.connectors,this.options),g={};a.styledMode||(g.stroke=e.lineColor||c.color,g["stroke-width"]=e.lineWidth,e.dashStyle&&(g.dashstyle=e.dashStyle));g["class"]="highcharts-point-connecting-path highcharts-color-"+c.colorIndex;e=F(g,e);k(e.marker.radius)||(e.marker.radius=d(A(Math.ceil((e.algorithmMargin||8)/2)-1,1),5));c=this.getPath(e);a=c.path;c.obstacles&&(f.lineObstacles=f.lineObstacles||[],f.lineObstacles=f.lineObstacles.concat(c.obstacles));
this.renderPath(a,g,b.options.animation);this.addMarker("start",F(e.marker,e.startMarker),a);this.addMarker("end",F(e.marker,e.endMarker),a)},destroy:function(){this.graphics&&(D(this.graphics,function(c){c.destroy()}),delete this.graphics)}};E.prototype={algorithms:t,init:function(c){this.chart=c;this.connections=[];e(c,"redraw",function(){this.pathfinder.update()})},update:function(c){var b=this.chart,d=this,f=d.connections;d.connections=[];b.series.forEach(function(c){c.visible&&!c.options.isInternal&&
c.points.forEach(function(c){var h,f=c.options&&c.options.connect&&g(c.options.connect);c.visible&&!1!==c.isInside&&f&&f.forEach(function(f){h=b.get("string"===typeof f?f:f.to);h instanceof a&&h.series.visible&&h.visible&&!1!==h.isInside&&d.connections.push(new v(c,h,"string"===typeof f?{}:f))})})});for(var e=0,k,p,A=f.length,h=d.connections.length;e<A;++e){p=!1;for(k=0;k<h;++k)if(f[e].fromPoint===d.connections[k].fromPoint&&f[e].toPoint===d.connections[k].toPoint){d.connections[k].graphics=f[e].graphics;
p=!0;break}p||f[e].destroy()}delete this.chartObstacles;delete this.lineObstacles;d.renderConnections(c)},renderConnections:function(c){c?this.chart.series.forEach(function(b){var c=function(){var c=b.chart.pathfinder;(c&&c.connections||[]).forEach(function(c){c.fromPoint&&c.fromPoint.series===b&&c.render()});b.pathfinderRemoveRenderEvent&&(b.pathfinderRemoveRenderEvent(),delete b.pathfinderRemoveRenderEvent)};!1===b.options.animation?c():b.pathfinderRemoveRenderEvent=e(b,"afterAnimate",c)}):this.connections.forEach(function(b){b.render()})},
getChartObstacles:function(c){for(var b=[],d=this.chart.series,a=C(c.algorithmMargin,0),f,e=0,g=d.length;e<g;++e)if(d[e].visible&&!d[e].options.isInternal)for(var p=0,h=d[e].points.length,q;p<h;++p)q=d[e].points[p],q.visible&&(q=r(q))&&b.push({xMin:q.xMin-a,xMax:q.xMax+a,yMin:q.yMin-a,yMax:q.yMax+a});b=b.sort(function(b,c){return b.xMin-c.xMin});k(c.algorithmMargin)||(f=c.algorithmMargin=w(b),b.forEach(function(b){b.xMin-=f;b.xMax+=f;b.yMin-=f;b.yMax+=f}));return b},getObstacleMetrics:function(c){for(var b=
0,d=0,a,f,e=c.length;e--;)a=c[e].xMax-c[e].xMin,f=c[e].yMax-c[e].yMin,b<a&&(b=a),d<f&&(d=f);return{maxHeight:d,maxWidth:b}},getAlgorithmStartDirection:function(c){var b="top"!==c.verticalAlign&&"bottom"!==c.verticalAlign;return"left"!==c.align&&"right"!==c.align?b?void 0:!1:b?!0:void 0}};n.Connection=v;n.Pathfinder=E;u(a.prototype,{getPathfinderAnchorPoint:function(c){var b=r(this);switch(c.align){case "right":var d="xMax";break;case "left":d="xMin"}switch(c.verticalAlign){case "top":var a="yMin";
break;case "bottom":a="yMax"}return{x:d?b[d]:(b.xMin+b.xMax)/2,y:a?b[a]:(b.yMin+b.yMax)/2}},getRadiansToVector:function(c,b){k(b)||(b=r(this),b={x:(b.xMin+b.xMax)/2,y:(b.yMin+b.yMax)/2});return Math.atan2(b.y-c.y,c.x-b.x)},getMarkerVector:function(c,b,d){var a=2*Math.PI,f=r(this),e=f.xMax-f.xMin,l=f.yMax-f.yMin,g=Math.atan2(l,e),h=!1;e/=2;var q=l/2,k=f.xMin+e;f=f.yMin+q;for(var p=k,A=f,m={},u=1,L=1;c<-Math.PI;)c+=a;for(;c>Math.PI;)c-=a;a=Math.tan(c);c>-g&&c<=g?(L=-1,h=!0):c>g&&c<=Math.PI-g?L=-1:c>
Math.PI-g||c<=-(Math.PI-g)?(u=-1,h=!0):u=-1;h?(p+=u*e,A+=L*e*a):(p+=l/(2*a)*u,A+=L*q);d.x!==k&&(p=d.x);d.y!==f&&(A=d.y);m.x=p+b*Math.cos(c);m.y=A-b*Math.sin(c);return m}});n.Chart.prototype.callbacks.push(function(c){!1!==c.options.connectors.enabled&&(x(c),this.pathfinder=new E(this),this.pathfinder.update(!0))})});G(n,"modules/xrange.src.js",[n["parts/Globals.js"],n["parts/Color.js"],n["parts/Point.js"],n["parts/Utilities.js"]],function(n,a,m,t){var r=a.parse;a=t.addEvent;var w=t.clamp,v=t.correctFloat,
E=t.defined,x=t.find,e=t.isNumber,k=t.isObject,p=t.merge,u=t.pick;t=t.seriesType;var F=n.seriesTypes.column,D=n.seriesTypes,C=n.Axis,g=n.Series;t("xrange","column",{colorByPoint:!0,dataLabels:{formatter:function(){var a=this.point.partialFill;k(a)&&(a=a.amount);if(e(a)&&0<a)return v(100*a)+"%"},inside:!0,verticalAlign:"middle"},tooltip:{headerFormat:'<span style="font-size: 10px">{point.x} - {point.x2}</span><br/>',pointFormat:'<span style="color:{point.color}">\u25cf</span> {series.name}: <b>{point.yCategory}</b><br/>'},
borderRadius:3,pointRange:0},{type:"xrange",parallelArrays:["x","x2","y"],requireSorting:!1,animate:D.line.prototype.animate,cropShoulder:1,getExtremesFromAll:!0,autoIncrement:n.noop,buildKDTree:n.noop,init:function(){D.column.prototype.init.apply(this,arguments);this.options.stacking=void 0},getColumnMetrics:function(){function a(){e.series.forEach(function(c){var b=c.xAxis;c.xAxis=c.yAxis;c.yAxis=b})}var e=this.chart;a();var d=F.prototype.getColumnMetrics.call(this);a();return d},cropData:function(a,
e,d,c){e=g.prototype.cropData.call(this,this.x2Data,e,d,c);e.xData=a.slice(e.start,e.end);return e},findPointIndex:function(a){var f=this.cropped,d=this.cropStart,c=this.points,b=a.id;if(b)var l=(l=x(c,function(c){return c.id===b}))?l.index:void 0;"undefined"===typeof l&&(l=(l=x(c,function(b){return b.x===a.x&&b.x2===a.x2&&!b.touched}))?l.index:void 0);f&&e(l)&&e(d)&&l>=d&&(l-=d);return l},translatePoint:function(a){var f=this.xAxis,d=this.yAxis,c=this.columnMetrics,b=this.options,l=b.minPointLength||
0,g=a.plotX,m=u(a.x2,a.x+(a.len||0)),n=f.translate(m,0,0,0,1);m=Math.abs(n-g);var x=this.chart.inverted,z=u(b.borderWidth,1)%2/2,h=c.offset,q=Math.round(c.width);l&&(l-=m,0>l&&(l=0),g-=l/2,n+=l/2);g=Math.max(g,-10);n=w(n,-10,f.len+10);E(a.options.pointWidth)&&(h-=(Math.ceil(a.options.pointWidth)-q)/2,q=Math.ceil(a.options.pointWidth));b.pointPlacement&&e(a.plotY)&&d.categories&&(a.plotY=d.translate(a.y,0,1,0,1,b.pointPlacement));a.shapeArgs={x:Math.floor(Math.min(g,n))+z,y:Math.floor(a.plotY+h)+z,
width:Math.round(Math.abs(n-g)),height:q,r:this.options.borderRadius};b=a.shapeArgs.x;l=b+a.shapeArgs.width;0>b||l>f.len?(b=w(b,0,f.len),l=w(l,0,f.len),n=l-b,a.dlBox=p(a.shapeArgs,{x:b,width:l-b,centerX:n?n/2:null})):a.dlBox=null;b=a.tooltipPos;l=x?1:0;n=x?0:1;c=this.columnMetrics?this.columnMetrics.offset:-c.width/2;b[l]=w(b[l]+m/2*(f.reversed?-1:1)*(x?-1:1),0,f.len-1);b[n]=w(b[n]+(x?-1:1)*c,0,d.len-1);if(c=a.partialFill)k(c)&&(c=c.amount),e(c)||(c=0),d=a.shapeArgs,a.partShapeArgs={x:d.x,y:d.y,width:d.width,
height:d.height,r:this.options.borderRadius},g=Math.max(Math.round(m*c+a.plotX-g),0),a.clipRectArgs={x:f.reversed?d.x+m-g:d.x,y:d.y,width:g,height:d.height}},translate:function(){F.prototype.translate.apply(this,arguments);this.points.forEach(function(a){this.translatePoint(a)},this)},drawPoint:function(a,e){var d=this.options,c=this.chart.renderer,b=a.graphic,f=a.shapeType,g=a.shapeArgs,m=a.partShapeArgs,A=a.clipRectArgs,n=a.partialFill,z=d.stacking&&!d.borderRadius,h=a.state,q=d.states[h||"normal"]||
{},y="undefined"===typeof h?"attr":e;h=this.pointAttribs(a,h);q=u(this.chart.options.chart.animation,q.animation);if(a.isNull||!1===a.visible)b&&(a.graphic=b.destroy());else{if(b)b.rect[e](g);else a.graphic=b=c.g("point").addClass(a.getClassName()).add(a.group||this.group),b.rect=c[f](p(g)).addClass(a.getClassName()).addClass("highcharts-partfill-original").add(b);m&&(b.partRect?(b.partRect[e](p(m)),b.partialClipRect[e](p(A))):(b.partialClipRect=c.clipRect(A.x,A.y,A.width,A.height),b.partRect=c[f](m).addClass("highcharts-partfill-overlay").add(b).clip(b.partialClipRect)));
this.chart.styledMode||(b.rect[e](h,q).shadow(d.shadow,null,z),m&&(k(n)||(n={}),k(d.partialFill)&&(n=p(n,d.partialFill)),a=n.fill||r(h.fill).brighten(-.3).get()||r(a.color||this.color).brighten(-.3).get(),h.fill=a,b.partRect[y](h,q).shadow(d.shadow,null,z)))}},drawPoints:function(){var a=this,e=a.getAnimationVerb();a.points.forEach(function(d){a.drawPoint(d,e)})},getAnimationVerb:function(){return this.chart.pointCount<(this.options.animationLimit||250)?"animate":"attr"}},{resolveColor:function(){var a=
this.series;if(a.options.colorByPoint&&!this.options.color){var e=a.options.colors||a.chart.options.colors;var d=this.y%(e?e.length:a.chart.options.chart.colorCount);e=e&&e[d];a.chart.styledMode||(this.color=e);this.options.colorIndex||(this.colorIndex=d)}else this.color||(this.color=a.color)},init:function(){m.prototype.init.apply(this,arguments);this.y||(this.y=0);return this},setState:function(){m.prototype.setState.apply(this,arguments);this.series.drawPoint(this,this.series.getAnimationVerb())},
getLabelConfig:function(){var a=m.prototype.getLabelConfig.call(this),e=this.series.yAxis.categories;a.x2=this.x2;a.yCategory=this.yCategory=e&&e[this.y];return a},tooltipDateKeys:["x","x2"],isValid:function(){return"number"===typeof this.x&&"number"===typeof this.x2}});a(C,"afterGetSeriesExtremes",function(){var a=this.series,e;if(this.isXAxis){var d=u(this.dataMax,-Number.MAX_VALUE);a.forEach(function(c){c.x2Data&&c.x2Data.forEach(function(b){b>d&&(d=b,e=!0)})});e&&(this.dataMax=d)}});""});G(n,
"parts-gantt/GanttSeries.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,a){var m=a.isNumber,t=a.merge,r=a.pick,w=a.seriesType,v=a.splat,E=n.dateFormat,x=n.seriesTypes.xrange;w("gantt","xrange",{grouping:!1,dataLabels:{enabled:!0},tooltip:{headerFormat:'<span style="font-size: 10px">{series.name}</span><br/>',pointFormat:null,pointFormatter:function(){var a=this.series,k=a.chart.tooltip,p=a.xAxis,m=a.tooltipOptions.dateTimeLabelFormats,n=p.options.startOfWeek,x=a.tooltipOptions,r=x.xDateFormat;
a=this.options.milestone;var g="<b>"+(this.name||this.yCategory)+"</b>";if(x.pointFormat)return this.tooltipFormatter(x.pointFormat);r||(r=v(k.getDateFormat(p.closestPointRange,this.start,n,m))[0]);k=E(r,this.start);p=E(r,this.end);g+="<br/>";return a?g+(k+"<br/>"):g+("Start: "+k+"<br/>End: ")+(p+"<br/>")}},connectors:{type:"simpleConnect",animation:{reversed:!0},startMarker:{enabled:!0,symbol:"arrow-filled",radius:4,fill:"#fa0",align:"left"},endMarker:{enabled:!1,align:"right"}}},{pointArrayMap:["start",
"end","y"],keyboardMoveVertical:!1,translatePoint:function(a){x.prototype.translatePoint.call(this,a);if(a.options.milestone){var e=a.shapeArgs;var p=e.height;a.shapeArgs={x:e.x-p/2,y:e.y,width:p,height:p}}},drawPoint:function(a,k){var e=this.options,n=this.chart.renderer,r=a.shapeArgs,t=a.plotY,w=a.graphic,g=a.selected&&"select",f=e.stacking&&!e.borderRadius;if(a.options.milestone)if(m(t)&&null!==a.y&&!1!==a.visible){r=n.symbols.diamond(r.x,r.y,r.width,r.height);if(w)w[k]({d:r});else a.graphic=n.path(r).addClass(a.getClassName(),
!0).add(a.group||this.group);this.chart.styledMode||a.graphic.attr(this.pointAttribs(a,g)).shadow(e.shadow,null,f)}else w&&(a.graphic=w.destroy());else x.prototype.drawPoint.call(this,a,k)},setData:n.Series.prototype.setData,setGanttPointAliases:function(a){function e(e,k){"undefined"!==typeof k&&(a[e]=k)}e("x",r(a.start,a.x));e("x2",r(a.end,a.x2));e("partialFill",r(a.completed,a.partialFill));e("connect",r(a.dependency,a.connect))}},t(x.prototype.pointClass.prototype,{applyOptions:function(a,k){a=
t(a);n.seriesTypes.gantt.prototype.setGanttPointAliases(a);return a=x.prototype.pointClass.prototype.applyOptions.call(this,a,k)},isValid:function(){return("number"===typeof this.start||"number"===typeof this.x)&&("number"===typeof this.end||"number"===typeof this.x2||this.milestone)}}));""});G(n,"parts-gantt/GanttChart.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,a){var m=a.isArray,t=a.merge,r=a.splat,w=n.Chart;n.ganttChart=function(a,v,x){var e="string"===typeof a||a.nodeName,
k=v.series,p=n.getOptions(),u,F=v;v=arguments[e?1:0];m(v.xAxis)||(v.xAxis=[v.xAxis||{},{}]);v.xAxis=v.xAxis.map(function(a,e){1===e&&(u=0);return t(p.xAxis,{grid:{enabled:!0},opposite:!0,linkedTo:u},a,{type:"datetime"})});v.yAxis=r(v.yAxis||{}).map(function(a){return t(p.yAxis,{grid:{enabled:!0},staticScale:50,reversed:!0,type:a.categories?a.type:"treegrid"},a)});v.series=null;v=t(!0,{chart:{type:"gantt"},title:{text:null},legend:{enabled:!1}},v,{isGantt:!0});v.series=F.series=k;v.series.forEach(function(a){a.data.forEach(function(a){n.seriesTypes.gantt.prototype.setGanttPointAliases(a)})});
return e?new w(a,v,x):new w(v,v)}});G(n,"parts/ScrollbarAxis.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,a){var m=a.addEvent,t=a.defined,r=a.pick;return function(){function a(){}a.compose=function(a,w){m(a,"afterInit",function(){var a=this;a.options&&a.options.scrollbar&&a.options.scrollbar.enabled&&(a.options.scrollbar.vertical=!a.horiz,a.options.startOnTick=a.options.endOnTick=!1,a.scrollbar=new w(a.chart.renderer,a.options.scrollbar,a.chart),m(a.scrollbar,"changed",function(e){var k=
r(a.options&&a.options.min,a.min),p=r(a.options&&a.options.max,a.max),m=t(a.dataMin)?Math.min(k,a.min,a.dataMin):k,w=(t(a.dataMax)?Math.max(p,a.max,a.dataMax):p)-m;t(k)&&t(p)&&(a.horiz&&!a.reversed||!a.horiz&&a.reversed?(k=m+w*this.to,m+=w*this.from):(k=m+w*(1-this.from),m+=w*(1-this.to)),r(this.options.liveRedraw,n.svg&&!n.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===e.DOMType||!t(e.DOMType)?a.setExtremes(m,k,!0,"mousemove"!==e.DOMType,e):this.setRange(this.from,this.to))}))});m(a,"afterRender",
function(){var a=Math.min(r(this.options.min,this.min),this.min,r(this.dataMin,this.min)),e=Math.max(r(this.options.max,this.max),this.max,r(this.dataMax,this.max)),k=this.scrollbar,p=this.axisTitleMargin+(this.titleOffset||0),m=this.chart.scrollbarsOffsets,n=this.options.margin||0;k&&(this.horiz?(this.opposite||(m[1]+=p),k.position(this.left,this.top+this.height+2+m[1]-(this.opposite?n:0),this.width,this.height),this.opposite||(m[1]+=n),p=1):(this.opposite&&(m[0]+=p),k.position(this.left+this.width+
2+m[0]-(this.opposite?0:n),this.top,this.width,this.height),this.opposite&&(m[0]+=n),p=0),m[p]+=k.size+k.options.margin,isNaN(a)||isNaN(e)||!t(this.min)||!t(this.max)||this.min===this.max?k.setRange(0,1):(m=(this.min-a)/(e-a),a=(this.max-a)/(e-a),this.horiz&&!this.reversed||!this.horiz&&this.reversed?k.setRange(m,a):k.setRange(1-a,1-m)))});m(a,"afterGetOffset",function(){var a=this.horiz?2:1,e=this.scrollbar;e&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[a]+=e.size+e.options.margin)})};
return a}()});G(n,"parts/Scrollbar.js",[n["parts/Axis.js"],n["parts/Globals.js"],n["parts/ScrollbarAxis.js"],n["parts/Utilities.js"]],function(n,a,m,t){var r=t.addEvent,w=t.correctFloat,v=t.defined,E=t.destroyObjectProperties,x=t.fireEvent,e=t.merge,k=t.pick,p=t.removeEvent;t=a.defaultOptions;var u=a.hasTouch,F=a.isTouchDevice,D=a.swapXY=function(a,f){var e=a.length;if(f)for(f=0;f<e;f+=3){var d=a[f+1];a[f+1]=a[f+2];a[f+2]=d}return a},C=function(){function a(a,e,d){this._events=[];this.from=this.chartY=
this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=d;this.options=e;this.renderer=d.renderer;this.init(a,e,d)}a.prototype.addEvents=function(){var a=this.options.inverted?[1,0]:[0,1],e=this.scrollbarButtons,d=this.scrollbarGroup.element,c=this.track.element,
b=this.mouseDownHandler.bind(this),l=this.mouseMoveHandler.bind(this),g=this.mouseUpHandler.bind(this);a=[[e[a[0]].element,"click",this.buttonToMinClick.bind(this)],[e[a[1]].element,"click",this.buttonToMaxClick.bind(this)],[c,"click",this.trackClick.bind(this)],[d,"mousedown",b],[d.ownerDocument,"mousemove",l],[d.ownerDocument,"mouseup",g]];u&&a.push([d,"touchstart",b],[d.ownerDocument,"touchmove",l],[d.ownerDocument,"touchend",g]);a.forEach(function(a){r.apply(null,a)});this._events=a};a.prototype.buttonToMaxClick=
function(a){var e=(this.to-this.from)*k(this.options.step,.2);this.updatePosition(this.from+e,this.to+e);x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.buttonToMinClick=function(a){var e=w(this.to-this.from)*k(this.options.step,.2);this.updatePosition(w(this.from-e),w(this.to-e));x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.cursorToScrollbarPosition=function(a){var e=this.options;e=e.minWidth>this.calculatedWidth?
e.minWidth:0;return{chartX:(a.chartX-this.x-this.xOffset)/(this.barWidth-e),chartY:(a.chartY-this.y-this.yOffset)/(this.barWidth-e)}};a.prototype.destroy=function(){var a=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(a){this[a]&&this[a].destroy&&(this[a]=this[a].destroy())},this);a&&this===a.scrollbar&&(a.scrollbar=null,E(a.scrollbarButtons))};a.prototype.drawScrollbarButton=function(a){var e=this.renderer,d=this.scrollbarButtons,
c=this.options,b=this.size;var f=e.g().add(this.group);d.push(f);f=e.rect().addClass("highcharts-scrollbar-button").add(f);this.chart.styledMode||f.attr({stroke:c.buttonBorderColor,"stroke-width":c.buttonBorderWidth,fill:c.buttonBackgroundColor});f.attr(f.crisp({x:-.5,y:-.5,width:b+1,height:b+1,r:c.buttonBorderRadius},f.strokeWidth()));f=e.path(D(["M",b/2+(a?-1:1),b/2-3,"L",b/2+(a?-1:1),b/2+3,"L",b/2+(a?2:-2),b/2],c.vertical)).addClass("highcharts-scrollbar-arrow").add(d[a]);this.chart.styledMode||
f.attr({fill:c.buttonArrowColor})};a.prototype.init=function(f,g,d){this.scrollbarButtons=[];this.renderer=f;this.userOptions=g;this.options=e(a.defaultOptions,g);this.chart=d;this.size=k(this.options.size,this.options.height);g.enabled&&(this.render(),this.addEvents())};a.prototype.mouseDownHandler=function(a){a=this.chart.pointer.normalize(a);a=this.cursorToScrollbarPosition(a);this.chartX=a.chartX;this.chartY=a.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};a.prototype.mouseMoveHandler=
function(a){var e=this.chart.pointer.normalize(a),d=this.options.vertical?"chartY":"chartX",c=this.initPositions||[];!this.grabbedCenter||a.touches&&0===a.touches[0][d]||(e=this.cursorToScrollbarPosition(e)[d],d=this[d],d=e-d,this.hasDragged=!0,this.updatePosition(c[0]+d,c[1]+d),this.hasDragged&&x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:a.type,DOMEvent:a}))};a.prototype.mouseUpHandler=function(a){this.hasDragged&&x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",
DOMType:a.type,DOMEvent:a});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};a.prototype.position=function(a,e,d,c){var b=this.options.vertical,f=0,g=this.rendered?"animate":"attr";this.x=a;this.y=e+this.trackBorderWidth;this.width=d;this.xOffset=this.height=c;this.yOffset=f;b?(this.width=this.yOffset=d=f=this.size,this.xOffset=e=0,this.barWidth=c-2*d,this.x=a+=this.options.margin):(this.height=this.xOffset=c=e=this.size,this.barWidth=d-2*c,this.y+=this.options.margin);this.group[g]({translateX:a,
translateY:this.y});this.track[g]({width:d,height:c});this.scrollbarButtons[1][g]({translateX:b?0:d-e,translateY:b?c-f:0})};a.prototype.removeEvents=function(){this._events.forEach(function(a){p.apply(null,a)});this._events.length=0};a.prototype.render=function(){var a=this.renderer,e=this.options,d=this.size,c=this.chart.styledMode,b;this.group=b=a.g("scrollbar").attr({zIndex:e.zIndex,translateY:-99999}).add();this.track=a.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:e.trackBorderRadius||
0,height:d,width:d}).add(b);c||this.track.attr({fill:e.trackBackgroundColor,stroke:e.trackBorderColor,"stroke-width":e.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=a.g().add(b);this.scrollbar=a.rect().addClass("highcharts-scrollbar-thumb").attr({height:d,width:d,r:e.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=a.path(D(["M",-3,d/4,"L",-3,2*d/3,"M",0,d/4,"L",0,2*d/3,"M",3,d/4,"L",3,2*d/3],
e.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);c||(this.scrollbar.attr({fill:e.barBackgroundColor,stroke:e.barBorderColor,"stroke-width":e.barBorderWidth}),this.scrollbarRifles.attr({stroke:e.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};a.prototype.setRange=function(a,e){var d=this.options,
c=d.vertical,b=d.minWidth,l=this.barWidth,f,g=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(v(l)){a=Math.max(a,0);var k=Math.ceil(l*a);this.calculatedWidth=f=w(l*Math.min(e,1)-k);f<b&&(k=(l-b+f)*a,f=b);b=Math.floor(k+this.xOffset+this.yOffset);l=f/2-.5;this.from=a;this.to=e;c?(this.scrollbarGroup[g]({translateY:b}),this.scrollbar[g]({height:f}),this.scrollbarRifles[g]({translateY:l}),this.scrollbarTop=b,this.scrollbarLeft=0):(this.scrollbarGroup[g]({translateX:b}),
this.scrollbar[g]({width:f}),this.scrollbarRifles[g]({translateX:l}),this.scrollbarLeft=b,this.scrollbarTop=0);12>=f?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===d.showFull&&(0>=a&&1<=e?this.group.hide():this.group.show());this.rendered=!0}};a.prototype.trackClick=function(a){var e=this.chart.pointer.normalize(a),d=this.to-this.from,c=this.y+this.scrollbarTop,b=this.x+this.scrollbarLeft;this.options.vertical&&e.chartY>c||!this.options.vertical&&e.chartX>b?this.updatePosition(this.from+
d,this.to+d):this.updatePosition(this.from-d,this.to-d);x(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:a})};a.prototype.update=function(a){this.destroy();this.init(this.chart.renderer,e(!0,this.options,a),this.chart)};a.prototype.updatePosition=function(a,e){1<e&&(a=w(1-w(e-a)),e=1);0>a&&(e=w(e-a),a=0);this.from=a;this.to=e};a.defaultOptions={height:F?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",
barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};return a}();a.Scrollbar||(t.scrollbar=e(!0,C.defaultOptions,t.scrollbar),a.Scrollbar=C,m.compose(n,C));return a.Scrollbar});G(n,"parts/RangeSelector.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,a){function m(a){this.init(a)}var t=a.addEvent,
r=a.createElement,w=a.css,v=a.defined,E=a.destroyObjectProperties,x=a.discardElement,e=a.extend,k=a.fireEvent,p=a.isNumber,u=a.merge,F=a.objectEach,D=a.pick,C=a.pInt,g=a.splat,f=n.Axis;a=n.Chart;var A=n.defaultOptions;e(A,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});A.lang=u(A.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",
rangeSelectorTo:"To"});m.prototype={clickButton:function(a,c){var b=this.chart,d=this.buttonOptions[a],e=b.xAxis[0],k=b.scroller&&b.scroller.getUnionExtremes()||e||{},m=k.dataMin,n=k.dataMax,z=e&&Math.round(Math.min(e.max,D(n,e.max))),h=d.type;k=d._range;var q,y=d.dataGrouping;if(null!==m&&null!==n){b.fixedRange=k;y&&(this.forcedDataGrouping=!0,f.prototype.setDataGrouping.call(e||{chart:this.chart},y,!1),this.frozenStates=d.preserveDataGrouping);if("month"===h||"year"===h)if(e){h={range:d,max:z,chart:b,
dataMin:m,dataMax:n};var H=e.minFromRange.call(h);p(h.newMax)&&(z=h.newMax)}else k=d;else if(k)H=Math.max(z-k,m),z=Math.min(H+k,n);else if("ytd"===h)if(e)"undefined"===typeof n&&(m=Number.MAX_VALUE,n=Number.MIN_VALUE,b.series.forEach(function(a){a=a.xData;m=Math.min(a[0],m);n=Math.max(a[a.length-1],n)}),c=!1),z=this.getYTDExtremes(n,m,b.time.useUTC),H=q=z.min,z=z.max;else{this.deferredYTDClick=a;return}else"all"===h&&e&&(H=m,z=n);H+=d._offsetMin;z+=d._offsetMax;this.setSelected(a);if(e)e.setExtremes(H,
z,D(c,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:d});else{var I=g(b.options.xAxis)[0];var u=I.range;I.range=k;var r=I.min;I.min=q;t(b,"load",function(){I.range=u;I.min=r})}}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var c=this,b=a.options.rangeSelector,
d=b.buttons||[].concat(c.defaultButtons),e=b.selected,f=function(){var a=c.minInput,b=c.maxInput;a&&a.blur&&k(a,"blur");b&&b.blur&&k(b,"blur")};c.chart=a;c.options=b;c.buttons=[];c.buttonOptions=d;this.unMouseDown=t(a.container,"mousedown",f);this.unResize=t(a,"resize",f);d.forEach(c.computeButtonRange);"undefined"!==typeof e&&d[e]&&this.clickButton(e,!1);t(a,"load",function(){a.xAxis&&a.xAxis[0]&&t(a.xAxis[0],"setExtremes",function(b){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==b.trigger&&
"updatedData"!==b.trigger&&c.forcedDataGrouping&&!c.frozenStates&&this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this,c=this.chart,b=c.xAxis[0],e=Math.round(b.max-b.min),f=!b.hasVisibleSeries,g=c.scroller&&c.scroller.getUnionExtremes()||b,k=g.dataMin,m=g.dataMax;c=a.getYTDExtremes(m,k,c.time.useUTC);var n=c.min,h=c.max,q=a.selected,y=p(q),H=a.options.allButtonsEnabled,I=a.buttons;a.buttonOptions.forEach(function(c,d){var l=c._range,g=c.type,p=c.count||1,z=I[d],u=0,r=c._offsetMax-
c._offsetMin;c=d===q;var t=l>m-k,w=l<b.minRange,T=!1,v=!1;l=l===e;("month"===g||"year"===g)&&e+36E5>=864E5*{month:28,year:365}[g]*p-r&&e-36E5<=864E5*{month:31,year:366}[g]*p+r?l=!0:"ytd"===g?(l=h-n+r===e,T=!c):"all"===g&&(l=b.max-b.min>=m-k,v=!c&&y&&l);g=!H&&(t||w||v||f);p=c&&l||l&&!y&&!T||c&&a.frozenStates;g?u=3:p&&(y=!0,u=2);z.state!==u&&(z.setState(u),0===u&&q===d&&a.setSelected(null))})},computeButtonRange:function(a){var c=a.type,b=a.count||1,d={millisecond:1,second:1E3,minute:6E4,hour:36E5,
day:864E5,week:6048E5};if(d[c])a._range=d[c]*b;else if("month"===c||"year"===c)a._range=864E5*{month:30,year:365}[c]*b;a._offsetMin=D(a.offsetMin,0);a._offsetMax=D(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,c){var b=this.chart.options.rangeSelector,d=this.chart.time,e=this[a+"Input"];v(c)&&(e.previousValue=e.HCTime,e.HCTime=c);e.value=d.dateFormat(b.inputEditDateFormat||"%Y-%m-%d",e.HCTime);this[a+"DateBox"].attr({text:d.dateFormat(b.inputDateFormat||"%b %e, %Y",
e.HCTime)})},showInput:function(a){var c=this.inputGroup,b=this[a+"DateBox"];w(this[a+"Input"],{left:c.translateX+b.x+"px",top:c.translateY+"px",width:b.width-2+"px",height:b.height-2+"px",border:"2px solid silver"})},hideInput:function(a){w(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(a){function c(){var a=h.value,c=(k.inputDateParser||Date.parse)(a),e=d.xAxis[0],f=d.scroller&&d.scroller.xAxis?d.scroller.xAxis:e,q=f.dataMin;f=f.dataMax;c!==h.previousValue&&
(h.previousValue=c,p(c)||(c=a.split("-"),c=Date.UTC(C(c[0]),C(c[1])-1,C(c[2]))),p(c)&&(d.time.useUTC||(c+=6E4*(new Date).getTimezoneOffset()),z?c>b.maxInput.HCTime?c=void 0:c<q&&(c=q):c<b.minInput.HCTime?c=void 0:c>f&&(c=f),"undefined"!==typeof c&&e.setExtremes(z?c:e.min,z?e.max:c,void 0,void 0,{trigger:"rangeSelectorInput"})))}var b=this,d=b.chart,f=d.renderer.style||{},g=d.renderer,k=d.options.rangeSelector,m=b.div,z="min"===a,h,q,y=this.inputGroup;this[a+"Label"]=q=g.label(A.lang[z?"rangeSelectorFrom":
"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(y);y.offset+=q.width+5;this[a+"DateBox"]=g=g.label("",y.offset).addClass("highcharts-range-input").attr({padding:2,width:k.inputBoxWidth||90,height:k.inputBoxHeight||17,"text-align":"center"}).on("click",function(){b.showInput(a);b[a+"Input"].focus()});d.styledMode||g.attr({stroke:k.inputBoxBorderColor||"#cccccc","stroke-width":1});g.add(y);y.offset+=g.width+(z?10:0);this[a+"Input"]=h=r("input",{name:a,
className:"highcharts-range-selector",type:"text"},{top:d.plotTop+"px"},m);d.styledMode||(q.css(u(f,k.labelStyle)),g.css(u({color:"#333333"},f,k.inputStyle)),w(h,e({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:f.fontSize,fontFamily:f.fontFamily,top:"-9999em"},k.inputStyle)));h.onfocus=function(){b.showInput(a)};h.onblur=function(){h===n.doc.activeElement&&c();b.hideInput(a);h.blur()};h.onchange=c;h.onkeypress=function(a){13===a.keyCode&&c()}},getPosition:function(){var a=
this.chart,c=a.options.rangeSelector;a="top"===c.verticalAlign?a.plotTop-a.axisOffset[0]:0;return{buttonTop:a+c.buttonPosition.y,inputTop:a+c.inputPosition.y-10}},getYTDExtremes:function(a,c,b){var d=this.chart.time,e=new d.Date(a),f=d.get("FullYear",e);b=b?d.Date.UTC(f,0,1):+new d.Date(f,0,1);c=Math.max(c||0,b);e=e.getTime();return{max:Math.min(a||e,e),min:c}},render:function(a,c){var b=this,d=b.chart,e=d.renderer,f=d.container,g=d.options,k=g.exporting&&!1!==g.exporting.enabled&&g.navigation&&g.navigation.buttonOptions,
m=A.lang,h=b.div,q=g.rangeSelector,p=D(g.chart.style&&g.chart.style.zIndex,0)+1;g=q.floating;var n=b.buttons;h=b.inputGroup;var u=q.buttonTheme,t=q.buttonPosition,w=q.inputPosition,L=q.inputEnabled,v=u&&u.states,x=d.plotLeft,C=b.buttonGroup,S,F=b.options.verticalAlign,E=d.legend,K=E&&E.options,G=t.y,Q=w.y,R=d.hasLoaded,U=R?"animate":"attr",N=0,M=0;if(!1!==q.enabled){b.rendered||(b.group=S=e.g("range-selector-group").attr({zIndex:7}).add(),b.buttonGroup=C=e.g("range-selector-buttons").add(S),b.zoomText=
e.text(m.rangeSelectorZoom,0,15).add(C),d.styledMode||(b.zoomText.css(q.labelStyle),u["stroke-width"]=D(u["stroke-width"],0)),b.buttonOptions.forEach(function(a,c){n[c]=e.button(a.text,0,0,function(d){var h=a.events&&a.events.click,e;h&&(e=h.call(a,d));!1!==e&&b.clickButton(c);b.isActive=!0},u,v&&v.hover,v&&v.select,v&&v.disabled).attr({"text-align":"center"}).add(C)}),!1!==L&&(b.div=h=r("div",null,{position:"relative",height:0,zIndex:p}),f.parentNode.insertBefore(h,f),b.inputGroup=h=e.g("input-group").add(S),
h.offset=0,b.drawInput("min"),b.drawInput("max")));b.zoomText[U]({x:D(x+t.x,x)});var V=D(x+t.x,x)+b.zoomText.getBBox().width+5;b.buttonOptions.forEach(function(a,b){n[b][U]({x:V});V+=n[b].width+D(q.buttonSpacing,5)});x=d.plotLeft-d.spacing[3];b.updateButtonStates();k&&this.titleCollision(d)&&"top"===F&&"right"===t.align&&t.y+C.getBBox().height-12<(k.y||0)+k.height&&(N=-40);f=t.x-d.spacing[3];"right"===t.align?f+=N-x:"center"===t.align&&(f-=x/2);C.align({y:t.y,width:C.getBBox().width,align:t.align,
x:f},!0,d.spacingBox);b.group.placed=R;b.buttonGroup.placed=R;!1!==L&&(N=k&&this.titleCollision(d)&&"top"===F&&"right"===w.align&&w.y-h.getBBox().height-12<(k.y||0)+k.height+d.spacing[0]?-40:0,"left"===w.align?f=x:"right"===w.align&&(f=-Math.max(d.axisOffset[1],-N)),h.align({y:w.y,width:h.getBBox().width,align:w.align,x:w.x+f-2},!0,d.spacingBox),k=h.alignAttr.translateX+h.alignOptions.x-N+h.getBBox().x+2,f=h.alignOptions.width,m=C.alignAttr.translateX+C.getBBox().x,x=C.getBBox().width+20,(w.align===
t.align||m+x>k&&k+f>m&&G<Q+h.getBBox().height)&&h.attr({translateX:h.alignAttr.translateX+(d.axisOffset[1]>=-N?0:-N),translateY:h.alignAttr.translateY+C.getBBox().height+10}),b.setInputValue("min",a),b.setInputValue("max",c),b.inputGroup.placed=R);b.group.align({verticalAlign:F},!0,d.spacingBox);a=b.group.getBBox().height+20;c=b.group.alignAttr.translateY;"bottom"===F&&(E=K&&"bottom"===K.verticalAlign&&K.enabled&&!K.floating?E.legendHeight+D(K.margin,10):0,a=a+E-20,M=c-a-(g?0:q.y)-(d.titleOffset?
d.titleOffset[2]:0)-10);if("top"===F)g&&(M=0),d.titleOffset&&d.titleOffset[0]&&(M=d.titleOffset[0]),M+=d.margin[0]-d.spacing[0]||0;else if("middle"===F)if(Q===G)M=0>Q?c+void 0:c;else if(Q||G)M=0>Q||0>G?M-Math.min(Q,G):c-a+NaN;b.group.translate(q.x,q.y+Math.floor(M));!1!==L&&(b.minInput.style.marginTop=b.group.translateY+"px",b.maxInput.style.marginTop=b.group.translateY+"px");b.rendered=!0}},getHeight:function(){var a=this.options,c=this.group,b=a.y,e=a.buttonPosition.y,f=a.inputPosition.y;if(a.height)return a.height;
a=c?c.getBBox(!0).height+13+b:0;c=Math.min(f,e);if(0>f&&0>e||0<f&&0<e)a+=Math.abs(c);return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var c=this.chart;u(!0,c.options.rangeSelector,a);this.destroy();this.init(c);c.rangeSelector.render()},destroy:function(){var a=this,c=a.minInput,b=a.maxInput;a.unMouseDown();a.unResize();E(a.buttons);c&&(c.onfocus=c.onblur=c.onchange=null);b&&(b.onfocus=b.onblur=b.onchange=null);F(a,function(b,c){b&&"chart"!==
c&&(b.destroy?b.destroy():b.nodeType&&x(this[c]));b!==m.prototype[c]&&(a[c]=null)},this)}};f.prototype.minFromRange=function(){var a=this.range,c=a.type,b=this.max,e=this.chart.time,f=function(a,b){var d="year"===c?"FullYear":"Month",h=new e.Date(a),f=e.get(d,h);e.set(d,h,f+b);f===e.get(d,h)&&e.set("Date",h,0);return h.getTime()-a};if(p(a)){var g=b-a;var k=a}else g=b+f(b,-a.count),this.chart&&(this.chart.fixedRange=b-g);var m=D(this.dataMin,Number.MIN_VALUE);p(g)||(g=m);g<=m&&(g=m,"undefined"===typeof k&&
(k=f(g,a.count)),this.newMax=Math.min(g+k,this.dataMax));p(b)||(g=void 0);return g};n.RangeSelector||(t(a,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new m(this))}),t(a,"beforeRender",function(){var a=this.axes,c=this.rangeSelector;c&&(p(c.deferredYTDClick)&&(c.clickButton(c.deferredYTDClick),delete c.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),c.render(),a=c.options.verticalAlign,c.options.floating||("bottom"===
a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),t(a,"update",function(a){var c=a.options.rangeSelector;a=this.rangeSelector;var b=this.extraBottomMargin,d=this.extraTopMargin;c&&c.enabled&&!v(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new m(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),c=c&&c.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===c?this.extraBottomMargin=!0:"middle"!==c&&(this.extraTopMargin=
!0)),this.extraBottomMargin!==b||this.extraTopMargin!==d)&&(this.isDirtyBox=!0)}),t(a,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),t(a,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),a.prototype.callbacks.push(function(a){function c(){b=a.xAxis[0].getExtremes();
p(b.min)&&d.render(b.min,b.max)}var b,d=a.rangeSelector;if(d){var e=t(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)});var f=t(a,"redraw",c);c()}t(a,"destroy",function(){d&&(f(),e())})}),n.RangeSelector=m)});G(n,"parts/NavigatorAxis.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,a){var m=n.isTouchDevice,t=a.addEvent,r=a.correctFloat,w=a.defined,v=a.isNumber,E=a.pick,x=function(){function a(a){this.axis=a}a.prototype.destroy=function(){this.axis=void 0};a.prototype.toFixedRange=
function(a,e,m,n){var k=this.axis,p=k.chart;p=p&&p.fixedRange;var g=(k.pointRange||0)/2;a=E(m,k.translate(a,!0,!k.horiz));e=E(n,k.translate(e,!0,!k.horiz));k=p&&(e-a)/p;w(m)||(a=r(a+g));w(n)||(e=r(e-g));.7<k&&1.3>k&&(n?a=e-p:e=a+p);v(a)&&v(e)||(a=e=void 0);return{min:a,max:e}};return a}();return function(){function a(){}a.compose=function(a){a.keepProps.push("navigatorAxis");t(a,"init",function(){this.navigatorAxis||(this.navigatorAxis=new x(this))});t(a,"zoom",function(a){var e=this.chart.options,
k=e.navigator,n=this.navigatorAxis,p=e.chart.pinchType,g=e.rangeSelector;e=e.chart.zoomType;this.isXAxis&&(k&&k.enabled||g&&g.enabled)&&("y"===e?a.zoomed=!1:(!m&&"xy"===e||m&&"xy"===p)&&this.options.range&&(k=n.previousZoom,w(a.newMin)?n.previousZoom=[this.min,this.max]:k&&(a.newMin=k[0],a.newMax=k[1],n.previousZoom=void 0)));"undefined"!==typeof a.zoomed&&a.preventDefault()})};a.AdditionsClass=x;return a}()});G(n,"parts/Navigator.js",[n["parts/Axis.js"],n["parts/Color.js"],n["parts/Globals.js"],
n["parts/NavigatorAxis.js"],n["parts/Scrollbar.js"],n["parts/Utilities.js"]],function(n,a,m,t,r,w){a=a.parse;var v=w.addEvent,E=w.clamp,x=w.correctFloat,e=w.defined,k=w.destroyObjectProperties,p=w.erase,u=w.extend,F=w.find,D=w.isArray,C=w.isNumber,g=w.merge,f=w.pick,A=w.removeEvent,d=w.splat;w=m.Chart;var c=m.defaultOptions,b=m.hasTouch,l=m.isTouchDevice,G=m.Series,J=function(a){for(var b=[],c=1;c<arguments.length;c++)b[c-1]=arguments[c];b=[].filter.call(b,C);if(b.length)return Math[a].apply(0,b)};
var P="undefined"===typeof m.seriesTypes.areaspline?"line":"areaspline";u(c,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:a("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:P,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",
[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",
style:{color:"#999999"},x:3,y:-4},crosshair:!1},yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});m.Renderer.prototype.symbols["navigator-handle"]=function(a,b,c,d,e){a=e.width/2;b=Math.round(a/3)+.5;e=e.height;return["M",-a-1,.5,"L",a,.5,"L",a,e+.5,"L",-a-1,e+.5,"L",-a-1,.5,"M",-b,4,"L",-b,e-3,"M",b-1,4,"L",b-1,e-3]};var B=function(){function a(a){this.zoomedMin=
this.zoomedMax=this.yAxis=this.xAxis=this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(a)}a.prototype.drawHandle=function(a,b,c,e){var d=this.navigatorOptions.handles.height;this.handles[b][e](c?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+
parseInt(a,10)+.5-d)}:{translateX:Math.round(this.left+parseInt(a,10)),translateY:Math.round(this.top+this.height/2-d/2-1)})};a.prototype.drawOutline=function(a,b,c,e){var d=this.navigatorOptions.maskInside,h=this.outline.strokeWidth(),f=h/2;h=h%2/2;var g=this.outlineHeight,q=this.scrollbarHeight,k=this.size,l=this.left-q,m=this.top;c?(l-=f,c=m+b+h,b=m+a+h,a=["M",l+g,m-q-h,"L",l+g,c,"L",l,c,"L",l,b,"L",l+g,b,"L",l+g,m+k+q].concat(d?["M",l+g,c-f,"L",l+g,b+f]:[])):(a+=l+q-h,b+=l+q-h,m+=f,a=["M",l,m,
"L",a,m,"L",a,m+g,"L",b,m+g,"L",b,m,"L",l+k+2*q,m].concat(d?["M",a-f,m,"L",b+f,m]:[]));this.outline[e]({d:a})};a.prototype.drawMasks=function(a,b,c,e){var d=this.left,h=this.top,f=this.height;if(c){var g=[d,d,d];var q=[h,h+a,h+b];var k=[f,f,f];var l=[a,b-a,this.size-b]}else g=[d,d+a,d+b],q=[h,h,h],k=[a,b-a,this.size-b],l=[f,f,f];this.shades.forEach(function(a,b){a[e]({x:g[b],y:q[b],width:k[b],height:l[b]})})};a.prototype.renderElements=function(){var a=this,b=a.navigatorOptions,c=b.maskInside,d=a.chart,
e=d.renderer,f,g={cursor:d.inverted?"ns-resize":"ew-resize"};a.navigatorGroup=f=e.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!c,c,!c].forEach(function(c,h){a.shades[h]=e.rect().addClass("highcharts-navigator-mask"+(1===h?"-inside":"-outside")).add(f);d.styledMode||a.shades[h].attr({fill:c?b.maskFill:"rgba(0,0,0,0)"}).css(1===h&&g)});a.outline=e.path().addClass("highcharts-navigator-outline").add(f);d.styledMode||a.outline.attr({"stroke-width":b.outlineWidth,stroke:b.outlineColor});
b.handles.enabled&&[0,1].forEach(function(c){b.handles.inverted=d.inverted;a.handles[c]=e.symbol(b.handles.symbols[c],-b.handles.width/2-1,0,b.handles.width,b.handles.height,b.handles);a.handles[c].attr({zIndex:7-c}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][c]).add(f);if(!d.styledMode){var h=b.handles;a.handles[c].attr({fill:h.backgroundColor,stroke:h.borderColor,"stroke-width":h.lineWidth}).css(g)}})};a.prototype.update=function(a){(this.series||[]).forEach(function(a){a.baseSeries&&
delete a.baseSeries.navigatorSeries});this.destroy();g(!0,this.chart.options.navigator,this.options,a);this.init(this.chart)};a.prototype.render=function(a,b,c,d){var h=this.chart,g=this.scrollbarHeight,q,k=this.xAxis,l=k.pointRange||0;var m=k.navigatorAxis.fake?h.xAxis[0]:k;var n=this.navigatorEnabled,p,y=this.rendered;var r=h.inverted;var u=h.xAxis[0].minRange,t=h.xAxis[0].options.maxRange;if(!this.hasDragged||e(c)){a=x(a-l/2);b=x(b+l/2);if(!C(a)||!C(b))if(y)c=0,d=f(k.width,m.width);else return;
this.left=f(k.left,h.plotLeft+g+(r?h.plotWidth:0));this.size=p=q=f(k.len,(r?h.plotHeight:h.plotWidth)-2*g);h=r?g:q+2*g;c=f(c,k.toPixels(a,!0));d=f(d,k.toPixels(b,!0));C(c)&&Infinity!==Math.abs(c)||(c=0,d=h);a=k.toValue(c,!0);b=k.toValue(d,!0);var v=Math.abs(x(b-a));v<u?this.grabbedLeft?c=k.toPixels(b-u-l,!0):this.grabbedRight&&(d=k.toPixels(a+u+l,!0)):e(t)&&x(v-l)>t&&(this.grabbedLeft?c=k.toPixels(b-t-l,!0):this.grabbedRight&&(d=k.toPixels(a+t+l,!0)));this.zoomedMax=E(Math.max(c,d),0,p);this.zoomedMin=
E(this.fixedWidth?this.zoomedMax-this.fixedWidth:Math.min(c,d),0,p);this.range=this.zoomedMax-this.zoomedMin;p=Math.round(this.zoomedMax);c=Math.round(this.zoomedMin);n&&(this.navigatorGroup.attr({visibility:"visible"}),y=y&&!this.hasDragged?"animate":"attr",this.drawMasks(c,p,r,y),this.drawOutline(c,p,r,y),this.navigatorOptions.handles.enabled&&(this.drawHandle(c,0,r,y),this.drawHandle(p,1,r,y)));this.scrollbar&&(r?(r=this.top-g,m=this.left-g+(n||!m.opposite?0:(m.titleOffset||0)+m.axisTitleMargin),
g=q+2*g):(r=this.top+(n?this.height:-g),m=this.left-g),this.scrollbar.position(m,r,h,g),this.scrollbar.setRange(this.zoomedMin/(q||1),this.zoomedMax/(q||1)));this.rendered=!0}};a.prototype.addMouseEvents=function(){var a=this,c=a.chart,d=c.container,e=[],f,g;a.mouseMoveHandler=f=function(b){a.onMouseMove(b)};a.mouseUpHandler=g=function(b){a.onMouseUp(b)};e=a.getPartsEvents("mousedown");e.push(v(c.renderTo,"mousemove",f),v(d.ownerDocument,"mouseup",g));b&&(e.push(v(c.renderTo,"touchmove",f),v(d.ownerDocument,
"touchend",g)),e.concat(a.getPartsEvents("touchstart")));a.eventsToUnbind=e;a.series&&a.series[0]&&e.push(v(a.series[0].xAxis,"foundExtremes",function(){c.navigator.modifyNavigatorAxisExtremes()}))};a.prototype.getPartsEvents=function(a){var b=this,c=[];["shades","handles"].forEach(function(d){b[d].forEach(function(e,h){c.push(v(e.element,a,function(a){b[d+"Mousedown"](a,h)}))})});return c};a.prototype.shadesMousedown=function(a,b){a=this.chart.pointer.normalize(a);var c=this.chart,d=this.xAxis,h=
this.zoomedMin,f=this.left,g=this.size,k=this.range,q=a.chartX;c.inverted&&(q=a.chartY,f=this.top);if(1===b)this.grabbedCenter=q,this.fixedWidth=k,this.dragOffset=q-h;else{a=q-f-k/2;if(0===b)a=Math.max(0,a);else if(2===b&&a+k>=g)if(a=g-k,this.reversedExtremes){a-=k;var l=this.getUnionExtremes().dataMin}else var m=this.getUnionExtremes().dataMax;a!==h&&(this.fixedWidth=k,b=d.navigatorAxis.toFixedRange(a,a+k,l,m),e(b.min)&&c.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,null,{trigger:"navigator"}))}};
a.prototype.handlesMousedown=function(a,b){this.chart.pointer.normalize(a);a=this.chart;var c=a.xAxis[0],d=this.reversedExtremes;0===b?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=d?c.min:c.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=d?c.max:c.min);a.fixedRange=null};a.prototype.onMouseMove=function(a){var b=this,c=b.chart,d=b.left,e=b.navigatorSize,h=b.range,g=b.dragOffset,k=c.inverted;a.touches&&0===a.touches[0].pageX||(a=c.pointer.normalize(a),
c=a.chartX,k&&(d=b.top,c=a.chartY),b.grabbedLeft?(b.hasDragged=!0,b.render(0,0,c-d,b.otherHandlePos)):b.grabbedRight?(b.hasDragged=!0,b.render(0,0,b.otherHandlePos,c-d)):b.grabbedCenter&&(b.hasDragged=!0,c<g?c=g:c>e+g-h&&(c=e+g-h),b.render(0,0,c-g,c-g+h)),b.hasDragged&&b.scrollbar&&f(b.scrollbar.options.liveRedraw,m.svg&&!l&&!this.chart.isBoosting)&&(a.DOMType=a.type,setTimeout(function(){b.onMouseUp(a)},0)))};a.prototype.onMouseUp=function(a){var b=this.chart,c=this.xAxis,d=this.scrollbar,h=a.DOMEvent||
a,f=b.inverted,g=this.rendered&&!this.hasDragged?"animate":"attr",k=Math.round(this.zoomedMax),l=Math.round(this.zoomedMin);if(this.hasDragged&&(!d||!d.hasDragged)||"scrollbar"===a.trigger){d=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var m=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var n=this.fixedExtreme;this.zoomedMax===this.size&&(n=this.reversedExtremes?d.dataMin:d.dataMax);0===this.zoomedMin&&(m=this.reversedExtremes?d.dataMax:d.dataMin);c=c.navigatorAxis.toFixedRange(this.zoomedMin,
this.zoomedMax,m,n);e(c.min)&&b.xAxis[0].setExtremes(Math.min(c.min,c.max),Math.max(c.min,c.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:h})}"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&(this.shades&&this.drawMasks(l,k,f,g),this.outline&&this.drawOutline(l,k,f,g),this.navigatorOptions.handles.enabled&&
Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(l,0,f,g),this.drawHandle(k,1,f,g)))};a.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(a){a()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};a.prototype.removeBaseSeriesEvents=function(){var a=this.baseSeries||[];this.navigatorEnabled&&a[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&a.forEach(function(a){A(a,"updatedData",this.updatedDataHandler)},this),a[0].xAxis&&
A(a[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};a.prototype.init=function(a){var b=a.options,c=b.navigator,d=c.enabled,e=b.scrollbar,h=e.enabled;b=d?c.height:0;var k=h?e.height:0;this.handles=[];this.shades=[];this.chart=a;this.setBaseSeries();this.height=b;this.scrollbarHeight=k;this.scrollbarEnabled=h;this.navigatorEnabled=d;this.navigatorOptions=c;this.scrollbarOptions=e;this.outlineHeight=b+k;this.opposite=f(c.opposite,!(d||!a.inverted));var l=this;d=l.baseSeries;e=a.xAxis.length;
h=a.yAxis.length;var m=d&&d[0]&&d[0].xAxis||a.xAxis[0]||{options:{}};a.isDirtyBox=!0;l.navigatorEnabled?(l.xAxis=new n(a,g({breaks:m.options.breaks,ordinal:m.options.ordinal},c.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:e,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},a.inverted?{offsets:[k,0,-k,0],width:b}:{offsets:[0,-k,0,k],height:b})),l.yAxis=new n(a,g(c.yAxis,{id:"navigator-y-axis",alignTicks:!1,
offset:0,index:h,isInternal:!0,zoomEnabled:!1},a.inverted?{width:b}:{height:b})),d||c.series.data?l.updateNavigatorSeries(!1):0===a.series.length&&(l.unbindRedraw=v(a,"beforeRedraw",function(){0<a.series.length&&!l.series&&(l.setBaseSeries(),l.unbindRedraw())})),l.reversedExtremes=a.inverted&&!l.xAxis.reversed||!a.inverted&&l.xAxis.reversed,l.renderElements(),l.addMouseEvents()):(l.xAxis={chart:a,navigatorAxis:{fake:!0},translate:function(b,c){var d=a.xAxis[0],e=d.getExtremes(),h=d.len-2*k,f=J("min",
d.options.min,e.dataMin);d=J("max",d.options.max,e.dataMax)-f;return c?b*d/h+f:h*(b-f)/d},toPixels:function(a){return this.translate(a)},toValue:function(a){return this.translate(a,!0)}},l.xAxis.navigatorAxis.axis=l.xAxis,l.xAxis.navigatorAxis.toFixedRange=t.AdditionsClass.prototype.toFixedRange.bind(l.xAxis.navigatorAxis));a.options.scrollbar.enabled&&(a.scrollbar=l.scrollbar=new r(a.renderer,g(a.options.scrollbar,{margin:l.navigatorEnabled?0:10,vertical:a.inverted}),a),v(l.scrollbar,"changed",function(b){var c=
l.size,d=c*this.to;c*=this.from;l.hasDragged=l.scrollbar.hasDragged;l.render(0,0,c,d);(a.options.scrollbar.liveRedraw||"mousemove"!==b.DOMType&&"touchmove"!==b.DOMType)&&setTimeout(function(){l.onMouseUp(b)})}));l.addBaseSeriesEvents();l.addChartEvents()};a.prototype.getUnionExtremes=function(a){var b=this.chart.xAxis[0],c=this.xAxis,d=c.options,e=b.options,h;a&&null===b.dataMin||(h={dataMin:f(d&&d.min,J("min",e.min,b.dataMin,c.dataMin,c.min)),dataMax:f(d&&d.max,J("max",e.max,b.dataMax,c.dataMax,
c.max))});return h};a.prototype.setBaseSeries=function(a,b){var c=this.chart,d=this.baseSeries=[];a=a||c.options&&c.options.navigator.baseSeries||(c.series.length?F(c.series,function(a){return!a.options.isInternal}).index:0);(c.series||[]).forEach(function(b,c){b.options.isInternal||!b.options.showInNavigator&&(c!==a&&b.options.id!==a||!1===b.options.showInNavigator)||d.push(b)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,b)};a.prototype.updateNavigatorSeries=function(a,
b){var e=this,h=e.chart,k=e.baseSeries,l,m,n=e.navigatorOptions.series,q,p={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,isInternal:!0,states:{inactive:{opacity:1}}},r=e.series=(e.series||[]).filter(function(a){var b=a.baseSeries;return 0>k.indexOf(b)?(b&&(A(b,"updatedData",e.updatedDataHandler),delete b.navigatorSeries),a.chart&&a.destroy(),!1):!0});k&&k.length&&k.forEach(function(a){var d=
a.navigatorSeries,t=u({color:a.color,visible:a.visible},D(n)?c.navigator.series:n);d&&!1===e.navigatorOptions.adaptToUpdatedData||(p.name="Navigator "+k.length,l=a.options||{},q=l.navigatorOptions||{},m=g(l,p,t,q),m.pointRange=f(t.pointRange,q.pointRange,c.plotOptions[m.type||"line"].pointRange),t=q.data||t.data,e.hasNavigatorData=e.hasNavigatorData||!!t,m.data=t||l.data&&l.data.slice(0),d&&d.options?d.update(m,b):(a.navigatorSeries=h.initSeries(m),a.navigatorSeries.baseSeries=a,r.push(a.navigatorSeries)))});
if(n.data&&(!k||!k.length)||D(n))e.hasNavigatorData=!1,n=d(n),n.forEach(function(a,b){p.name="Navigator "+(r.length+1);m=g(c.navigator.series,{color:h.series[b]&&!h.series[b].options.isInternal&&h.series[b].color||h.options.colors[b]||h.options.colors[0]},p,a);m.data=a.data;m.data&&(e.hasNavigatorData=!0,r.push(h.initSeries(m)))});a&&this.addBaseSeriesEvents()};a.prototype.addBaseSeriesEvents=function(){var a=this,b=a.baseSeries||[];b[0]&&b[0].xAxis&&v(b[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);
b.forEach(function(b){v(b,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});v(b,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&b.xAxis&&v(b,"updatedData",this.updatedDataHandler);v(b,"remove",function(){this.navigatorSeries&&(p(a.series,this.navigatorSeries),e(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};a.prototype.getBaseSeriesMin=
function(a){return this.baseSeries.reduce(function(a,b){return Math.min(a,b.xData?b.xData[0]:a)},a)};a.prototype.modifyNavigatorAxisExtremes=function(){var a=this.xAxis,b;"undefined"!==typeof a.getExtremes&&(!(b=this.getUnionExtremes(!0))||b.dataMin===a.min&&b.dataMax===a.max||(a.min=b.dataMin,a.max=b.dataMax))};a.prototype.modifyBaseAxisExtremes=function(){var a=this.chart.navigator,b=this.getExtremes(),c=b.dataMin,d=b.dataMax;b=b.max-b.min;var e=a.stickToMin,g=a.stickToMax,k=f(this.options.overscroll,
0),l=a.series&&a.series[0],m=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(e){var n=c;var p=n+b}g&&(p=d+k,e||(n=Math.max(p-b,a.getBaseSeriesMin(l&&l.xData?l.xData[0]:-Number.MAX_VALUE))));m&&(e||g)&&C(n)&&(this.min=this.userMin=n,this.max=this.userMax=p)}a.stickToMin=a.stickToMax=null};a.prototype.updatedDataHandler=function(){var a=this.chart.navigator,b=this.navigatorSeries,c=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):
Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=C(this.xAxis.min)&&this.xAxis.min<=c&&(!this.chart.fixedRange||!a.stickToMax);b&&!a.hasNavigatorData&&(b.options.pointStart=this.xData[0],b.setData(this.options.data,!1,null,!1))};a.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(v(this.chart,"redraw",function(){var a=this.navigator,b=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||this.xAxis[0]);b&&a.render(b.min,b.max)}),
v(this.chart,"getMargins",function(){var a=this.navigator,b=a.opposite?"plotTop":"marginBottom";this.inverted&&(b=a.opposite?"marginRight":"plotLeft");this[b]=(this[b]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))};a.prototype.destroy=function(){this.removeEvents();this.xAxis&&(p(this.chart.xAxis,this.xAxis),p(this.chart.axes,this.xAxis));this.yAxis&&(p(this.chart.yAxis,this.yAxis),p(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&
a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){k(a)},this)};return a}();m.Navigator||(m.Navigator=B,t.compose(n),v(w,"beforeShowResetZoom",function(){var a=this.options,b=a.navigator,c=a.rangeSelector;if((b&&b.enabled||c&&c.enabled)&&(!l&&"x"===a.chart.zoomType||l&&"x"===a.chart.pinchType))return!1}),
v(w,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new B(this)}),v(w,"afterSetChartSize",function(){var a=this.legend,b=this.navigator;if(b){var c=a&&a.options;var d=b.xAxis;var e=b.yAxis;var g=b.scrollbarHeight;this.inverted?(b.left=b.opposite?this.chartWidth-g-b.height:this.spacing[3]+g,b.top=this.plotTop+g):(b.left=this.plotLeft+g,b.top=b.navigatorOptions.top||this.chartHeight-b.height-g-this.spacing[2]-(this.rangeSelector&&
this.extraBottomMargin?this.rangeSelector.getHeight():0)-(c&&"bottom"===c.verticalAlign&&c.enabled&&!c.floating?a.legendHeight+f(c.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));d&&e&&(this.inverted?d.options.left=e.options.left=b.left:d.options.top=e.options.top=b.top,d.setAxisSize(),e.setAxisSize())}}),v(w,"update",function(a){var b=a.options.navigator||{},c=a.options.scrollbar||{};this.navigator||this.scroller||!b.enabled&&!c.enabled||(g(!0,this.options.navigator,b),g(!0,this.options.scrollbar,
c),delete a.options.navigator,delete a.options.scrollbar)}),v(w,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new B(this),f(a.redraw,!0)&&this.redraw(a.animation))}),v(w,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),v(G,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),w.prototype.callbacks.push(function(a){var b=
a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}));m.Navigator=B;return m.Navigator});G(n,"masters/modules/gantt.src.js",[],function(){})});
//# sourceMappingURL=gantt.js.map