/*
 Highmaps JS v8.0.4 (2020-04-02)

 (c) 2009-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/heatmap",["highcharts"],function(q){b(q);b.Highcharts=q;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function q(b,r,k,y){b.hasOwnProperty(r)||(b[r]=y.apply(null,k))}b=b?b._modules:{};q(b,"parts-map/ColorSeriesMixin.js",[b["parts/Globals.js"]],function(b){b.colorPointMixin={setVisible:function(b){var k=this,n=b?"show":
"hide";k.visible=k.options.visible=!!b;["graphic","dataLabel"].forEach(function(b){if(k[b])k[b][n]()})}};b.colorSeriesMixin={optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var b=this,k=this.options.nullColor,n=this.colorAxis,q=this.colorKey;(this.data.length?this.data:this.points).forEach(function(f){var w=f.getNestedProperty(q);if(w=f.options.color||(f.isNull||null===f.value?k:n&&"undefined"!==typeof w?n.toColor(w,f):f.color||b.color))f.color=w})}}});q(b,"parts-map/ColorAxis.js",
[b["parts/Globals.js"],b["parts/Color.js"],b["parts/Point.js"],b["parts/Legend.js"],b["mixins/legend-symbol.js"],b["parts/Utilities.js"]],function(b,r,k,y,q,f){"";var n=r.parse;r=f.addEvent;var x=f.erase,v=f.extend,C=f.Fx,t=f.isNumber,u=f.merge,a=f.pick,e=f.splat,m=b.Axis;f=b.Chart;var z=b.Series,p=b.colorPointMixin,l=b.noop;v(z.prototype,b.colorSeriesMixin);v(k.prototype,p);f.prototype.collectionsWithUpdate.push("colorAxis");f.prototype.collectionsWithInit.colorAxis=[f.prototype.addColorAxis];var g=
b.ColorAxis=function(){this.init.apply(this,arguments)};v(g.prototype,m.prototype);v(g.prototype,{defaultColorAxisOptions:{lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0},keepProps:["legendGroup","legendItemHeight","legendItemWidth","legendItem","legendSymbol"].concat(m.keepProps),
init:function(d,c){this.coll="colorAxis";var a=this.buildOptions.call(d,this.defaultColorAxisOptions,c);m.prototype.init.call(this,d,a);c.dataClasses&&this.initDataClasses(c);this.initStops();this.horiz=!a.opposite;this.zoomEnabled=!1;this.defaultLegendLength=200},initDataClasses:function(d){var c=this.chart,a,h=0,B=c.options.chart.colorCount,b=this.options,e=d.dataClasses.length;this.dataClasses=a=[];this.legendItems=[];d.dataClasses.forEach(function(d,A){d=u(d);a.push(d);if(c.styledMode||!d.color)"category"===
b.dataClassColor?(c.styledMode||(A=c.options.colors,B=A.length,d.color=A[h]),d.colorIndex=h,h++,h===B&&(h=0)):d.color=n(b.minColor).tweenTo(n(b.maxColor),2>e?.5:A/(e-1))})},hasData:function(){return!(!this.tickPositions||!this.tickPositions.length)},setTickPositions:function(){if(!this.dataClasses)return m.prototype.setTickPositions.call(this)},initStops:function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];this.stops.forEach(function(d){d.color=n(d[1])})},
buildOptions:function(d,c){var a=this.options.legend,h=c.layout?"vertical"!==c.layout:"vertical"!==a.layout;return u(d,{side:h?2:1,reversed:!h},c,{opposite:!h,showEmpty:!1,title:null,visible:a.enabled&&(c?!1!==c.visible:!0)})},setOptions:function(d){m.prototype.setOptions.call(this,d);this.options.crosshair=this.options.marker},setAxisSize:function(){var d=this.legendSymbol,c=this.chart,a=c.options.legend||{},h,b;d?(this.left=a=d.attr("x"),this.top=h=d.attr("y"),this.width=b=d.attr("width"),this.height=
d=d.attr("height"),this.right=c.chartWidth-a-b,this.bottom=c.chartHeight-h-d,this.len=this.horiz?b:d,this.pos=this.horiz?a:h):this.len=(this.horiz?a.symbolWidth:a.symbolHeight)||this.defaultLegendLength},normalizedValue:function(d){this.logarithmic&&(d=this.logarithmic.log2lin(d));return 1-(this.max-d)/(this.max-this.min||1)},toColor:function(d,c){var a=this.stops,h=this.dataClasses,b;if(h)for(b=h.length;b--;){var e=h[b];var l=e.from;a=e.to;if(("undefined"===typeof l||d>=l)&&("undefined"===typeof a||
d<=a)){var g=e.color;c&&(c.dataClass=b,c.colorIndex=e.colorIndex);break}}else{d=this.normalizedValue(d);for(b=a.length;b--&&!(d>a[b][0]););l=a[b]||a[b+1];a=a[b+1]||l;d=1-(a[0]-d)/(a[0]-l[0]||1);g=l.color.tweenTo(a.color,d)}return g},getOffset:function(){var d=this.legendGroup,c=this.chart.axisOffset[this.side];d&&(this.axisParent=d,m.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=c)},setLegendColor:function(){var d=
this.reversed;var c=d?1:0;d=d?0:1;c=this.horiz?[c,0,d,0]:[0,d,0,c];this.legendColor={linearGradient:{x1:c[0],y1:c[1],x2:c[2],y2:c[3]},stops:this.stops}},drawLegendSymbol:function(d,c){var b=d.padding,h=d.options,e=this.horiz,l=a(h.symbolWidth,e?this.defaultLegendLength:12),g=a(h.symbolHeight,e?12:this.defaultLegendLength),f=a(h.labelPadding,e?16:30);h=a(h.itemDistance,10);this.setLegendColor();c.legendSymbol=this.chart.renderer.rect(0,d.baseline-11,l,g).attr({zIndex:1}).add(c.legendGroup);this.legendItemWidth=
l+b+(e?h:f);this.legendItemHeight=g+b+(e?f:0)},setState:function(d){this.series.forEach(function(c){c.setState(d)})},visible:!0,setVisible:l,getSeriesExtremes:function(){var d=this.series,c=d.length,b;this.dataMin=Infinity;for(this.dataMax=-Infinity;c--;){var h=d[c];var e=h.colorKey=a(h.options.colorKey,h.colorKey,h.pointValKey,h.zoneAxis,"y");var l=h.pointArrayMap;var g=h[e+"Min"]&&h[e+"Max"];if(h[e+"Data"])var f=h[e+"Data"];else if(l){f=[];l=l.indexOf(e);var m=h.yData;if(0<=l&&m)for(b=0;b<m.length;b++)f.push(a(m[b][l],
m[b]))}else f=h.yData;g?(h.minColorValue=h[e+"Min"],h.maxColorValue=h[e+"Max"]):(f=z.prototype.getExtremes.call(h,f),h.minColorValue=f.dataMin,h.maxColorValue=f.dataMax);"undefined"!==typeof h.minColorValue&&(this.dataMin=Math.min(this.dataMin,h.minColorValue),this.dataMax=Math.max(this.dataMax,h.maxColorValue));g||z.prototype.applyExtremes.call(h)}},drawCrosshair:function(d,c){var a=c&&c.plotX,b=c&&c.plotY,e=this.pos,l=this.len;if(c){var g=this.toPixels(c.getNestedProperty(c.series.colorKey));g<
e?g=e-2:g>e+l&&(g=e+l+2);c.plotX=g;c.plotY=this.len-g;m.prototype.drawCrosshair.call(this,d,c);c.plotX=a;c.plotY=b;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||this.cross.attr({fill:this.crosshair.color}))}},getPlotLinePath:function(d){var c=d.translatedValue;return t(c)?this.horiz?["M",c-4,this.top-6,"L",c+4,this.top-6,c,this.top,"Z"]:["M",this.left,c,"L",
this.left-6,c+6,this.left-6,c-6,"Z"]:m.prototype.getPlotLinePath.apply(this,arguments)},update:function(d,c){var a=this.chart,b=a.legend,e=this.buildOptions.call(a,{},d);this.series.forEach(function(c){c.isDirtyData=!0});(d.dataClasses&&b.allItems||this.dataClasses)&&this.destroyItems();a.options[this.coll]=u(this.userOptions,e);m.prototype.update.call(this,e,c);this.legendItem&&(this.setLegendColor(),b.colorizeItem(this,!0))},destroyItems:function(){var a=this.chart;this.legendItem?a.legend.destroyItem(this):
this.legendItems&&this.legendItems.forEach(function(c){a.legend.destroyItem(c)});a.isDirtyLegend=!0},remove:function(a){this.destroyItems();m.prototype.remove.call(this,a)},getDataClassLegendSymbols:function(){var a=this,c=this.chart,b=this.legendItems,e=c.options.legend,g=e.valueDecimals,f=e.valueSuffix||"",m;b.length||this.dataClasses.forEach(function(d,e){var h=!0,p=d.from,n=d.to,k=c.numberFormatter;m="";"undefined"===typeof p?m="< ":"undefined"===typeof n&&(m="> ");"undefined"!==typeof p&&(m+=
k(p,g)+f);"undefined"!==typeof p&&"undefined"!==typeof n&&(m+=" - ");"undefined"!==typeof n&&(m+=k(n,g)+f);b.push(v({chart:c,name:m,options:{},drawLegendSymbol:q.drawRectangle,visible:!0,setState:l,isDataClass:!0,setVisible:function(){h=this.visible=!h;a.series.forEach(function(a){a.points.forEach(function(a){a.dataClass===e&&a.setVisible(h)})});c.legend.colorizeItem(this,h)}},d))});return b},beforePadding:!1,name:""});["fill","stroke"].forEach(function(a){C.prototype[a+"Setter"]=function(){this.elem.attr(a,
n(this.start).tweenTo(n(this.end),this.pos),null,!0)}});r(f,"afterGetAxes",function(){var a=this,c=a.options;this.colorAxis=[];c.colorAxis&&(c.colorAxis=e(c.colorAxis),c.colorAxis.forEach(function(c,d){c.index=d;new g(a,c)}))});r(z,"bindAxes",function(){var a=this.axisTypes;a?-1===a.indexOf("colorAxis")&&a.push("colorAxis"):this.axisTypes=["colorAxis"]});r(y,"afterGetAllItems",function(a){var c=[],d,b;(this.chart.colorAxis||[]).forEach(function(b){(d=b.options)&&d.showInLegend&&(d.dataClasses&&d.visible?
c=c.concat(b.getDataClassLegendSymbols()):d.visible&&c.push(b),b.series.forEach(function(c){if(!c.options.showInLegend||d.dataClasses)"point"===c.options.legendType?c.points.forEach(function(c){x(a.allItems,c)}):x(a.allItems,c)}))});for(b=c.length;b--;)a.allItems.unshift(c[b])});r(y,"afterColorizeItem",function(a){a.visible&&a.item.legendColor&&a.item.legendSymbol.attr({fill:a.item.legendColor})});r(y,"afterUpdate",function(){var a=this.chart.colorAxis;a&&a.forEach(function(a,b,d){a.update({},d)})});
r(z,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()})});q(b,"parts-map/ColorMapSeriesMixin.js",[b["parts/Globals.js"],b["parts/Point.js"],b["parts/Utilities.js"]],function(b,r,k){var n=k.defined;k=b.noop;var q=b.seriesTypes;b.colorMapPointMixin={dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(b){r.prototype.setState.call(this,b);this.graphic&&
this.graphic.attr({zIndex:"hover"===b?1:0})}};b.colorMapSeriesMixin={pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:k,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:q.column.prototype.pointAttribs,colorAttribs:function(b){var f={};n(b.color)&&(f[this.colorProp||"fill"]=b.color);return f}}});q(b,"parts-map/HeatmapSeries.js",[b["parts/Globals.js"],b["mixins/legend-symbol.js"],b["parts/Utilities.js"]],
function(b,r,k){var n=k.clamp,q=k.extend,f=k.fireEvent,w=k.isNumber,x=k.merge,v=k.pick;k=k.seriesType;var D=b.colorMapPointMixin,t=b.Series,u=b.SVGRenderer.prototype.symbols;k("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){return this.point.value},inside:!0,verticalAlign:"middle",crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},
states:{hover:{halo:!1,brightness:.2}}},x(b.colorMapSeriesMixin,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){t.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=v(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=a.rowsize||1;q(u,{ellipse:u.circle,rect:u.square})},getSymbol:t.prototype.getSymbol,setClip:function(a){var b=this.chart;t.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||
this.clipBox)&&this.sharedClipKey?b[this.sharedClipKey]:b.clipRect)},translate:function(){var a=this.options,b=a.marker&&a.marker.symbol||"",m=u[b]?b:"rect";a=this.options;var k=-1!==["circle","square"].indexOf(m);this.generatePoints();this.points.forEach(function(a){var e=a.getCellAttributes(),g={x:Math.min(e.x1,e.x2),y:Math.min(e.y1,e.y2),width:Math.max(Math.abs(e.x2-e.x1),0),height:Math.max(Math.abs(e.y2-e.y1),0)};var d=a.hasImage=0===(a.marker&&a.marker.symbol||b||"").indexOf("url");if(k){var c=
Math.abs(g.width-g.height);g.x=Math.min(e.x1,e.x2)+(g.width<g.height?0:c/2);g.y=Math.min(e.y1,e.y2)+(g.width<g.height?c/2:0);g.width=g.height=Math.min(g.width,g.height)}c={plotX:(e.x1+e.x2)/2,plotY:(e.y1+e.y2)/2,clientX:(e.x1+e.x2)/2,shapeType:"path",shapeArgs:x(!0,g,{d:u[m](g.x,g.y,g.width,g.height)})};d&&(a.marker={width:g.width,height:g.height});q(a,c)});f(this,"afterTranslate")},pointAttribs:function(a,e){var f=t.prototype.pointAttribs.call(this,a,e),k=this.options||{},p=this.chart.options.plotOptions||
{},l=p.series||{},g=p.heatmap||{};p=k.borderColor||g.borderColor||l.borderColor;l=k.borderWidth||g.borderWidth||l.borderWidth||f["stroke-width"];f.stroke=a&&a.marker&&a.marker.lineColor||k.marker&&k.marker.lineColor||p||this.color;f["stroke-width"]=l;e&&(a=x(k.states[e],k.marker&&k.marker.states[e],a.options.states&&a.options.states[e]||{}),e=a.brightness,f.fill=a.color||b.color(f.fill).brighten(e||0).get(),f.stroke=a.lineColor);return f},markerAttribs:function(a,b){var e=a.marker||{},f=this.options.marker||
{},k=a.shapeArgs||{},l={};if(a.hasImage)return{x:a.plotX,y:a.plotY};if(b){var g=f.states[b]||{};var d=e.states&&e.states[b]||{};[["width","x"],["height","y"]].forEach(function(a){l[a[0]]=(d[a[0]]||g[a[0]]||k[a[0]])+(d[a[0]+"Plus"]||g[a[0]+"Plus"]||0);l[a[1]]=k[a[1]]+(k[a[0]]-l[a[0]])/2})}return b?l:k},drawPoints:function(){var a=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)t.prototype.drawPoints.call(this),this.points.forEach(function(b){b.graphic&&b.graphic[a.chart.styledMode?
"css":"animate"](a.colorAttribs(b))})},hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,b){return t.prototype.getValidPoints.call(this,a,b,!0)},getBox:b.noop,drawLegendSymbol:r.drawRectangle,alignDataLabel:b.seriesTypes.column.prototype.alignDataLabel,getExtremes:function(){var a=t.prototype.getExtremes.call(this,this.valueData),b=a.dataMin;a=a.dataMax;w(b)&&(this.valueMin=b);w(a)&&(this.valueMax=a);return t.prototype.getExtremes.call(this)}}),x(D,{applyOptions:function(a,
e){a=b.Point.prototype.applyOptions.call(this,a,e);a.formatPrefix=a.isNull||null===a.value?"null":"point";return a},isValid:function(){return Infinity!==this.value&&-Infinity!==this.value},haloPath:function(a){if(!a)return[];var b=this.shapeArgs;return["M",b.x-a,b.y-a,"L",b.x-a,b.y+b.height+a,b.x+b.width+a,b.y+b.height+a,b.x+b.width+a,b.y-a,"Z"]},getCellAttributes:function(){var a=this.series,b=a.options,f=(b.colsize||1)/2,k=(b.rowsize||1)/2,p=a.xAxis,l=a.yAxis,g=this.options.marker||a.options.marker;
a=a.pointPlacementToXValue();var d=v(this.pointPadding,b.pointPadding,0),c={x1:n(Math.round(p.len-(p.translate(this.x-f,!1,!0,!1,!0,-a)||0)),-p.len,2*p.len),x2:n(Math.round(p.len-(p.translate(this.x+f,!1,!0,!1,!0,-a)||0)),-p.len,2*p.len),y1:n(Math.round(l.translate(this.y-k,!1,!0,!1,!0)||0),-l.len,2*l.len),y2:n(Math.round(l.translate(this.y+k,!1,!0,!1,!0)||0),-l.len,2*l.len)};[["width","x"],["height","y"]].forEach(function(a){var b=a[0];a=a[1];var e=a+"1",f=a+"2",k=Math.abs(c[e]-c[f]),l=g&&g.lineWidth||
0,m=Math.abs(c[e]+c[f])/2;g[b]&&g[b]<k&&(c[e]=m-g[b]/2-l/2,c[f]=m+g[b]/2+l/2);d&&("y"===a&&(e=f,f=a+"1"),c[e]+=d,c[f]-=d)});return c}}));""});q(b,"masters/modules/heatmap.src.js",[],function(){})});
//# sourceMappingURL=heatmap.js.map