/*
 Highmaps JS v8.0.4 (2020-04-02)

 Highmaps as a plugin for Highcharts or Highstock.

 (c) 2011-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(d){"object"===typeof module&&module.exports?(d["default"]=d,module.exports=d):"function"===typeof define&&define.amd?define("highcharts/modules/map",["highcharts"],function(x){d(x);d.Highcharts=x;return d}):d("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(d){function x(a,p,d,f){a.hasOwnProperty(p)||(a[p]=f.apply(null,d))}d=d?d._modules:{};x(d,"parts-map/MapAxis.js",[d["parts/Axis.js"],d["parts/Utilities.js"]],function(a,p){var d=p.addEvent,f=p.pick,y=function(){return function(a){this.axis=
a}}();p=function(){function a(){}a.compose=function(a){a.keepProps.push("mapAxis");d(a,"init",function(){this.mapAxis||(this.mapAxis=new y(this))});d(a,"getSeriesExtremes",function(){if(this.mapAxis){var a=[];this.isXAxis&&(this.series.forEach(function(f,r){f.useMapGeometry&&(a[r]=f.xData,f.xData=[])}),this.mapAxis.seriesXData=a)}});d(a,"afterGetSeriesExtremes",function(){if(this.mapAxis){var a=this.mapAxis.seriesXData||[],q;if(this.isXAxis){var r=f(this.dataMin,Number.MAX_VALUE);var c=f(this.dataMax,
-Number.MAX_VALUE);this.series.forEach(function(l,g){l.useMapGeometry&&(r=Math.min(r,f(l.minX,r)),c=Math.max(c,f(l.maxX,c)),l.xData=a[g],q=!0)});q&&(this.dataMin=r,this.dataMax=c);this.mapAxis.seriesXData=void 0}}});d(a,"afterSetAxisTranslation",function(){if(this.mapAxis){var a=this.chart,f=a.plotWidth/a.plotHeight;a=a.xAxis[0];var q;"yAxis"===this.coll&&"undefined"!==typeof a.transA&&this.series.forEach(function(c){c.preserveAspectRatio&&(q=!0)});if(q&&(this.transA=a.transA=Math.min(this.transA,
a.transA),f/=(a.max-a.min)/(this.max-this.min),f=1>f?this:a,a=(f.max-f.min)*f.transA,f.mapAxis.pixelPadding=f.len-a,f.minPixelPadding=f.mapAxis.pixelPadding/2,a=f.mapAxis.fixTo)){a=a[1]-f.toValue(a[0],!0);a*=f.transA;if(Math.abs(a)>f.minPixelPadding||f.min===f.dataMin&&f.max===f.dataMax)a=0;f.minPixelPadding-=a}}});d(a,"render",function(){this.mapAxis&&(this.mapAxis.fixTo=void 0)})};return a}();p.compose(a);return p});x(d,"parts-map/ColorSeriesMixin.js",[d["parts/Globals.js"]],function(a){a.colorPointMixin=
{setVisible:function(a){var d=this,f=a?"show":"hide";d.visible=d.options.visible=!!a;["graphic","dataLabel"].forEach(function(a){if(d[a])d[a][f]()})}};a.colorSeriesMixin={optionalAxis:"colorAxis",colorAxis:0,translateColors:function(){var a=this,d=this.options.nullColor,f=this.colorAxis,y=this.colorKey;(this.data.length?this.data:this.points).forEach(function(q){var p=q.getNestedProperty(y);if(p=q.options.color||(q.isNull||null===q.value?d:f&&"undefined"!==typeof p?f.toColor(p,q):q.color||a.color))q.color=
p})}}});x(d,"parts-map/ColorAxis.js",[d["parts/Globals.js"],d["parts/Color.js"],d["parts/Point.js"],d["parts/Legend.js"],d["mixins/legend-symbol.js"],d["parts/Utilities.js"]],function(a,d,t,f,y,q){"";var p=d.parse;d=q.addEvent;var z=q.erase,u=q.extend,r=q.Fx,c=q.isNumber,l=q.merge,g=q.pick,k=q.splat,v=a.Axis;q=a.Chart;var w=a.Series,n=a.colorPointMixin,h=a.noop;u(w.prototype,a.colorSeriesMixin);u(t.prototype,n);q.prototype.collectionsWithUpdate.push("colorAxis");q.prototype.collectionsWithInit.colorAxis=
[q.prototype.addColorAxis];var b=a.ColorAxis=function(){this.init.apply(this,arguments)};u(b.prototype,v.prototype);u(b.prototype,{defaultColorAxisOptions:{lineWidth:0,minPadding:0,maxPadding:0,gridLineWidth:1,tickPixelInterval:72,startOnTick:!0,endOnTick:!0,offset:0,marker:{animation:{duration:50},width:.01,color:"#999999"},labels:{overflow:"justify",rotation:0},minColor:"#e6ebf5",maxColor:"#003399",tickLength:5,showInLegend:!0},keepProps:["legendGroup","legendItemHeight","legendItemWidth","legendItem",
"legendSymbol"].concat(v.keepProps),init:function(e,b){this.coll="colorAxis";var m=this.buildOptions.call(e,this.defaultColorAxisOptions,b);v.prototype.init.call(this,e,m);b.dataClasses&&this.initDataClasses(b);this.initStops();this.horiz=!m.opposite;this.zoomEnabled=!1;this.defaultLegendLength=200},initDataClasses:function(e){var b=this.chart,c,B=0,h=b.options.chart.colorCount,g=this.options,a=e.dataClasses.length;this.dataClasses=c=[];this.legendItems=[];e.dataClasses.forEach(function(e,m){e=l(e);
c.push(e);if(b.styledMode||!e.color)"category"===g.dataClassColor?(b.styledMode||(m=b.options.colors,h=m.length,e.color=m[B]),e.colorIndex=B,B++,B===h&&(B=0)):e.color=p(g.minColor).tweenTo(p(g.maxColor),2>a?.5:m/(a-1))})},hasData:function(){return!(!this.tickPositions||!this.tickPositions.length)},setTickPositions:function(){if(!this.dataClasses)return v.prototype.setTickPositions.call(this)},initStops:function(){this.stops=this.options.stops||[[0,this.options.minColor],[1,this.options.maxColor]];
this.stops.forEach(function(e){e.color=p(e[1])})},buildOptions:function(e,b){var m=this.options.legend,c=b.layout?"vertical"!==b.layout:"vertical"!==m.layout;return l(e,{side:c?2:1,reversed:!c},b,{opposite:!c,showEmpty:!1,title:null,visible:m.enabled&&(b?!1!==b.visible:!0)})},setOptions:function(e){v.prototype.setOptions.call(this,e);this.options.crosshair=this.options.marker},setAxisSize:function(){var e=this.legendSymbol,b=this.chart,c=b.options.legend||{},h,g;e?(this.left=c=e.attr("x"),this.top=
h=e.attr("y"),this.width=g=e.attr("width"),this.height=e=e.attr("height"),this.right=b.chartWidth-c-g,this.bottom=b.chartHeight-h-e,this.len=this.horiz?g:e,this.pos=this.horiz?c:h):this.len=(this.horiz?c.symbolWidth:c.symbolHeight)||this.defaultLegendLength},normalizedValue:function(e){this.logarithmic&&(e=this.logarithmic.log2lin(e));return 1-(this.max-e)/(this.max-this.min||1)},toColor:function(e,b){var m=this.stops,c=this.dataClasses,h;if(c)for(h=c.length;h--;){var g=c[h];var a=g.from;m=g.to;if(("undefined"===
typeof a||e>=a)&&("undefined"===typeof m||e<=m)){var l=g.color;b&&(b.dataClass=h,b.colorIndex=g.colorIndex);break}}else{e=this.normalizedValue(e);for(h=m.length;h--&&!(e>m[h][0]););a=m[h]||m[h+1];m=m[h+1]||a;e=1-(m[0]-e)/(m[0]-a[0]||1);l=a.color.tweenTo(m.color,e)}return l},getOffset:function(){var e=this.legendGroup,b=this.chart.axisOffset[this.side];e&&(this.axisParent=e,v.prototype.getOffset.call(this),this.added||(this.added=!0,this.labelLeft=0,this.labelRight=this.width),this.chart.axisOffset[this.side]=
b)},setLegendColor:function(){var e=this.reversed;var b=e?1:0;e=e?0:1;b=this.horiz?[b,0,e,0]:[0,e,0,b];this.legendColor={linearGradient:{x1:b[0],y1:b[1],x2:b[2],y2:b[3]},stops:this.stops}},drawLegendSymbol:function(b,m){var e=b.padding,c=b.options,h=this.horiz,a=g(c.symbolWidth,h?this.defaultLegendLength:12),l=g(c.symbolHeight,h?12:this.defaultLegendLength),k=g(c.labelPadding,h?16:30);c=g(c.itemDistance,10);this.setLegendColor();m.legendSymbol=this.chart.renderer.rect(0,b.baseline-11,a,l).attr({zIndex:1}).add(m.legendGroup);
this.legendItemWidth=a+e+(h?c:k);this.legendItemHeight=l+e+(h?k:0)},setState:function(b){this.series.forEach(function(e){e.setState(b)})},visible:!0,setVisible:h,getSeriesExtremes:function(){var b=this.series,m=b.length,c;this.dataMin=Infinity;for(this.dataMax=-Infinity;m--;){var h=b[m];var a=h.colorKey=g(h.options.colorKey,h.colorKey,h.pointValKey,h.zoneAxis,"y");var l=h.pointArrayMap;var k=h[a+"Min"]&&h[a+"Max"];if(h[a+"Data"])var n=h[a+"Data"];else if(l){n=[];l=l.indexOf(a);var f=h.yData;if(0<=
l&&f)for(c=0;c<f.length;c++)n.push(g(f[c][l],f[c]))}else n=h.yData;k?(h.minColorValue=h[a+"Min"],h.maxColorValue=h[a+"Max"]):(n=w.prototype.getExtremes.call(h,n),h.minColorValue=n.dataMin,h.maxColorValue=n.dataMax);"undefined"!==typeof h.minColorValue&&(this.dataMin=Math.min(this.dataMin,h.minColorValue),this.dataMax=Math.max(this.dataMax,h.maxColorValue));k||w.prototype.applyExtremes.call(h)}},drawCrosshair:function(b,m){var e=m&&m.plotX,c=m&&m.plotY,h=this.pos,g=this.len;if(m){var a=this.toPixels(m.getNestedProperty(m.series.colorKey));
a<h?a=h-2:a>h+g&&(a=h+g+2);m.plotX=a;m.plotY=this.len-a;v.prototype.drawCrosshair.call(this,b,m);m.plotX=e;m.plotY=c;this.cross&&!this.cross.addedToColorAxis&&this.legendGroup&&(this.cross.addClass("highcharts-coloraxis-marker").add(this.legendGroup),this.cross.addedToColorAxis=!0,this.chart.styledMode||this.cross.attr({fill:this.crosshair.color}))}},getPlotLinePath:function(b){var e=b.translatedValue;return c(e)?this.horiz?["M",e-4,this.top-6,"L",e+4,this.top-6,e,this.top,"Z"]:["M",this.left,e,"L",
this.left-6,e+6,this.left-6,e-6,"Z"]:v.prototype.getPlotLinePath.apply(this,arguments)},update:function(b,m){var e=this.chart,c=e.legend,h=this.buildOptions.call(e,{},b);this.series.forEach(function(b){b.isDirtyData=!0});(b.dataClasses&&c.allItems||this.dataClasses)&&this.destroyItems();e.options[this.coll]=l(this.userOptions,h);v.prototype.update.call(this,h,m);this.legendItem&&(this.setLegendColor(),c.colorizeItem(this,!0))},destroyItems:function(){var b=this.chart;this.legendItem?b.legend.destroyItem(this):
this.legendItems&&this.legendItems.forEach(function(e){b.legend.destroyItem(e)});b.isDirtyLegend=!0},remove:function(b){this.destroyItems();v.prototype.remove.call(this,b)},getDataClassLegendSymbols:function(){var b=this,m=this.chart,c=this.legendItems,g=m.options.legend,a=g.valueDecimals,l=g.valueSuffix||"",k;c.length||this.dataClasses.forEach(function(e,g){var n=!0,f=e.from,B=e.to,A=m.numberFormatter;k="";"undefined"===typeof f?k="< ":"undefined"===typeof B&&(k="> ");"undefined"!==typeof f&&(k+=
A(f,a)+l);"undefined"!==typeof f&&"undefined"!==typeof B&&(k+=" - ");"undefined"!==typeof B&&(k+=A(B,a)+l);c.push(u({chart:m,name:k,options:{},drawLegendSymbol:y.drawRectangle,visible:!0,setState:h,isDataClass:!0,setVisible:function(){n=this.visible=!n;b.series.forEach(function(b){b.points.forEach(function(b){b.dataClass===g&&b.setVisible(n)})});m.legend.colorizeItem(this,n)}},e))});return c},beforePadding:!1,name:""});["fill","stroke"].forEach(function(b){r.prototype[b+"Setter"]=function(){this.elem.attr(b,
p(this.start).tweenTo(p(this.end),this.pos),null,!0)}});d(q,"afterGetAxes",function(){var e=this,m=e.options;this.colorAxis=[];m.colorAxis&&(m.colorAxis=k(m.colorAxis),m.colorAxis.forEach(function(m,c){m.index=c;new b(e,m)}))});d(w,"bindAxes",function(){var b=this.axisTypes;b?-1===b.indexOf("colorAxis")&&b.push("colorAxis"):this.axisTypes=["colorAxis"]});d(f,"afterGetAllItems",function(b){var e=[],c,h;(this.chart.colorAxis||[]).forEach(function(m){(c=m.options)&&c.showInLegend&&(c.dataClasses&&c.visible?
e=e.concat(m.getDataClassLegendSymbols()):c.visible&&e.push(m),m.series.forEach(function(e){if(!e.options.showInLegend||c.dataClasses)"point"===e.options.legendType?e.points.forEach(function(e){z(b.allItems,e)}):z(b.allItems,e)}))});for(h=e.length;h--;)b.allItems.unshift(e[h])});d(f,"afterColorizeItem",function(b){b.visible&&b.item.legendColor&&b.item.legendSymbol.attr({fill:b.item.legendColor})});d(f,"afterUpdate",function(){var b=this.chart.colorAxis;b&&b.forEach(function(b,e,c){b.update({},c)})});
d(w,"afterTranslate",function(){(this.chart.colorAxis&&this.chart.colorAxis.length||this.colorAttribs)&&this.translateColors()})});x(d,"parts-map/ColorMapSeriesMixin.js",[d["parts/Globals.js"],d["parts/Point.js"],d["parts/Utilities.js"]],function(a,d,t){var f=t.defined;t=a.noop;var y=a.seriesTypes;a.colorMapPointMixin={dataLabelOnNull:!0,isValid:function(){return null!==this.value&&Infinity!==this.value&&-Infinity!==this.value},setState:function(a){d.prototype.setState.call(this,a);this.graphic&&
this.graphic.attr({zIndex:"hover"===a?1:0})}};a.colorMapSeriesMixin={pointArrayMap:["value"],axisTypes:["xAxis","yAxis","colorAxis"],trackerGroups:["group","markerGroup","dataLabelsGroup"],getSymbol:t,parallelArrays:["x","y","value"],colorKey:"value",pointAttribs:y.column.prototype.pointAttribs,colorAttribs:function(a){var d={};f(a.color)&&(d[this.colorProp||"fill"]=a.color);return d}}});x(d,"parts-map/MapNavigation.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(a,d){function p(c){c&&
(c.preventDefault&&c.preventDefault(),c.stopPropagation&&c.stopPropagation(),c.cancelBubble=!0)}function f(c){this.init(c)}var y=d.addEvent,q=d.extend,C=d.merge,z=d.objectEach,u=d.pick;d=a.Chart;var r=a.doc;f.prototype.init=function(c){this.chart=c;c.mapNavButtons=[]};f.prototype.update=function(c){var a=this.chart,g=a.options.mapNavigation,k,f,d,n,h,b=function(b){this.handler.call(a,b);p(b)},e=a.mapNavButtons;c&&(g=a.options.mapNavigation=C(a.options.mapNavigation,c));for(;e.length;)e.pop().destroy();
u(g.enableButtons,g.enabled)&&!a.renderer.forExport&&z(g.buttons,function(c,l){k=C(g.buttonOptions,c);a.styledMode||(f=k.theme,f.style=C(k.theme.style,k.style),n=(d=f.states)&&d.hover,h=d&&d.select);c=a.renderer.button(k.text,0,0,b,f,n,h,0,"zoomIn"===l?"topbutton":"bottombutton").addClass("highcharts-map-navigation highcharts-"+{zoomIn:"zoom-in",zoomOut:"zoom-out"}[l]).attr({width:k.width,height:k.height,title:a.options.lang[l],padding:k.padding,zIndex:5}).add();c.handler=k.onclick;y(c.element,"dblclick",
p);e.push(c);var m=k,w=y(a,"load",function(){c.align(q(m,{width:c.width,height:2*c.height}),null,m.alignTo);w()})});this.updateEvents(g)};f.prototype.updateEvents=function(c){var a=this.chart;u(c.enableDoubleClickZoom,c.enabled)||c.enableDoubleClickZoomTo?this.unbindDblClick=this.unbindDblClick||y(a.container,"dblclick",function(c){a.pointer.onContainerDblClick(c)}):this.unbindDblClick&&(this.unbindDblClick=this.unbindDblClick());u(c.enableMouseWheelZoom,c.enabled)?this.unbindMouseWheel=this.unbindMouseWheel||
y(a.container,"undefined"===typeof r.onmousewheel?"DOMMouseScroll":"mousewheel",function(c){a.pointer.onContainerMouseWheel(c);p(c);return!1}):this.unbindMouseWheel&&(this.unbindMouseWheel=this.unbindMouseWheel())};q(d.prototype,{fitToBox:function(c,a){[["x","width"],["y","height"]].forEach(function(g){var k=g[0];g=g[1];c[k]+c[g]>a[k]+a[g]&&(c[g]>a[g]?(c[g]=a[g],c[k]=a[k]):c[k]=a[k]+a[g]-c[g]);c[g]>a[g]&&(c[g]=a[g]);c[k]<a[k]&&(c[k]=a[k])});return c},mapZoom:function(c,a,g,k,f){var l=this.xAxis[0],
n=l.max-l.min,h=u(a,l.min+n/2),b=n*c;n=this.yAxis[0];var e=n.max-n.min,m=u(g,n.min+e/2);e*=c;h=this.fitToBox({x:h-b*(k?(k-l.pos)/l.len:.5),y:m-e*(f?(f-n.pos)/n.len:.5),width:b,height:e},{x:l.dataMin,y:n.dataMin,width:l.dataMax-l.dataMin,height:n.dataMax-n.dataMin});b=h.x<=l.dataMin&&h.width>=l.dataMax-l.dataMin&&h.y<=n.dataMin&&h.height>=n.dataMax-n.dataMin;k&&l.mapAxis&&(l.mapAxis.fixTo=[k-l.pos,a]);f&&n.mapAxis&&(n.mapAxis.fixTo=[f-n.pos,g]);"undefined"===typeof c||b?(l.setExtremes(void 0,void 0,
!1),n.setExtremes(void 0,void 0,!1)):(l.setExtremes(h.x,h.x+h.width,!1),n.setExtremes(h.y,h.y+h.height,!1));this.redraw()}});y(d,"beforeRender",function(){this.mapNavigation=new f(this);this.mapNavigation.update()});a.MapNavigation=f});x(d,"parts-map/MapPointer.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(a,d){var p=d.extend,f=d.pick;d=d.wrap;a=a.Pointer;p(a.prototype,{onContainerDblClick:function(a){var f=this.chart;a=this.normalize(a);f.options.mapNavigation.enableDoubleClickZoomTo?
f.pointer.inClass(a.target,"highcharts-tracker")&&f.hoverPoint&&f.hoverPoint.zoomTo():f.isInsidePlot(a.chartX-f.plotLeft,a.chartY-f.plotTop)&&f.mapZoom(.5,f.xAxis[0].toValue(a.chartX),f.yAxis[0].toValue(a.chartY),a.chartX,a.chartY)},onContainerMouseWheel:function(a){var f=this.chart;a=this.normalize(a);var d=a.detail||-(a.wheelDelta/120);f.isInsidePlot(a.chartX-f.plotLeft,a.chartY-f.plotTop)&&f.mapZoom(Math.pow(f.options.mapNavigation.mouseWheelSensitivity,d),f.xAxis[0].toValue(a.chartX),f.yAxis[0].toValue(a.chartY),
a.chartX,a.chartY)}});d(a.prototype,"zoomOption",function(a){var d=this.chart.options.mapNavigation;f(d.enableTouchZoom,d.enabled)&&(this.chart.options.chart.pinchType="xy");a.apply(this,[].slice.call(arguments,1))});d(a.prototype,"pinchTranslate",function(a,f,d,p,t,r,c){a.call(this,f,d,p,t,r,c);"map"===this.chart.options.chart.type&&this.hasZoom&&(a=p.scaleX>p.scaleY,this.pinchTranslateDirection(!a,f,d,p,t,r,c,a?p.scaleX:p.scaleY))})});x(d,"parts-map/MapSeries.js",[d["parts/Globals.js"],d["mixins/legend-symbol.js"],
d["parts/Point.js"],d["parts/Utilities.js"]],function(a,d,t,f){var p=f.extend,q=f.fireEvent,C=f.getNestedProperty,z=f.isArray,u=f.isNumber,r=f.merge,c=f.objectEach,l=f.pick,g=f.seriesType,k=f.splat,v=a.colorMapPointMixin,w=a.noop,n=a.Series,h=a.seriesTypes;g("map","scatter",{animation:!1,dataLabels:{crop:!1,formatter:function(){return this.point.value},inside:!0,overflow:!1,padding:0,verticalAlign:"middle"},marker:null,nullColor:"#f7f7f7",stickyTracking:!1,tooltip:{followPointer:!0,pointFormat:"{point.name}: {point.value}<br/>"},
turboThreshold:0,allAreas:!0,borderColor:"#cccccc",borderWidth:1,joinBy:"hc-key",states:{hover:{halo:null,brightness:.2},normal:{animation:!0},select:{color:"#cccccc"},inactive:{opacity:1}}},r(a.colorMapSeriesMixin,{type:"map",getExtremesFromAll:!0,useMapGeometry:!0,forceDL:!0,searchPoint:w,directTouch:!0,preserveAspectRatio:!0,pointArrayMap:["value"],setOptions:function(b){b=n.prototype.setOptions.call(this,b);var e=b.joinBy;null===e&&(e="_i");e=this.joinBy=k(e);e[1]||(e[1]=e[0]);return b},getBox:function(b){var e=
Number.MAX_VALUE,c=-e,h=e,g=-e,f=e,d=e,k=this.xAxis,n=this.yAxis,w;(b||[]).forEach(function(b){if(b.path){"string"===typeof b.path&&(b.path=a.splitPath(b.path));var m=b.path||[],k=m.length,n=!1,B=-e,A=e,D=-e,r=e,p=b.properties;if(!b._foundBox){for(;k--;)u(m[k])&&(n?(B=Math.max(B,m[k]),A=Math.min(A,m[k])):(D=Math.max(D,m[k]),r=Math.min(r,m[k])),n=!n);b._midX=A+(B-A)*l(b.middleX,p&&p["hc-middle-x"],.5);b._midY=r+(D-r)*l(b.middleY,p&&p["hc-middle-y"],.5);b._maxX=B;b._minX=A;b._maxY=D;b._minY=r;b.labelrank=
l(b.labelrank,(B-A)*(D-r));b._foundBox=!0}c=Math.max(c,b._maxX);h=Math.min(h,b._minX);g=Math.max(g,b._maxY);f=Math.min(f,b._minY);d=Math.min(b._maxX-b._minX,b._maxY-b._minY,d);w=!0}});w&&(this.minY=Math.min(f,l(this.minY,e)),this.maxY=Math.max(g,l(this.maxY,-e)),this.minX=Math.min(h,l(this.minX,e)),this.maxX=Math.max(c,l(this.maxX,-e)),k&&"undefined"===typeof k.options.minRange&&(k.minRange=Math.min(5*d,(this.maxX-this.minX)/5,k.minRange||e)),n&&"undefined"===typeof n.options.minRange&&(n.minRange=
Math.min(5*d,(this.maxY-this.minY)/5,n.minRange||e)))},hasData:function(){return!!this.processedXData.length},getExtremes:function(){var b=n.prototype.getExtremes.call(this,this.valueData),e=b.dataMin;b=b.dataMax;this.chart.hasRendered&&this.isDirtyData&&this.getBox(this.options.data);u(e)&&(this.valueMin=e);u(b)&&(this.valueMax=b);return{dataMin:this.minY,dataMax:this.maxY}},translatePath:function(b){var e=!1,c=this.xAxis,a=this.yAxis,h=c.min,g=c.transA;c=c.minPixelPadding;var f=a.min,k=a.transA;
a=a.minPixelPadding;var d,n=[];if(b)for(d=b.length;d--;)u(b[d])?(n[d]=e?(b[d]-h)*g+c:(b[d]-f)*k+a,e=!e):n[d]=b[d];return n},setData:function(b,e,m,h){var g=this.options,f=this.chart.options.chart,d=f&&f.map,k=g.mapData,l=this.joinBy,w=g.keys||this.pointArrayMap,A=[],p={},v=this.chart.mapTransforms;!k&&d&&(k="string"===typeof d?a.maps[d]:d);b&&b.forEach(function(e,c){var a=0;if(u(e))b[c]={value:e};else if(z(e)){b[c]={};!g.keys&&e.length>w.length&&"string"===typeof e[0]&&(b[c]["hc-key"]=e[0],++a);for(var m=
0;m<w.length;++m,++a)w[m]&&"undefined"!==typeof e[a]&&(0<w[m].indexOf(".")?t.prototype.setNestedProperty(b[c],e[a],w[m]):b[c][w[m]]=e[a])}l&&"_i"===l[0]&&(b[c]._i=c)});this.getBox(b);(this.chart.mapTransforms=v=f&&f.mapTransforms||k&&k["hc-transform"]||v)&&c(v,function(b){b.rotation&&(b.cosAngle=Math.cos(b.rotation),b.sinAngle=Math.sin(b.rotation))});if(k){"FeatureCollection"===k.type&&(this.mapTitle=k.title,k=a.geojson(k,this.type,this));this.mapData=k;this.mapMap={};for(v=0;v<k.length;v++)f=k[v],
d=f.properties,f._i=v,l[0]&&d&&d[l[0]]&&(f[l[0]]=d[l[0]]),p[f[l[0]]]=f;this.mapMap=p;if(b&&l[1]){var q=l[1];b.forEach(function(b){b=C(q,b);p[b]&&A.push(p[b])})}if(g.allAreas){this.getBox(k);b=b||[];if(l[1]){var y=l[1];b.forEach(function(b){A.push(C(y,b))})}A="|"+A.map(function(b){return b&&b[l[0]]}).join("|")+"|";k.forEach(function(e){l[0]&&-1!==A.indexOf("|"+e[l[0]]+"|")||(b.push(r(e,{value:null})),h=!1)})}else this.getBox(A)}n.prototype.setData.call(this,b,e,m,h)},drawGraph:w,drawDataLabels:w,doFullTranslate:function(){return this.isDirtyData||
this.chart.isResizing||this.chart.renderer.isVML||!this.baseTrans},translate:function(){var b=this,e=b.xAxis,c=b.yAxis,a=b.doFullTranslate();b.generatePoints();b.data.forEach(function(m){u(m._midX)&&u(m._midY)&&(m.plotX=e.toPixels(m._midX,!0),m.plotY=c.toPixels(m._midY,!0));a&&(m.shapeType="path",m.shapeArgs={d:b.translatePath(m.path)})});q(b,"afterTranslate")},pointAttribs:function(b,e){e=b.series.chart.styledMode?this.colorAttribs(b):h.column.prototype.pointAttribs.call(this,b,e);e["stroke-width"]=
l(b.options[this.pointAttrToOptions&&this.pointAttrToOptions["stroke-width"]||"borderWidth"],"inherit");return e},drawPoints:function(){var b=this,e=b.xAxis,c=b.yAxis,a=b.group,g=b.chart,f=g.renderer,k=this.baseTrans;b.transformGroup||(b.transformGroup=f.g().attr({scaleX:1,scaleY:1}).add(a),b.transformGroup.survive=!0);if(b.doFullTranslate())g.hasRendered&&!g.styledMode&&b.points.forEach(function(e){e.shapeArgs&&(e.shapeArgs.fill=b.pointAttribs(e,e.state).fill)}),b.group=b.transformGroup,h.column.prototype.drawPoints.apply(b),
b.group=a,b.points.forEach(function(e){if(e.graphic){var c="";e.name&&(c+="highcharts-name-"+e.name.replace(/ /g,"-").toLowerCase());e.properties&&e.properties["hc-key"]&&(c+=" highcharts-key-"+e.properties["hc-key"].toLowerCase());c&&e.graphic.addClass(c);g.styledMode&&e.graphic.css(b.pointAttribs(e,e.selected&&"select"||void 0))}}),this.baseTrans={originX:e.min-e.minPixelPadding/e.transA,originY:c.min-c.minPixelPadding/c.transA+(c.reversed?0:c.len/c.transA),transAX:e.transA,transAY:c.transA},this.transformGroup.animate({translateX:0,
translateY:0,scaleX:1,scaleY:1});else{var d=e.transA/k.transAX;var n=c.transA/k.transAY;var w=e.toPixels(k.originX,!0);var r=c.toPixels(k.originY,!0);.99<d&&1.01>d&&.99<n&&1.01>n&&(n=d=1,w=Math.round(w),r=Math.round(r));var p=this.transformGroup;if(g.renderer.globalAnimation){var v=p.attr("translateX");var q=p.attr("translateY");var t=p.attr("scaleX");var y=p.attr("scaleY");p.attr({animator:0}).animate({animator:1},{step:function(b,e){p.attr({translateX:v+(w-v)*e.pos,translateY:q+(r-q)*e.pos,scaleX:t+
(d-t)*e.pos,scaleY:y+(n-y)*e.pos})}})}else p.attr({translateX:w,translateY:r,scaleX:d,scaleY:n})}g.styledMode||a.element.setAttribute("stroke-width",l(b.options[b.pointAttrToOptions&&b.pointAttrToOptions["stroke-width"]||"borderWidth"],1)/(d||1));this.drawMapDataLabels()},drawMapDataLabels:function(){n.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)},render:function(){var b=this,e=n.prototype.render;b.chart.renderer.isVML&&3E3<b.data.length?
setTimeout(function(){e.call(b)}):e.call(b)},animate:function(b){var e=this.options.animation,c=this.group,a=this.xAxis,h=this.yAxis,g=a.pos,f=h.pos;this.chart.renderer.isSVG&&(!0===e&&(e={duration:1E3}),b?c.attr({translateX:g+a.len/2,translateY:f+h.len/2,scaleX:.001,scaleY:.001}):c.animate({translateX:g,translateY:f,scaleX:1,scaleY:1},e))},animateDrilldown:function(b){var e=this.chart.plotBox,c=this.chart.drilldownLevels[this.chart.drilldownLevels.length-1],a=c.bBox,h=this.chart.options.drilldown.animation;
b||(b=Math.min(a.width/e.width,a.height/e.height),c.shapeArgs={scaleX:b,scaleY:b,translateX:a.x,translateY:a.y},this.points.forEach(function(b){b.graphic&&b.graphic.attr(c.shapeArgs).animate({scaleX:1,scaleY:1,translateX:0,translateY:0},h)}))},drawLegendSymbol:d.drawRectangle,animateDrillupFrom:function(b){h.column.prototype.animateDrillupFrom.call(this,b)},animateDrillupTo:function(b){h.column.prototype.animateDrillupTo.call(this,b)}}),p({applyOptions:function(b,e){var c=this.series;b=t.prototype.applyOptions.call(this,
b,e);e=c.joinBy;c.mapData&&c.mapMap&&(e=t.prototype.getNestedProperty.call(b,e[1]),(e="undefined"!==typeof e&&c.mapMap[e])?(c.xyFromShape&&(b.x=e._midX,b.y=e._midY),p(b,e)):b.value=b.value||null);return b},onMouseOver:function(b){f.clearTimeout(this.colorInterval);if(null!==this.value||this.series.options.nullInteraction)t.prototype.onMouseOver.call(this,b);else this.series.onMouseOut(b)},zoomTo:function(){var b=this.series;b.xAxis.setExtremes(this._minX,this._maxX,!1);b.yAxis.setExtremes(this._minY,
this._maxY,!1);b.chart.redraw()}},v));""});x(d,"parts-map/MapLineSeries.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(a,d){d=d.seriesType;var p=a.seriesTypes;d("mapline","map",{lineWidth:1,fillColor:"none"},{type:"mapline",colorProp:"stroke",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},pointAttribs:function(a,d){a=p.map.prototype.pointAttribs.call(this,a,d);a.fill=this.options.fillColor;return a},drawLegendSymbol:p.line.prototype.drawLegendSymbol});""});x(d,"parts-map/MapPointSeries.js",
[d["parts/Globals.js"]],function(a){var d=a.merge,t=a.Point,f=a.Series;a=a.seriesType;a("mappoint","scatter",{dataLabels:{crop:!1,defer:!1,enabled:!0,formatter:function(){return this.point.name},overflow:!1,style:{color:"#000000"}}},{type:"mappoint",forceDL:!0,drawDataLabels:function(){f.prototype.drawDataLabels.call(this);this.dataLabelsGroup&&this.dataLabelsGroup.clip(this.chart.clipRect)}},{applyOptions:function(a,f){a="undefined"!==typeof a.lat&&"undefined"!==typeof a.lon?d(a,this.series.chart.fromLatLonToPoint(a)):
a;return t.prototype.applyOptions.call(this,a,f)}});""});x(d,"parts-more/BubbleLegend.js",[d["parts/Globals.js"],d["parts/Color.js"],d["parts/Legend.js"],d["parts/Utilities.js"]],function(a,d,t,f){"";var p=d.parse;d=f.addEvent;var q=f.arrayMax,C=f.arrayMin,z=f.isNumber,u=f.merge,r=f.objectEach,c=f.pick,l=f.stableSort,g=f.wrap,k=a.Series,v=a.Chart,w=a.noop,n=a.setOptions;n({legend:{bubbleLegend:{borderColor:void 0,borderWidth:2,className:void 0,color:void 0,connectorClassName:void 0,connectorColor:void 0,
connectorDistance:60,connectorWidth:1,enabled:!1,labels:{className:void 0,allowOverlap:!1,format:"",formatter:void 0,align:"right",style:{fontSize:10,color:void 0},x:0,y:0},maxSize:60,minSize:10,legendIndex:0,ranges:{value:void 0,borderColor:void 0,color:void 0,connectorColor:void 0},sizeBy:"area",sizeByAbsoluteValue:!1,zIndex:1,zThreshold:0}}});n=function(){function a(b,e){this.options=this.symbols=this.visible=this.ranges=this.movementX=this.maxLabel=this.legendSymbol=this.legendItemWidth=this.legendItemHeight=
this.legendItem=this.legendGroup=this.legend=this.fontMetrics=this.chart=void 0;this.setState=w;this.init(b,e)}a.prototype.init=function(b,e){this.options=b;this.visible=!0;this.chart=e.chart;this.legend=e};a.prototype.addToLegend=function(b){b.splice(this.options.legendIndex,0,this)};a.prototype.drawLegendSymbol=function(b){var e=this.chart,a=this.options,h=c(b.options.itemDistance,20),g=a.ranges;var d=a.connectorDistance;this.fontMetrics=e.renderer.fontMetrics(a.labels.style.fontSize.toString()+
"px");g&&g.length&&z(g[0].value)?(l(g,function(b,e){return e.value-b.value}),this.ranges=g,this.setOptions(),this.render(),e=this.getMaxLabelSize(),g=this.ranges[0].radius,b=2*g,d=d-g+e.width,d=0<d?d:0,this.maxLabel=e,this.movementX="left"===a.labels.align?d:0,this.legendItemWidth=b+d+h,this.legendItemHeight=b+this.fontMetrics.h/2):b.options.bubbleLegend.autoRanges=!0};a.prototype.setOptions=function(){var b=this.ranges,e=this.options,a=this.chart.series[e.seriesIndex],h=this.legend.baseline,g={"z-index":e.zIndex,
"stroke-width":e.borderWidth},d={"z-index":e.zIndex,"stroke-width":e.connectorWidth},f=this.getLabelStyles(),k=a.options.marker.fillOpacity,l=this.chart.styledMode;b.forEach(function(m,n){l||(g.stroke=c(m.borderColor,e.borderColor,a.color),g.fill=c(m.color,e.color,1!==k?p(a.color).setOpacity(k).get("rgba"):a.color),d.stroke=c(m.connectorColor,e.connectorColor,a.color));b[n].radius=this.getRangeRadius(m.value);b[n]=u(b[n],{center:b[0].radius-b[n].radius+h});l||u(!0,b[n],{bubbleStyle:u(!1,g),connectorStyle:u(!1,
d),labelStyle:f})},this)};a.prototype.getLabelStyles=function(){var b=this.options,e={},a="left"===b.labels.align,h=this.legend.options.rtl;r(b.labels.style,function(b,c){"color"!==c&&"fontSize"!==c&&"z-index"!==c&&(e[c]=b)});return u(!1,e,{"font-size":b.labels.style.fontSize,fill:c(b.labels.style.color,"#000000"),"z-index":b.zIndex,align:h||a?"right":"left"})};a.prototype.getRangeRadius=function(b){var e=this.options;return this.chart.series[this.options.seriesIndex].getRadius.call(this,e.ranges[e.ranges.length-
1].value,e.ranges[0].value,e.minSize,e.maxSize,b)};a.prototype.render=function(){var b=this.chart.renderer,e=this.options.zThreshold;this.symbols||(this.symbols={connectors:[],bubbleItems:[],labels:[]});this.legendSymbol=b.g("bubble-legend");this.legendItem=b.g("bubble-legend-item");this.legendSymbol.translateX=0;this.legendSymbol.translateY=0;this.ranges.forEach(function(b){b.value>=e&&this.renderRange(b)},this);this.legendSymbol.add(this.legendItem);this.legendItem.add(this.legendGroup);this.hideOverlappingLabels()};
a.prototype.renderRange=function(b){var e=this.options,c=e.labels,a=this.chart.renderer,h=this.symbols,g=h.labels,d=b.center,f=Math.abs(b.radius),k=e.connectorDistance,l=c.align,n=c.style.fontSize;k=this.legend.options.rtl||"left"===l?-k:k;c=e.connectorWidth;var w=this.ranges[0].radius,r=d-f-e.borderWidth/2+c/2;n=n/2-(this.fontMetrics.h-n)/2;var p=a.styledMode;"center"===l&&(k=0,e.connectorDistance=0,b.labelStyle.align="center");l=r+e.labels.y;var v=w+k+e.labels.x;h.bubbleItems.push(a.circle(w,d+
((r%1?1:.5)-(c%2?0:.5)),f).attr(p?{}:b.bubbleStyle).addClass((p?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-symbol "+(e.className||"")).add(this.legendSymbol));h.connectors.push(a.path(a.crispLine(["M",w,r,"L",w+k,r],e.connectorWidth)).attr(p?{}:b.connectorStyle).addClass((p?"highcharts-color-"+this.options.seriesIndex+" ":"")+"highcharts-bubble-legend-connectors "+(e.connectorClassName||"")).add(this.legendSymbol));b=a.text(this.formatLabel(b),v,l+n).attr(p?{}:
b.labelStyle).addClass("highcharts-bubble-legend-labels "+(e.labels.className||"")).add(this.legendSymbol);g.push(b);b.placed=!0;b.alignAttr={x:v,y:l+n}};a.prototype.getMaxLabelSize=function(){var b,e;this.symbols.labels.forEach(function(c){e=c.getBBox(!0);b=b?e.width>b.width?e:b:e});return b||{}};a.prototype.formatLabel=function(b){var e=this.options,c=e.labels.formatter;e=e.labels.format;var a=this.chart.numberFormatter;return e?f.format(e,b):c?c.call(b):a(b.value,1)};a.prototype.hideOverlappingLabels=
function(){var b=this.chart,e=this.symbols;!this.options.labels.allowOverlap&&e&&(b.hideOverlappingLabels(e.labels),e.labels.forEach(function(b,c){b.newOpacity?b.newOpacity!==b.oldOpacity&&e.connectors[c].show():e.connectors[c].hide()}))};a.prototype.getRanges=function(){var b=this.legend.bubbleLegend,e=b.options.ranges,a,h=Number.MAX_VALUE,g=-Number.MAX_VALUE;b.chart.series.forEach(function(b){b.isBubble&&!b.ignoreSeries&&(a=b.zData.filter(z),a.length&&(h=c(b.options.zMin,Math.min(h,Math.max(C(a),
!1===b.options.displayNegative?b.options.zThreshold:-Number.MAX_VALUE))),g=c(b.options.zMax,Math.max(g,q(a)))))});var d=h===g?[{value:g}]:[{value:h},{value:(h+g)/2},{value:g,autoRanges:!0}];e.length&&e[0].radius&&d.reverse();d.forEach(function(b,c){e&&e[c]&&(d[c]=u(!1,e[c],b))});return d};a.prototype.predictBubbleSizes=function(){var b=this.chart,e=this.fontMetrics,c=b.legend.options,a="horizontal"===c.layout,h=a?b.legend.lastLineHeight:0,g=b.plotSizeX,d=b.plotSizeY,f=b.series[this.options.seriesIndex];
b=Math.ceil(f.minPxSize);var k=Math.ceil(f.maxPxSize);f=f.options.maxSize;var l=Math.min(d,g);if(c.floating||!/%$/.test(f))e=k;else if(f=parseFloat(f),e=(l+h-e.h/2)*f/100/(f/100+1),a&&d-e>=g||!a&&g-e>=d)e=k;return[b,Math.ceil(e)]};a.prototype.updateRanges=function(b,e){var c=this.legend.options.bubbleLegend;c.minSize=b;c.maxSize=e;c.ranges=this.getRanges()};a.prototype.correctSizes=function(){var b=this.legend,e=this.chart.series[this.options.seriesIndex];1<Math.abs(Math.ceil(e.maxPxSize)-this.options.maxSize)&&
(this.updateRanges(this.options.minSize,e.maxPxSize),b.render())};return a}();d(t,"afterGetAllItems",function(c){var b=this.bubbleLegend,e=this.options,h=e.bubbleLegend,g=this.chart.getVisibleBubbleSeriesIndex();b&&b.ranges&&b.ranges.length&&(h.ranges.length&&(h.autoRanges=!!h.ranges[0].autoRanges),this.destroyItem(b));0<=g&&e.enabled&&h.enabled&&(h.seriesIndex=g,this.bubbleLegend=new a.BubbleLegend(h,this),this.bubbleLegend.addToLegend(c.allItems))});v.prototype.getVisibleBubbleSeriesIndex=function(){for(var c=
this.series,b=0;b<c.length;){if(c[b]&&c[b].isBubble&&c[b].visible&&c[b].zData.length)return b;b++}return-1};t.prototype.getLinesHeights=function(){var c=this.allItems,b=[],e=c.length,a,g=0;for(a=0;a<e;a++)if(c[a].legendItemHeight&&(c[a].itemHeight=c[a].legendItemHeight),c[a]===c[e-1]||c[a+1]&&c[a]._legendItemPos[1]!==c[a+1]._legendItemPos[1]){b.push({height:0});var d=b[b.length-1];for(g;g<=a;g++)c[g].itemHeight>d.height&&(d.height=c[g].itemHeight);d.step=a}return b};t.prototype.retranslateItems=function(c){var b,
e,a,g=this.options.rtl,h=0;this.allItems.forEach(function(d,f){b=d.legendGroup.translateX;e=d._legendItemPos[1];if((a=d.movementX)||g&&d.ranges)a=g?b-d.options.maxSize/2:b+a,d.legendGroup.attr({translateX:a});f>c[h].step&&h++;d.legendGroup.attr({translateY:Math.round(e+c[h].height/2)});d._legendItemPos[1]=e+c[h].height/2})};d(k,"legendItemClick",function(){var c=this.chart,b=this.visible,e=this.chart.legend;e&&e.bubbleLegend&&(this.visible=!b,this.ignoreSeries=b,c=0<=c.getVisibleBubbleSeriesIndex(),
e.bubbleLegend.visible!==c&&(e.update({bubbleLegend:{enabled:c}}),e.bubbleLegend.visible=c),this.visible=b)});g(v.prototype,"drawChartBox",function(c,b,e){var a=this.legend,g=0<=this.getVisibleBubbleSeriesIndex();if(a&&a.options.enabled&&a.bubbleLegend&&a.options.bubbleLegend.autoRanges&&g){var d=a.bubbleLegend.options;g=a.bubbleLegend.predictBubbleSizes();a.bubbleLegend.updateRanges(g[0],g[1]);d.placed||(a.group.placed=!1,a.allItems.forEach(function(b){b.legendGroup.translateY=null}));a.render();
this.getMargins();this.axes.forEach(function(b){b.visible&&b.render();d.placed||(b.setScale(),b.updateNames(),r(b.ticks,function(b){b.isNew=!0;b.isNewLabel=!0}))});d.placed=!0;this.getMargins();c.call(this,b,e);a.bubbleLegend.correctSizes();a.retranslateItems(a.getLinesHeights())}else c.call(this,b,e),a&&a.options.enabled&&a.bubbleLegend&&(a.render(),a.retranslateItems(a.getLinesHeights()))});a.BubbleLegend=n;return a.BubbleLegend});x(d,"parts-more/BubbleSeries.js",[d["parts/Globals.js"],d["parts/Color.js"],
d["parts/Point.js"],d["parts/Utilities.js"]],function(a,d,t,f){var p=d.parse,q=f.arrayMax,C=f.arrayMin,z=f.clamp,u=f.extend,r=f.isNumber,c=f.pick,l=f.pInt;d=f.seriesType;f=a.Axis;var g=a.noop,k=a.Series,v=a.seriesTypes;d("bubble","scatter",{dataLabels:{formatter:function(){return this.point.z},inside:!0,verticalAlign:"middle"},animationLimit:250,marker:{lineColor:null,lineWidth:1,fillOpacity:.5,radius:null,states:{hover:{radiusPlus:0}},symbol:"circle"},minSize:8,maxSize:"20%",softThreshold:!1,states:{hover:{halo:{size:5}}},
tooltip:{pointFormat:"({point.x}, {point.y}), Size: {point.z}"},turboThreshold:0,zThreshold:0,zoneAxis:"z"},{pointArrayMap:["y","z"],parallelArrays:["x","y","z"],trackerGroups:["group","dataLabelsGroup"],specialGroup:"group",bubblePadding:!0,zoneAxis:"z",directTouch:!0,isBubble:!0,pointAttribs:function(c,a){var g=this.options.marker.fillOpacity;c=k.prototype.pointAttribs.call(this,c,a);1!==g&&(c.fill=p(c.fill).setOpacity(g).get("rgba"));return c},getRadii:function(c,a,g){var b=this.zData,e=this.yData,
d=g.minPxSize,h=g.maxPxSize,f=[];var k=0;for(g=b.length;k<g;k++){var l=b[k];f.push(this.getRadius(c,a,d,h,l,e[k]))}this.radii=f},getRadius:function(c,a,g,b,e,d){var h=this.options,f="width"!==h.sizeBy,k=h.zThreshold,l=a-c,n=.5;if(null===d||null===e)return null;if(r(e)){h.sizeByAbsoluteValue&&(e=Math.abs(e-k),l=Math.max(a-k,Math.abs(c-k)),c=0);if(e<c)return g/2-1;0<l&&(n=(e-c)/l)}f&&0<=n&&(n=Math.sqrt(n));return Math.ceil(g+n*(b-g))/2},animate:function(c){!c&&this.points.length<this.options.animationLimit&&
this.points.forEach(function(c){var a=c.graphic;if(a&&a.width){var b={x:a.x,y:a.y,width:a.width,height:a.height};a.attr({x:c.plotX,y:c.plotY,width:1,height:1});a.animate(b,this.options.animation)}},this)},hasData:function(){return!!this.processedXData.length},translate:function(){var c,a=this.data,g=this.radii;v.scatter.prototype.translate.call(this);for(c=a.length;c--;){var b=a[c];var e=g?g[c]:0;r(e)&&e>=this.minPxSize/2?(b.marker=u(b.marker,{radius:e,width:2*e,height:2*e}),b.dlBox={x:b.plotX-e,
y:b.plotY-e,width:2*e,height:2*e}):b.shapeArgs=b.plotY=b.dlBox=void 0}},alignDataLabel:v.column.prototype.alignDataLabel,buildKDTree:g,applyZones:g},{haloPath:function(c){return t.prototype.haloPath.call(this,0===c?0:(this.marker?this.marker.radius||0:0)+c)},ttBelow:!1});f.prototype.beforePadding=function(){var a=this,g=this.len,d=this.chart,b=0,e=g,f=this.isXAxis,k=f?"xData":"yData",p=this.min,v={},t=Math.min(d.plotWidth,d.plotHeight),u=Number.MAX_VALUE,y=-Number.MAX_VALUE,x=this.max-p,E=g/x,F=[];
this.series.forEach(function(b){var e=b.options;!b.bubblePadding||!b.visible&&d.options.chart.ignoreHiddenSeries||(a.allowZoomOutside=!0,F.push(b),f&&(["minSize","maxSize"].forEach(function(b){var c=e[b],a=/%$/.test(c);c=l(c);v[b]=a?t*c/100:c}),b.minPxSize=v.minSize,b.maxPxSize=Math.max(v.maxSize,v.minSize),b=b.zData.filter(r),b.length&&(u=c(e.zMin,z(C(b),!1===e.displayNegative?e.zThreshold:-Number.MAX_VALUE,u)),y=c(e.zMax,Math.max(y,q(b))))))});F.forEach(function(c){var g=c[k],d=g.length;f&&c.getRadii(u,
y,c);if(0<x)for(;d--;)if(r(g[d])&&a.dataMin<=g[d]&&g[d]<=a.max){var h=c.radii?c.radii[d]:0;b=Math.min((g[d]-p)*E-h,b);e=Math.max((g[d]-p)*E+h,e)}});F.length&&0<x&&!this.logarithmic&&(e-=g,E*=(g+Math.max(0,b)-Math.min(e,g))/g,[["min","userMin",b],["max","userMax",e]].forEach(function(b){"undefined"===typeof c(a.options[b[0]],a[b[1]])&&(a[b[0]]+=b[2]/E)}))};""});x(d,"parts-map/MapBubbleSeries.js",[d["parts/Globals.js"],d["parts/Point.js"],d["parts/Utilities.js"]],function(a,d,t){var f=t.merge;t=t.seriesType;
var p=a.seriesTypes;p.bubble&&t("mapbubble","bubble",{animationLimit:500,tooltip:{pointFormat:"{point.name}: {point.z}"}},{xyFromShape:!0,type:"mapbubble",pointArrayMap:["z"],getMapData:p.map.prototype.getMapData,getBox:p.map.prototype.getBox,setData:p.map.prototype.setData,setOptions:p.map.prototype.setOptions},{applyOptions:function(a,t){return a&&"undefined"!==typeof a.lat&&"undefined"!==typeof a.lon?d.prototype.applyOptions.call(this,f(a,this.series.chart.fromLatLonToPoint(a)),t):p.map.prototype.pointClass.prototype.applyOptions.call(this,
a,t)},isValid:function(){return"number"===typeof this.z},ttBelow:!1});""});x(d,"parts-map/HeatmapSeries.js",[d["parts/Globals.js"],d["mixins/legend-symbol.js"],d["parts/Utilities.js"]],function(a,d,t){var f=t.clamp,p=t.extend,q=t.fireEvent,x=t.isNumber,z=t.merge,u=t.pick;t=t.seriesType;var r=a.colorMapPointMixin,c=a.Series,l=a.SVGRenderer.prototype.symbols;t("heatmap","scatter",{animation:!1,borderWidth:0,nullColor:"#f7f7f7",dataLabels:{formatter:function(){return this.point.value},inside:!0,verticalAlign:"middle",
crop:!1,overflow:!1,padding:0},marker:{symbol:"rect",radius:0,lineColor:void 0,states:{hover:{lineWidthPlus:0},select:{}}},clip:!0,pointRange:null,tooltip:{pointFormat:"{point.x}, {point.y}: {point.value}<br/>"},states:{hover:{halo:!1,brightness:.2}}},z(a.colorMapSeriesMixin,{pointArrayMap:["y","value"],hasPointSpecificOptions:!0,getExtremesFromAll:!0,directTouch:!0,init:function(){c.prototype.init.apply(this,arguments);var a=this.options;a.pointRange=u(a.pointRange,a.colsize||1);this.yAxis.axisPointRange=
a.rowsize||1;p(l,{ellipse:l.circle,rect:l.square})},getSymbol:c.prototype.getSymbol,setClip:function(a){var g=this.chart;c.prototype.setClip.apply(this,arguments);(!1!==this.options.clip||a)&&this.markerGroup.clip((a||this.clipBox)&&this.sharedClipKey?g[this.sharedClipKey]:g.clipRect)},translate:function(){var c=this.options,a=c.marker&&c.marker.symbol||"",d=l[a]?a:"rect";c=this.options;var f=-1!==["circle","square"].indexOf(d);this.generatePoints();this.points.forEach(function(c){var g=c.getCellAttributes(),
b={x:Math.min(g.x1,g.x2),y:Math.min(g.y1,g.y2),width:Math.max(Math.abs(g.x2-g.x1),0),height:Math.max(Math.abs(g.y2-g.y1),0)};var e=c.hasImage=0===(c.marker&&c.marker.symbol||a||"").indexOf("url");if(f){var k=Math.abs(b.width-b.height);b.x=Math.min(g.x1,g.x2)+(b.width<b.height?0:k/2);b.y=Math.min(g.y1,g.y2)+(b.width<b.height?k/2:0);b.width=b.height=Math.min(b.width,b.height)}k={plotX:(g.x1+g.x2)/2,plotY:(g.y1+g.y2)/2,clientX:(g.x1+g.x2)/2,shapeType:"path",shapeArgs:z(!0,b,{d:l[d](b.x,b.y,b.width,b.height)})};
e&&(c.marker={width:b.width,height:b.height});p(c,k)});q(this,"afterTranslate")},pointAttribs:function(g,d){var f=c.prototype.pointAttribs.call(this,g,d),k=this.options||{},l=this.chart.options.plotOptions||{},h=l.series||{},b=l.heatmap||{};l=k.borderColor||b.borderColor||h.borderColor;h=k.borderWidth||b.borderWidth||h.borderWidth||f["stroke-width"];f.stroke=g&&g.marker&&g.marker.lineColor||k.marker&&k.marker.lineColor||l||this.color;f["stroke-width"]=h;d&&(g=z(k.states[d],k.marker&&k.marker.states[d],
g.options.states&&g.options.states[d]||{}),d=g.brightness,f.fill=g.color||a.color(f.fill).brighten(d||0).get(),f.stroke=g.lineColor);return f},markerAttribs:function(c,a){var g=c.marker||{},d=this.options.marker||{},f=c.shapeArgs||{},k={};if(c.hasImage)return{x:c.plotX,y:c.plotY};if(a){var b=d.states[a]||{};var e=g.states&&g.states[a]||{};[["width","x"],["height","y"]].forEach(function(c){k[c[0]]=(e[c[0]]||b[c[0]]||f[c[0]])+(e[c[0]+"Plus"]||b[c[0]+"Plus"]||0);k[c[1]]=f[c[1]]+(f[c[0]]-k[c[0]])/2})}return a?
k:f},drawPoints:function(){var a=this;if((this.options.marker||{}).enabled||this._hasPointMarkers)c.prototype.drawPoints.call(this),this.points.forEach(function(c){c.graphic&&c.graphic[a.chart.styledMode?"css":"animate"](a.colorAttribs(c))})},hasData:function(){return!!this.processedXData.length},getValidPoints:function(a,d){return c.prototype.getValidPoints.call(this,a,d,!0)},getBox:a.noop,drawLegendSymbol:d.drawRectangle,alignDataLabel:a.seriesTypes.column.prototype.alignDataLabel,getExtremes:function(){var a=
c.prototype.getExtremes.call(this,this.valueData),d=a.dataMin;a=a.dataMax;x(d)&&(this.valueMin=d);x(a)&&(this.valueMax=a);return c.prototype.getExtremes.call(this)}}),z(r,{applyOptions:function(c,d){c=a.Point.prototype.applyOptions.call(this,c,d);c.formatPrefix=c.isNull||null===c.value?"null":"point";return c},isValid:function(){return Infinity!==this.value&&-Infinity!==this.value},haloPath:function(c){if(!c)return[];var a=this.shapeArgs;return["M",a.x-c,a.y-c,"L",a.x-c,a.y+a.height+c,a.x+a.width+
c,a.y+a.height+c,a.x+a.width+c,a.y-c,"Z"]},getCellAttributes:function(){var c=this.series,a=c.options,d=(a.colsize||1)/2,l=(a.rowsize||1)/2,n=c.xAxis,h=c.yAxis,b=this.options.marker||c.options.marker;c=c.pointPlacementToXValue();var e=u(this.pointPadding,a.pointPadding,0),m={x1:f(Math.round(n.len-(n.translate(this.x-d,!1,!0,!1,!0,-c)||0)),-n.len,2*n.len),x2:f(Math.round(n.len-(n.translate(this.x+d,!1,!0,!1,!0,-c)||0)),-n.len,2*n.len),y1:f(Math.round(h.translate(this.y-l,!1,!0,!1,!0)||0),-h.len,2*
h.len),y2:f(Math.round(h.translate(this.y+l,!1,!0,!1,!0)||0),-h.len,2*h.len)};[["width","x"],["height","y"]].forEach(function(c){var a=c[0];c=c[1];var d=c+"1",g=c+"2",f=Math.abs(m[d]-m[g]),l=b&&b.lineWidth||0,h=Math.abs(m[d]+m[g])/2;b[a]&&b[a]<f&&(m[d]=h-b[a]/2-l/2,m[g]=h+b[a]/2+l/2);e&&("y"===c&&(d=g,g=c+"1"),m[d]+=e,m[g]-=e)});return m}}));""});x(d,"parts-map/GeoJSON.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(a,d){function p(a,c){var d,g=!1,f=a.x,p=a.y;a=0;for(d=c.length-1;a<c.length;d=
a++){var r=c[a][1]>p;var n=c[d][1]>p;r!==n&&f<(c[d][0]-c[a][0])*(p-c[a][1])/(c[d][1]-c[a][1])+c[a][0]&&(g=!g)}return g}var f=d.error,y=d.extend,q=d.format,x=d.merge;d=d.wrap;var z=a.Chart,u=a.win;z.prototype.transformFromLatLon=function(a,c){var d,g=(null===(d=this.userOptions.chart)||void 0===d?void 0:d.proj4)||u.proj4;if(!g)return f(21,!1,this),{x:0,y:null};a=g(c.crs,[a.lon,a.lat]);d=c.cosAngle||c.rotation&&Math.cos(c.rotation);g=c.sinAngle||c.rotation&&Math.sin(c.rotation);a=c.rotation?[a[0]*d+
a[1]*g,-a[0]*g+a[1]*d]:a;return{x:((a[0]-(c.xoffset||0))*(c.scale||1)+(c.xpan||0))*(c.jsonres||1)+(c.jsonmarginX||0),y:(((c.yoffset||0)-a[1])*(c.scale||1)+(c.ypan||0))*(c.jsonres||1)-(c.jsonmarginY||0)}};z.prototype.transformToLatLon=function(a,c){if("undefined"===typeof u.proj4)f(21,!1,this);else{a={x:((a.x-(c.jsonmarginX||0))/(c.jsonres||1)-(c.xpan||0))/(c.scale||1)+(c.xoffset||0),y:((-a.y-(c.jsonmarginY||0))/(c.jsonres||1)+(c.ypan||0))/(c.scale||1)+(c.yoffset||0)};var d=c.cosAngle||c.rotation&&
Math.cos(c.rotation),g=c.sinAngle||c.rotation&&Math.sin(c.rotation);c=u.proj4(c.crs,"WGS84",c.rotation?{x:a.x*d+a.y*-g,y:a.x*g+a.y*d}:a);return{lat:c.y,lon:c.x}}};z.prototype.fromPointToLatLon=function(a){var c=this.mapTransforms,d;if(c){for(d in c)if(Object.hasOwnProperty.call(c,d)&&c[d].hitZone&&p({x:a.x,y:-a.y},c[d].hitZone.coordinates[0]))return this.transformToLatLon(a,c[d]);return this.transformToLatLon(a,c["default"])}f(22,!1,this)};z.prototype.fromLatLonToPoint=function(a){var c=this.mapTransforms,
d;if(!c)return f(22,!1,this),{x:0,y:null};for(d in c)if(Object.hasOwnProperty.call(c,d)&&c[d].hitZone){var g=this.transformFromLatLon(a,c[d]);if(p({x:g.x,y:-g.y},c[d].hitZone.coordinates[0]))return g}return this.transformFromLatLon(a,c["default"])};a.geojson=function(a,c,d){var g=[],f=[],l=function(a){var c,d=a.length;f.push("M");for(c=0;c<d;c++)1===c&&f.push("L"),f.push(a[c][0],-a[c][1])};c=c||"map";a.features.forEach(function(a){var d=a.geometry,h=d.type;d=d.coordinates;a=a.properties;var b;f=[];
"map"===c||"mapbubble"===c?("Polygon"===h?(d.forEach(l),f.push("Z")):"MultiPolygon"===h&&(d.forEach(function(a){a.forEach(l)}),f.push("Z")),f.length&&(b={path:f})):"mapline"===c?("LineString"===h?l(d):"MultiLineString"===h&&d.forEach(l),f.length&&(b={path:f})):"mappoint"===c&&"Point"===h&&(b={x:d[0],y:-d[1]});b&&g.push(y(b,{name:a.name||a.NAME,properties:a}))});d&&a.copyrightShort&&(d.chart.mapCredits=q(d.chart.options.credits.mapText,{geojson:a}),d.chart.mapCreditsFull=q(d.chart.options.credits.mapTextFull,
{geojson:a}));return g};d(z.prototype,"addCredits",function(a,c){c=x(!0,this.options.credits,c);this.mapCredits&&(c.href=null);a.call(this,c);this.credits&&this.mapCreditsFull&&this.credits.attr({title:this.mapCreditsFull})})});x(d,"parts-map/Map.js",[d["parts/Globals.js"],d["parts/Utilities.js"]],function(a,d){function p(a,d,g,f,p,q,n,h){return["M",a+p,d,"L",a+g-q,d,"C",a+g-q/2,d,a+g,d+q/2,a+g,d+q,"L",a+g,d+f-n,"C",a+g,d+f-n/2,a+g-n/2,d+f,a+g-n,d+f,"L",a+h,d+f,"C",a+h/2,d+f,a,d+f-h/2,a,d+f-h,"L",
a,d+p,"C",a,d+p/2,a+p/2,d,a+p,d,"Z"]}var f=d.extend,x=d.merge,q=d.pick,C=a.Chart;d=a.defaultOptions;var z=a.Renderer,u=a.SVGRenderer,r=a.VMLRenderer;f(d.lang,{zoomIn:"Zoom in",zoomOut:"Zoom out"});d.mapNavigation={buttonOptions:{alignTo:"plotBox",align:"left",verticalAlign:"top",x:0,width:18,height:18,padding:5,style:{fontSize:"15px",fontWeight:"bold"},theme:{"stroke-width":1,"text-align":"center"}},buttons:{zoomIn:{onclick:function(){this.mapZoom(.5)},text:"+",y:0},zoomOut:{onclick:function(){this.mapZoom(2)},
text:"-",y:28}},mouseWheelSensitivity:1.1};a.splitPath=function(a){var c;a=a.replace(/([A-Za-z])/g," $1 ");a=a.replace(/^\s*/,"").replace(/\s*$/,"");a=a.split(/[ ,]+/);for(c=0;c<a.length;c++)/[a-zA-Z]/.test(a[c])||(a[c]=parseFloat(a[c]));return a};a.maps={};u.prototype.symbols.topbutton=function(a,d,g,f,q){return p(a-1,d-1,g,f,q.r,q.r,0,0)};u.prototype.symbols.bottombutton=function(a,d,g,f,q){return p(a-1,d-1,g,f,0,0,q.r,q.r)};z===r&&["topbutton","bottombutton"].forEach(function(a){r.prototype.symbols[a]=
u.prototype.symbols[a]});a.Map=a.mapChart=function(c,d,f){var g="string"===typeof c||c.nodeName,l=arguments[g?1:0],p=l,n={endOnTick:!1,visible:!1,minPadding:0,maxPadding:0,startOnTick:!1},h=a.getOptions().credits;var b=l.series;l.series=null;l=x({chart:{panning:{enabled:!0,type:"xy"},type:"map"},credits:{mapText:q(h.mapText,' \u00a9 <a href="{geojson.copyrightUrl}">{geojson.copyrightShort}</a>'),mapTextFull:q(h.mapTextFull,"{geojson.copyright}")},tooltip:{followTouchMove:!1},xAxis:n,yAxis:x(n,{reversed:!0})},
l,{chart:{inverted:!1,alignTicks:!1}});l.series=p.series=b;return g?new C(c,l,f):new C(l,d)}});x(d,"masters/modules/map.src.js",[],function(){})});
//# sourceMappingURL=map.js.map