/*
 Highstock JS v8.0.4 (2020-04-02)

 Highstock as a plugin for Highcharts

 (c) 2010-2019 Torstein Honsi

 License: www.highcharts.com/license
*/
(function(n){"object"===typeof module&&module.exports?(n["default"]=n,module.exports=n):"function"===typeof define&&define.amd?define("highcharts/modules/stock",["highcharts"],function(G){n(G);n.Highcharts=G;return n}):n("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(n){function G(n,d,D,v){n.hasOwnProperty(d)||(n[d]=v.apply(null,D))}n=n?n._modules:{};G(n,"parts/NavigatorAxis.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,d){var D=n.isTouchDevice,v=d.addEvent,x=d.correctFloat,
r=d.defined,E=d.isNumber,w=d.pick,e=function(){function e(e){this.axis=e}e.prototype.destroy=function(){this.axis=void 0};e.prototype.toFixedRange=function(e,d,u,l){var z=this.axis,B=z.chart;B=B&&B.fixedRange;var b=(z.pointRange||0)/2;e=w(u,z.translate(e,!0,!z.horiz));d=w(l,z.translate(d,!0,!z.horiz));z=B&&(d-e)/B;r(u)||(e=x(e+b));r(l)||(d=x(d-b));.7<z&&1.3>z&&(l?e=d-B:d=e+B);E(e)&&E(d)||(e=d=void 0);return{min:e,max:d}};return e}();return function(){function d(){}d.compose=function(d){d.keepProps.push("navigatorAxis");
v(d,"init",function(){this.navigatorAxis||(this.navigatorAxis=new e(this))});v(d,"zoom",function(e){var u=this.chart.options,l=u.navigator,z=this.navigatorAxis,B=u.chart.pinchType,b=u.rangeSelector;u=u.chart.zoomType;this.isXAxis&&(l&&l.enabled||b&&b.enabled)&&("y"===u?e.zoomed=!1:(!D&&"xy"===u||D&&"xy"===B)&&this.options.range&&(l=z.previousZoom,r(e.newMin)?z.previousZoom=[this.min,this.max]:l&&(e.newMin=l[0],e.newMax=l[1],z.previousZoom=void 0)));"undefined"!==typeof e.zoomed&&e.preventDefault()})};
d.AdditionsClass=e;return d}()});G(n,"parts/ScrollbarAxis.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,d){var D=d.addEvent,v=d.defined,x=d.pick;return function(){function d(){}d.compose=function(d,r){D(d,"afterInit",function(){var e=this;e.options&&e.options.scrollbar&&e.options.scrollbar.enabled&&(e.options.scrollbar.vertical=!e.horiz,e.options.startOnTick=e.options.endOnTick=!1,e.scrollbar=new r(e.chart.renderer,e.options.scrollbar,e.chart),D(e.scrollbar,"changed",function(d){var r=
x(e.options&&e.options.min,e.min),w=x(e.options&&e.options.max,e.max),u=v(e.dataMin)?Math.min(r,e.min,e.dataMin):r,l=(v(e.dataMax)?Math.max(w,e.max,e.dataMax):w)-u;v(r)&&v(w)&&(e.horiz&&!e.reversed||!e.horiz&&e.reversed?(r=u+l*this.to,u+=l*this.from):(r=u+l*(1-this.from),u+=l*(1-this.to)),x(this.options.liveRedraw,n.svg&&!n.isTouchDevice&&!this.chart.isBoosting)||"mouseup"===d.DOMType||!v(d.DOMType)?e.setExtremes(u,r,!0,"mousemove"!==d.DOMType,d):this.setRange(this.from,this.to))}))});D(d,"afterRender",
function(){var e=Math.min(x(this.options.min,this.min),this.min,x(this.dataMin,this.min)),d=Math.max(x(this.options.max,this.max),this.max,x(this.dataMax,this.max)),r=this.scrollbar,w=this.axisTitleMargin+(this.titleOffset||0),u=this.chart.scrollbarsOffsets,l=this.options.margin||0;r&&(this.horiz?(this.opposite||(u[1]+=w),r.position(this.left,this.top+this.height+2+u[1]-(this.opposite?l:0),this.width,this.height),this.opposite||(u[1]+=l),w=1):(this.opposite&&(u[0]+=w),r.position(this.left+this.width+
2+u[0]-(this.opposite?0:l),this.top,this.width,this.height),this.opposite&&(u[0]+=l),w=0),u[w]+=r.size+r.options.margin,isNaN(e)||isNaN(d)||!v(this.min)||!v(this.max)||this.min===this.max?r.setRange(0,1):(u=(this.min-e)/(d-e),e=(this.max-e)/(d-e),this.horiz&&!this.reversed||!this.horiz&&this.reversed?r.setRange(u,e):r.setRange(1-e,1-u)))});D(d,"afterGetOffset",function(){var e=this.horiz?2:1,d=this.scrollbar;d&&(this.chart.scrollbarsOffsets=[0,0],this.chart.axisOffset[e]+=d.size+d.options.margin)})};
return d}()});G(n,"parts/Scrollbar.js",[n["parts/Axis.js"],n["parts/Globals.js"],n["parts/ScrollbarAxis.js"],n["parts/Utilities.js"]],function(n,d,D,v){var x=v.addEvent,r=v.correctFloat,E=v.defined,w=v.destroyObjectProperties,e=v.fireEvent,H=v.merge,I=v.pick,F=v.removeEvent;v=d.defaultOptions;var u=d.hasTouch,l=d.isTouchDevice,z=d.swapXY=function(b,c){var y=b.length;if(c)for(c=0;c<y;c+=3){var a=b[c+1];b[c+1]=b[c+2];b[c+2]=a}return b},B=function(){function b(c,b,a){this._events=[];this.from=this.chartY=
this.chartX=0;this.scrollbar=this.group=void 0;this.scrollbarButtons=[];this.scrollbarGroup=void 0;this.scrollbarLeft=0;this.scrollbarRifles=void 0;this.scrollbarStrokeWidth=1;this.to=this.size=this.scrollbarTop=0;this.track=void 0;this.trackBorderWidth=1;this.userOptions={};this.y=this.x=0;this.chart=a;this.options=b;this.renderer=a.renderer;this.init(c,b,a)}b.prototype.addEvents=function(){var c=this.options.inverted?[1,0]:[0,1],b=this.scrollbarButtons,a=this.scrollbarGroup.element,g=this.track.element,
f=this.mouseDownHandler.bind(this),m=this.mouseMoveHandler.bind(this),q=this.mouseUpHandler.bind(this);c=[[b[c[0]].element,"click",this.buttonToMinClick.bind(this)],[b[c[1]].element,"click",this.buttonToMaxClick.bind(this)],[g,"click",this.trackClick.bind(this)],[a,"mousedown",f],[a.ownerDocument,"mousemove",m],[a.ownerDocument,"mouseup",q]];u&&c.push([a,"touchstart",f],[a.ownerDocument,"touchmove",m],[a.ownerDocument,"touchend",q]);c.forEach(function(a){x.apply(null,a)});this._events=c};b.prototype.buttonToMaxClick=
function(c){var b=(this.to-this.from)*I(this.options.step,.2);this.updatePosition(this.from+b,this.to+b);e(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:c})};b.prototype.buttonToMinClick=function(c){var b=r(this.to-this.from)*I(this.options.step,.2);this.updatePosition(r(this.from-b),r(this.to-b));e(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:c})};b.prototype.cursorToScrollbarPosition=function(c){var b=this.options;b=b.minWidth>this.calculatedWidth?
b.minWidth:0;return{chartX:(c.chartX-this.x-this.xOffset)/(this.barWidth-b),chartY:(c.chartY-this.y-this.yOffset)/(this.barWidth-b)}};b.prototype.destroy=function(){var c=this.chart.scroller;this.removeEvents();["track","scrollbarRifles","scrollbar","scrollbarGroup","group"].forEach(function(c){this[c]&&this[c].destroy&&(this[c]=this[c].destroy())},this);c&&this===c.scrollbar&&(c.scrollbar=null,w(c.scrollbarButtons))};b.prototype.drawScrollbarButton=function(c){var b=this.renderer,a=this.scrollbarButtons,
g=this.options,f=this.size;var m=b.g().add(this.group);a.push(m);m=b.rect().addClass("highcharts-scrollbar-button").add(m);this.chart.styledMode||m.attr({stroke:g.buttonBorderColor,"stroke-width":g.buttonBorderWidth,fill:g.buttonBackgroundColor});m.attr(m.crisp({x:-.5,y:-.5,width:f+1,height:f+1,r:g.buttonBorderRadius},m.strokeWidth()));m=b.path(z(["M",f/2+(c?-1:1),f/2-3,"L",f/2+(c?-1:1),f/2+3,"L",f/2+(c?2:-2),f/2],g.vertical)).addClass("highcharts-scrollbar-arrow").add(a[c]);this.chart.styledMode||
m.attr({fill:g.buttonArrowColor})};b.prototype.init=function(c,y,a){this.scrollbarButtons=[];this.renderer=c;this.userOptions=y;this.options=H(b.defaultOptions,y);this.chart=a;this.size=I(this.options.size,this.options.height);y.enabled&&(this.render(),this.addEvents())};b.prototype.mouseDownHandler=function(c){c=this.chart.pointer.normalize(c);c=this.cursorToScrollbarPosition(c);this.chartX=c.chartX;this.chartY=c.chartY;this.initPositions=[this.from,this.to];this.grabbedCenter=!0};b.prototype.mouseMoveHandler=
function(c){var b=this.chart.pointer.normalize(c),a=this.options.vertical?"chartY":"chartX",g=this.initPositions||[];!this.grabbedCenter||c.touches&&0===c.touches[0][a]||(b=this.cursorToScrollbarPosition(b)[a],a=this[a],a=b-a,this.hasDragged=!0,this.updatePosition(g[0]+a,g[1]+a),this.hasDragged&&e(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMType:c.type,DOMEvent:c}))};b.prototype.mouseUpHandler=function(c){this.hasDragged&&e(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",
DOMType:c.type,DOMEvent:c});this.grabbedCenter=this.hasDragged=this.chartX=this.chartY=null};b.prototype.position=function(c,b,a,g){var f=this.options.vertical,m=0,q=this.rendered?"animate":"attr";this.x=c;this.y=b+this.trackBorderWidth;this.width=a;this.xOffset=this.height=g;this.yOffset=m;f?(this.width=this.yOffset=a=m=this.size,this.xOffset=b=0,this.barWidth=g-2*a,this.x=c+=this.options.margin):(this.height=this.xOffset=g=b=this.size,this.barWidth=a-2*g,this.y+=this.options.margin);this.group[q]({translateX:c,
translateY:this.y});this.track[q]({width:a,height:g});this.scrollbarButtons[1][q]({translateX:f?0:a-b,translateY:f?g-m:0})};b.prototype.removeEvents=function(){this._events.forEach(function(c){F.apply(null,c)});this._events.length=0};b.prototype.render=function(){var c=this.renderer,b=this.options,a=this.size,g=this.chart.styledMode,f;this.group=f=c.g("scrollbar").attr({zIndex:b.zIndex,translateY:-99999}).add();this.track=c.rect().addClass("highcharts-scrollbar-track").attr({x:0,r:b.trackBorderRadius||
0,height:a,width:a}).add(f);g||this.track.attr({fill:b.trackBackgroundColor,stroke:b.trackBorderColor,"stroke-width":b.trackBorderWidth});this.trackBorderWidth=this.track.strokeWidth();this.track.attr({y:-this.trackBorderWidth%2/2});this.scrollbarGroup=c.g().add(f);this.scrollbar=c.rect().addClass("highcharts-scrollbar-thumb").attr({height:a,width:a,r:b.barBorderRadius||0}).add(this.scrollbarGroup);this.scrollbarRifles=c.path(z(["M",-3,a/4,"L",-3,2*a/3,"M",0,a/4,"L",0,2*a/3,"M",3,a/4,"L",3,2*a/3],
b.vertical)).addClass("highcharts-scrollbar-rifles").add(this.scrollbarGroup);g||(this.scrollbar.attr({fill:b.barBackgroundColor,stroke:b.barBorderColor,"stroke-width":b.barBorderWidth}),this.scrollbarRifles.attr({stroke:b.rifleColor,"stroke-width":1}));this.scrollbarStrokeWidth=this.scrollbar.strokeWidth();this.scrollbarGroup.translate(-this.scrollbarStrokeWidth%2/2,-this.scrollbarStrokeWidth%2/2);this.drawScrollbarButton(0);this.drawScrollbarButton(1)};b.prototype.setRange=function(b,e){var a=this.options,
c=a.vertical,f=a.minWidth,m=this.barWidth,q,y=!this.rendered||this.hasDragged||this.chart.navigator&&this.chart.navigator.hasDragged?"attr":"animate";if(E(m)){b=Math.max(b,0);var t=Math.ceil(m*b);this.calculatedWidth=q=r(m*Math.min(e,1)-t);q<f&&(t=(m-f+q)*b,q=f);f=Math.floor(t+this.xOffset+this.yOffset);m=q/2-.5;this.from=b;this.to=e;c?(this.scrollbarGroup[y]({translateY:f}),this.scrollbar[y]({height:q}),this.scrollbarRifles[y]({translateY:m}),this.scrollbarTop=f,this.scrollbarLeft=0):(this.scrollbarGroup[y]({translateX:f}),
this.scrollbar[y]({width:q}),this.scrollbarRifles[y]({translateX:m}),this.scrollbarLeft=f,this.scrollbarTop=0);12>=q?this.scrollbarRifles.hide():this.scrollbarRifles.show(!0);!1===a.showFull&&(0>=b&&1<=e?this.group.hide():this.group.show());this.rendered=!0}};b.prototype.trackClick=function(b){var c=this.chart.pointer.normalize(b),a=this.to-this.from,g=this.y+this.scrollbarTop,f=this.x+this.scrollbarLeft;this.options.vertical&&c.chartY>g||!this.options.vertical&&c.chartX>f?this.updatePosition(this.from+
a,this.to+a):this.updatePosition(this.from-a,this.to-a);e(this,"changed",{from:this.from,to:this.to,trigger:"scrollbar",DOMEvent:b})};b.prototype.update=function(b){this.destroy();this.init(this.chart.renderer,H(!0,this.options,b),this.chart)};b.prototype.updatePosition=function(b,e){1<e&&(b=r(1-r(e-b)),e=1);0>b&&(e=r(e-b),b=0);this.from=b;this.to=e};b.defaultOptions={height:l?20:14,barBorderRadius:0,buttonBorderRadius:0,liveRedraw:void 0,margin:10,minWidth:6,step:.2,zIndex:3,barBackgroundColor:"#cccccc",
barBorderWidth:1,barBorderColor:"#cccccc",buttonArrowColor:"#333333",buttonBackgroundColor:"#e6e6e6",buttonBorderColor:"#cccccc",buttonBorderWidth:1,rifleColor:"#333333",trackBackgroundColor:"#f2f2f2",trackBorderColor:"#f2f2f2",trackBorderWidth:1};return b}();d.Scrollbar||(v.scrollbar=H(!0,B.defaultOptions,v.scrollbar),d.Scrollbar=B,D.compose(n,B));return d.Scrollbar});G(n,"parts/Navigator.js",[n["parts/Axis.js"],n["parts/Color.js"],n["parts/Globals.js"],n["parts/NavigatorAxis.js"],n["parts/Scrollbar.js"],
n["parts/Utilities.js"]],function(n,d,D,v,x,r){d=d.parse;var E=r.addEvent,w=r.clamp,e=r.correctFloat,H=r.defined,I=r.destroyObjectProperties,F=r.erase,u=r.extend,l=r.find,z=r.isArray,B=r.isNumber,b=r.merge,c=r.pick,y=r.removeEvent,a=r.splat;r=D.Chart;var g=D.defaultOptions,f=D.hasTouch,m=D.isTouchDevice,q=D.Series,K=function(k){for(var h=[],p=1;p<arguments.length;p++)h[p-1]=arguments[p];h=[].filter.call(h,B);if(h.length)return Math[k].apply(0,h)};var t="undefined"===typeof D.seriesTypes.areaspline?
"line":"areaspline";u(g,{navigator:{height:40,margin:25,maskInside:!0,handles:{width:7,height:15,symbols:["navigator-handle","navigator-handle"],enabled:!0,lineWidth:1,backgroundColor:"#f2f2f2",borderColor:"#999999"},maskFill:d("#6685c2").setOpacity(.3).get(),outlineColor:"#cccccc",outlineWidth:1,series:{type:t,fillOpacity:.05,lineWidth:1,compare:null,dataGrouping:{approximation:"average",enabled:!0,groupPixelWidth:2,smoothed:!0,units:[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,
2,5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1,2,3,4]],["week",[1,2,3]],["month",[1,3,6]],["year",null]]},dataLabels:{enabled:!1,zIndex:2},id:"highcharts-navigator-series",className:"highcharts-navigator-series",lineColor:null,marker:{enabled:!1},threshold:null},xAxis:{overscroll:0,className:"highcharts-navigator-xaxis",tickLength:0,lineWidth:0,gridLineColor:"#e6e6e6",gridLineWidth:1,tickPixelInterval:200,labels:{align:"left",style:{color:"#999999"},x:3,y:-4},crosshair:!1},
yAxis:{className:"highcharts-navigator-yaxis",gridLineWidth:0,startOnTick:!1,endOnTick:!1,minPadding:.1,maxPadding:.1,labels:{enabled:!1},crosshair:!1,title:{text:null},tickLength:0,tickWidth:0}}});D.Renderer.prototype.symbols["navigator-handle"]=function(k,h,p,b,a){k=a.width/2;h=Math.round(k/3)+.5;a=a.height;return["M",-k-1,.5,"L",k,.5,"L",k,a+.5,"L",-k-1,a+.5,"L",-k-1,.5,"M",-h,4,"L",-h,a-3,"M",h-1,4,"L",h-1,a-3]};var A=function(){function k(h){this.zoomedMin=this.zoomedMax=this.yAxis=this.xAxis=
this.top=this.size=this.shades=this.rendered=this.range=this.outlineHeight=this.outline=this.opposite=this.navigatorSize=this.navigatorSeries=this.navigatorOptions=this.navigatorGroup=this.navigatorEnabled=this.left=this.height=this.handles=this.chart=this.baseSeries=void 0;this.init(h)}k.prototype.drawHandle=function(h,p,a,k){var b=this.navigatorOptions.handles.height;this.handles[p][k](a?{translateX:Math.round(this.left+this.height/2),translateY:Math.round(this.top+parseInt(h,10)+.5-b)}:{translateX:Math.round(this.left+
parseInt(h,10)),translateY:Math.round(this.top+this.height/2-b/2-1)})};k.prototype.drawOutline=function(h,p,a,b){var k=this.navigatorOptions.maskInside,c=this.outline.strokeWidth(),f=c/2;c=c%2/2;var C=this.outlineHeight,g=this.scrollbarHeight,m=this.size,J=this.left-g,t=this.top;a?(J-=f,a=t+p+c,p=t+h+c,h=["M",J+C,t-g-c,"L",J+C,a,"L",J,a,"L",J,p,"L",J+C,p,"L",J+C,t+m+g].concat(k?["M",J+C,a-f,"L",J+C,p+f]:[])):(h+=J+g-c,p+=J+g-c,t+=f,h=["M",J,t,"L",h,t,"L",h,t+C,"L",p,t+C,"L",p,t,"L",J+m+2*g,t].concat(k?
["M",h-f,t,"L",p+f,t]:[]));this.outline[b]({d:h})};k.prototype.drawMasks=function(h,p,a,k){var b=this.left,c=this.top,f=this.height;if(a){var C=[b,b,b];var g=[c,c+h,c+p];var m=[f,f,f];var J=[h,p-h,this.size-p]}else C=[b,b+h,b+p],g=[c,c,c],m=[h,p-h,this.size-p],J=[f,f,f];this.shades.forEach(function(h,p){h[k]({x:C[p],y:g[p],width:m[p],height:J[p]})})};k.prototype.renderElements=function(){var h=this,p=h.navigatorOptions,a=p.maskInside,b=h.chart,k=b.renderer,c,f={cursor:b.inverted?"ns-resize":"ew-resize"};
h.navigatorGroup=c=k.g("navigator").attr({zIndex:8,visibility:"hidden"}).add();[!a,a,!a].forEach(function(a,C){h.shades[C]=k.rect().addClass("highcharts-navigator-mask"+(1===C?"-inside":"-outside")).add(c);b.styledMode||h.shades[C].attr({fill:a?p.maskFill:"rgba(0,0,0,0)"}).css(1===C&&f)});h.outline=k.path().addClass("highcharts-navigator-outline").add(c);b.styledMode||h.outline.attr({"stroke-width":p.outlineWidth,stroke:p.outlineColor});p.handles.enabled&&[0,1].forEach(function(a){p.handles.inverted=
b.inverted;h.handles[a]=k.symbol(p.handles.symbols[a],-p.handles.width/2-1,0,p.handles.width,p.handles.height,p.handles);h.handles[a].attr({zIndex:7-a}).addClass("highcharts-navigator-handle highcharts-navigator-handle-"+["left","right"][a]).add(c);if(!b.styledMode){var C=p.handles;h.handles[a].attr({fill:C.backgroundColor,stroke:C.borderColor,"stroke-width":C.lineWidth}).css(f)}})};k.prototype.update=function(h){(this.series||[]).forEach(function(h){h.baseSeries&&delete h.baseSeries.navigatorSeries});
this.destroy();b(!0,this.chart.options.navigator,this.options,h);this.init(this.chart)};k.prototype.render=function(h,p,a,b){var k=this.chart,f=this.scrollbarHeight,g,C=this.xAxis,m=C.pointRange||0;var t=C.navigatorAxis.fake?k.xAxis[0]:C;var J=this.navigatorEnabled,q,A=this.rendered;var y=k.inverted;var d=k.xAxis[0].minRange,l=k.xAxis[0].options.maxRange;if(!this.hasDragged||H(a)){h=e(h-m/2);p=e(p+m/2);if(!B(h)||!B(p))if(A)a=0,b=c(C.width,t.width);else return;this.left=c(C.left,k.plotLeft+f+(y?k.plotWidth:
0));this.size=q=g=c(C.len,(y?k.plotHeight:k.plotWidth)-2*f);k=y?f:g+2*f;a=c(a,C.toPixels(h,!0));b=c(b,C.toPixels(p,!0));B(a)&&Infinity!==Math.abs(a)||(a=0,b=k);h=C.toValue(a,!0);p=C.toValue(b,!0);var K=Math.abs(e(p-h));K<d?this.grabbedLeft?a=C.toPixels(p-d-m,!0):this.grabbedRight&&(b=C.toPixels(h+d+m,!0)):H(l)&&e(K-m)>l&&(this.grabbedLeft?a=C.toPixels(p-l-m,!0):this.grabbedRight&&(b=C.toPixels(h+l+m,!0)));this.zoomedMax=w(Math.max(a,b),0,q);this.zoomedMin=w(this.fixedWidth?this.zoomedMax-this.fixedWidth:
Math.min(a,b),0,q);this.range=this.zoomedMax-this.zoomedMin;q=Math.round(this.zoomedMax);a=Math.round(this.zoomedMin);J&&(this.navigatorGroup.attr({visibility:"visible"}),A=A&&!this.hasDragged?"animate":"attr",this.drawMasks(a,q,y,A),this.drawOutline(a,q,y,A),this.navigatorOptions.handles.enabled&&(this.drawHandle(a,0,y,A),this.drawHandle(q,1,y,A)));this.scrollbar&&(y?(y=this.top-f,t=this.left-f+(J||!t.opposite?0:(t.titleOffset||0)+t.axisTitleMargin),f=g+2*f):(y=this.top+(J?this.height:-f),t=this.left-
f),this.scrollbar.position(t,y,k,f),this.scrollbar.setRange(this.zoomedMin/(g||1),this.zoomedMax/(g||1)));this.rendered=!0}};k.prototype.addMouseEvents=function(){var h=this,p=h.chart,a=p.container,b=[],k,c;h.mouseMoveHandler=k=function(p){h.onMouseMove(p)};h.mouseUpHandler=c=function(p){h.onMouseUp(p)};b=h.getPartsEvents("mousedown");b.push(E(p.renderTo,"mousemove",k),E(a.ownerDocument,"mouseup",c));f&&(b.push(E(p.renderTo,"touchmove",k),E(a.ownerDocument,"touchend",c)),b.concat(h.getPartsEvents("touchstart")));
h.eventsToUnbind=b;h.series&&h.series[0]&&b.push(E(h.series[0].xAxis,"foundExtremes",function(){p.navigator.modifyNavigatorAxisExtremes()}))};k.prototype.getPartsEvents=function(h){var p=this,a=[];["shades","handles"].forEach(function(b){p[b].forEach(function(k,f){a.push(E(k.element,h,function(h){p[b+"Mousedown"](h,f)}))})});return a};k.prototype.shadesMousedown=function(h,p){h=this.chart.pointer.normalize(h);var a=this.chart,b=this.xAxis,k=this.zoomedMin,f=this.left,c=this.size,g=this.range,m=h.chartX;
a.inverted&&(m=h.chartY,f=this.top);if(1===p)this.grabbedCenter=m,this.fixedWidth=g,this.dragOffset=m-k;else{h=m-f-g/2;if(0===p)h=Math.max(0,h);else if(2===p&&h+g>=c)if(h=c-g,this.reversedExtremes){h-=g;var t=this.getUnionExtremes().dataMin}else var q=this.getUnionExtremes().dataMax;h!==k&&(this.fixedWidth=g,p=b.navigatorAxis.toFixedRange(h,h+g,t,q),H(p.min)&&a.xAxis[0].setExtremes(Math.min(p.min,p.max),Math.max(p.min,p.max),!0,null,{trigger:"navigator"}))}};k.prototype.handlesMousedown=function(h,
p){this.chart.pointer.normalize(h);h=this.chart;var a=h.xAxis[0],b=this.reversedExtremes;0===p?(this.grabbedLeft=!0,this.otherHandlePos=this.zoomedMax,this.fixedExtreme=b?a.min:a.max):(this.grabbedRight=!0,this.otherHandlePos=this.zoomedMin,this.fixedExtreme=b?a.max:a.min);h.fixedRange=null};k.prototype.onMouseMove=function(h){var p=this,a=p.chart,b=p.left,k=p.navigatorSize,f=p.range,g=p.dragOffset,t=a.inverted;h.touches&&0===h.touches[0].pageX||(h=a.pointer.normalize(h),a=h.chartX,t&&(b=p.top,a=
h.chartY),p.grabbedLeft?(p.hasDragged=!0,p.render(0,0,a-b,p.otherHandlePos)):p.grabbedRight?(p.hasDragged=!0,p.render(0,0,p.otherHandlePos,a-b)):p.grabbedCenter&&(p.hasDragged=!0,a<g?a=g:a>k+g-f&&(a=k+g-f),p.render(0,0,a-g,a-g+f)),p.hasDragged&&p.scrollbar&&c(p.scrollbar.options.liveRedraw,D.svg&&!m&&!this.chart.isBoosting)&&(h.DOMType=h.type,setTimeout(function(){p.onMouseUp(h)},0)))};k.prototype.onMouseUp=function(h){var a=this.chart,b=this.xAxis,k=this.scrollbar,f=h.DOMEvent||h,c=a.inverted,g=
this.rendered&&!this.hasDragged?"animate":"attr",m=Math.round(this.zoomedMax),t=Math.round(this.zoomedMin);if(this.hasDragged&&(!k||!k.hasDragged)||"scrollbar"===h.trigger){k=this.getUnionExtremes();if(this.zoomedMin===this.otherHandlePos)var q=this.fixedExtreme;else if(this.zoomedMax===this.otherHandlePos)var e=this.fixedExtreme;this.zoomedMax===this.size&&(e=this.reversedExtremes?k.dataMin:k.dataMax);0===this.zoomedMin&&(q=this.reversedExtremes?k.dataMax:k.dataMin);b=b.navigatorAxis.toFixedRange(this.zoomedMin,
this.zoomedMax,q,e);H(b.min)&&a.xAxis[0].setExtremes(Math.min(b.min,b.max),Math.max(b.min,b.max),!0,this.hasDragged?!1:null,{trigger:"navigator",triggerOp:"navigator-drag",DOMEvent:f})}"mousemove"!==h.DOMType&&"touchmove"!==h.DOMType&&(this.grabbedLeft=this.grabbedRight=this.grabbedCenter=this.fixedWidth=this.fixedExtreme=this.otherHandlePos=this.hasDragged=this.dragOffset=null);this.navigatorEnabled&&(this.shades&&this.drawMasks(t,m,c,g),this.outline&&this.drawOutline(t,m,c,g),this.navigatorOptions.handles.enabled&&
Object.keys(this.handles).length===this.handles.length&&(this.drawHandle(t,0,c,g),this.drawHandle(m,1,c,g)))};k.prototype.removeEvents=function(){this.eventsToUnbind&&(this.eventsToUnbind.forEach(function(h){h()}),this.eventsToUnbind=void 0);this.removeBaseSeriesEvents()};k.prototype.removeBaseSeriesEvents=function(){var h=this.baseSeries||[];this.navigatorEnabled&&h[0]&&(!1!==this.navigatorOptions.adaptToUpdatedData&&h.forEach(function(h){y(h,"updatedData",this.updatedDataHandler)},this),h[0].xAxis&&
y(h[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes))};k.prototype.init=function(h){var a=h.options,k=a.navigator,f=k.enabled,g=a.scrollbar,m=g.enabled;a=f?k.height:0;var t=m?g.height:0;this.handles=[];this.shades=[];this.chart=h;this.setBaseSeries();this.height=a;this.scrollbarHeight=t;this.scrollbarEnabled=m;this.navigatorEnabled=f;this.navigatorOptions=k;this.scrollbarOptions=g;this.outlineHeight=a+t;this.opposite=c(k.opposite,!(f||!h.inverted));var q=this;f=q.baseSeries;g=h.xAxis.length;
m=h.yAxis.length;var e=f&&f[0]&&f[0].xAxis||h.xAxis[0]||{options:{}};h.isDirtyBox=!0;q.navigatorEnabled?(q.xAxis=new n(h,b({breaks:e.options.breaks,ordinal:e.options.ordinal},k.xAxis,{id:"navigator-x-axis",yAxis:"navigator-y-axis",isX:!0,type:"datetime",index:g,isInternal:!0,offset:0,keepOrdinalPadding:!0,startOnTick:!1,endOnTick:!1,minPadding:0,maxPadding:0,zoomEnabled:!1},h.inverted?{offsets:[t,0,-t,0],width:a}:{offsets:[0,-t,0,t],height:a})),q.yAxis=new n(h,b(k.yAxis,{id:"navigator-y-axis",alignTicks:!1,
offset:0,index:m,isInternal:!0,zoomEnabled:!1},h.inverted?{width:a}:{height:a})),f||k.series.data?q.updateNavigatorSeries(!1):0===h.series.length&&(q.unbindRedraw=E(h,"beforeRedraw",function(){0<h.series.length&&!q.series&&(q.setBaseSeries(),q.unbindRedraw())})),q.reversedExtremes=h.inverted&&!q.xAxis.reversed||!h.inverted&&q.xAxis.reversed,q.renderElements(),q.addMouseEvents()):(q.xAxis={chart:h,navigatorAxis:{fake:!0},translate:function(a,b){var k=h.xAxis[0],p=k.getExtremes(),f=k.len-2*t,c=K("min",
k.options.min,p.dataMin);k=K("max",k.options.max,p.dataMax)-c;return b?a*k/f+c:f*(a-c)/k},toPixels:function(h){return this.translate(h)},toValue:function(h){return this.translate(h,!0)}},q.xAxis.navigatorAxis.axis=q.xAxis,q.xAxis.navigatorAxis.toFixedRange=v.AdditionsClass.prototype.toFixedRange.bind(q.xAxis.navigatorAxis));h.options.scrollbar.enabled&&(h.scrollbar=q.scrollbar=new x(h.renderer,b(h.options.scrollbar,{margin:q.navigatorEnabled?0:10,vertical:h.inverted}),h),E(q.scrollbar,"changed",function(a){var k=
q.size,b=k*this.to;k*=this.from;q.hasDragged=q.scrollbar.hasDragged;q.render(0,0,k,b);(h.options.scrollbar.liveRedraw||"mousemove"!==a.DOMType&&"touchmove"!==a.DOMType)&&setTimeout(function(){q.onMouseUp(a)})}));q.addBaseSeriesEvents();q.addChartEvents()};k.prototype.getUnionExtremes=function(h){var a=this.chart.xAxis[0],k=this.xAxis,b=k.options,f=a.options,g;h&&null===a.dataMin||(g={dataMin:c(b&&b.min,K("min",f.min,a.dataMin,k.dataMin,k.min)),dataMax:c(b&&b.max,K("max",f.max,a.dataMax,k.dataMax,
k.max))});return g};k.prototype.setBaseSeries=function(h,a){var k=this.chart,b=this.baseSeries=[];h=h||k.options&&k.options.navigator.baseSeries||(k.series.length?l(k.series,function(a){return!a.options.isInternal}).index:0);(k.series||[]).forEach(function(a,k){a.options.isInternal||!a.options.showInNavigator&&(k!==h&&a.options.id!==h||!1===a.options.showInNavigator)||b.push(a)});this.xAxis&&!this.xAxis.navigatorAxis.fake&&this.updateNavigatorSeries(!0,a)};k.prototype.updateNavigatorSeries=function(h,
k){var p=this,f=p.chart,m=p.baseSeries,t,q,e=p.navigatorOptions.series,A,d={enableMouseTracking:!1,index:null,linkedTo:null,group:"nav",padXAxis:!1,xAxis:"navigator-x-axis",yAxis:"navigator-y-axis",showInLegend:!1,stacking:void 0,isInternal:!0,states:{inactive:{opacity:1}}},l=p.series=(p.series||[]).filter(function(a){var h=a.baseSeries;return 0>m.indexOf(h)?(h&&(y(h,"updatedData",p.updatedDataHandler),delete h.navigatorSeries),a.chart&&a.destroy(),!1):!0});m&&m.length&&m.forEach(function(a){var h=
a.navigatorSeries,C=u({color:a.color,visible:a.visible},z(e)?g.navigator.series:e);h&&!1===p.navigatorOptions.adaptToUpdatedData||(d.name="Navigator "+m.length,t=a.options||{},A=t.navigatorOptions||{},q=b(t,d,C,A),q.pointRange=c(C.pointRange,A.pointRange,g.plotOptions[q.type||"line"].pointRange),C=A.data||C.data,p.hasNavigatorData=p.hasNavigatorData||!!C,q.data=C||t.data&&t.data.slice(0),h&&h.options?h.update(q,k):(a.navigatorSeries=f.initSeries(q),a.navigatorSeries.baseSeries=a,l.push(a.navigatorSeries)))});
if(e.data&&(!m||!m.length)||z(e))p.hasNavigatorData=!1,e=a(e),e.forEach(function(a,h){d.name="Navigator "+(l.length+1);q=b(g.navigator.series,{color:f.series[h]&&!f.series[h].options.isInternal&&f.series[h].color||f.options.colors[h]||f.options.colors[0]},d,a);q.data=a.data;q.data&&(p.hasNavigatorData=!0,l.push(f.initSeries(q)))});h&&this.addBaseSeriesEvents()};k.prototype.addBaseSeriesEvents=function(){var a=this,k=a.baseSeries||[];k[0]&&k[0].xAxis&&E(k[0].xAxis,"foundExtremes",this.modifyBaseAxisExtremes);
k.forEach(function(h){E(h,"show",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!0,!1)});E(h,"hide",function(){this.navigatorSeries&&this.navigatorSeries.setVisible(!1,!1)});!1!==this.navigatorOptions.adaptToUpdatedData&&h.xAxis&&E(h,"updatedData",this.updatedDataHandler);E(h,"remove",function(){this.navigatorSeries&&(F(a.series,this.navigatorSeries),H(this.navigatorSeries.options)&&this.navigatorSeries.remove(!1),delete this.navigatorSeries)})},this)};k.prototype.getBaseSeriesMin=
function(a){return this.baseSeries.reduce(function(a,h){return Math.min(a,h.xData?h.xData[0]:a)},a)};k.prototype.modifyNavigatorAxisExtremes=function(){var a=this.xAxis,k;"undefined"!==typeof a.getExtremes&&(!(k=this.getUnionExtremes(!0))||k.dataMin===a.min&&k.dataMax===a.max||(a.min=k.dataMin,a.max=k.dataMax))};k.prototype.modifyBaseAxisExtremes=function(){var a=this.chart.navigator,k=this.getExtremes(),b=k.dataMin,f=k.dataMax;k=k.max-k.min;var g=a.stickToMin,m=a.stickToMax,q=c(this.options.overscroll,
0),t=a.series&&a.series[0],e=!!this.setExtremes;if(!this.eventArgs||"rangeSelectorButton"!==this.eventArgs.trigger){if(g){var A=b;var y=A+k}m&&(y=f+q,g||(A=Math.max(y-k,a.getBaseSeriesMin(t&&t.xData?t.xData[0]:-Number.MAX_VALUE))));e&&(g||m)&&B(A)&&(this.min=this.userMin=A,this.max=this.userMax=y)}a.stickToMin=a.stickToMax=null};k.prototype.updatedDataHandler=function(){var a=this.chart.navigator,k=this.navigatorSeries,b=a.getBaseSeriesMin(this.xData[0]);a.stickToMax=a.reversedExtremes?0===Math.round(a.zoomedMin):
Math.round(a.zoomedMax)>=Math.round(a.size);a.stickToMin=B(this.xAxis.min)&&this.xAxis.min<=b&&(!this.chart.fixedRange||!a.stickToMax);k&&!a.hasNavigatorData&&(k.options.pointStart=this.xData[0],k.setData(this.options.data,!1,null,!1))};k.prototype.addChartEvents=function(){this.eventsToUnbind||(this.eventsToUnbind=[]);this.eventsToUnbind.push(E(this.chart,"redraw",function(){var a=this.navigator,k=a&&(a.baseSeries&&a.baseSeries[0]&&a.baseSeries[0].xAxis||this.xAxis[0]);k&&a.render(k.min,k.max)}),
E(this.chart,"getMargins",function(){var a=this.navigator,k=a.opposite?"plotTop":"marginBottom";this.inverted&&(k=a.opposite?"marginRight":"plotLeft");this[k]=(this[k]||0)+(a.navigatorEnabled||!this.inverted?a.outlineHeight:0)+a.navigatorOptions.margin}))};k.prototype.destroy=function(){this.removeEvents();this.xAxis&&(F(this.chart.xAxis,this.xAxis),F(this.chart.axes,this.xAxis));this.yAxis&&(F(this.chart.yAxis,this.yAxis),F(this.chart.axes,this.yAxis));(this.series||[]).forEach(function(a){a.destroy&&
a.destroy()});"series xAxis yAxis shades outline scrollbarTrack scrollbarRifles scrollbarGroup scrollbar navigatorGroup rendered".split(" ").forEach(function(a){this[a]&&this[a].destroy&&this[a].destroy();this[a]=null},this);[this.handles].forEach(function(a){I(a)},this)};return k}();D.Navigator||(D.Navigator=A,v.compose(n),E(r,"beforeShowResetZoom",function(){var a=this.options,h=a.navigator,b=a.rangeSelector;if((h&&h.enabled||b&&b.enabled)&&(!m&&"x"===a.chart.zoomType||m&&"x"===a.chart.pinchType))return!1}),
E(r,"beforeRender",function(){var a=this.options;if(a.navigator.enabled||a.scrollbar.enabled)this.scroller=this.navigator=new A(this)}),E(r,"afterSetChartSize",function(){var a=this.legend,b=this.navigator;if(b){var p=a&&a.options;var f=b.xAxis;var g=b.yAxis;var m=b.scrollbarHeight;this.inverted?(b.left=b.opposite?this.chartWidth-m-b.height:this.spacing[3]+m,b.top=this.plotTop+m):(b.left=this.plotLeft+m,b.top=b.navigatorOptions.top||this.chartHeight-b.height-m-this.spacing[2]-(this.rangeSelector&&
this.extraBottomMargin?this.rangeSelector.getHeight():0)-(p&&"bottom"===p.verticalAlign&&p.enabled&&!p.floating?a.legendHeight+c(p.margin,10):0)-(this.titleOffset?this.titleOffset[2]:0));f&&g&&(this.inverted?f.options.left=g.options.left=b.left:f.options.top=g.options.top=b.top,f.setAxisSize(),g.setAxisSize())}}),E(r,"update",function(a){var k=a.options.navigator||{},f=a.options.scrollbar||{};this.navigator||this.scroller||!k.enabled&&!f.enabled||(b(!0,this.options.navigator,k),b(!0,this.options.scrollbar,
f),delete a.options.navigator,delete a.options.scrollbar)}),E(r,"afterUpdate",function(a){this.navigator||this.scroller||!this.options.navigator.enabled&&!this.options.scrollbar.enabled||(this.scroller=this.navigator=new A(this),c(a.redraw,!0)&&this.redraw(a.animation))}),E(r,"afterAddSeries",function(){this.navigator&&this.navigator.setBaseSeries(null,!1)}),E(q,"afterUpdate",function(){this.chart.navigator&&!this.options.isInternal&&this.chart.navigator.setBaseSeries(null,!1)}),r.prototype.callbacks.push(function(a){var b=
a.navigator;b&&a.xAxis[0]&&(a=a.xAxis[0].getExtremes(),b.render(a.min,a.max))}));D.Navigator=A;return D.Navigator});G(n,"parts/OrdinalAxis.js",[n["parts/Axis.js"],n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,d,D){var v=D.addEvent,x=D.css,r=D.defined,E=D.pick,w=D.timeUnits;D=d.Chart;var e=d.Series,H=function(){function e(e){this.index={};this.axis=e}e.prototype.getExtendedPositions=function(){var e=this,l=e.axis,z=l.constructor.prototype,B=l.chart,b=l.series[0].currentDataGrouping,c=e.index,
y=b?b.count+b.unitName:"raw",a=l.options.overscroll,g=l.getExtremes(),f;c||(c=e.index={});if(!c[y]){var m={series:[],chart:B,getExtremes:function(){return{min:g.dataMin,max:g.dataMax+a}},options:{ordinal:!0},ordinal:{},ordinal2lin:z.ordinal2lin,val2lin:z.val2lin};m.ordinal.axis=m;l.series.forEach(function(a){f={xAxis:m,xData:a.xData.slice(),chart:B,destroyGroupedData:d.noop,getProcessedData:d.Series.prototype.getProcessedData};f.xData=f.xData.concat(e.getOverscrollPositions());f.options={dataGrouping:b?
{enabled:!0,forced:!0,approximation:"open",units:[[b.unitName,[b.count]]]}:{enabled:!1}};a.processData.apply(f);m.series.push(f)});l.beforeSetTickPositions.apply(m);c[y]=m.ordinal.positions}return c[y]};e.prototype.getGroupIntervalFactor=function(e,d,z){z=z.processedXData;var l=z.length,b=[];var c=this.groupIntervalFactor;if(!c){for(c=0;c<l-1;c++)b[c]=z[c+1]-z[c];b.sort(function(b,a){return b-a});b=b[Math.floor(l/2)];e=Math.max(e,z[0]);d=Math.min(d,z[l-1]);this.groupIntervalFactor=c=l*b/(d-e)}return c};
e.prototype.getOverscrollPositions=function(){var e=this.axis,d=e.options.overscroll,z=this.overscrollPointsRange,B=[],b=e.dataMax;if(r(z))for(B.push(b);b<=e.dataMax+d;)b+=z,B.push(b);return B};e.prototype.postProcessTickInterval=function(e){var d=this.axis,z=this.slope;return z?d.options.breaks?d.closestPointRange||e:e/(z/d.closestPointRange):e};return e}(),I=function(){function e(){}e.compose=function(e,d,z){e.keepProps.push("ordinal");var l=e.prototype;l.beforeSetTickPositions=function(){var b=
this.ordinal,c=[],e,a=!1,g=this.getExtremes(),f=g.min,m=g.max,q,d=this.isXAxis&&!!this.options.breaks;g=this.options.ordinal;var t=Number.MAX_VALUE,A=this.chart.options.chart.ignoreHiddenSeries,k;if(g||d){this.series.forEach(function(a,b){e=[];if(!(A&&!1===a.visible||!1===a.takeOrdinalPosition&&!d)&&(c=c.concat(a.processedXData),h=c.length,c.sort(function(a,b){return a-b}),t=Math.min(t,E(a.closestPointRange,t)),h)){for(b=0;b<h-1;)c[b]!==c[b+1]&&e.push(c[b+1]),b++;e[0]!==c[0]&&e.unshift(c[0]);c=e}a.isSeriesBoosting&&
(k=!0)});k&&(c.length=0);var h=c.length;if(2<h){var p=c[1]-c[0];for(q=h-1;q--&&!a;)c[q+1]-c[q]!==p&&(a=!0);!this.options.keepOrdinalPadding&&(c[0]-f>p||m-c[c.length-1]>p)&&(a=!0)}else this.options.overscroll&&(2===h?t=c[1]-c[0]:1===h?(t=this.options.overscroll,c=[c[0],c[0]+t]):t=b.overscrollPointsRange);a?(this.options.overscroll&&(b.overscrollPointsRange=t,c=c.concat(b.getOverscrollPositions())),b.positions=c,p=this.ordinal2lin(Math.max(f,c[0]),!0),q=Math.max(this.ordinal2lin(Math.min(m,c[c.length-
1]),!0),1),b.slope=m=(m-f)/(q-p),b.offset=f-p*m):(b.overscrollPointsRange=E(this.closestPointRange,b.overscrollPointsRange),b.positions=this.ordinal.slope=b.offset=void 0)}this.isOrdinal=g&&a;b.groupIntervalFactor=null};e.prototype.getTimeTicks=function(b,c,e,a,g,f,m){void 0===g&&(g=[]);void 0===f&&(f=0);var q=0,d,t,A={},k=[],h=-Number.MAX_VALUE,p=this.options.tickPixelInterval,C=this.chart.time,y=[];if(!this.options.ordinal&&!this.options.breaks||!g||3>g.length||"undefined"===typeof c)return C.getTimeTicks.apply(C,
arguments);var l=g.length;for(d=0;d<l;d++){var z=d&&g[d-1]>e;g[d]<c&&(q=d);if(d===l-1||g[d+1]-g[d]>5*f||z){if(g[d]>h){for(t=C.getTimeTicks(b,g[q],g[d],a);t.length&&t[0]<=h;)t.shift();t.length&&(h=t[t.length-1]);y.push(k.length);k=k.concat(t)}q=d+1}if(z)break}t=t.info;if(m&&t.unitRange<=w.hour){d=k.length-1;for(q=1;q<d;q++)if(C.dateFormat("%d",k[q])!==C.dateFormat("%d",k[q-1])){A[k[q]]="day";var B=!0}B&&(A[k[0]]="day");t.higherRanks=A}t.segmentStarts=y;k.info=t;if(m&&r(p)){q=y=k.length;B=[];var u;
for(C=[];q--;)d=this.translate(k[q]),u&&(C[q]=u-d),B[q]=u=d;C.sort();C=C[Math.floor(C.length/2)];C<.6*p&&(C=null);q=k[y-1]>e?y-1:y;for(u=void 0;q--;)d=B[q],y=Math.abs(u-d),u&&y<.8*p&&(null===C||y<.8*C)?(A[k[q]]&&!A[k[q+1]]?(y=q+1,u=d):y=q,k.splice(y,1)):u=d}return k};l.lin2val=function(b,c){var e=this.ordinal,a=e.positions;if(a){var g=e.slope,f=e.offset;e=a.length-1;if(c)if(0>b)b=a[0];else if(b>e)b=a[e];else{e=Math.floor(b);var m=b-e}else for(;e--;)if(c=g*e+f,b>=c){g=g*(e+1)+f;m=(b-c)/(g-c);break}return"undefined"!==
typeof m&&"undefined"!==typeof a[e]?a[e]+(m?m*(a[e+1]-a[e]):0):b}return b};l.val2lin=function(b,c){var e=this.ordinal,a=e.positions;if(a){var g=a.length,f;for(f=g;f--;)if(a[f]===b){var m=f;break}for(f=g-1;f--;)if(b>a[f]||0===f){b=(b-a[f])/(a[f+1]-a[f]);m=f+b;break}c=c?m:e.slope*(m||0)+e.offset}else c=b;return c};l.ordinal2lin=l.val2lin;v(e,"afterInit",function(){this.ordinal||(this.ordinal=new H(this))});v(e,"foundExtremes",function(){this.isXAxis&&r(this.options.overscroll)&&this.max===this.dataMax&&
(!this.chart.mouseIsDown||this.isInternal)&&(!this.eventArgs||this.eventArgs&&"navigator"!==this.eventArgs.trigger)&&(this.max+=this.options.overscroll,!this.isInternal&&r(this.userMin)&&(this.min+=this.options.overscroll))});v(e,"afterSetScale",function(){this.horiz&&!this.isDirty&&(this.isDirty=this.isOrdinal&&this.chart.navigator&&!this.chart.navigator.adaptToUpdatedData)});v(d,"pan",function(b){var c=this.xAxis[0],e=c.options.overscroll,a=b.originalEvent.chartX,g=this.options.chart&&this.options.chart.panning,
f=!1;if(g&&"y"!==g.type&&c.options.ordinal&&c.series.length){var m=this.mouseDownX,q=c.getExtremes(),d=q.dataMax,t=q.min,A=q.max,k=this.hoverPoints,h=c.closestPointRange||c.ordinal&&c.ordinal.overscrollPointsRange;m=(m-a)/(c.translationSlope*(c.ordinal.slope||h));var p={ordinal:{positions:c.ordinal.getExtendedPositions()}};h=c.lin2val;var C=c.val2lin;if(!p.ordinal.positions)f=!0;else if(1<Math.abs(m)){k&&k.forEach(function(a){a.setState()});if(0>m){k=p;var l=c.ordinal.positions?c:p}else k=c.ordinal.positions?
c:p,l=p;p=l.ordinal.positions;d>p[p.length-1]&&p.push(d);this.fixedRange=A-t;m=c.navigatorAxis.toFixedRange(null,null,h.apply(k,[C.apply(k,[t,!0])+m,!0]),h.apply(l,[C.apply(l,[A,!0])+m,!0]));m.min>=Math.min(q.dataMin,t)&&m.max<=Math.max(d,A)+e&&c.setExtremes(m.min,m.max,!0,!1,{trigger:"pan"});this.mouseDownX=a;x(this.container,{cursor:"move"})}}else f=!0;f||g&&/y/.test(g.type)?e&&(c.max=c.dataMax+e):b.preventDefault()});v(z,"updatedData",function(){var b=this.xAxis;b&&b.options.ordinal&&delete b.ordinal.index})};
return e}();I.compose(n,D,e);return I});G(n,"modules/broken-axis.src.js",[n["parts/Axis.js"],n["parts/Globals.js"],n["parts/Utilities.js"],n["parts/Stacking.js"]],function(n,d,D,v){var x=D.addEvent,r=D.find,E=D.fireEvent,w=D.isArray,e=D.isNumber,H=D.pick,I=d.Series,F=function(){function e(e){this.hasBreaks=!1;this.axis=e}e.isInBreak=function(e,d){var l=e.repeat||Infinity,b=e.from,c=e.to-e.from;d=d>=b?(d-b)%l:l-(b-d)%l;return e.inclusive?d<=c:d<c&&0!==d};e.lin2Val=function(d){var l=this.brokenAxis;
l=l&&l.breakArray;if(!l)return d;var r;for(r=0;r<l.length;r++){var b=l[r];if(b.from>=d)break;else b.to<d?d+=b.len:e.isInBreak(b,d)&&(d+=b.len)}return d};e.val2Lin=function(d){var l=this.brokenAxis;l=l&&l.breakArray;if(!l)return d;var r=d,b;for(b=0;b<l.length;b++){var c=l[b];if(c.to<=d)r-=c.len;else if(c.from>=d)break;else if(e.isInBreak(c,d)){r-=d-c.from;break}}return r};e.prototype.findBreakAt=function(e,d){return r(d,function(d){return d.from<e&&e<d.to})};e.prototype.isInAnyBreak=function(d,r){var l=
this.axis,b=l.options.breaks,c=b&&b.length,y;if(c){for(;c--;)if(e.isInBreak(b[c],d)){var a=!0;y||(y=H(b[c].showPoints,!l.isXAxis))}var g=a&&r?a&&!y:a}return g};e.prototype.setBreaks=function(d,r){var l=this,b=l.axis,c=w(d)&&!!d.length;b.isDirty=l.hasBreaks!==c;l.hasBreaks=c;b.options.breaks=b.userOptions.breaks=d;b.forceRedraw=!0;b.series.forEach(function(b){b.isDirty=!0});c||b.val2lin!==e.val2Lin||(delete b.val2lin,delete b.lin2val);c&&(b.userOptions.ordinal=!1,b.lin2val=e.lin2Val,b.val2lin=e.val2Lin,
b.setExtremes=function(b,a,c,f,e){if(l.hasBreaks){for(var g,m=this.options.breaks;g=l.findBreakAt(b,m);)b=g.to;for(;g=l.findBreakAt(a,m);)a=g.from;a<b&&(a=b)}n.prototype.setExtremes.call(this,b,a,c,f,e)},b.setAxisTranslation=function(c){n.prototype.setAxisTranslation.call(this,c);l.unitLength=null;if(l.hasBreaks){c=b.options.breaks||[];var a=[],g=[],f=0,m,d=b.userMin||b.min,r=b.userMax||b.max,t=H(b.pointRangePadding,0),A;c.forEach(function(a){m=a.repeat||Infinity;e.isInBreak(a,d)&&(d+=a.to%m-d%m);
e.isInBreak(a,r)&&(r-=r%m-a.from%m)});c.forEach(function(b){h=b.from;for(m=b.repeat||Infinity;h-m>d;)h-=m;for(;h<d;)h+=m;for(A=h;A<r;A+=m)a.push({value:A,move:"in"}),a.push({value:A+(b.to-b.from),move:"out",size:b.breakSize})});a.sort(function(a,b){return a.value===b.value?("in"===a.move?0:1)-("in"===b.move?0:1):a.value-b.value});var k=0;var h=d;a.forEach(function(a){k+="in"===a.move?1:-1;1===k&&"in"===a.move&&(h=a.value);0===k&&(g.push({from:h,to:a.value,len:a.value-h-(a.size||0)}),f+=a.value-h-
(a.size||0))});b.breakArray=l.breakArray=g;l.unitLength=r-d-f+t;E(b,"afterBreaks");b.staticScale?b.transA=b.staticScale:l.unitLength&&(b.transA*=(r-b.min+t)/l.unitLength);t&&(b.minPixelPadding=b.transA*b.minPointOffset);b.min=d;b.max=r}});H(r,!0)&&b.chart.redraw()};return e}();d=function(){function d(){}d.compose=function(d,r){d.keepProps.push("brokenAxis");var l=I.prototype;l.drawBreaks=function(b,c){var d=this,a=d.points,g,f,m,q;if(b&&b.brokenAxis&&b.brokenAxis.hasBreaks){var l=b.brokenAxis;c.forEach(function(c){g=
l&&l.breakArray||[];f=b.isXAxis?b.min:H(d.options.threshold,b.min);a.forEach(function(a){q=H(a["stack"+c.toUpperCase()],a[c]);g.forEach(function(k){if(e(f)&&e(q)){m=!1;if(f<k.from&&q>k.to||f>k.from&&q<k.from)m="pointBreak";else if(f<k.from&&q>k.from&&q<k.to||f>k.from&&q>k.to&&q<k.from)m="pointInBreak";m&&E(b,m,{point:a,brk:k})}})})})}};l.gappedPath=function(){var b=this.currentDataGrouping,c=b&&b.gapSize;b=this.options.gapSize;var e=this.points.slice(),a=e.length-1,g=this.yAxis,f;if(b&&0<a)for("value"!==
this.options.gapUnit&&(b*=this.basePointRange),c&&c>b&&c>=this.basePointRange&&(b=c),f=void 0;a--;)f&&!1!==f.visible||(f=e[a+1]),c=e[a],!1!==f.visible&&!1!==c.visible&&(f.x-c.x>b&&(f=(c.x+f.x)/2,e.splice(a+1,0,{isNull:!0,x:f}),this.options.stacking&&(f=g.stacks[this.stackKey][f]=new v(g,g.options.stackLabels,!1,f,this.stack),f.total=0)),f=c);return this.getGraphPath(e)};x(d,"init",function(){this.brokenAxis||(this.brokenAxis=new F(this))});x(d,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&
this.brokenAxis.setBreaks(this.options.breaks,!1)});x(d,"afterSetTickPositions",function(){var b=this.brokenAxis;if(b&&b.hasBreaks){var c=this.tickPositions,e=this.tickPositions.info,a=[],g;for(g=0;g<c.length;g++)b.isInAnyBreak(c[g])||a.push(c[g]);this.tickPositions=a;this.tickPositions.info=e}});x(d,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});x(r,"afterGeneratePoints",function(){var b=this.options.connectNulls,c=this.points,e=this.xAxis,a=
this.yAxis;if(this.isDirty)for(var g=c.length;g--;){var f=c[g],d=!(null===f.y&&!1===b)&&(e&&e.brokenAxis&&e.brokenAxis.isInAnyBreak(f.x,!0)||a&&a.brokenAxis&&a.brokenAxis.isInAnyBreak(f.y,!0));f.visible=d?!1:!1!==f.options.visible}});x(r,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,H(this.pointArrayMap,["y"]))})};return d}();d.compose(n,I);return d});G(n,"masters/modules/broken-axis.src.js",[],function(){});G(n,"parts/DataGrouping.js",[n["parts/DateTimeAxis.js"],
n["parts/Globals.js"],n["parts/Point.js"],n["parts/Tooltip.js"],n["parts/Utilities.js"]],function(n,d,D,v,x){"";var r=x.addEvent,E=x.arrayMax,w=x.arrayMin,e=x.correctFloat,H=x.defined,I=x.error,F=x.extend,u=x.format,l=x.isNumber,z=x.merge,B=x.pick,b=d.Axis,c=d.defaultPlotOptions;x=d.Series;var y=d.approximations={sum:function(a){var b=a.length;if(!b&&a.hasNulls)var k=null;else if(b)for(k=0;b--;)k+=a[b];return k},average:function(a){var b=a.length;a=y.sum(a);l(a)&&b&&(a=e(a/b));return a},averages:function(){var a=
[];[].forEach.call(arguments,function(b){a.push(y.average(b))});return"undefined"===typeof a[0]?void 0:a},open:function(a){return a.length?a[0]:a.hasNulls?null:void 0},high:function(a){return a.length?E(a):a.hasNulls?null:void 0},low:function(a){return a.length?w(a):a.hasNulls?null:void 0},close:function(a){return a.length?a[a.length-1]:a.hasNulls?null:void 0},ohlc:function(a,b,f,c){a=y.open(a);b=y.high(b);f=y.low(f);c=y.close(c);if(l(a)||l(b)||l(f)||l(c))return[a,b,f,c]},range:function(a,b){a=y.low(a);
b=y.high(b);if(l(a)||l(b))return[a,b];if(null===a&&null===b)return null}},a=function(a,b,f,c){var k=this,h=k.data,e=k.options&&k.options.data,p=[],g=[],d=[],m=a.length,t=!!b,q=[],A=k.pointArrayMap,C=A&&A.length,r=["x"].concat(A||["y"]),n=0,w=0,x;c="function"===typeof c?c:y[c]?y[c]:y[k.getDGApproximation&&k.getDGApproximation()||"average"];C?A.forEach(function(){q.push([])}):q.push([]);var v=C||1;for(x=0;x<=m&&!(a[x]>=f[0]);x++);for(x;x<=m;x++){for(;"undefined"!==typeof f[n+1]&&a[x]>=f[n+1]||x===m;){var u=
f[n];k.dataGroupInfo={start:k.cropStart+w,length:q[0].length};var B=c.apply(k,q);k.pointClass&&!H(k.dataGroupInfo.options)&&(k.dataGroupInfo.options=z(k.pointClass.prototype.optionsToObject.call({series:k},k.options.data[k.cropStart+w])),r.forEach(function(a){delete k.dataGroupInfo.options[a]}));"undefined"!==typeof B&&(p.push(u),g.push(B),d.push(k.dataGroupInfo));w=x;for(u=0;u<v;u++)q[u].length=0,q[u].hasNulls=!1;n+=1;if(x===m)break}if(x===m)break;if(A)for(u=k.cropStart+x,B=h&&h[u]||k.pointClass.prototype.applyOptions.apply({series:k},
[e[u]]),u=0;u<C;u++){var K=B[A[u]];l(K)?q[u].push(K):null===K&&(q[u].hasNulls=!0)}else u=t?b[x]:null,l(u)?q[0].push(u):null===u&&(q[0].hasNulls=!0)}return{groupedXData:p,groupedYData:g,groupMap:d}},g={approximations:y,groupData:a},f=x.prototype,m=f.processData,q=f.generatePoints,K={groupPixelWidth:2,dateTimeLabelFormats:{millisecond:["%A, %b %e, %H:%M:%S.%L","%A, %b %e, %H:%M:%S.%L","-%H:%M:%S.%L"],second:["%A, %b %e, %H:%M:%S","%A, %b %e, %H:%M:%S","-%H:%M:%S"],minute:["%A, %b %e, %H:%M","%A, %b %e, %H:%M",
"-%H:%M"],hour:["%A, %b %e, %H:%M","%A, %b %e, %H:%M","-%H:%M"],day:["%A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],week:["Week from %A, %b %e, %Y","%A, %b %e","-%A, %b %e, %Y"],month:["%B %Y","%B","-%B %Y"],year:["%Y","%Y","-%Y"]}},t={line:{},spline:{},area:{},areaspline:{},arearange:{},column:{groupPixelWidth:10},columnrange:{groupPixelWidth:10},candlestick:{groupPixelWidth:10},ohlc:{groupPixelWidth:5}},A=d.defaultDataGroupingUnits=[["millisecond",[1,2,5,10,20,25,50,100,200,500]],["second",[1,2,
5,10,15,30]],["minute",[1,2,5,10,15,30]],["hour",[1,2,3,4,6,8,12]],["day",[1]],["week",[1]],["month",[1,3,6]],["year",null]];f.getDGApproximation=function(){return this.is("arearange")?"range":this.is("ohlc")?"ohlc":this.is("column")?"sum":"average"};f.groupData=a;f.processData=function(){var a=this.chart,b=this.options.dataGrouping,c=!1!==this.allowDG&&b&&B(b.enabled,a.options.isStock),e=this.visible||!a.options.chart.ignoreHiddenSeries,g,d=this.currentDataGrouping,t=!1;this.forceCrop=c;this.groupPixelWidth=
null;this.hasProcessed=!0;c&&!this.requireSorting&&(this.requireSorting=t=!0);c=!1===m.apply(this,arguments)||!c;t&&(this.requireSorting=!1);if(!c){this.destroyGroupedData();c=b.groupAll?this.xData:this.processedXData;var q=b.groupAll?this.yData:this.processedYData,l=a.plotSizeX;a=this.xAxis;var r=a.options.ordinal,y=this.groupPixelWidth=a.getGroupPixelWidth&&a.getGroupPixelWidth();if(y){this.isDirty=g=!0;this.points=null;t=a.getExtremes();var u=t.min;t=t.max;r=r&&a.ordinal&&a.ordinal.getGroupIntervalFactor(u,
t,this)||1;y=y*(t-u)/l*r;l=a.getTimeTicks(n.AdditionsClass.prototype.normalizeTimeTickInterval(y,b.units||A),Math.min(u,c[0]),Math.max(t,c[c.length-1]),a.options.startOfWeek,c,this.closestPointRange);q=f.groupData.apply(this,[c,q,l,b.approximation]);c=q.groupedXData;r=q.groupedYData;var x=0;if(b.smoothed&&c.length){var w=c.length-1;for(c[w]=Math.min(c[w],t);w--&&0<w;)c[w]+=y/2;c[0]=Math.max(c[0],u)}for(w=1;w<l.length;w++)l.info.segmentStarts&&-1!==l.info.segmentStarts.indexOf(w)||(x=Math.max(l[w]-
l[w-1],x));u=l.info;u.gapSize=x;this.closestPointRange=l.info.totalRange;this.groupMap=q.groupMap;if(H(c[0])&&c[0]<a.min&&e){if(!H(a.options.min)&&a.min<=a.dataMin||a.min===a.dataMin)a.min=Math.min(c[0],a.min);a.dataMin=Math.min(c[0],a.dataMin)}b.groupAll&&(b=this.cropData(c,r,a.min,a.max,1),c=b.xData,r=b.yData);this.processedXData=c;this.processedYData=r}else this.groupMap=null;this.hasGroupedData=g;this.currentDataGrouping=u;this.preventGraphAnimation=(d&&d.totalRange)!==(u&&u.totalRange)}};f.destroyGroupedData=
function(){this.groupedData&&(this.groupedData.forEach(function(a,b){a&&(this.groupedData[b]=a.destroy?a.destroy():null)},this),this.groupedData.length=0)};f.generatePoints=function(){q.apply(this);this.destroyGroupedData();this.groupedData=this.hasGroupedData?this.points:null};r(D,"update",function(){if(this.dataGroup)return I(24,!1,this.series.chart),!1});r(v,"headerFormatter",function(a){var b=this.chart,c=b.time,f=a.labelConfig,k=f.series,e=k.tooltipOptions,g=k.options.dataGrouping,d=e.xDateFormat,
m=k.xAxis,t=e[(a.isFooter?"footer":"header")+"Format"];if(m&&"datetime"===m.options.type&&g&&l(f.key)){var q=k.currentDataGrouping;g=g.dateTimeLabelFormats||K.dateTimeLabelFormats;if(q)if(e=g[q.unitName],1===q.count)d=e[0];else{d=e[1];var A=e[2]}else!d&&g&&(d=this.getXDateFormat(f,e,m));d=c.dateFormat(d,f.key);A&&(d+=c.dateFormat(A,f.key+q.totalRange-1));k.chart.styledMode&&(t=this.styledModeFormat(t));a.text=u(t,{point:F(f.point,{key:d}),series:k},b);a.preventDefault()}});r(x,"destroy",f.destroyGroupedData);
r(x,"afterSetOptions",function(a){a=a.options;var b=this.type,f=this.chart.options.plotOptions,k=c[b].dataGrouping,e=this.useCommonDataGrouping&&K;if(t[b]||e)k||(k=z(K,t[b])),a.dataGrouping=z(e,k,f.series&&f.series.dataGrouping,f[b].dataGrouping,this.userOptions.dataGrouping)});r(b,"afterSetScale",function(){this.series.forEach(function(a){a.hasProcessed=!1})});b.prototype.getGroupPixelWidth=function(){var a=this.series,b=a.length,f,c=0,e=!1,g;for(f=b;f--;)(g=a[f].options.dataGrouping)&&(c=Math.max(c,
B(g.groupPixelWidth,K.groupPixelWidth)));for(f=b;f--;)(g=a[f].options.dataGrouping)&&a[f].hasProcessed&&(b=(a[f].processedXData||a[f].data).length,a[f].groupPixelWidth||b>this.chart.plotSizeX/c||b&&g.forced)&&(e=!0);return e?c:0};b.prototype.setDataGrouping=function(a,f){var c;f=B(f,!0);a||(a={forced:!1,units:null});if(this instanceof b)for(c=this.series.length;c--;)this.series[c].update({dataGrouping:a},!1);else this.chart.options.series.forEach(function(b){b.dataGrouping=a},!1);this.ordinal&&(this.ordinal.slope=
void 0);f&&this.chart.redraw()};d.dataGrouping=g;"";return g});G(n,"parts/OHLCSeries.js",[n["parts/Globals.js"],n["parts/Point.js"],n["parts/Utilities.js"]],function(n,d,D){D=D.seriesType;var v=n.seriesTypes;D("ohlc","column",{lineWidth:1,tooltip:{pointFormat:'<span style="color:{point.color}">\u25cf</span> <b> {series.name}</b><br/>Open: {point.open}<br/>High: {point.high}<br/>Low: {point.low}<br/>Close: {point.close}<br/>'},threshold:null,states:{hover:{lineWidth:3}},stickyTracking:!0},{directTouch:!1,
pointArrayMap:["open","high","low","close"],toYData:function(d){return[d.open,d.high,d.low,d.close]},pointValKey:"close",pointAttrToOptions:{stroke:"color","stroke-width":"lineWidth"},init:function(){v.column.prototype.init.apply(this,arguments);this.options.stacking=void 0},pointAttribs:function(d,r){r=v.column.prototype.pointAttribs.call(this,d,r);var n=this.options;delete r.fill;!d.options.color&&n.upColor&&d.open<d.close&&(r.stroke=n.upColor);return r},translate:function(){var d=this,r=d.yAxis,
n=!!d.modifyValue,w=["plotOpen","plotHigh","plotLow","plotClose","yBottom"];v.column.prototype.translate.apply(d);d.points.forEach(function(e){[e.open,e.high,e.low,e.close,e.low].forEach(function(x,v){null!==x&&(n&&(x=d.modifyValue(x)),e[w[v]]=r.toPixels(x,!0))});e.tooltipPos[1]=e.plotHigh+r.pos-d.chart.plotTop})},drawPoints:function(){var d=this,r=d.chart,n=function(d,e,r){d[2]=Math.max(r+e,d[2]);d[5]=Math.min(r-e,d[5])};d.points.forEach(function(w){var e=w.graphic,v=!e;if("undefined"!==typeof w.plotY){e||
(w.graphic=e=r.renderer.path().add(d.group));r.styledMode||e.attr(d.pointAttribs(w,w.selected&&"select"));var x=e.strokeWidth();var D=x%2/2;var u=Math.round(w.plotX)-D;var l=Math.round(w.shapeArgs.width/2);var z=["M",u,Math.round(w.yBottom),"L",u,Math.round(w.plotHigh)];if(null!==w.open){var B=Math.round(w.plotOpen)+D;z.push("M",u,B,"L",u-l,B);n(z,x/2,B)}null!==w.close&&(B=Math.round(w.plotClose)+D,z.push("M",u,B,"L",u+l,B),n(z,x/2,B));e[v?"attr":"animate"]({d:z}).addClass(w.getClassName(),!0)}})},
animate:null},{getClassName:function(){return d.prototype.getClassName.call(this)+(this.open<this.close?" highcharts-point-up":" highcharts-point-down")}});""});G(n,"parts/CandlestickSeries.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,d){var D=d.merge;d=d.seriesType;var v=n.defaultPlotOptions,x=n.seriesTypes;d("candlestick","ohlc",D(v.column,{states:{hover:{lineWidth:2}},tooltip:v.ohlc.tooltip,threshold:null,lineColor:"#000000",lineWidth:1,upColor:"#ffffff",stickyTracking:!0}),{pointAttribs:function(d,
n){var r=x.column.prototype.pointAttribs.call(this,d,n),e=this.options,v=d.open<d.close,D=e.lineColor||this.color;r["stroke-width"]=e.lineWidth;r.fill=d.options.color||(v?e.upColor||this.color:this.color);r.stroke=d.options.lineColor||(v?e.upLineColor||D:D);n&&(d=e.states[n],r.fill=d.color||r.fill,r.stroke=d.lineColor||r.stroke,r["stroke-width"]=d.lineWidth||r["stroke-width"]);return r},drawPoints:function(){var d=this,n=d.chart,v=d.yAxis.reversed;d.points.forEach(function(e){var r=e.graphic,x=!r;
if("undefined"!==typeof e.plotY){r||(e.graphic=r=n.renderer.path().add(d.group));d.chart.styledMode||r.attr(d.pointAttribs(e,e.selected&&"select")).shadow(d.options.shadow);var w=r.strokeWidth()%2/2;var u=Math.round(e.plotX)-w;var l=e.plotOpen;var z=e.plotClose;var B=Math.min(l,z);l=Math.max(l,z);var b=Math.round(e.shapeArgs.width/2);z=v?l!==e.yBottom:Math.round(B)!==Math.round(e.plotHigh);var c=v?Math.round(B)!==Math.round(e.plotHigh):l!==e.yBottom;B=Math.round(B)+w;l=Math.round(l)+w;w=[];w.push("M",
u-b,l,"L",u-b,B,"L",u+b,B,"L",u+b,l,"Z","M",u,B,"L",u,z?Math.round(v?e.yBottom:e.plotHigh):B,"M",u,l,"L",u,c?Math.round(v?e.plotHigh:e.yBottom):l);r[x?"attr":"animate"]({d:w}).addClass(e.getClassName(),!0)}})}});""});G(n,"mixins/on-series.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,d){var D=d.defined,v=d.stableSort,x=n.seriesTypes;return{getPlotBox:function(){return n.Series.prototype.getPlotBox.call(this.options.onSeries&&this.chart.get(this.options.onSeries)||this)},translate:function(){x.column.prototype.translate.apply(this);
var d=this,n=d.options,w=d.chart,e=d.points,I=e.length-1,G,F=n.onSeries;F=F&&w.get(F);n=n.onKey||"y";var u=F&&F.options.step,l=F&&F.points,z=l&&l.length,B=w.inverted,b=d.xAxis,c=d.yAxis,y=0,a;if(F&&F.visible&&z){y=(F.pointXOffset||0)+(F.barW||0)/2;w=F.currentDataGrouping;var g=l[z-1].x+(w?w.totalRange:0);v(e,function(a,b){return a.x-b.x});for(n="plot"+n[0].toUpperCase()+n.substr(1);z--&&e[I];){var f=l[z];w=e[I];w.y=f.y;if(f.x<=w.x&&"undefined"!==typeof f[n]){if(w.x<=g&&(w.plotY=f[n],f.x<w.x&&!u&&
(a=l[z+1])&&"undefined"!==typeof a[n])){var m=(w.x-f.x)/(a.x-f.x);w.plotY+=m*(a[n]-f[n]);w.y+=m*(a.y-f.y)}I--;z++;if(0>I)break}}}e.forEach(function(a,f){a.plotX+=y;if("undefined"===typeof a.plotY||B)0<=a.plotX&&a.plotX<=b.len?B?(a.plotY=b.translate(a.x,0,1,0,1),a.plotX=D(a.y)?c.translate(a.y,0,0,0,1):0):a.plotY=(b.opposite?0:d.yAxis.len)+b.offset:a.shapeArgs={};if((G=e[f-1])&&G.plotX===a.plotX){"undefined"===typeof G.stackIndex&&(G.stackIndex=0);var g=G.stackIndex+1}a.stackIndex=g});this.onSeries=
F}}});G(n,"parts/FlagsSeries.js",[n["parts/Globals.js"],n["parts/Utilities.js"],n["mixins/on-series.js"]],function(n,d,D){function v(b){B[b+"pin"]=function(c,d,a,e,f){var g=f&&f.anchorX;f=f&&f.anchorY;"circle"===b&&e>a&&(c-=Math.round((e-a)/2),a=e);var q=B[b](c,d,a,e);g&&f&&(q.push("M","circle"===b?c+a/2:q[1]+q[4]/2,d>f?d:d+e,"L",g,f),q=q.concat(B.circle(g-1,f-1,2,2)));return q}}var x=d.addEvent,r=d.defined,E=d.isNumber,w=d.merge,e=d.objectEach,I=d.seriesType,G=d.wrap;d=n.noop;var F=n.Renderer,u=
n.Series,l=n.TrackerMixin,z=n.VMLRenderer,B=n.SVGRenderer.prototype.symbols;I("flags","column",{pointRange:0,allowOverlapX:!1,shape:"flag",stackDistance:12,textAlign:"center",tooltip:{pointFormat:"{point.text}<br/>"},threshold:null,y:-30,fillColor:"#ffffff",lineWidth:1,states:{hover:{lineColor:"#000000",fillColor:"#ccd6eb"}},style:{fontSize:"11px",fontWeight:"bold"}},{sorted:!1,noSharedTooltip:!0,allowDG:!1,takeOrdinalPosition:!1,trackerGroups:["markerGroup"],forceCrop:!0,init:u.prototype.init,pointAttribs:function(b,
c){var d=this.options,a=b&&b.color||this.color,e=d.lineColor,f=b&&b.lineWidth;b=b&&b.fillColor||d.fillColor;c&&(b=d.states[c].fillColor,e=d.states[c].lineColor,f=d.states[c].lineWidth);return{fill:b||a,stroke:e||a,"stroke-width":f||d.lineWidth||0}},translate:D.translate,getPlotBox:D.getPlotBox,drawPoints:function(){var b=this.points,c=this.chart,d=c.renderer,a=c.inverted,g=this.options,f=g.y,m,q=this.yAxis,l={},t=[];for(m=b.length;m--;){var A=b[m];var k=(a?A.plotY:A.plotX)>this.xAxis.len;var h=A.plotX;
var p=A.stackIndex;var C=A.options.shape||g.shape;var u=A.plotY;"undefined"!==typeof u&&(u=A.plotY+f-("undefined"!==typeof p&&p*g.stackDistance));A.anchorX=p?void 0:A.plotX;var v=p?void 0:A.plotY;var x="flag"!==C;p=A.graphic;"undefined"!==typeof u&&0<=h&&!k?(p||(p=A.graphic=d.label("",null,null,C,null,null,g.useHTML),c.styledMode||p.attr(this.pointAttribs(A)).css(w(g.style,A.style)),p.attr({align:x?"center":"left",width:g.width,height:g.height,"text-align":g.textAlign}).addClass("highcharts-point").add(this.markerGroup),
A.graphic.div&&(A.graphic.div.point=A),c.styledMode||p.shadow(g.shadow),p.isNew=!0),0<h&&(h-=p.strokeWidth()%2),C={y:u,anchorY:v},g.allowOverlapX&&(C.x=h,C.anchorX=A.anchorX),p.attr({text:A.options.title||g.title||"A"})[p.isNew?"attr":"animate"](C),g.allowOverlapX||(l[A.plotX]?l[A.plotX].size=Math.max(l[A.plotX].size,p.width):l[A.plotX]={align:x?.5:0,size:p.width,target:h,anchorX:h}),A.tooltipPos=[h,u+q.pos-c.plotTop]):p&&(A.graphic=p.destroy())}g.allowOverlapX||(e(l,function(a){a.plotX=a.anchorX;
t.push(a)}),n.distribute(t,a?q.len:this.xAxis.len,100),b.forEach(function(a){var b=a.graphic&&l[a.plotX];b&&(a.graphic[a.graphic.isNew?"attr":"animate"]({x:b.pos+b.align*b.size,anchorX:a.anchorX}),r(b.pos)?a.graphic.isNew=!1:(a.graphic.attr({x:-9999,anchorX:-9999}),a.graphic.isNew=!0))}));g.useHTML&&G(this.markerGroup,"on",function(a){return n.SVGElement.prototype.on.apply(a.apply(this,[].slice.call(arguments,1)),[].slice.call(arguments,1))})},drawTracker:function(){var b=this.points;l.drawTrackerPoint.apply(this);
b.forEach(function(c){var d=c.graphic;d&&x(d.element,"mouseover",function(){0<c.stackIndex&&!c.raised&&(c._y=d.y,d.attr({y:c._y-8}),c.raised=!0);b.forEach(function(a){a!==c&&a.raised&&a.graphic&&(a.graphic.attr({y:a._y}),a.raised=!1)})})})},animate:function(b){b&&this.setClip()},setClip:function(){u.prototype.setClip.apply(this,arguments);!1!==this.options.clip&&this.sharedClipKey&&this.markerGroup.clip(this.chart[this.sharedClipKey])},buildKDTree:d,invertGroups:d},{isValid:function(){return E(this.y)||
"undefined"===typeof this.y}});B.flag=function(b,c,d,a,e){var f=e&&e.anchorX||b;e=e&&e.anchorY||c;return B.circle(f-1,e-1,2,2).concat(["M",f,e,"L",b,c+a,b,c,b+d,c,b+d,c+a,b,c+a,"Z"])};v("circle");v("square");F===z&&["circlepin","flag","squarepin"].forEach(function(b){z.prototype.symbols[b]=B[b]});""});G(n,"parts/RangeSelector.js",[n["parts/Globals.js"],n["parts/Utilities.js"]],function(n,d){function D(a){this.init(a)}var v=d.addEvent,x=d.createElement,r=d.css,E=d.defined,w=d.destroyObjectProperties,
e=d.discardElement,I=d.extend,G=d.fireEvent,F=d.isNumber,u=d.merge,l=d.objectEach,z=d.pick,B=d.pInt,b=d.splat,c=n.Axis;d=n.Chart;var y=n.defaultOptions;I(y,{rangeSelector:{verticalAlign:"top",buttonTheme:{width:28,height:18,padding:2,zIndex:7},floating:!1,x:0,y:0,height:void 0,inputPosition:{align:"right",x:0,y:0},buttonPosition:{align:"left",x:0,y:0},labelStyle:{color:"#666666"}}});y.lang=u(y.lang,{rangeSelectorZoom:"Zoom",rangeSelectorFrom:"From",rangeSelectorTo:"To"});D.prototype={clickButton:function(a,
d){var f=this.chart,e=this.buttonOptions[a],g=f.xAxis[0],l=f.scroller&&f.scroller.getUnionExtremes()||g||{},t=l.dataMin,A=l.dataMax,k=g&&Math.round(Math.min(g.max,z(A,g.max))),h=e.type;l=e._range;var p,n=e.dataGrouping;if(null!==t&&null!==A){f.fixedRange=l;n&&(this.forcedDataGrouping=!0,c.prototype.setDataGrouping.call(g||{chart:this.chart},n,!1),this.frozenStates=e.preserveDataGrouping);if("month"===h||"year"===h)if(g){h={range:e,max:k,chart:f,dataMin:t,dataMax:A};var r=g.minFromRange.call(h);F(h.newMax)&&
(k=h.newMax)}else l=e;else if(l)r=Math.max(k-l,t),k=Math.min(r+l,A);else if("ytd"===h)if(g)"undefined"===typeof A&&(t=Number.MAX_VALUE,A=Number.MIN_VALUE,f.series.forEach(function(a){a=a.xData;t=Math.min(a[0],t);A=Math.max(a[a.length-1],A)}),d=!1),k=this.getYTDExtremes(A,t,f.time.useUTC),r=p=k.min,k=k.max;else{this.deferredYTDClick=a;return}else"all"===h&&g&&(r=t,k=A);r+=e._offsetMin;k+=e._offsetMax;this.setSelected(a);if(g)g.setExtremes(r,k,z(d,1),null,{trigger:"rangeSelectorButton",rangeSelectorButton:e});
else{var u=b(f.options.xAxis)[0];var x=u.range;u.range=l;var w=u.min;u.min=p;v(f,"load",function(){u.range=x;u.min=w})}}},setSelected:function(a){this.selected=this.options.selected=a},defaultButtons:[{type:"month",count:1,text:"1m"},{type:"month",count:3,text:"3m"},{type:"month",count:6,text:"6m"},{type:"ytd",text:"YTD"},{type:"year",count:1,text:"1y"},{type:"all",text:"All"}],init:function(a){var b=this,f=a.options.rangeSelector,c=f.buttons||[].concat(b.defaultButtons),d=f.selected,e=function(){var a=
b.minInput,f=b.maxInput;a&&a.blur&&G(a,"blur");f&&f.blur&&G(f,"blur")};b.chart=a;b.options=f;b.buttons=[];b.buttonOptions=c;this.unMouseDown=v(a.container,"mousedown",e);this.unResize=v(a,"resize",e);c.forEach(b.computeButtonRange);"undefined"!==typeof d&&c[d]&&this.clickButton(d,!1);v(a,"load",function(){a.xAxis&&a.xAxis[0]&&v(a.xAxis[0],"setExtremes",function(f){this.max-this.min!==a.fixedRange&&"rangeSelectorButton"!==f.trigger&&"updatedData"!==f.trigger&&b.forcedDataGrouping&&!b.frozenStates&&
this.setDataGrouping(!1,!1)})})},updateButtonStates:function(){var a=this,b=this.chart,f=b.xAxis[0],c=Math.round(f.max-f.min),d=!f.hasVisibleSeries,e=b.scroller&&b.scroller.getUnionExtremes()||f,t=e.dataMin,l=e.dataMax;b=a.getYTDExtremes(l,t,b.time.useUTC);var k=b.min,h=b.max,p=a.selected,n=F(p),r=a.options.allButtonsEnabled,u=a.buttons;a.buttonOptions.forEach(function(b,e){var g=b._range,m=b.type,q=b.count||1,A=u[e],C=0,v=b._offsetMax-b._offsetMin;b=e===p;var x=g>l-t,w=g<f.minRange,y=!1,z=!1;g=g===
c;("month"===m||"year"===m)&&c+36E5>=864E5*{month:28,year:365}[m]*q-v&&c-36E5<=864E5*{month:31,year:366}[m]*q+v?g=!0:"ytd"===m?(g=h-k+v===c,y=!b):"all"===m&&(g=f.max-f.min>=l-t,z=!b&&n&&g);m=!r&&(x||w||z||d);q=b&&g||g&&!n&&!y||b&&a.frozenStates;m?C=3:q&&(n=!0,C=2);A.state!==C&&(A.setState(C),0===C&&p===e&&a.setSelected(null))})},computeButtonRange:function(a){var b=a.type,f=a.count||1,c={millisecond:1,second:1E3,minute:6E4,hour:36E5,day:864E5,week:6048E5};if(c[b])a._range=c[b]*f;else if("month"===
b||"year"===b)a._range=864E5*{month:30,year:365}[b]*f;a._offsetMin=z(a.offsetMin,0);a._offsetMax=z(a.offsetMax,0);a._range+=a._offsetMax-a._offsetMin},setInputValue:function(a,b){var f=this.chart.options.rangeSelector,c=this.chart.time,d=this[a+"Input"];E(b)&&(d.previousValue=d.HCTime,d.HCTime=b);d.value=c.dateFormat(f.inputEditDateFormat||"%Y-%m-%d",d.HCTime);this[a+"DateBox"].attr({text:c.dateFormat(f.inputDateFormat||"%b %e, %Y",d.HCTime)})},showInput:function(a){var b=this.inputGroup,f=this[a+
"DateBox"];r(this[a+"Input"],{left:b.translateX+f.x+"px",top:b.translateY+"px",width:f.width-2+"px",height:f.height-2+"px",border:"2px solid silver"})},hideInput:function(a){r(this[a+"Input"],{border:0,width:"1px",height:"1px"});this.setInputValue(a)},drawInput:function(a){function b(){var a=h.value,b=(t.inputDateParser||Date.parse)(a),d=c.xAxis[0],e=c.scroller&&c.scroller.xAxis?c.scroller.xAxis:d,g=e.dataMin;e=e.dataMax;b!==h.previousValue&&(h.previousValue=b,F(b)||(b=a.split("-"),b=Date.UTC(B(b[0]),
B(b[1])-1,B(b[2]))),F(b)&&(c.time.useUTC||(b+=6E4*(new Date).getTimezoneOffset()),k?b>f.maxInput.HCTime?b=void 0:b<g&&(b=g):b<f.minInput.HCTime?b=void 0:b>e&&(b=e),"undefined"!==typeof b&&d.setExtremes(k?b:d.min,k?d.max:b,void 0,void 0,{trigger:"rangeSelectorInput"})))}var f=this,c=f.chart,d=c.renderer.style||{},e=c.renderer,t=c.options.rangeSelector,l=f.div,k="min"===a,h,p,C=this.inputGroup;this[a+"Label"]=p=e.label(y.lang[k?"rangeSelectorFrom":"rangeSelectorTo"],this.inputGroup.offset).addClass("highcharts-range-label").attr({padding:2}).add(C);
C.offset+=p.width+5;this[a+"DateBox"]=e=e.label("",C.offset).addClass("highcharts-range-input").attr({padding:2,width:t.inputBoxWidth||90,height:t.inputBoxHeight||17,"text-align":"center"}).on("click",function(){f.showInput(a);f[a+"Input"].focus()});c.styledMode||e.attr({stroke:t.inputBoxBorderColor||"#cccccc","stroke-width":1});e.add(C);C.offset+=e.width+(k?10:0);this[a+"Input"]=h=x("input",{name:a,className:"highcharts-range-selector",type:"text"},{top:c.plotTop+"px"},l);c.styledMode||(p.css(u(d,
t.labelStyle)),e.css(u({color:"#333333"},d,t.inputStyle)),r(h,I({position:"absolute",border:0,width:"1px",height:"1px",padding:0,textAlign:"center",fontSize:d.fontSize,fontFamily:d.fontFamily,top:"-9999em"},t.inputStyle)));h.onfocus=function(){f.showInput(a)};h.onblur=function(){h===n.doc.activeElement&&b();f.hideInput(a);h.blur()};h.onchange=b;h.onkeypress=function(a){13===a.keyCode&&b()}},getPosition:function(){var a=this.chart,b=a.options.rangeSelector;a="top"===b.verticalAlign?a.plotTop-a.axisOffset[0]:
0;return{buttonTop:a+b.buttonPosition.y,inputTop:a+b.inputPosition.y-10}},getYTDExtremes:function(a,b,c){var f=this.chart.time,d=new f.Date(a),e=f.get("FullYear",d);c=c?f.Date.UTC(e,0,1):+new f.Date(e,0,1);b=Math.max(b||0,c);d=d.getTime();return{max:Math.min(a||d,d),min:b}},render:function(a,b){var c=this,d=c.chart,e=d.renderer,g=d.container,t=d.options,l=t.exporting&&!1!==t.exporting.enabled&&t.navigation&&t.navigation.buttonOptions,k=y.lang,h=c.div,p=t.rangeSelector,n=z(t.chart.style&&t.chart.style.zIndex,
0)+1;t=p.floating;var r=c.buttons;h=c.inputGroup;var u=p.buttonTheme,v=p.buttonPosition,w=p.inputPosition,B=p.inputEnabled,D=u&&u.states,E=d.plotLeft,F=c.buttonGroup,I,G=c.options.verticalAlign,H=d.legend,O=H&&H.options,P=v.y,N=w.y,Q=d.hasLoaded,R=Q?"animate":"attr",M=0,L=0;if(!1!==p.enabled){c.rendered||(c.group=I=e.g("range-selector-group").attr({zIndex:7}).add(),c.buttonGroup=F=e.g("range-selector-buttons").add(I),c.zoomText=e.text(k.rangeSelectorZoom,0,15).add(F),d.styledMode||(c.zoomText.css(p.labelStyle),
u["stroke-width"]=z(u["stroke-width"],0)),c.buttonOptions.forEach(function(a,b){r[b]=e.button(a.text,0,0,function(d){var e=a.events&&a.events.click,f;e&&(f=e.call(a,d));!1!==f&&c.clickButton(b);c.isActive=!0},u,D&&D.hover,D&&D.select,D&&D.disabled).attr({"text-align":"center"}).add(F)}),!1!==B&&(c.div=h=x("div",null,{position:"relative",height:0,zIndex:n}),g.parentNode.insertBefore(h,g),c.inputGroup=h=e.g("input-group").add(I),h.offset=0,c.drawInput("min"),c.drawInput("max")));c.zoomText[R]({x:z(E+
v.x,E)});var S=z(E+v.x,E)+c.zoomText.getBBox().width+5;c.buttonOptions.forEach(function(a,b){r[b][R]({x:S});S+=r[b].width+z(p.buttonSpacing,5)});E=d.plotLeft-d.spacing[3];c.updateButtonStates();l&&this.titleCollision(d)&&"top"===G&&"right"===v.align&&v.y+F.getBBox().height-12<(l.y||0)+l.height&&(M=-40);g=v.x-d.spacing[3];"right"===v.align?g+=M-E:"center"===v.align&&(g-=E/2);F.align({y:v.y,width:F.getBBox().width,align:v.align,x:g},!0,d.spacingBox);c.group.placed=Q;c.buttonGroup.placed=Q;!1!==B&&(M=
l&&this.titleCollision(d)&&"top"===G&&"right"===w.align&&w.y-h.getBBox().height-12<(l.y||0)+l.height+d.spacing[0]?-40:0,"left"===w.align?g=E:"right"===w.align&&(g=-Math.max(d.axisOffset[1],-M)),h.align({y:w.y,width:h.getBBox().width,align:w.align,x:w.x+g-2},!0,d.spacingBox),l=h.alignAttr.translateX+h.alignOptions.x-M+h.getBBox().x+2,g=h.alignOptions.width,k=F.alignAttr.translateX+F.getBBox().x,E=F.getBBox().width+20,(w.align===v.align||k+E>l&&l+g>k&&P<N+h.getBBox().height)&&h.attr({translateX:h.alignAttr.translateX+
(d.axisOffset[1]>=-M?0:-M),translateY:h.alignAttr.translateY+F.getBBox().height+10}),c.setInputValue("min",a),c.setInputValue("max",b),c.inputGroup.placed=Q);c.group.align({verticalAlign:G},!0,d.spacingBox);a=c.group.getBBox().height+20;b=c.group.alignAttr.translateY;"bottom"===G&&(H=O&&"bottom"===O.verticalAlign&&O.enabled&&!O.floating?H.legendHeight+z(O.margin,10):0,a=a+H-20,L=b-a-(t?0:p.y)-(d.titleOffset?d.titleOffset[2]:0)-10);if("top"===G)t&&(L=0),d.titleOffset&&d.titleOffset[0]&&(L=d.titleOffset[0]),
L+=d.margin[0]-d.spacing[0]||0;else if("middle"===G)if(N===P)L=0>N?b+void 0:b;else if(N||P)L=0>N||0>P?L-Math.min(N,P):b-a+NaN;c.group.translate(p.x,p.y+Math.floor(L));!1!==B&&(c.minInput.style.marginTop=c.group.translateY+"px",c.maxInput.style.marginTop=c.group.translateY+"px");c.rendered=!0}},getHeight:function(){var a=this.options,b=this.group,c=a.y,d=a.buttonPosition.y,e=a.inputPosition.y;if(a.height)return a.height;a=b?b.getBBox(!0).height+13+c:0;b=Math.min(e,d);if(0>e&&0>d||0<e&&0<d)a+=Math.abs(b);
return a},titleCollision:function(a){return!(a.options.title.text||a.options.subtitle.text)},update:function(a){var b=this.chart;u(!0,b.options.rangeSelector,a);this.destroy();this.init(b);b.rangeSelector.render()},destroy:function(){var a=this,b=a.minInput,c=a.maxInput;a.unMouseDown();a.unResize();w(a.buttons);b&&(b.onfocus=b.onblur=b.onchange=null);c&&(c.onfocus=c.onblur=c.onchange=null);l(a,function(b,c){b&&"chart"!==c&&(b.destroy?b.destroy():b.nodeType&&e(this[c]));b!==D.prototype[c]&&(a[c]=null)},
this)}};c.prototype.minFromRange=function(){var a=this.range,b=a.type,c=this.max,d=this.chart.time,e=function(a,c){var e="year"===b?"FullYear":"Month",f=new d.Date(a),k=d.get(e,f);d.set(e,f,k+c);k===d.get(e,f)&&d.set("Date",f,0);return f.getTime()-a};if(F(a)){var l=c-a;var t=a}else l=c+e(c,-a.count),this.chart&&(this.chart.fixedRange=c-l);var n=z(this.dataMin,Number.MIN_VALUE);F(l)||(l=n);l<=n&&(l=n,"undefined"===typeof t&&(t=e(l,a.count)),this.newMax=Math.min(l+t,this.dataMax));F(c)||(l=void 0);
return l};n.RangeSelector||(v(d,"afterGetContainer",function(){this.options.rangeSelector.enabled&&(this.rangeSelector=new D(this))}),v(d,"beforeRender",function(){var a=this.axes,b=this.rangeSelector;b&&(F(b.deferredYTDClick)&&(b.clickButton(b.deferredYTDClick),delete b.deferredYTDClick),a.forEach(function(a){a.updateNames();a.setScale()}),this.getAxisMargins(),b.render(),a=b.options.verticalAlign,b.options.floating||("bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0)))}),
v(d,"update",function(a){var b=a.options.rangeSelector;a=this.rangeSelector;var c=this.extraBottomMargin,d=this.extraTopMargin;b&&b.enabled&&!E(a)&&(this.options.rangeSelector.enabled=!0,this.rangeSelector=new D(this));this.extraTopMargin=this.extraBottomMargin=!1;a&&(a.render(),b=b&&b.verticalAlign||a.options&&a.options.verticalAlign,a.options.floating||("bottom"===b?this.extraBottomMargin=!0:"middle"!==b&&(this.extraTopMargin=!0)),this.extraBottomMargin!==c||this.extraTopMargin!==d)&&(this.isDirtyBox=
!0)}),v(d,"render",function(){var a=this.rangeSelector;a&&!a.options.floating&&(a.render(),a=a.options.verticalAlign,"bottom"===a?this.extraBottomMargin=!0:"middle"!==a&&(this.extraTopMargin=!0))}),v(d,"getMargins",function(){var a=this.rangeSelector;a&&(a=a.getHeight(),this.extraTopMargin&&(this.plotTop+=a),this.extraBottomMargin&&(this.marginBottom+=a))}),d.prototype.callbacks.push(function(a){function b(){c=a.xAxis[0].getExtremes();F(c.min)&&d.render(c.min,c.max)}var c,d=a.rangeSelector;if(d){var e=
v(a.xAxis[0],"afterSetExtremes",function(a){d.render(a.min,a.max)});var l=v(a,"redraw",b);b()}v(a,"destroy",function(){d&&(l(),e())})}),n.RangeSelector=D)});G(n,"parts/StockChart.js",[n["parts/Axis.js"],n["parts/Globals.js"],n["parts/Point.js"],n["parts/Utilities.js"]],function(n,d,D,v){var x=v.addEvent,r=v.arrayMax,E=v.arrayMin,w=v.clamp,e=v.defined,G=v.extend,I=v.find,F=v.format,u=v.isNumber,l=v.isString,z=v.merge,B=v.pick,b=v.splat,c=d.Chart;v=d.Renderer;var y=d.Series,a=d.SVGRenderer,g=d.VMLRenderer,
f=y.prototype,m=f.init,q=f.processData,K=D.prototype.tooltipFormatter;d.StockChart=d.stockChart=function(a,e,f){var k=l(a)||a.nodeName,g=arguments[k?1:0],t=g,n=g.series,m=d.getOptions(),q,r=B(g.navigator&&g.navigator.enabled,m.navigator.enabled,!0);g.xAxis=b(g.xAxis||{}).map(function(a,b){return z({minPadding:0,maxPadding:0,overscroll:0,ordinal:!0,title:{text:null},labels:{overflow:"justify"},showLastLabel:!0},m.xAxis,m.xAxis&&m.xAxis[b],a,{type:"datetime",categories:null},r?{startOnTick:!1,endOnTick:!1}:
null)});g.yAxis=b(g.yAxis||{}).map(function(a,b){q=B(a.opposite,!0);return z({labels:{y:-2},opposite:q,showLastLabel:!(!a.categories&&"category"!==a.type),title:{text:null}},m.yAxis,m.yAxis&&m.yAxis[b],a)});g.series=null;g=z({chart:{panning:{enabled:!0,type:"x"},pinchType:"x"},navigator:{enabled:r},scrollbar:{enabled:B(m.scrollbar.enabled,!0)},rangeSelector:{enabled:B(m.rangeSelector.enabled,!0)},title:{text:null},tooltip:{split:B(m.tooltip.split,!0),crosshairs:!0},legend:{enabled:!1}},g,{isStock:!0});
g.series=t.series=n;return k?new c(a,g,f):new c(g,e)};x(y,"setOptions",function(a){var b;this.chart.options.isStock&&(this.is("column")||this.is("columnrange")?b={borderWidth:0,shadow:!1}:this.is("scatter")||this.is("sma")||(b={marker:{enabled:!1,radius:2}}),b&&(a.plotOptions[this.type]=z(a.plotOptions[this.type],b)))});x(n,"autoLabelAlign",function(a){var b=this.chart,c=this.options;b=b._labelPanes=b._labelPanes||{};var d=this.options.labels;this.chart.options.isStock&&"yAxis"===this.coll&&(c=c.top+
","+c.height,!b[c]&&d.enabled&&(15===d.x&&(d.x=0),"undefined"===typeof d.align&&(d.align="right"),b[c]=this,a.align="right",a.preventDefault()))});x(n,"destroy",function(){var a=this.chart,b=this.options&&this.options.top+","+this.options.height;b&&a._labelPanes&&a._labelPanes[b]===this&&delete a._labelPanes[b]});x(n,"getPlotLinePath",function(a){function b(a){var b="xAxis"===a?"yAxis":"xAxis";a=c.options[b];return u(a)?[f[b][a]]:l(a)?[f.get(a)]:d.map(function(a){return a[b]})}var c=this,d=this.isLinked&&
!this.series?this.linkedParent.series:this.series,f=c.chart,g=f.renderer,t=c.left,m=c.top,n,q,r,v,x=[],y=[],z=a.translatedValue,D=a.value,E=a.force;if(f.options.isStock&&!1!==a.acrossPanes&&"xAxis"===c.coll||"yAxis"===c.coll){a.preventDefault();y=b(c.coll);var F=c.isXAxis?f.yAxis:f.xAxis;F.forEach(function(a){if(e(a.options.id)?-1===a.options.id.indexOf("navigator"):1){var b=a.isXAxis?"yAxis":"xAxis";b=e(a.options[b])?f[b][a.options[b]]:f[b][0];c===b&&y.push(a)}});var G=y.length?[]:[c.isXAxis?f.yAxis[0]:
f.xAxis[0]];y.forEach(function(a){-1!==G.indexOf(a)||I(G,function(b){return b.pos===a.pos&&b.len===a.len})||G.push(a)});var H=B(z,c.translate(D,null,null,a.old));u(H)&&(c.horiz?G.forEach(function(a){var b;q=a.pos;v=q+a.len;n=r=Math.round(H+c.transB);"pass"!==E&&(n<t||n>t+c.width)&&(E?n=r=w(n,t,t+c.width):b=!0);b||x.push("M",n,q,"L",r,v)}):G.forEach(function(a){var b;n=a.pos;r=n+a.len;q=v=Math.round(m+c.height-H);"pass"!==E&&(q<m||q>m+c.height)&&(E?q=v=w(q,m,m+c.height):b=!0);b||x.push("M",n,q,"L",
r,v)}));a.path=0<x.length?g.crispPolyLine(x,a.lineWidth||1):null}});a.prototype.crispPolyLine=function(a,b){var c;for(c=0;c<a.length;c+=6)a[c+1]===a[c+4]&&(a[c+1]=a[c+4]=Math.round(a[c+1])-b%2/2),a[c+2]===a[c+5]&&(a[c+2]=a[c+5]=Math.round(a[c+2])+b%2/2);return a};v===g&&(g.prototype.crispPolyLine=a.prototype.crispPolyLine);x(n,"afterHideCrosshair",function(){this.crossLabel&&(this.crossLabel=this.crossLabel.hide())});x(n,"afterDrawCrosshair",function(a){var b,c;if(e(this.crosshair.label)&&this.crosshair.label.enabled&&
this.cross){var d=this.chart,f=this.logarithmic,g=this.options.crosshair.label,l=this.horiz,t=this.opposite,n=this.left,m=this.top,q=this.crossLabel,r=g.format,u="",v="inside"===this.options.tickPosition,w=!1!==this.crosshair.snap,x=0,y=a.e||this.cross&&this.cross.e,z=a.point;a=this.min;var D=this.max;f&&(a=f.lin2log(a),D=f.lin2log(D));f=l?"center":t?"right"===this.labelAlign?"right":"left":"left"===this.labelAlign?"left":"center";q||(q=this.crossLabel=d.renderer.label(null,null,null,g.shape||"callout").addClass("highcharts-crosshair-label"+
(this.series[0]&&" highcharts-color-"+this.series[0].colorIndex)).attr({align:g.align||f,padding:B(g.padding,8),r:B(g.borderRadius,3),zIndex:2}).add(this.labelGroup),d.styledMode||q.attr({fill:g.backgroundColor||this.series[0]&&this.series[0].color||"#666666",stroke:g.borderColor||"","stroke-width":g.borderWidth||0}).css(G({color:"#ffffff",fontWeight:"normal",fontSize:"11px",textAlign:"center"},g.style)));l?(f=w?z.plotX+n:y.chartX,m+=t?0:this.height):(f=t?this.width+n:0,m=w?z.plotY+m:y.chartY);r||
g.formatter||(this.dateTime&&(u="%b %d, %Y"),r="{value"+(u?":"+u:"")+"}");u=w?z[this.isXAxis?"x":"y"]:this.toValue(l?y.chartX:y.chartY);q.attr({text:r?F(r,{value:u},d):g.formatter.call(this,u),x:f,y:m,visibility:u<a||u>D?"hidden":"visible"});g=q.getBBox();if(l){if(v&&!t||!v&&t)m=q.y-g.height}else m=q.y-g.height/2;l?(b=n-g.x,c=n+this.width-g.x):(b="left"===this.labelAlign?n:0,c="right"===this.labelAlign?n+this.width:d.chartWidth);q.translateX<b&&(x=b-q.translateX);q.translateX+g.width>=c&&(x=-(q.translateX+
g.width-c));q.attr({x:f+x,y:m,anchorX:l?f:this.opposite?0:d.chartWidth,anchorY:l?this.opposite?d.chartHeight:0:m+g.height/2})}});f.init=function(){m.apply(this,arguments);this.setCompare(this.options.compare)};f.setCompare=function(a){this.modifyValue="value"===a||"percent"===a?function(b,c){var d=this.compareValue;return"undefined"!==typeof b&&"undefined"!==typeof d?(b="value"===a?b-d:b/d*100-(100===this.options.compareBase?0:100),c&&(c.change=b),b):0}:null;this.userOptions.compare=a;this.chart.hasRendered&&
(this.isDirty=!0)};f.processData=function(a){var b,c=-1,d=!0===this.options.compareStart?0:1;q.apply(this,arguments);if(this.xAxis&&this.processedYData){var e=this.processedXData;var f=this.processedYData;var g=f.length;this.pointArrayMap&&(c=this.pointArrayMap.indexOf(this.options.pointValKey||this.pointValKey||"y"));for(b=0;b<g-d;b++){var l=f[b]&&-1<c?f[b][c]:f[b];if(u(l)&&e[b+d]>=this.xAxis.min&&0!==l){this.compareValue=l;break}}}};x(y,"afterGetExtremes",function(a){a=a.dataExtremes;if(this.modifyValue&&
a){var b=[this.modifyValue(a.dataMin),this.modifyValue(a.dataMax)];a.dataMin=E(b);a.dataMax=r(b)}});n.prototype.setCompare=function(a,b){this.isXAxis||(this.series.forEach(function(b){b.setCompare(a)}),B(b,!0)&&this.chart.redraw())};D.prototype.tooltipFormatter=function(a){var b=this.series.chart.numberFormatter;a=a.replace("{point.change}",(0<this.change?"+":"")+b(this.change,B(this.series.tooltipOptions.changeDecimals,2)));return K.apply(this,[a])};x(y,"render",function(){var a=this.chart;if(!(a.is3d&&
a.is3d()||a.polar)&&this.xAxis&&!this.xAxis.isRadial){var b=this.yAxis.len;if(this.xAxis.axisLine){var c=a.plotTop+a.plotHeight-this.yAxis.pos-this.yAxis.len,d=Math.floor(this.xAxis.axisLine.strokeWidth()/2);0<=c&&(b-=Math.max(d-c,0))}!this.clipBox&&this.animate?(this.clipBox=z(a.clipBox),this.clipBox.width=this.xAxis.len,this.clipBox.height=b):a[this.sharedClipKey]&&(a[this.sharedClipKey].animate({width:this.xAxis.len,height:b}),a[this.sharedClipKey+"m"]&&a[this.sharedClipKey+"m"].animate({width:this.xAxis.len}))}});
x(c,"update",function(a){a=a.options;"scrollbar"in a&&this.navigator&&(z(!0,this.options.scrollbar,a.scrollbar),this.navigator.update({},!1),delete a.scrollbar)})});G(n,"masters/modules/stock.src.js",[],function(){})});
//# sourceMappingURL=stock.js.map