/*
 Highstock JS v8.0.4 (2020-04-02)

 Advanced Highstock tools

 (c) 2010-2019 Highsoft AS
 Author: Torstein Honsi

 License: www.highcharts.com/license
*/
(function(g){"object"===typeof module&&module.exports?(g["default"]=g,module.exports=g):"function"===typeof define&&define.amd?define("highcharts/modules/stock-tools",["highcharts","highcharts/modules/stock"],function(r){g(r);g.Highcharts=r;return g}):g("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(g){function r(t,h,n,g){t.hasOwnProperty(h)||(t[h]=g.apply(null,n))}g=g?g._modules:{};r(g,"modules/stock-tools-bindings.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(g,h){var n=
h.correctFloat,t=h.defined,r=h.extend,k=h.fireEvent,y=h.isNumber,l=h.merge,w=h.pick,v=h.uniqueKey,c=g.NavigationBindings.prototype.utils;c.addFlagFromForm=function(a){return function(b){var d=this,f=d.chart,e=f.stockTools,m=c.getFieldType;b=c.attractToPoint(b,f);var x={type:"flags",onSeries:b.series.id,shape:a,data:[{x:b.x,y:b.y}],point:{events:{click:function(){var a=this,b=a.options;k(d,"showPopup",{point:a,formType:"annotation-toolbar",options:{langKey:"flags",type:"flags",title:[b.title,m(b.title)],
name:[b.name,m(b.name)]},onSubmit:function(b){"remove"===b.actionType?a.remove():a.update(d.fieldsToOptions(b.fields,{}))}})}}}};e&&e.guiEnabled||f.addSeries(x);k(d,"showPopup",{formType:"flag",options:{langKey:"flags",type:"flags",title:["A",m("A")],name:["Flag A",m("Flag A")]},onSubmit:function(a){d.fieldsToOptions(a.fields,x.data[0]);f.addSeries(x)}})}};c.manageIndicators=function(a){var b=this.chart,d={linkedTo:a.linkedTo,type:a.type},f=["ad","cmf","mfi","vbp","vwap"],e="ad atr cci cmf macd mfi roc rsi ao aroon aroonoscillator trix apo dpo ppo natr williamsr stochastic slowstochastic linearRegression linearRegressionSlope linearRegressionIntercept linearRegressionAngle".split(" ");
if("edit"===a.actionType)this.fieldsToOptions(a.fields,d),(a=b.get(a.seriesId))&&a.update(d,!1);else if("remove"===a.actionType){if(a=b.get(a.seriesId)){var m=a.yAxis;a.linkedSeries&&a.linkedSeries.forEach(function(a){a.remove(!1)});a.remove(!1);0<=e.indexOf(a.type)&&(m.remove(!1),this.resizeYAxes())}}else d.id=v(),this.fieldsToOptions(a.fields,d),0<=e.indexOf(a.type)?(m=b.addAxis({id:v(),offset:0,opposite:!0,title:{text:""},tickPixelInterval:40,showLastLabel:!1,labels:{align:"left",y:-2}},!1,!1),
d.yAxis=m.options.id,this.resizeYAxes()):d.yAxis=b.get(a.linkedTo).options.yAxis,0<=f.indexOf(a.type)&&(d.params.volumeSeriesID=b.series.filter(function(a){return"column"===a.options.type})[0].options.id),b.addSeries(d,!1);k(this,"deselectButton",{button:this.selectedButtonElement});b.redraw()};c.updateHeight=function(a,b){b.update({typeOptions:{height:this.chart.pointer.getCoordinates(a).yAxis[0].value-b.options.typeOptions.points[1].y}})};c.attractToPoint=function(a,b){a=b.pointer.getCoordinates(a);
var d=a.xAxis[0].value;a=a.yAxis[0].value;var f=Number.MAX_VALUE,e;b.series.forEach(function(a){a.points.forEach(function(a){a&&f>Math.abs(a.x-d)&&(f=Math.abs(a.x-d),e=a)})});return{x:e.x,y:e.y,below:a<e.y,series:e.series,xAxis:e.series.xAxis.index||0,yAxis:e.series.yAxis.index||0}};c.isNotNavigatorYAxis=function(a){return"highcharts-navigator-yaxis"!==a.userOptions.className};c.updateNthPoint=function(a){return function(b,d){var f=d.options.typeOptions;b=this.chart.pointer.getCoordinates(b);var e=
b.xAxis[0].value,m=b.yAxis[0].value;f.points.forEach(function(b,d){d>=a&&(b.x=e,b.y=m)});d.update({typeOptions:{points:f.points}})}};r(g.NavigationBindings.prototype,{getYAxisPositions:function(a,b,d){function f(a){return t(a)&&!y(a)&&a.match("%")}var e=0;a=a.map(function(a){var m=f(a.options.height)?parseFloat(a.options.height)/100:a.height/b;a=f(a.options.top)?parseFloat(a.options.top)/100:n(a.top-a.chart.plotTop)/b;y(m)||(m=d/100);e=n(e+m);return{height:100*m,top:100*a}});a.allAxesHeight=e;return a},
getYAxisResizers:function(a){var b=[];a.forEach(function(d,f){d=a[f+1];b[f]=d?{enabled:!0,controlledAxis:{next:[w(d.options.id,d.options.index)]}}:{enabled:!1}});return b},resizeYAxes:function(a){a=a||20;var b=this.chart,d=b.yAxis.filter(this.utils.isNotNavigatorYAxis),f=d.length;b=this.getYAxisPositions(d,b.plotHeight,a);var e=this.getYAxisResizers(d),m=b.allAxesHeight,c=a;1<m?(6>f?(b[0].height=n(b[0].height-c),b=this.recalculateYAxisPositions(b,c)):(a=100/f,b=this.recalculateYAxisPositions(b,a/
(f-1),!0,-1)),b[f-1]={top:n(100-a),height:a}):(c=100*n(1-m),5>f?(b[0].height=n(b[0].height+c),b=this.recalculateYAxisPositions(b,c)):b=this.recalculateYAxisPositions(b,c/f,!0,1));b.forEach(function(a,b){d[b].update({height:a.height+"%",top:a.top+"%",resize:e[b]},!1)})},recalculateYAxisPositions:function(a,b,d,f){a.forEach(function(e,m){m=a[m-1];e.top=m?n(m.height+m.top):0;d&&(e.height=n(e.height+f*b))});return a}});h={segment:{className:"highcharts-segment",start:function(a){a=this.chart.pointer.getCoordinates(a);
var b=this.chart.options.navigation;a=l({langKey:"segment",type:"crookedLine",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.segment.annotationsOptions);return this.chart.addAnnotation(a)},steps:[c.updateNthPoint(1)]},arrowSegment:{className:"highcharts-arrow-segment",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"arrowSegment",type:"crookedLine",typeOptions:{line:{markerEnd:"arrow"},
points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.arrowSegment.annotationsOptions);return this.chart.addAnnotation(a)},steps:[c.updateNthPoint(1)]},ray:{className:"highcharts-ray",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"ray",type:"crookedLine",typeOptions:{type:"ray",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,
b.bindings.ray.annotationsOptions);return this.chart.addAnnotation(a)},steps:[c.updateNthPoint(1)]},arrowRay:{className:"highcharts-arrow-ray",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"arrowRay",type:"infinityLine",typeOptions:{type:"ray",line:{markerEnd:"arrow"},points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.arrowRay.annotationsOptions);return this.chart.addAnnotation(a)},
steps:[c.updateNthPoint(1)]},infinityLine:{className:"highcharts-infinity-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"infinityLine",type:"infinityLine",typeOptions:{type:"line",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.infinityLine.annotationsOptions);return this.chart.addAnnotation(a)},steps:[c.updateNthPoint(1)]},arrowInfinityLine:{className:"highcharts-arrow-infinity-line",
start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"arrowInfinityLine",type:"infinityLine",typeOptions:{type:"line",line:{markerEnd:"arrow"},points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.arrowInfinityLine.annotationsOptions);return this.chart.addAnnotation(a)},steps:[c.updateNthPoint(1)]},horizontalLine:{className:"highcharts-horizontal-line",start:function(a){a=this.chart.pointer.getCoordinates(a);
var b=this.chart.options.navigation;a=l({langKey:"horizontalLine",type:"infinityLine",draggable:"y",typeOptions:{type:"horizontalLine",points:[{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.horizontalLine.annotationsOptions);this.chart.addAnnotation(a)}},verticalLine:{className:"highcharts-vertical-line",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"verticalLine",type:"infinityLine",draggable:"x",typeOptions:{type:"verticalLine",
points:[{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.verticalLine.annotationsOptions);this.chart.addAnnotation(a)}},crooked3:{className:"highcharts-crooked3",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"crooked3",type:"crookedLine",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.crooked3.annotationsOptions);
return this.chart.addAnnotation(a)},steps:[c.updateNthPoint(1),c.updateNthPoint(2)]},crooked5:{className:"highcharts-crooked5",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"crookedLine",type:"crookedLine",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,
b.bindings.crooked5.annotationsOptions);return this.chart.addAnnotation(a)},steps:[c.updateNthPoint(1),c.updateNthPoint(2),c.updateNthPoint(3),c.updateNthPoint(4)]},elliott3:{className:"highcharts-elliott3",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"elliott3",type:"elliottWave",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,
y:a.yAxis[0].value}]},labelOptions:{style:{color:"#666666"}}},b.annotationsOptions,b.bindings.elliott3.annotationsOptions);return this.chart.addAnnotation(a)},steps:[c.updateNthPoint(1),c.updateNthPoint(2),c.updateNthPoint(3)]},elliott5:{className:"highcharts-elliott5",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"elliott5",type:"elliottWave",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},
{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]},labelOptions:{style:{color:"#666666"}}},b.annotationsOptions,b.bindings.elliott5.annotationsOptions);return this.chart.addAnnotation(a)},steps:[c.updateNthPoint(1),c.updateNthPoint(2),c.updateNthPoint(3),c.updateNthPoint(4),c.updateNthPoint(5)]},measureX:{className:"highcharts-measure-x",start:function(a){a=this.chart.pointer.getCoordinates(a);
var b=this.chart.options.navigation;a=l({langKey:"measure",type:"measure",typeOptions:{selectType:"x",point:{x:a.xAxis[0].value,y:a.yAxis[0].value,xAxis:0,yAxis:0},crosshairX:{strokeWidth:1,stroke:"#000000"},crosshairY:{enabled:!1,strokeWidth:0,stroke:"#000000"},background:{width:0,height:0,strokeWidth:0,stroke:"#ffffff"}},labelOptions:{style:{color:"#666666"}}},b.annotationsOptions,b.bindings.measureX.annotationsOptions);return this.chart.addAnnotation(a)},steps:[c.updateRectSize]},measureY:{className:"highcharts-measure-y",
start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"measure",type:"measure",typeOptions:{selectType:"y",point:{x:a.xAxis[0].value,y:a.yAxis[0].value,xAxis:0,yAxis:0},crosshairX:{enabled:!1,strokeWidth:0,stroke:"#000000"},crosshairY:{strokeWidth:1,stroke:"#000000"},background:{width:0,height:0,strokeWidth:0,stroke:"#ffffff"}},labelOptions:{style:{color:"#666666"}}},b.annotationsOptions,b.bindings.measureY.annotationsOptions);return this.chart.addAnnotation(a)},
steps:[c.updateRectSize]},measureXY:{className:"highcharts-measure-xy",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"measure",type:"measure",typeOptions:{selectType:"xy",point:{x:a.xAxis[0].value,y:a.yAxis[0].value,xAxis:0,yAxis:0},background:{width:0,height:0,strokeWidth:10},crosshairX:{strokeWidth:1,stroke:"#000000"},crosshairY:{strokeWidth:1,stroke:"#000000"}},labelOptions:{style:{color:"#666666"}}},b.annotationsOptions,b.bindings.measureXY.annotationsOptions);
return this.chart.addAnnotation(a)},steps:[c.updateRectSize]},fibonacci:{className:"highcharts-fibonacci",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"fibonacci",type:"fibonacci",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]},labelOptions:{style:{color:"#666666"}}},b.annotationsOptions,b.bindings.fibonacci.annotationsOptions);return this.chart.addAnnotation(a)},steps:[c.updateNthPoint(1),
c.updateHeight]},parallelChannel:{className:"highcharts-parallel-channel",start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"parallelChannel",type:"tunnel",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}]}},b.annotationsOptions,b.bindings.parallelChannel.annotationsOptions);return this.chart.addAnnotation(a)},steps:[c.updateNthPoint(1),c.updateHeight]},pitchfork:{className:"highcharts-pitchfork",
start:function(a){a=this.chart.pointer.getCoordinates(a);var b=this.chart.options.navigation;a=l({langKey:"pitchfork",type:"pitchfork",typeOptions:{points:[{x:a.xAxis[0].value,y:a.yAxis[0].value,controlPoint:{style:{fill:"red"}}},{x:a.xAxis[0].value,y:a.yAxis[0].value},{x:a.xAxis[0].value,y:a.yAxis[0].value}],innerBackground:{fill:"rgba(100, 170, 255, 0.8)"}},shapeOptions:{strokeWidth:2}},b.annotationsOptions,b.bindings.pitchfork.annotationsOptions);return this.chart.addAnnotation(a)},steps:[c.updateNthPoint(1),
c.updateNthPoint(2)]},verticalCounter:{className:"highcharts-vertical-counter",start:function(a){a=c.attractToPoint(a,this.chart);var b=this.chart.options.navigation,d=t(this.verticalCounter)?this.verticalCounter:0;a=l({langKey:"verticalCounter",type:"verticalLine",typeOptions:{point:{x:a.x,y:a.y,xAxis:a.xAxis,yAxis:a.yAxis},label:{offset:a.below?40:-40,text:d.toString()}},labelOptions:{style:{color:"#666666",fontSize:"11px"}},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1}},b.annotationsOptions,
b.bindings.verticalCounter.annotationsOptions);a=this.chart.addAnnotation(a);a.options.events.click.call(a,{})}},verticalLabel:{className:"highcharts-vertical-label",start:function(a){a=c.attractToPoint(a,this.chart);var b=this.chart.options.navigation;a=l({langKey:"verticalLabel",type:"verticalLine",typeOptions:{point:{x:a.x,y:a.y,xAxis:a.xAxis,yAxis:a.yAxis},label:{offset:a.below?40:-40}},labelOptions:{style:{color:"#666666",fontSize:"11px"}},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",strokeWidth:1}},
b.annotationsOptions,b.bindings.verticalLabel.annotationsOptions);a=this.chart.addAnnotation(a);a.options.events.click.call(a,{})}},verticalArrow:{className:"highcharts-vertical-arrow",start:function(a){a=c.attractToPoint(a,this.chart);var b=this.chart.options.navigation;a=l({langKey:"verticalArrow",type:"verticalLine",typeOptions:{point:{x:a.x,y:a.y,xAxis:a.xAxis,yAxis:a.yAxis},label:{offset:a.below?40:-40,format:" "},connector:{fill:"none",stroke:a.below?"red":"green"}},shapeOptions:{stroke:"rgba(0, 0, 0, 0.75)",
strokeWidth:1}},b.annotationsOptions,b.bindings.verticalArrow.annotationsOptions);a=this.chart.addAnnotation(a);a.options.events.click.call(a,{})}},flagCirclepin:{className:"highcharts-flag-circlepin",start:c.addFlagFromForm("circlepin")},flagDiamondpin:{className:"highcharts-flag-diamondpin",start:c.addFlagFromForm("flag")},flagSquarepin:{className:"highcharts-flag-squarepin",start:c.addFlagFromForm("squarepin")},flagSimplepin:{className:"highcharts-flag-simplepin",start:c.addFlagFromForm("nopin")},
zoomX:{className:"highcharts-zoom-x",init:function(a){this.chart.update({chart:{zoomType:"x"}});k(this,"deselectButton",{button:a})}},zoomY:{className:"highcharts-zoom-y",init:function(a){this.chart.update({chart:{zoomType:"y"}});k(this,"deselectButton",{button:a})}},zoomXY:{className:"highcharts-zoom-xy",init:function(a){this.chart.update({chart:{zoomType:"xy"}});k(this,"deselectButton",{button:a})}},seriesTypeLine:{className:"highcharts-series-type-line",init:function(a){this.chart.series[0].update({type:"line",
useOhlcData:!0});k(this,"deselectButton",{button:a})}},seriesTypeOhlc:{className:"highcharts-series-type-ohlc",init:function(a){this.chart.series[0].update({type:"ohlc"});k(this,"deselectButton",{button:a})}},seriesTypeCandlestick:{className:"highcharts-series-type-candlestick",init:function(a){this.chart.series[0].update({type:"candlestick"});k(this,"deselectButton",{button:a})}},fullScreen:{className:"highcharts-full-screen",init:function(a){k(this,"deselectButton",{button:a})}},currentPriceIndicator:{className:"highcharts-current-price-indicator",
init:function(a){var b=this.chart,d=b.series[0],f=d.options,e=f.lastVisiblePrice&&f.lastVisiblePrice.enabled;f=f.lastPrice&&f.lastPrice.enabled;b=b.stockTools;var m=b.getIconsURL();b&&b.guiEnabled&&(a.firstChild.style["background-image"]=f?'url("'+m+'current-price-show.svg")':'url("'+m+'current-price-hide.svg")');d.update({lastPrice:{enabled:!f,color:"red"},lastVisiblePrice:{enabled:!e,label:{enabled:!0}}});k(this,"deselectButton",{button:a})}},indicators:{className:"highcharts-indicators",init:function(){var a=
this;k(a,"showPopup",{formType:"indicators",options:{},onSubmit:function(b){a.utils.manageIndicators.call(a,b)}})}},toggleAnnotations:{className:"highcharts-toggle-annotations",init:function(a){var b=this.chart,d=b.stockTools,f=d.getIconsURL();this.toggledAnnotations=!this.toggledAnnotations;(b.annotations||[]).forEach(function(a){a.setVisibility(!this.toggledAnnotations)},this);d&&d.guiEnabled&&(a.firstChild.style["background-image"]=this.toggledAnnotations?'url("'+f+'annotations-hidden.svg")':'url("'+
f+'annotations-visible.svg")');k(this,"deselectButton",{button:a})}},saveChart:{className:"highcharts-save-chart",init:function(a){var b=this,d=b.chart,f=[],e=[],m=[],c=[];d.annotations.forEach(function(a,b){f[b]=a.userOptions});d.series.forEach(function(a){a.is("sma")?e.push(a.userOptions):"flags"===a.type&&m.push(a.userOptions)});d.yAxis.forEach(function(a){b.utils.isNotNavigatorYAxis(a)&&c.push(a.options)});g.win.localStorage.setItem("highcharts-chart",JSON.stringify({annotations:f,indicators:e,
flags:m,yAxes:c}));k(this,"deselectButton",{button:a})}}};g.setOptions({navigation:{bindings:h}})});r(g,"modules/stock-tools-gui.js",[g["parts/Globals.js"],g["parts/Utilities.js"]],function(g,h){var n=h.addEvent,p=h.createElement,r=h.css,k=h.extend,t=h.fireEvent,l=h.getStyle,w=h.isArray,v=h.merge,c=h.pick,a=g.win;g.setOptions({lang:{stockTools:{gui:{simpleShapes:"Simple shapes",lines:"Lines",crookedLines:"Crooked lines",measure:"Measure",advanced:"Advanced",toggleAnnotations:"Toggle annotations",
verticalLabels:"Vertical labels",flags:"Flags",zoomChange:"Zoom change",typeChange:"Type change",saveChart:"Save chart",indicators:"Indicators",currentPriceIndicator:"Current Price Indicators",zoomX:"Zoom X",zoomY:"Zoom Y",zoomXY:"Zooom XY",fullScreen:"Fullscreen",typeOHLC:"OHLC",typeLine:"Line",typeCandlestick:"Candlestick",circle:"Circle",label:"Label",rectangle:"Rectangle",flagCirclepin:"Flag circle",flagDiamondpin:"Flag diamond",flagSquarepin:"Flag square",flagSimplepin:"Flag simple",measureXY:"Measure XY",
measureX:"Measure X",measureY:"Measure Y",segment:"Segment",arrowSegment:"Arrow segment",ray:"Ray",arrowRay:"Arrow ray",line:"Line",arrowLine:"Arrow line",horizontalLine:"Horizontal line",verticalLine:"Vertical line",infinityLine:"Infinity line",crooked3:"Crooked 3 line",crooked5:"Crooked 5 line",elliott3:"Elliott 3 line",elliott5:"Elliott 5 line",verticalCounter:"Vertical counter",verticalLabel:"Vertical label",verticalArrow:"Vertical arrow",fibonacci:"Fibonacci",pitchfork:"Pitchfork",parallelChannel:"Parallel channel"}},
navigation:{popup:{circle:"Circle",rectangle:"Rectangle",label:"Label",segment:"Segment",arrowSegment:"Arrow segment",ray:"Ray",arrowRay:"Arrow ray",line:"Line",arrowLine:"Arrow line",horizontalLine:"Horizontal line",verticalLine:"Vertical line",crooked3:"Crooked 3 line",crooked5:"Crooked 5 line",elliott3:"Elliott 3 line",elliott5:"Elliott 5 line",verticalCounter:"Vertical counter",verticalLabel:"Vertical label",verticalArrow:"Vertical arrow",fibonacci:"Fibonacci",pitchfork:"Pitchfork",parallelChannel:"Parallel channel",
infinityLine:"Infinity line",measure:"Measure",measureXY:"Measure XY",measureX:"Measure X",measureY:"Measure Y",flags:"Flags",addButton:"add",saveButton:"save",editButton:"edit",removeButton:"remove",series:"Series",volume:"Volume",connector:"Connector",innerBackground:"Inner background",outerBackground:"Outer background",crosshairX:"Crosshair X",crosshairY:"Crosshair Y",tunnel:"Tunnel",background:"Background"}}},stockTools:{gui:{enabled:!0,className:"highcharts-bindings-wrapper",toolbarClassName:"stocktools-toolbar",
buttons:"indicators separator simpleShapes lines crookedLines measure advanced toggleAnnotations separator verticalLabels flags separator zoomChange fullScreen typeChange separator currentPriceIndicator saveChart".split(" "),definitions:{separator:{symbol:"separator.svg"},simpleShapes:{items:["label","circle","rectangle"],circle:{symbol:"circle.svg"},rectangle:{symbol:"rectangle.svg"},label:{symbol:"label.svg"}},flags:{items:["flagCirclepin","flagDiamondpin","flagSquarepin","flagSimplepin"],flagSimplepin:{symbol:"flag-basic.svg"},
flagDiamondpin:{symbol:"flag-diamond.svg"},flagSquarepin:{symbol:"flag-trapeze.svg"},flagCirclepin:{symbol:"flag-elipse.svg"}},lines:{items:"segment arrowSegment ray arrowRay line arrowLine horizontalLine verticalLine".split(" "),segment:{symbol:"segment.svg"},arrowSegment:{symbol:"arrow-segment.svg"},ray:{symbol:"ray.svg"},arrowRay:{symbol:"arrow-ray.svg"},line:{symbol:"line.svg"},arrowLine:{symbol:"arrow-line.svg"},verticalLine:{symbol:"vertical-line.svg"},horizontalLine:{symbol:"horizontal-line.svg"}},
crookedLines:{items:["elliott3","elliott5","crooked3","crooked5"],crooked3:{symbol:"crooked-3.svg"},crooked5:{symbol:"crooked-5.svg"},elliott3:{symbol:"elliott-3.svg"},elliott5:{symbol:"elliott-5.svg"}},verticalLabels:{items:["verticalCounter","verticalLabel","verticalArrow"],verticalCounter:{symbol:"vertical-counter.svg"},verticalLabel:{symbol:"vertical-label.svg"},verticalArrow:{symbol:"vertical-arrow.svg"}},advanced:{items:["fibonacci","pitchfork","parallelChannel"],pitchfork:{symbol:"pitchfork.svg"},
fibonacci:{symbol:"fibonacci.svg"},parallelChannel:{symbol:"parallel-channel.svg"}},measure:{items:["measureXY","measureX","measureY"],measureX:{symbol:"measure-x.svg"},measureY:{symbol:"measure-y.svg"},measureXY:{symbol:"measure-xy.svg"}},toggleAnnotations:{symbol:"annotations-visible.svg"},currentPriceIndicator:{symbol:"current-price-show.svg"},indicators:{symbol:"indicators.svg"},zoomChange:{items:["zoomX","zoomY","zoomXY"],zoomX:{symbol:"zoom-x.svg"},zoomY:{symbol:"zoom-y.svg"},zoomXY:{symbol:"zoom-xy.svg"}},
typeChange:{items:["typeOHLC","typeLine","typeCandlestick"],typeOHLC:{symbol:"series-ohlc.svg"},typeLine:{symbol:"series-line.svg"},typeCandlestick:{symbol:"series-candlestick.svg"}},fullScreen:{symbol:"fullscreen.svg"},saveChart:{symbol:"save-chart.svg"}}}}});n(g.Chart,"afterGetContainer",function(){this.setStockTools()});n(g.Chart,"getMargins",function(){var a=this.stockTools&&this.stockTools.listWrapper;(a=a&&(a.startWidth+l(a,"padding-left")+l(a,"padding-right")||a.offsetWidth))&&a<this.plotWidth&&
(this.plotLeft+=a)});n(g.Chart,"destroy",function(){this.stockTools&&this.stockTools.destroy()});n(g.Chart,"redraw",function(){this.stockTools&&this.stockTools.guiEnabled&&this.stockTools.redraw()});h=function(){function b(a,b,e){this.wrapper=this.toolbar=this.submenu=this.showhideBtn=this.listWrapper=this.arrowWrapper=this.arrowUp=this.arrowDown=void 0;this.chart=e;this.options=a;this.lang=b;this.iconsURL=this.getIconsURL();this.guiEnabled=a.enabled;this.visible=c(a.visible,!0);this.placed=c(a.placed,
!1);this.eventsToUnbind=[];this.guiEnabled&&(this.createHTML(),this.init(),this.showHideNavigatorion());t(this,"afterInit")}b.prototype.init=function(){var a=this,b=this.lang,e=this.options,c=this.toolbar,g=a.addSubmenu,l=e.buttons,h=e.definitions,k=c.childNodes,p=this.inIframe(),q;l.forEach(function(d){q=a.addButton(c,h,d,b);p&&"fullScreen"===d&&(q.buttonWrapper.className+=" highcharts-disabled-btn");a.eventsToUnbind.push(n(q.buttonWrapper,"click",function(){a.eraseActiveButtons(k,q.buttonWrapper)}));
w(h[d].items)&&g.call(a,q,h[d])})};b.prototype.addSubmenu=function(a,b){var d=this,f=a.submenuArrow,c=a.buttonWrapper,g=l(c,"width"),h=this.wrapper,k=this.listWrapper,t=this.toolbar.childNodes,q=0,u;this.submenu=u=p("ul",{className:"highcharts-submenu-wrapper"},null,c);this.addSubmenuItems(c,b);d.eventsToUnbind.push(n(f,"click",function(a){a.stopPropagation();d.eraseActiveButtons(t,c);0<=c.className.indexOf("highcharts-current")?(k.style.width=k.startWidth+"px",c.classList.remove("highcharts-current"),
u.style.display="none"):(u.style.display="block",q=u.offsetHeight-c.offsetHeight-3,u.offsetHeight+c.offsetTop>h.offsetHeight&&c.offsetTop>q||(q=0),r(u,{top:-q+"px",left:g+3+"px"}),c.className+=" highcharts-current",k.startWidth=h.offsetWidth,k.style.width=k.startWidth+l(k,"padding-left")+u.offsetWidth+3+"px")}))};b.prototype.addSubmenuItems=function(a,b){var d=this,f=this.submenu,c=this.lang,g=this.listWrapper,h;b.items.forEach(function(e){h=d.addButton(f,b,e,c);d.eventsToUnbind.push(n(h.mainButton,
"click",function(){d.switchSymbol(this,a,!0);g.style.width=g.startWidth+"px";f.style.display="none"}))});var l=f.querySelectorAll("li > .highcharts-menu-item-btn")[0];d.switchSymbol(l,!1)};b.prototype.eraseActiveButtons=function(a,b,e){[].forEach.call(a,function(a){a!==b&&(a.classList.remove("highcharts-current"),a.classList.remove("highcharts-active"),e=a.querySelectorAll(".highcharts-submenu-wrapper"),0<e.length&&(e[0].style.display="none"))})};b.prototype.addButton=function(a,f,e,g){void 0===g&&
(g={});f=f[e];var d=f.items,m=f.className||"";e=p("li",{className:c(b.prototype.classMapping[e],"")+" "+m,title:g[e]||e},null,a);a=p("span",{className:"highcharts-menu-item-btn"},null,e);if(d&&d.length){var h=p("span",{className:"highcharts-submenu-item-arrow highcharts-arrow-right"},null,e);h.style["background-image"]="url("+this.iconsURL+"arrow-bottom.svg)"}else a.style["background-image"]="url("+this.iconsURL+f.symbol+")";return{buttonWrapper:e,mainButton:a,submenuArrow:h}};b.prototype.addNavigation=
function(){var a=this.wrapper;this.arrowWrapper=p("div",{className:"highcharts-arrow-wrapper"});this.arrowUp=p("div",{className:"highcharts-arrow-up"},null,this.arrowWrapper);this.arrowUp.style["background-image"]="url("+this.iconsURL+"arrow-right.svg)";this.arrowDown=p("div",{className:"highcharts-arrow-down"},null,this.arrowWrapper);this.arrowDown.style["background-image"]="url("+this.iconsURL+"arrow-right.svg)";a.insertBefore(this.arrowWrapper,a.childNodes[0]);this.scrollButtons()};b.prototype.scrollButtons=
function(){var a=0,b=this.wrapper,e=this.toolbar,c=.1*b.offsetHeight;this.eventsToUnbind.push(n(this.arrowUp,"click",function(){0<a&&(a-=c,e.style["margin-top"]=-a+"px")}));this.eventsToUnbind.push(n(this.arrowDown,"click",function(){b.offsetHeight+a<=e.offsetHeight+c&&(a+=c,e.style["margin-top"]=-a+"px")}))};b.prototype.createHTML=function(){var a=this.chart,b=this.options,c=a.container;a=a.options.navigation;this.wrapper=a=p("div",{className:"highcharts-stocktools-wrapper "+b.className+" "+(a&&
a.bindingsClassName)});c.parentNode.insertBefore(a,c);this.toolbar=c=p("ul",{className:"highcharts-stocktools-toolbar "+b.toolbarClassName});this.listWrapper=b=p("div",{className:"highcharts-menu-wrapper"});a.insertBefore(b,a.childNodes[0]);b.insertBefore(c,b.childNodes[0]);this.showHideToolbar();this.addNavigation()};b.prototype.showHideNavigatorion=function(){this.visible&&this.toolbar.offsetHeight>this.wrapper.offsetHeight-50?this.arrowWrapper.style.display="block":(this.toolbar.style.marginTop=
"0px",this.arrowWrapper.style.display="none")};b.prototype.showHideToolbar=function(){var a=this.chart,b=this.wrapper,c=this.listWrapper,g=this.submenu,h=this.visible,k;this.showhideBtn=k=p("div",{className:"highcharts-toggle-toolbar highcharts-arrow-left"},null,b);k.style["background-image"]="url("+this.iconsURL+"arrow-right.svg)";h?(b.style.height="100%",k.style.top=l(c,"padding-top")+"px",k.style.left=b.offsetWidth+l(c,"padding-left")+"px"):(g&&(g.style.display="none"),k.style.left="0px",this.visible=
h=!1,c.classList.add("highcharts-hide"),k.classList.toggle("highcharts-arrow-right"),b.style.height=k.offsetHeight+"px");this.eventsToUnbind.push(n(k,"click",function(){a.update({stockTools:{gui:{visible:!h,placed:!0}}})}))};b.prototype.switchSymbol=function(a,b){var d=a.parentNode,c=d.classList.value;d=d.parentNode.parentNode;d.className="";c&&d.classList.add(c.trim());d.querySelectorAll(".highcharts-menu-item-btn")[0].style["background-image"]=a.style["background-image"];b&&this.selectButton(d)};
b.prototype.selectButton=function(a){0<=a.className.indexOf("highcharts-active")?a.classList.remove("highcharts-active"):a.classList.add("highcharts-active")};b.prototype.unselectAllButtons=function(a){var b=a.parentNode.querySelectorAll(".highcharts-active");[].forEach.call(b,function(b){b!==a&&b.classList.remove("highcharts-active")})};b.prototype.inIframe=function(){try{return a.self!==a.top}catch(d){return!0}};b.prototype.update=function(a){v(!0,this.chart.options.stockTools,a);this.destroy();
this.chart.setStockTools(a);this.chart.navigationBindings&&this.chart.navigationBindings.update()};b.prototype.destroy=function(){var a=this.wrapper,b=a&&a.parentNode;this.eventsToUnbind.forEach(function(a){a()});b&&b.removeChild(a);this.chart.isDirtyBox=!0;this.chart.redraw()};b.prototype.redraw=function(){this.showHideNavigatorion()};b.prototype.getIconsURL=function(){return this.chart.options.navigation.iconsURL||this.options.iconsURL||"https://code.highcharts.com/8.0.4/gfx/stock-icons/"};return b}();
h.prototype.classMapping={circle:"highcharts-circle-annotation",rectangle:"highcharts-rectangle-annotation",label:"highcharts-label-annotation",segment:"highcharts-segment",arrowSegment:"highcharts-arrow-segment",ray:"highcharts-ray",arrowRay:"highcharts-arrow-ray",line:"highcharts-infinity-line",arrowLine:"highcharts-arrow-infinity-line",verticalLine:"highcharts-vertical-line",horizontalLine:"highcharts-horizontal-line",crooked3:"highcharts-crooked3",crooked5:"highcharts-crooked5",elliott3:"highcharts-elliott3",
elliott5:"highcharts-elliott5",pitchfork:"highcharts-pitchfork",fibonacci:"highcharts-fibonacci",parallelChannel:"highcharts-parallel-channel",measureX:"highcharts-measure-x",measureY:"highcharts-measure-y",measureXY:"highcharts-measure-xy",verticalCounter:"highcharts-vertical-counter",verticalLabel:"highcharts-vertical-label",verticalArrow:"highcharts-vertical-arrow",currentPriceIndicator:"highcharts-current-price-indicator",indicators:"highcharts-indicators",flagCirclepin:"highcharts-flag-circlepin",
flagDiamondpin:"highcharts-flag-diamondpin",flagSquarepin:"highcharts-flag-squarepin",flagSimplepin:"highcharts-flag-simplepin",zoomX:"highcharts-zoom-x",zoomY:"highcharts-zoom-y",zoomXY:"highcharts-zoom-xy",typeLine:"highcharts-series-type-line",typeOHLC:"highcharts-series-type-ohlc",typeCandlestick:"highcharts-series-type-candlestick",fullScreen:"highcharts-full-screen",toggleAnnotations:"highcharts-toggle-annotations",saveChart:"highcharts-save-chart",separator:"highcharts-separator"};k(g.Chart.prototype,
{setStockTools:function(a){var b=this.options,c=b.lang;a=v(b.stockTools&&b.stockTools.gui,a&&a.gui);this.stockTools=new g.Toolbar(a,c.stockTools&&c.stockTools.gui,this);this.stockTools.guiEnabled&&(this.isDirtyBox=!0)}});n(g.NavigationBindings,"selectButton",function(a){var b=a.button,c=this.chart.stockTools;c&&c.guiEnabled&&(c.unselectAllButtons(a.button),0<=b.parentNode.className.indexOf("highcharts-submenu-wrapper")&&(b=b.parentNode.parentNode),c.selectButton(b))});n(g.NavigationBindings,"deselectButton",
function(a){a=a.button;var b=this.chart.stockTools;b&&b.guiEnabled&&(0<=a.parentNode.className.indexOf("highcharts-submenu-wrapper")&&(a=a.parentNode.parentNode),b.selectButton(a))});g.Toolbar=h;return g.Toolbar});r(g,"masters/modules/stock-tools.src.js",[],function(){})});
//# sourceMappingURL=stock-tools.js.map