/*
 Highcharts Gantt JS v8.0.4 (2020-04-02)

 Tree Grid

 (c) 2016-2019 Jon Arild Nygard

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/treegrid",["highcharts"],function(z){b(z);b.Highcharts=z;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function z(b,u,l,x){b.hasOwnProperty(u)||(b[u]=x.apply(null,l))}b=b?b._modules:{};z(b,"mixins/tree-series.js",[b["parts/Color.js"],b["parts/Utilities.js"]],function(b,u){var l=u.extend,x=u.isArray,k=u.isNumber,w=
u.isObject,G=u.merge,E=u.pick;return{getColor:function(f,c){var y=c.index,k=c.mapOptionsToLevel,q=c.parentColor,n=c.parentColorIndex,t=c.series,d=c.colors,a=c.siblings,h=t.points,v=t.chart.options.chart,D;if(f){h=h[f.i];f=k[f.level]||{};if(k=h&&f.colorByPoint){var e=h.index%(d?d.length:v.colorCount);var g=d&&d[e]}if(!t.chart.styledMode){d=h&&h.options.color;v=f&&f.color;if(D=q)D=(D=f&&f.colorVariation)&&"brightness"===D.key?b.parse(q).brighten(y/a*D.to).get():q;D=E(d,v,g,D,t.color)}var B=E(h&&h.options.colorIndex,
f&&f.colorIndex,e,n,c.colorIndex)}return{color:D,colorIndex:B}},getLevelOptions:function(f){var c=null;if(w(f)){c={};var y=k(f.from)?f.from:1;var b=f.levels;var q={};var n=w(f.defaults)?f.defaults:{};x(b)&&(q=b.reduce(function(c,d){if(w(d)&&k(d.level)){var a=G({},d);var h="boolean"===typeof a.levelIsConstant?a.levelIsConstant:n.levelIsConstant;delete a.levelIsConstant;delete a.level;d=d.level+(h?0:y-1);w(c[d])?l(c[d],a):c[d]=a}return c},{}));b=k(f.to)?f.to:1;for(f=0;f<=b;f++)c[f]=G({},n,w(q[f])?q[f]:
{})}return c},setTreeValues:function A(c,b){var q=b.before,n=b.idRoot,t=b.mapIdToNode[n],d=b.points[c.i],a=d&&d.options||{},h=0,v=[];l(c,{levelDynamic:c.level-(("boolean"===typeof b.levelIsConstant?b.levelIsConstant:1)?0:t.level),name:E(d&&d.name,""),visible:n===c.id||("boolean"===typeof b.visible?b.visible:!1)});"function"===typeof q&&(c=q(c,b));c.children.forEach(function(a,e){var g=l({},b);l(g,{index:e,siblings:c.children.length,visible:c.visible});a=A(a,g);v.push(a);a.visible&&(h+=a.val)});c.visible=
0<h||c.visible;q=E(a.value,h);l(c,{children:v,childrenTotal:h,isLeaf:c.visible&&!h,val:q});return c},updateRootId:function(c){if(w(c)){var b=w(c.options)?c.options:{};b=E(c.rootNode,b.rootId,"");w(c.userOptions)&&(c.userOptions.rootId=b);c.rootNode=b}return b}}});z(b,"parts-gantt/Tree.js",[b["parts/Utilities.js"]],function(b){var u=b.extend,l=b.isNumber,x=b.pick,k=function(b,k){var f=b.reduce(function(c,b){var f=x(b.parent,"");"undefined"===typeof c[f]&&(c[f]=[]);c[f].push(b);return c},{});Object.keys(f).forEach(function(c,
b){var l=f[c];""!==c&&-1===k.indexOf(c)&&(l.forEach(function(c){b[""].push(c)}),delete b[c])});return f},w=function(b,k,f,c,y,A){var q=0,n=0,t=A&&A.after,d=A&&A.before;k={data:c,depth:f-1,id:b,level:f,parent:k};var a,h;"function"===typeof d&&d(k,A);d=(y[b]||[]).map(function(c){var d=w(c.id,b,f+1,c,y,A),e=c.start;c=!0===c.milestone?e:c.end;a=!l(a)||e<a?e:a;h=!l(h)||c>h?c:h;q=q+1+d.descendants;n=Math.max(d.height+1,n);return d});c&&(c.start=x(c.start,a),c.end=x(c.end,h));u(k,{children:d,descendants:q,
height:n});"function"===typeof t&&t(k,A);return k};return{getListOfParents:k,getNode:w,getTree:function(b,l){var f=b.map(function(c){return c.id});b=k(b,f);return w("",null,1,null,b,l)}}});z(b,"parts-gantt/GridAxis.js",[b["parts/Globals.js"],b["parts/Tick.js"],b["parts/Utilities.js"]],function(b,u,l){var x=l.addEvent,k=l.defined,w=l.erase,z=l.find,E=l.isArray,f=l.isNumber,c=l.merge,y=l.pick,A=l.timeUnits,q=l.wrap,n=b.dateFormat,t=function(e){return l.isObject(e,!0)},d=b.Chart,a=b.Axis,h=function(e){var g=
e.options;g.labels||(g.labels={});g.labels.align=y(g.labels.align,"center");e.categories||(g.showLastLabel=!1);e.labelRotation=0;g.labels.rotation=0},v={top:0,right:1,bottom:2,left:3,0:"top",1:"right",2:"bottom",3:"left"};a.prototype.isOuterAxis=function(){var e=this,g=e.columnIndex,a=e.linkedParent&&e.linkedParent.columns||e.columns,b=g?e.linkedParent:e,c=-1,h=0;e.chart[e.coll].forEach(function(g,m){g.side!==e.side||g.options.isInternal||(h=m,g===b&&(c=m))});return h===c&&(f(g)?a.length===g:!0)};
a.prototype.getMaxLabelDimensions=function(e,g){var a={width:0,height:0};g.forEach(function(g){g=e[g];if(t(g)){var B=t(g.label)?g.label:{};g=B.getBBox?B.getBBox().height:0;B.textStr&&!f(B.textPxLength)&&(B.textPxLength=B.getBBox().width);B=f(B.textPxLength)?Math.round(B.textPxLength):0;a.height=Math.max(g,a.height);a.width=Math.max(B,a.width)}});return a};b.dateFormats.W=function(e){e=new this.Date(e);var g=(this.get("Day",e)+6)%7,a=new this.Date(e.valueOf());this.set("Date",a,this.get("Date",e)-
g+3);g=new this.Date(this.get("FullYear",a),0,1);4!==this.get("Day",g)&&(this.set("Month",e,0),this.set("Date",e,1+(11-this.get("Day",g))%7));return(1+Math.floor((a.valueOf()-g.valueOf())/6048E5)).toString()};b.dateFormats.E=function(e){return n("%a",e,!0).charAt(0)};x(u,"afterGetLabelPosition",function(e){var g=this.label,a=this.axis,c=a.reversed,b=a.chart,h=a.options,r=h&&t(h.grid)?h.grid:{};h=a.options.labels;var m=h.align,p=v[a.side],C=e.tickmarkOffset,d=a.tickPositions,F=this.pos-C;d=f(d[e.index+
1])?d[e.index+1]-C:a.max+C;var n=a.tickSize("tick",!0);C=E(n)?n[0]:0;n=n&&n[1]/2;if(!0===r.enabled){if("top"===p){r=a.top+a.offset;var k=r-C}else"bottom"===p?(k=b.chartHeight-a.bottom+a.offset,r=k+C):(r=a.top+a.len-a.translate(c?d:F),k=a.top+a.len-a.translate(c?F:d));"right"===p?(p=b.chartWidth-a.right+a.offset,c=p+C):"left"===p?(c=a.left+a.offset,p=c-C):(p=Math.round(a.left+a.translate(c?d:F))-n,c=Math.round(a.left+a.translate(c?F:d))-n);this.slotWidth=c-p;e.pos.x="left"===m?p:"right"===m?c:p+(c-
p)/2;e.pos.y=k+(r-k)/2;b=b.renderer.fontMetrics(h.style.fontSize,g.element);g=g.getBBox().height;h.useHTML?e.pos.y+=b.b+-(g/2):(g=Math.round(g/b.h),e.pos.y+=(b.b-(b.h-b.f))/2+-((g-1)*b.h/2));e.pos.x+=a.horiz&&h.x||0}});x(a,"afterTickSize",function(e){var g=a.defaultLeftAxisOptions,c=this.horiz,b=this.options.grid;b=void 0===b?{}:b;var h=this.maxLabelDimensions;b.enabled&&(g=2*Math.abs(g.labels.x),c=c?b.cellHeight||g+h.height:g+h.width,E(e.tickSize)?e.tickSize[0]=c:e.tickSize=[c])});x(a,"afterGetTitlePosition",
function(a){var e=this.options;if(!0===(e&&t(e.grid)?e.grid:{}).enabled){var c=this.axisTitle,b=c&&c.getBBox().width,h=this.horiz,d=this.left,r=this.top,m=this.width,p=this.height,C=e.title;e=this.opposite;var n=this.offset,F=this.tickSize()||[0],k=C.x||0,f=C.y||0,q=y(C.margin,h?5:10);c=this.chart.renderer.fontMetrics(C.style&&C.style.fontSize,c).f;F=(h?r+p:d)+F[0]/2*(e?-1:1)*(h?1:-1)+(this.side===v.bottom?c:0);a.titlePosition.x=h?d-b/2-q+k:F+(e?m:0)+n+k;a.titlePosition.y=h?F-(e?p:0)+(e?c:-c)/2+n+
f:r-q+f}});q(a.prototype,"unsquish",function(a){var e=this.options;return!0===(e&&t(e.grid)?e.grid:{}).enabled&&this.categories?this.tickInterval:a.apply(this,Array.prototype.slice.call(arguments,1))});x(a,"afterSetOptions",function(a){var e=this.options;a=a.userOptions;var b=e&&t(e.grid)?e.grid:{};if(!0===b.enabled){var h=c(!0,{className:"highcharts-grid-axis "+(a.className||""),dateTimeLabelFormats:{hour:{list:["%H:%M","%H"]},day:{list:["%A, %e. %B","%a, %e. %b","%E"]},week:{list:["Week %W","W%W"]},
month:{list:["%B","%b","%o"]}},grid:{borderWidth:1},labels:{padding:2,style:{fontSize:"13px"}},margin:0,title:{text:null,reserveSpace:!1,rotation:0},units:[["millisecond",[1,10,100]],["second",[1,10]],["minute",[1,5,15]],["hour",[1,6]],["day",[1]],["week",[1]],["month",[1]],["year",null]]},a);"xAxis"===this.coll&&(k(a.linkedTo)&&!k(a.tickPixelInterval)&&(h.tickPixelInterval=350),k(a.tickPixelInterval)||!k(a.linkedTo)||k(a.tickPositioner)||k(a.tickInterval)||(h.tickPositioner=function(a,e){var c=this.linkedParent&&
this.linkedParent.tickPositions&&this.linkedParent.tickPositions.info;if(c){var m,p=h.units;for(m=0;m<p.length;m++)if(p[m][0]===c.unitName){var b=m;break}if(p[b+1]){var g=p[b+1][0];var d=(p[b+1][1]||[1])[0]}else"year"===c.unitName&&(g="year",d=10*c.count);c=A[g];this.tickInterval=c*d;return this.getTimeTicks({unitRange:c,count:d,unitName:g},a,e,this.options.startOfWeek)}}));c(!0,this.options,h);this.horiz&&(e.minPadding=y(a.minPadding,0),e.maxPadding=y(a.maxPadding,0));f(e.grid.borderWidth)&&(e.tickWidth=
e.lineWidth=b.borderWidth)}});x(a,"afterSetAxisTranslation",function(){var a=this.options,c=a&&t(a.grid)?a.grid:{},b=this.tickPositions&&this.tickPositions.info,h=this.userOptions.labels||{};this.horiz&&(!0===c.enabled&&this.series.forEach(function(a){a.options.pointRange=0}),b&&(!1===a.dateTimeLabelFormats[b.unitName].range||1<b.count)&&!k(h.align)&&(a.labels.align="left",k(h.x)||(a.labels.x=3)))});x(a,"trimTicks",function(){var a=this.options,c=a&&t(a.grid)?a.grid:{},b=this.categories,h=this.tickPositions,
d=h[0],n=h[h.length-1],r=this.linkedParent&&this.linkedParent.min||this.min,m=this.linkedParent&&this.linkedParent.max||this.max,p=this.tickInterval;!0!==c.enabled||b||!this.horiz&&!this.isLinked||(d<r&&d+p>r&&!a.startOnTick&&(h[0]=r),n>m&&n-p<m&&!a.endOnTick&&(h[h.length-1]=m))});x(a,"afterRender",function(){var a=this.options,c=a&&t(a.grid)?a.grid:{},b=this.chart.renderer;if(!0===c.enabled){this.maxLabelDimensions=this.getMaxLabelDimensions(this.ticks,this.tickPositions);this.rightWall&&this.rightWall.destroy();
if(this.isOuterAxis()&&this.axisLine){var h=a.lineWidth;if(h){var d=this.getLinePath(h);var n=d.indexOf("M")+1;var r=d.indexOf("L")+1;c=d.indexOf("M")+2;var m=d.indexOf("L")+2;var p=(this.tickSize("tick")[0]-1)*(this.side===v.top||this.side===v.left?-1:1);this.horiz?(d[c]+=p,d[m]+=p):(d[n]+=p,d[r]+=p);this.axisLineExtra?this.axisLineExtra.animate({d:d}):(this.axisLineExtra=b.path(d).attr({zIndex:7}).addClass("highcharts-axis-line").add(this.axisGroup),b.styledMode||this.axisLineExtra.attr({stroke:a.lineColor,
"stroke-width":h}));this.axisLine[this.showAxis?"show":"hide"](!0)}}(this.columns||[]).forEach(function(a){a.render()})}});var D={afterGetOffset:function(){(this.columns||[]).forEach(function(a){a.getOffset()})},afterInit:function(){var e=this.chart,b=this.userOptions,d=this.options;d=d&&t(d.grid)?d.grid:{};d.enabled&&(h(this),q(this,"labelFormatter",function(a){var m=this.axis,c=m.tickPositions,e=this.value,b=(m.isLinked?m.linkedParent:m).series[0],h=e===c[0];c=e===c[c.length-1];b=b&&z(b.options.data,
function(a){return a[m.isXAxis?"x":"y"]===e});this.isFirst=h;this.isLast=c;this.point=b;return a.call(this)}));if(d.columns)for(var n=this.columns=[],k=this.columnIndex=0;++k<d.columns.length;){var f=c(b,d.columns[d.columns.length-k-1],{linkedTo:0,type:"category"});delete f.grid.columns;f=new a(this.chart,f,!0);f.isColumn=!0;f.columnIndex=k;w(e.axes,f);w(e[this.coll],f);n.push(f)}},afterSetOptions:function(a){a=(a=a.userOptions)&&t(a.grid)?a.grid:{};var b=a.columns;a.enabled&&b&&c(!0,this.options,
b[b.length-1])},afterSetScale:function(){(this.columns||[]).forEach(function(a){a.setScale()})},destroy:function(a){(this.columns||[]).forEach(function(c){c.destroy(a.keepEvents)})},init:function(a){var c=(a=a.userOptions)&&t(a.grid)?a.grid:{};c.enabled&&k(c.borderColor)&&(a.tickColor=a.lineColor=c.borderColor)}};Object.keys(D).forEach(function(c){x(a,c,D[c])});x(d,"afterSetChartSize",function(){this.axes.forEach(function(a){(a.columns||[]).forEach(function(a){a.setAxisSize();a.setAxisTranslation()})})})});
z(b,"modules/broken-axis.src.js",[b["parts/Axis.js"],b["parts/Globals.js"],b["parts/Utilities.js"],b["parts/Stacking.js"]],function(b,u,l,x){var k=l.addEvent,w=l.find,z=l.fireEvent,E=l.isArray,f=l.isNumber,c=l.pick,y=u.Series,A=function(){function f(c){this.hasBreaks=!1;this.axis=c}f.isInBreak=function(c,b){var d=c.repeat||Infinity,a=c.from,h=c.to-c.from;b=b>=a?(b-a)%d:d-(a-b)%d;return c.inclusive?b<=h:b<h&&0!==b};f.lin2Val=function(c){var b=this.brokenAxis;b=b&&b.breakArray;if(!b)return c;var d;
for(d=0;d<b.length;d++){var a=b[d];if(a.from>=c)break;else a.to<c?c+=a.len:f.isInBreak(a,c)&&(c+=a.len)}return c};f.val2Lin=function(c){var b=this.brokenAxis;b=b&&b.breakArray;if(!b)return c;var d=c,a;for(a=0;a<b.length;a++){var h=b[a];if(h.to<=c)d-=h.len;else if(h.from>=c)break;else if(f.isInBreak(h,c)){d-=c-h.from;break}}return d};f.prototype.findBreakAt=function(c,b){return w(b,function(b){return b.from<c&&c<b.to})};f.prototype.isInAnyBreak=function(b,k){var d=this.axis,a=d.options.breaks,h=a&&
a.length,v;if(h){for(;h--;)if(f.isInBreak(a[h],b)){var n=!0;v||(v=c(a[h].showPoints,!d.isXAxis))}var e=n&&k?n&&!v:n}return e};f.prototype.setBreaks=function(k,l){var d=this,a=d.axis,h=E(k)&&!!k.length;a.isDirty=d.hasBreaks!==h;d.hasBreaks=h;a.options.breaks=a.userOptions.breaks=k;a.forceRedraw=!0;a.series.forEach(function(a){a.isDirty=!0});h||a.val2lin!==f.val2Lin||(delete a.val2lin,delete a.lin2val);h&&(a.userOptions.ordinal=!1,a.lin2val=f.lin2Val,a.val2lin=f.val2Lin,a.setExtremes=function(a,c,h,
g,f){if(d.hasBreaks){for(var e,k=this.options.breaks;e=d.findBreakAt(a,k);)a=e.to;for(;e=d.findBreakAt(c,k);)c=e.from;c<a&&(c=a)}b.prototype.setExtremes.call(this,a,c,h,g,f)},a.setAxisTranslation=function(h){b.prototype.setAxisTranslation.call(this,h);d.unitLength=null;if(d.hasBreaks){h=a.options.breaks||[];var k=[],e=[],g=0,n,l=a.userMin||a.min,q=a.userMax||a.max,v=c(a.pointRangePadding,0),r;h.forEach(function(a){n=a.repeat||Infinity;f.isInBreak(a,l)&&(l+=a.to%n-l%n);f.isInBreak(a,q)&&(q-=q%n-a.from%
n)});h.forEach(function(a){p=a.from;for(n=a.repeat||Infinity;p-n>l;)p-=n;for(;p<l;)p+=n;for(r=p;r<q;r+=n)k.push({value:r,move:"in"}),k.push({value:r+(a.to-a.from),move:"out",size:a.breakSize})});k.sort(function(a,c){return a.value===c.value?("in"===a.move?0:1)-("in"===c.move?0:1):a.value-c.value});var m=0;var p=l;k.forEach(function(a){m+="in"===a.move?1:-1;1===m&&"in"===a.move&&(p=a.value);0===m&&(e.push({from:p,to:a.value,len:a.value-p-(a.size||0)}),g+=a.value-p-(a.size||0))});a.breakArray=d.breakArray=
e;d.unitLength=q-l-g+v;z(a,"afterBreaks");a.staticScale?a.transA=a.staticScale:d.unitLength&&(a.transA*=(q-a.min+v)/d.unitLength);v&&(a.minPixelPadding=a.transA*a.minPointOffset);a.min=l;a.max=q}});c(l,!0)&&a.chart.redraw()};return f}();u=function(){function b(){}b.compose=function(b,l){b.keepProps.push("brokenAxis");var d=y.prototype;d.drawBreaks=function(a,b){var h=this,d=h.points,e,g,k,l;if(a&&a.brokenAxis&&a.brokenAxis.hasBreaks){var n=a.brokenAxis;b.forEach(function(b){e=n&&n.breakArray||[];
g=a.isXAxis?a.min:c(h.options.threshold,a.min);d.forEach(function(h){l=c(h["stack"+b.toUpperCase()],h[b]);e.forEach(function(c){if(f(g)&&f(l)){k=!1;if(g<c.from&&l>c.to||g>c.from&&l<c.from)k="pointBreak";else if(g<c.from&&l>c.from&&l<c.to||g>c.from&&l>c.to&&l<c.from)k="pointInBreak";k&&z(a,k,{point:h,brk:c})}})})})}};d.gappedPath=function(){var a=this.currentDataGrouping,c=a&&a.gapSize;a=this.options.gapSize;var b=this.points.slice(),d=b.length-1,e=this.yAxis,g;if(a&&0<d)for("value"!==this.options.gapUnit&&
(a*=this.basePointRange),c&&c>a&&c>=this.basePointRange&&(a=c),g=void 0;d--;)g&&!1!==g.visible||(g=b[d+1]),c=b[d],!1!==g.visible&&!1!==c.visible&&(g.x-c.x>a&&(g=(c.x+g.x)/2,b.splice(d+1,0,{isNull:!0,x:g}),this.options.stacking&&(g=e.stacks[this.stackKey][g]=new x(e,e.options.stackLabels,!1,g,this.stack),g.total=0)),g=c);return this.getGraphPath(b)};k(b,"init",function(){this.brokenAxis||(this.brokenAxis=new A(this))});k(b,"afterInit",function(){"undefined"!==typeof this.brokenAxis&&this.brokenAxis.setBreaks(this.options.breaks,
!1)});k(b,"afterSetTickPositions",function(){var a=this.brokenAxis;if(a&&a.hasBreaks){var c=this.tickPositions,b=this.tickPositions.info,d=[],e;for(e=0;e<c.length;e++)a.isInAnyBreak(c[e])||d.push(c[e]);this.tickPositions=d;this.tickPositions.info=b}});k(b,"afterSetOptions",function(){this.brokenAxis&&this.brokenAxis.hasBreaks&&(this.options.ordinal=!1)});k(l,"afterGeneratePoints",function(){var a=this.options.connectNulls,c=this.points,b=this.xAxis,d=this.yAxis;if(this.isDirty)for(var e=c.length;e--;){var g=
c[e],f=!(null===g.y&&!1===a)&&(b&&b.brokenAxis&&b.brokenAxis.isInAnyBreak(g.x,!0)||d&&d.brokenAxis&&d.brokenAxis.isInAnyBreak(g.y,!0));g.visible=f?!1:!1!==g.options.visible}});k(l,"afterRender",function(){this.drawBreaks(this.xAxis,["x"]);this.drawBreaks(this.yAxis,c(this.pointArrayMap,["y"]))})};return b}();u.compose(b,y);return u});z(b,"parts-gantt/TreeGrid.js",[b["parts/Globals.js"],b["mixins/tree-series.js"],b["parts/Tick.js"],b["parts-gantt/Tree.js"],b["parts/Utilities.js"]],function(b,u,l,x,
k){var w=k.addEvent,z=k.defined,E=k.fireEvent,f=k.extend,c=k.isNumber,y=k.isString,A=k.merge,q=k.pick,n=k.wrap,t=function(a){return Array.prototype.slice.call(a,1)},d=k.find,a=u.getLevelOptions,h=function(a){return k.isObject(a,!0)};b=b.Axis;u=function(a,c){var b;for(b in c)if(Object.hasOwnProperty.call(c,b)){var m=c[b];n(a,b,m)}};var v=function(a,c){var b=a.collapseStart;a=a.collapseEnd;a>=c&&(b-=.5);return{from:b,to:a,showPoints:!1}},D=function(a){return Object.keys(a.mapOfPosToGridNode).reduce(function(c,
b){b=+b;!(a.min<=b&&a.max>=b)||a.brokenAxis&&a.brokenAxis.isInAnyBreak(b)||c.push(b);return c},[])},e=function(a,c){var b=a.options.breaks||[],d=v(c,a.max);return b.some(function(a){return a.from===d.from&&a.to===d.to})},g=function(a,c){var b=a.options.breaks||[];a=v(c,a.max);b.push(a);return b},B=function(a,c){var b=a.options.breaks||[],d=v(c,a.max);return b.reduce(function(a,c){c.to===d.to&&c.from===d.from||a.push(c);return a},[])},I=function(a,b){var d=a.labelIcon,e=!d,h=b.renderer,m=b.xy,g=b.options,
f=g.width,k=g.height,l=m.x-f/2-g.padding;m=m.y-k/2;var n=b.collapsed?90:180,r=b.show&&c(m);e&&(a.labelIcon=d=h.path(h.symbols[g.type](g.x,g.y,f,k)).addClass("highcharts-label-icon").add(b.group));r||d.attr({y:-9999});h.styledMode||d.attr({"stroke-width":1,fill:q(b.color,"#666666")}).css({cursor:"pointer",stroke:g.lineColor,strokeWidth:g.lineWidth});d[e?"attr":"animate"]({translateX:l,translateY:m,rotation:n})},J=function(a,c,b){var e=[],m=[],g={},f={},k=-1,p="boolean"===typeof c?c:!1;a=x.getTree(a,
{after:function(a){a=f[a.pos];var c=0,b=0;a.children.forEach(function(a){b+=a.descendants+1;c=Math.max(a.height+1,c)});a.descendants=b;a.height=c;a.collapsed&&m.push(a)},before:function(a){var c=h(a.data)?a.data:{},b=y(c.name)?c.name:"",m=g[a.parent];m=h(m)?f[m.pos]:null;var l=function(a){return a.name===b},n;p&&h(m)&&(n=d(m.children,l))?(l=n.pos,n.nodes.push(a)):l=k++;f[l]||(f[l]=n={depth:m?m.depth+1:0,name:b,nodes:[a],children:[],pos:l},-1!==l&&e.push(b),h(m)&&m.children.push(n));y(a.id)&&(g[a.id]=
a);!0===c.collapsed&&(n.collapsed=!0);a.pos=l}});f=function(a,c){var b=function(a,d,m){var e=d+(-1===d?0:c-1),g=(e-d)/2,f=d+g;a.nodes.forEach(function(a){var c=a.data;h(c)&&(c.y=d+c.seriesIndex,delete c.seriesIndex);a.pos=f});m[f]=a;a.pos=f;a.tickmarkOffset=g+.5;a.collapseStart=e+.5;a.children.forEach(function(a){b(a,e+1,m);e=a.collapseEnd-.5});a.collapseEnd=e+.5;return m};return b(a["-1"],-1,{})}(f,b);return{categories:e,mapOfIdToNode:g,mapOfPosToGridNode:f,collapsedNodes:m,tree:a}},H=function(c){c.target.axes.filter(function(a){return"treegrid"===
a.options.type}).forEach(function(b){var d=b.options||{},e=d.labels,m,f=d.uniqueNames,k=0;if(!b.mapOfPosToGridNode||b.series.some(function(a){return!a.hasRendered||a.isDirtyData||a.isDirty})){d=b.series.reduce(function(a,b){b.visible&&(b.options.data.forEach(function(b){h(b)&&(b.seriesIndex=k,a.push(b))}),!0===f&&k++);return a},[]);var l=J(d,f,!0===f?k:1);b.categories=l.categories;b.mapOfPosToGridNode=l.mapOfPosToGridNode;b.hasNames=!0;b.tree=l.tree;b.series.forEach(function(a){var b=a.options.data.map(function(a){return h(a)?
A(a):a});a.visible&&a.setData(b,!1)});b.mapOptionsToLevel=a({defaults:e,from:1,levels:e.levels,to:b.tree.height});"beforeRender"===c.type&&(m=w(b,"foundExtremes",function(){l.collapsedNodes.forEach(function(a){a=g(b,a);b.brokenAxis&&b.brokenAxis.setBreaks(a,!1)});m()}))}})};u(b.prototype,{init:function(a,b,c){var d="treegrid"===c.type;d&&(w(b,"beforeRender",H),w(b,"beforeRedraw",H),c=A({grid:{enabled:!0},labels:{align:"left",levels:[{level:void 0},{level:1,style:{fontWeight:"bold"}}],symbol:{type:"triangle",
x:-5,y:-5,height:10,width:10,padding:5}},uniqueNames:!1},c,{reversed:!0,grid:{columns:void 0}}));a.apply(this,[b,c]);d&&(this.hasNames=!0,this.options.showLastLabel=!0)},getMaxLabelDimensions:function(a){var b=this.options,d=b&&b.labels;b=d&&c(d.indentation)?b.labels.indentation:0;d=a.apply(this,t(arguments));if("treegrid"===this.options.type&&this.mapOfPosToGridNode){var e=this.mapOfPosToGridNode[-1].height;d.width+=b*(e-1)}return d},generateTick:function(a,b){var c=h(this.mapOptionsToLevel)?this.mapOptionsToLevel:
{},d=this.ticks,e=d[b],g;if("treegrid"===this.options.type){var f=this.mapOfPosToGridNode[b];(c=c[f.depth])&&(g={labels:c});e?(e.parameters.category=f.name,e.options=g,e.addLabel()):d[b]=new l(this,b,null,void 0,{category:f.name,tickmarkOffset:f.tickmarkOffset,options:g})}else a.apply(this,t(arguments))},setTickInterval:function(a){var b=this.options;"treegrid"===b.type?(this.min=q(this.userMin,b.min,this.dataMin),this.max=q(this.userMax,b.max,this.dataMax),E(this,"foundExtremes"),this.setAxisTranslation(!0),
this.tickmarkOffset=.5,this.tickInterval=1,this.tickPositions=this.mapOfPosToGridNode?D(this):[]):a.apply(this,t(arguments))}});u(l.prototype,{getLabelPosition:function(a,b,d,e,g,f,k,l,n){var m=q(this.options&&this.options.labels,f);f=this.pos;var p=this.axis,r="treegrid"===p.options.type;a=a.apply(this,[b,d,e,g,m,k,l,n]);r&&(b=m&&h(m.symbol)?m.symbol:{},m=m&&c(m.indentation)?m.indentation:0,f=(f=(p=p.mapOfPosToGridNode)&&p[f])&&f.depth||1,a.x+=b.width+2*b.padding+(f-1)*m);return a},renderLabel:function(a){var b=
this,c=b.pos,d=b.axis,f=b.label,g=d.mapOfPosToGridNode,k=d.options,l=q(b.options&&b.options.labels,k&&k.labels),n=l&&h(l.symbol)?l.symbol:{},r=(g=g&&g[c])&&g.depth;k="treegrid"===k.type;var u=!(!f||!f.element),v=-1<d.tickPositions.indexOf(c);c=d.chart.styledMode;k&&g&&u&&f.addClass("highcharts-treegrid-node-level-"+r);a.apply(b,t(arguments));k&&g&&u&&0<g.descendants&&(d=e(d,g),I(b,{color:!c&&f.styles.color,collapsed:d,group:f.parentGroup,options:n,renderer:f.renderer,show:v,xy:f.xy}),n="highcharts-treegrid-node-"+
(d?"expanded":"collapsed"),f.addClass("highcharts-treegrid-node-"+(d?"collapsed":"expanded")).removeClass(n),c||f.css({cursor:"pointer"}),[f,b.labelIcon].forEach(function(a){a.attachedTreeGridEvents||(w(a.element,"mouseover",function(){f.addClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:"underline"})}),w(a.element,"mouseout",function(){var a=z(l.style)?l.style:{};f.removeClass("highcharts-treegrid-node-active");f.renderer.styledMode||f.css({textDecoration:a.textDecoration})}),
w(a.element,"click",function(){b.toggleCollapse()}),a.attachedTreeGridEvents=!0)}))}});f(l.prototype,{collapse:function(a){var b=this.axis,c=b.brokenAxis;b=g(b,b.mapOfPosToGridNode[this.pos]);c&&c.setBreaks(b,q(a,!0))},expand:function(a){var b=this.axis,c=b.brokenAxis;b=B(b,b.mapOfPosToGridNode[this.pos]);c&&c.setBreaks(b,q(a,!0))},toggleCollapse:function(a){var b=this.axis,c=b.brokenAxis,d=b.mapOfPosToGridNode[this.pos];b=e(b,d)?B(b,d):g(b,d);c&&c.setBreaks(b,q(a,!0))}});b.prototype.utils={getNode:x.getNode}});
z(b,"masters/modules/treegrid.src.js",[],function(){})});
//# sourceMappingURL=treegrid.js.map