/*
 Highcharts JS v8.0.4 (2020-04-02)

 3D features for Highcharts JS

 License: www.highcharts.com/license
*/
(function(p){"object"===typeof module&&module.exports?(p["default"]=p,module.exports=p):"function"===typeof define&&define.amd?define("highcharts/highcharts-3d",["highcharts"],function(C){p(C);p.Highcharts=C;return p}):p("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(p){function C(b,e,q,p){b.hasOwnProperty(e)||(b[e]=p.apply(null,q))}p=p?p._modules:{};C(p,"parts-3d/Math.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(b,e){var q=e.pick,p=b.deg2rad;b.perspective3D=function(b,
e,v){e=0<v&&v<Number.POSITIVE_INFINITY?v/(b.z+e.z+v):1;return{x:b.x*e,y:b.y*e}};b.perspective=function(e,B,v,z){var m=B.options.chart.options3d,x=q(z,v?B.inverted:!1),u={x:B.plotWidth/2,y:B.plotHeight/2,z:m.depth/2,vd:q(m.depth,1)*q(m.viewDistance,0)},A=B.scale3d||1;z=p*m.beta*(x?-1:1);m=p*m.alpha*(x?-1:1);var r=Math.cos(m),a=Math.cos(-z),f=Math.sin(m),l=Math.sin(-z);v||(u.x+=B.plotLeft,u.y+=B.plotTop);return e.map(function(d){var c=(x?d.y:d.x)-u.x;var h=(x?d.x:d.y)-u.y;d=(d.z||0)-u.z;c={x:a*c-l*
d,y:-f*l*c+r*h-a*f*d,z:r*l*c+f*h+r*a*d};h=b.perspective3D(c,u,u.vd);h.x=h.x*A+u.x;h.y=h.y*A+u.y;h.z=c.z*A+u.z;return{x:x?h.y:h.x,y:x?h.x:h.y,z:h.z}})};b.pointCameraDistance=function(b,e){var v=e.options.chart.options3d,z=e.plotWidth/2;e=e.plotHeight/2;v=q(v.depth,1)*q(v.viewDistance,0)+v.depth;return Math.sqrt(Math.pow(z-q(b.plotX,b.x),2)+Math.pow(e-q(b.plotY,b.y),2)+Math.pow(v-q(b.plotZ,b.z),2))};b.shapeArea=function(b){var e=0,v;for(v=0;v<b.length;v++){var q=(v+1)%b.length;e+=b[v].x*b[q].y-b[q].x*
b[v].y}return e/2};b.shapeArea3d=function(e,q,v){return b.shapeArea(b.perspective(e,q,v))}});C(p,"parts-3d/SVGRenderer.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(b,e){function q(a,d,g,n,D,h,f,t){var k=[],G=h-D;return h>D&&h-D>Math.PI/2+.0001?(k=k.concat(q(a,d,g,n,D,D+Math.PI/2,f,t)),k=k.concat(q(a,d,g,n,D+Math.PI/2,h,f,t))):h<D&&D-h>Math.PI/2+.0001?(k=k.concat(q(a,d,g,n,D,D-Math.PI/2,f,t)),k=k.concat(q(a,d,g,n,D-Math.PI/2,h,f,t))):["C",a+g*Math.cos(D)-g*c*G*Math.sin(D)+f,d+n*Math.sin(D)+
n*c*G*Math.cos(D)+t,a+g*Math.cos(h)+g*c*G*Math.sin(h)+f,d+n*Math.sin(h)-n*c*G*Math.cos(h)+t,a+g*Math.cos(h)+f,d+n*Math.sin(h)+t]}var p=e.animObject,w=e.defined,B=e.extend,v=e.merge,z=e.objectEach,m=e.pick,x=Math.cos,u=Math.PI,A=Math.sin,r=b.charts,a=b.color,f=b.deg2rad,l=b.perspective,d=b.SVGElement;e=b.SVGRenderer;var c=4*(Math.sqrt(2)-1)/3/(u/2);e.prototype.toLinePath=function(a,c){var g=[];a.forEach(function(a){g.push("L",a.x,a.y)});a.length&&(g[0]="M",c&&g.push("Z"));return g};e.prototype.toLineSegments=
function(a){var c=[],g=!0;a.forEach(function(a){c.push(g?"M":"L",a.x,a.y);g=!g});return c};e.prototype.face3d=function(a){var c=this,g=this.createElement("path");g.vertexes=[];g.insidePlotArea=!1;g.enabled=!0;g.attr=function(a){if("object"===typeof a&&(w(a.enabled)||w(a.vertexes)||w(a.insidePlotArea))){this.enabled=m(a.enabled,this.enabled);this.vertexes=m(a.vertexes,this.vertexes);this.insidePlotArea=m(a.insidePlotArea,this.insidePlotArea);delete a.enabled;delete a.vertexes;delete a.insidePlotArea;
var g=l(this.vertexes,r[c.chartIndex],this.insidePlotArea),n=c.toLinePath(g,!0);g=b.shapeArea(g);g=this.enabled&&0<g?"visible":"hidden";a.d=n;a.visibility=g}return d.prototype.attr.apply(this,arguments)};g.animate=function(a){if("object"===typeof a&&(w(a.enabled)||w(a.vertexes)||w(a.insidePlotArea))){this.enabled=m(a.enabled,this.enabled);this.vertexes=m(a.vertexes,this.vertexes);this.insidePlotArea=m(a.insidePlotArea,this.insidePlotArea);delete a.enabled;delete a.vertexes;delete a.insidePlotArea;
var g=l(this.vertexes,r[c.chartIndex],this.insidePlotArea),k=c.toLinePath(g,!0);g=b.shapeArea(g);g=this.enabled&&0<g?"visible":"hidden";a.d=k;this.attr("visibility",g)}return d.prototype.animate.apply(this,arguments)};return g.attr(a)};e.prototype.polyhedron=function(a){var c=this,g=this.g(),k=g.destroy;this.styledMode||g.attr({"stroke-linejoin":"round"});g.faces=[];g.destroy=function(){for(var a=0;a<g.faces.length;a++)g.faces[a].destroy();return k.call(this)};g.attr=function(a,k,n,h){if("object"===
typeof a&&w(a.faces)){for(;g.faces.length>a.faces.length;)g.faces.pop().destroy();for(;g.faces.length<a.faces.length;)g.faces.push(c.face3d().add(g));for(var f=0;f<a.faces.length;f++)c.styledMode&&delete a.faces[f].fill,g.faces[f].attr(a.faces[f],null,n,h);delete a.faces}return d.prototype.attr.apply(this,arguments)};g.animate=function(a,k,n){if(a&&a.faces){for(;g.faces.length>a.faces.length;)g.faces.pop().destroy();for(;g.faces.length<a.faces.length;)g.faces.push(c.face3d().add(g));for(var h=0;h<
a.faces.length;h++)g.faces[h].animate(a.faces[h],k,n);delete a.faces}return d.prototype.animate.apply(this,arguments)};return g.attr(a)};var h={initArgs:function(a){var c=this,g=c.renderer,d=g[c.pathType+"Path"](a),k=d.zIndexes;c.parts.forEach(function(a){c[a]=g.path(d[a]).attr({"class":"highcharts-3d-"+a,zIndex:k[a]||0}).add(c)});c.attr({"stroke-linejoin":"round",zIndex:k.group});c.originalDestroy=c.destroy;c.destroy=c.destroyParts},singleSetterForParts:function(a,c,g,d,h,f){var k={};d=[null,null,
d||"attr",h,f];var n=g&&g.zIndexes;g?(n&&n.group&&this.attr({zIndex:n.group}),z(g,function(c,d){k[d]={};k[d][a]=c;n&&(k[d].zIndex=g.zIndexes[d]||0)}),d[1]=k):(k[a]=c,d[0]=k);return this.processParts.apply(this,d)},processParts:function(a,c,g,d,h){var k=this;k.parts.forEach(function(n){c&&(a=m(c[n],!1));if(!1!==a)k[n][g](a,d,h)});return k},destroyParts:function(){this.processParts(null,null,"destroy");return this.originalDestroy()}};var t=v(h,{parts:["front","top","side"],pathType:"cuboid",attr:function(a,
c,g,n){if("string"===typeof a&&"undefined"!==typeof c){var k=a;a={};a[k]=c}return a.shapeArgs||w(a.x)?this.singleSetterForParts("d",null,this.renderer[this.pathType+"Path"](a.shapeArgs||a)):d.prototype.attr.call(this,a,void 0,g,n)},animate:function(a,c,g){w(a.x)&&w(a.y)?(a=this.renderer[this.pathType+"Path"](a),this.singleSetterForParts("d",null,a,"animate",c,g),this.attr({zIndex:a.zIndexes.group})):d.prototype.animate.call(this,a,c,g);return this},fillSetter:function(c){this.singleSetterForParts("fill",
null,{front:c,top:a(c).brighten(.1).get(),side:a(c).brighten(-.1).get()});this.color=this.fill=c;return this}});e.prototype.elements3d={base:h,cuboid:t};e.prototype.element3d=function(a,c){var g=this.g();B(g,this.elements3d[a]);g.initArgs(c);return g};e.prototype.cuboid=function(a){return this.element3d("cuboid",a)};b.SVGRenderer.prototype.cuboidPath=function(a){function c(a){return 0===f&&1<a&&6>a?{x:u[a].x,y:u[a].y+10,z:u[a].z}:u[a]}function g(a){return u[a]}var d=a.x,h=a.y,k=a.z,f=a.height,t=a.width,
A=a.depth,e=r[this.chartIndex],H=e.options.chart.options3d.alpha,m=0,u=[{x:d,y:h,z:k},{x:d+t,y:h,z:k},{x:d+t,y:h+f,z:k},{x:d,y:h+f,z:k},{x:d,y:h+f,z:k+A},{x:d+t,y:h+f,z:k+A},{x:d+t,y:h,z:k+A},{x:d,y:h,z:k+A}];u=l(u,e,a.insidePlotArea);var x=function(a,d){var h=[[],-1],n=a.map(g),k=d.map(g);a=a.map(c);d=d.map(c);0>b.shapeArea(a)?h=[n,0]:0>b.shapeArea(d)&&(h=[k,1]);return h};var v=x([3,2,1,0],[7,6,5,4]);a=v[0];A=v[1];v=x([1,6,7,0],[4,5,2,3]);t=v[0];var q=v[1];v=x([1,2,5,6],[0,7,4,3]);x=v[0];v=v[1];
1===v?m+=1E6*(e.plotWidth-d):v||(m+=1E6*d);m+=10*(!q||0<=H&&180>=H||360>H&&357.5<H?e.plotHeight-h:10+h);1===A?m+=100*k:A||(m+=100*(1E3-k));return{front:this.toLinePath(a,!0),top:this.toLinePath(t,!0),side:this.toLinePath(x,!0),zIndexes:{group:Math.round(m)},isFront:A,isTop:q}};b.SVGRenderer.prototype.arc3d=function(c){function h(a){var c=!1,d={},g;a=v(a);for(g in a)-1!==k.indexOf(g)&&(d[g]=a[g],delete a[g],c=!0);return c?d:!1}var g=this.g(),n=g.renderer,k="x y r innerR start end depth".split(" ");
c=v(c);c.alpha=(c.alpha||0)*f;c.beta=(c.beta||0)*f;g.top=n.path();g.side1=n.path();g.side2=n.path();g.inn=n.path();g.out=n.path();g.onAdd=function(){var a=g.parentGroup,c=g.attr("class");g.top.add(g);["out","inn","side1","side2"].forEach(function(d){g[d].attr({"class":c+" highcharts-3d-side"}).add(a)})};["addClass","removeClass"].forEach(function(a){g[a]=function(){var c=arguments;["top","out","inn","side1","side2"].forEach(function(d){g[d][a].apply(g[d],c)})}});g.setPaths=function(a){var c=g.renderer.arc3dPath(a),
d=100*c.zTop;g.attribs=a;g.top.attr({d:c.top,zIndex:c.zTop});g.inn.attr({d:c.inn,zIndex:c.zInn});g.out.attr({d:c.out,zIndex:c.zOut});g.side1.attr({d:c.side1,zIndex:c.zSide1});g.side2.attr({d:c.side2,zIndex:c.zSide2});g.zIndex=d;g.attr({zIndex:d});a.center&&(g.top.setRadialReference(a.center),delete a.center)};g.setPaths(c);g.fillSetter=function(c){var d=a(c).brighten(-.1).get();this.fill=c;this.side1.attr({fill:d});this.side2.attr({fill:d});this.inn.attr({fill:d});this.out.attr({fill:d});this.top.attr({fill:c});
return this};["opacity","translateX","translateY","visibility"].forEach(function(a){g[a+"Setter"]=function(a,c){g[c]=a;["out","inn","side1","side2","top"].forEach(function(d){g[d].attr(c,a)})}});g.attr=function(a){var c;"object"===typeof a&&(c=h(a))&&(B(g.attribs,c),g.setPaths(g.attribs));return d.prototype.attr.apply(g,arguments)};g.animate=function(a,c,n){var k=this.attribs,f="data-"+Math.random().toString(26).substring(2,9);delete a.center;delete a.z;delete a.alpha;delete a.beta;var t=p(m(c,this.renderer.globalAnimation));
if(t.duration){var l=h(a);g[f]=0;a[f]=1;g[f+"Setter"]=b.noop;l&&(t.step=function(a,c){function d(a){return k[a]+(m(l[a],k[a])-k[a])*c.pos}c.prop===f&&c.elem.setPaths(v(k,{x:d("x"),y:d("y"),r:d("r"),innerR:d("innerR"),start:d("start"),end:d("end"),depth:d("depth")}))});c=t}return d.prototype.animate.call(this,a,c,n)};g.destroy=function(){this.top.destroy();this.out.destroy();this.inn.destroy();this.side1.destroy();this.side2.destroy();return d.prototype.destroy.call(this)};g.hide=function(){this.top.hide();
this.out.hide();this.inn.hide();this.side1.hide();this.side2.hide()};g.show=function(a){this.top.show(a);this.out.show(a);this.inn.show(a);this.side1.show(a);this.side2.show(a)};return g};e.prototype.arc3dPath=function(a){function c(a){a%=2*Math.PI;a>Math.PI&&(a=2*Math.PI-a);return a}var d=a.x,h=a.y,f=a.start,k=a.end-.00001,t=a.r,l=a.innerR||0,r=a.depth||0,b=a.alpha,e=a.beta,m=Math.cos(f),v=Math.sin(f);a=Math.cos(k);var z=Math.sin(k),p=t*Math.cos(e);t*=Math.cos(b);var w=l*Math.cos(e),B=l*Math.cos(b);
l=r*Math.sin(e);var y=r*Math.sin(b);r=["M",d+p*m,h+t*v];r=r.concat(q(d,h,p,t,f,k,0,0));r=r.concat(["L",d+w*a,h+B*z]);r=r.concat(q(d,h,w,B,k,f,0,0));r=r.concat(["Z"]);var C=0<e?Math.PI/2:0;e=0<b?0:Math.PI/2;C=f>-C?f:k>-C?-C:f;var E=k<u-e?k:f<u-e?u-e:k,F=2*u-e;b=["M",d+p*x(C),h+t*A(C)];b=b.concat(q(d,h,p,t,C,E,0,0));k>F&&f<F?(b=b.concat(["L",d+p*x(E)+l,h+t*A(E)+y]),b=b.concat(q(d,h,p,t,E,F,l,y)),b=b.concat(["L",d+p*x(F),h+t*A(F)]),b=b.concat(q(d,h,p,t,F,k,0,0)),b=b.concat(["L",d+p*x(k)+l,h+t*A(k)+y]),
b=b.concat(q(d,h,p,t,k,F,l,y)),b=b.concat(["L",d+p*x(F),h+t*A(F)]),b=b.concat(q(d,h,p,t,F,E,0,0))):k>u-e&&f<u-e&&(b=b.concat(["L",d+p*Math.cos(E)+l,h+t*Math.sin(E)+y]),b=b.concat(q(d,h,p,t,E,k,l,y)),b=b.concat(["L",d+p*Math.cos(k),h+t*Math.sin(k)]),b=b.concat(q(d,h,p,t,k,E,0,0)));b=b.concat(["L",d+p*Math.cos(E)+l,h+t*Math.sin(E)+y]);b=b.concat(q(d,h,p,t,E,C,l,y));b=b.concat(["Z"]);e=["M",d+w*m,h+B*v];e=e.concat(q(d,h,w,B,f,k,0,0));e=e.concat(["L",d+w*Math.cos(k)+l,h+B*Math.sin(k)+y]);e=e.concat(q(d,
h,w,B,k,f,l,y));e=e.concat(["Z"]);m=["M",d+p*m,h+t*v,"L",d+p*m+l,h+t*v+y,"L",d+w*m+l,h+B*v+y,"L",d+w*m,h+B*v,"Z"];d=["M",d+p*a,h+t*z,"L",d+p*a+l,h+t*z+y,"L",d+w*a+l,h+B*z+y,"L",d+w*a,h+B*z,"Z"];z=Math.atan2(y,-l);h=Math.abs(k+z);a=Math.abs(f+z);f=Math.abs((f+k)/2+z);h=c(h);a=c(a);f=c(f);f*=1E5;k=1E5*a;h*=1E5;return{top:r,zTop:1E5*Math.PI+1,out:b,zOut:Math.max(f,k,h),inn:e,zInn:Math.max(f,k,h),side1:m,zSide1:.99*h,side2:d,zSide2:.99*k}}});C(p,"parts-3d/Chart.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],
function(b,e){function p(b,r){var a=b.plotLeft,f=b.plotWidth+a,l=b.plotTop,d=b.plotHeight+l,c=a+b.plotWidth/2,h=l+b.plotHeight/2,t=Number.MAX_VALUE,k=-Number.MAX_VALUE,e=Number.MAX_VALUE,g=-Number.MAX_VALUE,n=1;var A=[{x:a,y:l,z:0},{x:a,y:l,z:r}];[0,1].forEach(function(a){A.push({x:f,y:A[a].y,z:A[a].z})});[0,1,2,3].forEach(function(a){A.push({x:A[a].x,y:d,z:A[a].z})});A=x(A,b,!1);A.forEach(function(a){t=Math.min(t,a.x);k=Math.max(k,a.x);e=Math.min(e,a.y);g=Math.max(g,a.y)});a>t&&(n=Math.min(n,1-Math.abs((a+
c)/(t+c))%1));f<k&&(n=Math.min(n,(f-c)/(k-c)));l>e&&(n=0>e?Math.min(n,(l+h)/(-e+l+h)):Math.min(n,1-(l+h)/(e+h)%1));d<g&&(n=Math.min(n,Math.abs((d-h)/(g-h))));return n}var y=e.addEvent,w=e.Fx,B=e.isArray,v=e.merge,z=e.pick;e=e.wrap;var m=b.Chart,x=b.perspective;m.prototype.is3d=function(){return this.options.chart.options3d&&this.options.chart.options3d.enabled};m.prototype.propsRequireDirtyBox.push("chart.options3d");m.prototype.propsRequireUpdateSeries.push("chart.options3d");y(m,"afterInit",function(){var b=
this.options;this.is3d()&&(b.series||[]).forEach(function(r){"scatter"===(r.type||b.chart.type||b.chart.defaultSeriesType)&&(r.type="scatter3d")})});y(m,"addSeries",function(b){this.is3d()&&"scatter"===b.options.type&&(b.options.type="scatter3d")});e(b.Chart.prototype,"isInsidePlot",function(b){return this.is3d()||b.apply(this,[].slice.call(arguments,1))});var u=b.getOptions();v(!0,u,{chart:{options3d:{enabled:!1,alpha:0,beta:0,depth:100,fitToPlot:!0,viewDistance:25,axisLabelPosition:null,frame:{visible:"default",
size:1,bottom:{},top:{},left:{},right:{},back:{},front:{}}}}});y(m,"afterGetContainer",function(){this.styledMode&&(this.renderer.definition({tagName:"style",textContent:".highcharts-3d-top{filter: url(#highcharts-brighter)}\n.highcharts-3d-side{filter: url(#highcharts-darker)}\n"}),[{name:"darker",slope:.6},{name:"brighter",slope:1.4}].forEach(function(b){this.renderer.definition({tagName:"filter",id:"highcharts-"+b.name,children:[{tagName:"feComponentTransfer",children:[{tagName:"feFuncR",type:"linear",
slope:b.slope},{tagName:"feFuncG",type:"linear",slope:b.slope},{tagName:"feFuncB",type:"linear",slope:b.slope}]}]})},this))});e(m.prototype,"setClassName",function(b){b.apply(this,[].slice.call(arguments,1));this.is3d()&&(this.container.className+=" highcharts-3d-chart")});y(b.Chart,"afterSetChartSize",function(){var b=this.options.chart.options3d;if(this.is3d()){b&&(b.alpha=b.alpha%360+(0<=b.alpha?0:360),b.beta=b.beta%360+(0<=b.beta?0:360));var r=this.inverted,a=this.clipBox,f=this.margin;a[r?"y":
"x"]=-(f[3]||0);a[r?"x":"y"]=-(f[0]||0);a[r?"height":"width"]=this.chartWidth+(f[3]||0)+(f[1]||0);a[r?"width":"height"]=this.chartHeight+(f[0]||0)+(f[2]||0);this.scale3d=1;!0===b.fitToPlot&&(this.scale3d=p(this,b.depth));this.frame3d=this.get3dFrame()}});y(m,"beforeRedraw",function(){this.is3d()&&(this.isDirtyBox=!0)});y(m,"beforeRender",function(){this.is3d()&&(this.frame3d=this.get3dFrame())});e(m.prototype,"renderSeries",function(b){var r=this.series.length;if(this.is3d())for(;r--;)b=this.series[r],
b.translate(),b.render();else b.call(this)});y(m,"afterDrawChartBox",function(){if(this.is3d()){var e=this.renderer,r=this.options.chart.options3d,a=this.get3dFrame(),f=this.plotLeft,l=this.plotLeft+this.plotWidth,d=this.plotTop,c=this.plotTop+this.plotHeight;r=r.depth;var h=f-(a.left.visible?a.left.size:0),t=l+(a.right.visible?a.right.size:0),k=d-(a.top.visible?a.top.size:0),m=c+(a.bottom.visible?a.bottom.size:0),g=0-(a.front.visible?a.front.size:0),n=r+(a.back.visible?a.back.size:0),v=this.hasRendered?
"animate":"attr";this.frame3d=a;this.frameShapes||(this.frameShapes={bottom:e.polyhedron().add(),top:e.polyhedron().add(),left:e.polyhedron().add(),right:e.polyhedron().add(),back:e.polyhedron().add(),front:e.polyhedron().add()});this.frameShapes.bottom[v]({"class":"highcharts-3d-frame highcharts-3d-frame-bottom",zIndex:a.bottom.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.bottom.color).brighten(.1).get(),vertexes:[{x:h,y:m,z:g},{x:t,y:m,z:g},{x:t,y:m,z:n},{x:h,y:m,z:n}],enabled:a.bottom.visible},
{fill:b.color(a.bottom.color).brighten(.1).get(),vertexes:[{x:f,y:c,z:r},{x:l,y:c,z:r},{x:l,y:c,z:0},{x:f,y:c,z:0}],enabled:a.bottom.visible},{fill:b.color(a.bottom.color).brighten(-.1).get(),vertexes:[{x:h,y:m,z:g},{x:h,y:m,z:n},{x:f,y:c,z:r},{x:f,y:c,z:0}],enabled:a.bottom.visible&&!a.left.visible},{fill:b.color(a.bottom.color).brighten(-.1).get(),vertexes:[{x:t,y:m,z:n},{x:t,y:m,z:g},{x:l,y:c,z:0},{x:l,y:c,z:r}],enabled:a.bottom.visible&&!a.right.visible},{fill:b.color(a.bottom.color).get(),vertexes:[{x:t,
y:m,z:g},{x:h,y:m,z:g},{x:f,y:c,z:0},{x:l,y:c,z:0}],enabled:a.bottom.visible&&!a.front.visible},{fill:b.color(a.bottom.color).get(),vertexes:[{x:h,y:m,z:n},{x:t,y:m,z:n},{x:l,y:c,z:r},{x:f,y:c,z:r}],enabled:a.bottom.visible&&!a.back.visible}]});this.frameShapes.top[v]({"class":"highcharts-3d-frame highcharts-3d-frame-top",zIndex:a.top.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.top.color).brighten(.1).get(),vertexes:[{x:h,y:k,z:n},{x:t,y:k,z:n},{x:t,y:k,z:g},{x:h,y:k,z:g}],enabled:a.top.visible},
{fill:b.color(a.top.color).brighten(.1).get(),vertexes:[{x:f,y:d,z:0},{x:l,y:d,z:0},{x:l,y:d,z:r},{x:f,y:d,z:r}],enabled:a.top.visible},{fill:b.color(a.top.color).brighten(-.1).get(),vertexes:[{x:h,y:k,z:n},{x:h,y:k,z:g},{x:f,y:d,z:0},{x:f,y:d,z:r}],enabled:a.top.visible&&!a.left.visible},{fill:b.color(a.top.color).brighten(-.1).get(),vertexes:[{x:t,y:k,z:g},{x:t,y:k,z:n},{x:l,y:d,z:r},{x:l,y:d,z:0}],enabled:a.top.visible&&!a.right.visible},{fill:b.color(a.top.color).get(),vertexes:[{x:h,y:k,z:g},
{x:t,y:k,z:g},{x:l,y:d,z:0},{x:f,y:d,z:0}],enabled:a.top.visible&&!a.front.visible},{fill:b.color(a.top.color).get(),vertexes:[{x:t,y:k,z:n},{x:h,y:k,z:n},{x:f,y:d,z:r},{x:l,y:d,z:r}],enabled:a.top.visible&&!a.back.visible}]});this.frameShapes.left[v]({"class":"highcharts-3d-frame highcharts-3d-frame-left",zIndex:a.left.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.left.color).brighten(.1).get(),vertexes:[{x:h,y:m,z:g},{x:f,y:c,z:0},{x:f,y:c,z:r},{x:h,y:m,z:n}],enabled:a.left.visible&&!a.bottom.visible},
{fill:b.color(a.left.color).brighten(.1).get(),vertexes:[{x:h,y:k,z:n},{x:f,y:d,z:r},{x:f,y:d,z:0},{x:h,y:k,z:g}],enabled:a.left.visible&&!a.top.visible},{fill:b.color(a.left.color).brighten(-.1).get(),vertexes:[{x:h,y:m,z:n},{x:h,y:k,z:n},{x:h,y:k,z:g},{x:h,y:m,z:g}],enabled:a.left.visible},{fill:b.color(a.left.color).brighten(-.1).get(),vertexes:[{x:f,y:d,z:r},{x:f,y:c,z:r},{x:f,y:c,z:0},{x:f,y:d,z:0}],enabled:a.left.visible},{fill:b.color(a.left.color).get(),vertexes:[{x:h,y:m,z:g},{x:h,y:k,z:g},
{x:f,y:d,z:0},{x:f,y:c,z:0}],enabled:a.left.visible&&!a.front.visible},{fill:b.color(a.left.color).get(),vertexes:[{x:h,y:k,z:n},{x:h,y:m,z:n},{x:f,y:c,z:r},{x:f,y:d,z:r}],enabled:a.left.visible&&!a.back.visible}]});this.frameShapes.right[v]({"class":"highcharts-3d-frame highcharts-3d-frame-right",zIndex:a.right.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.right.color).brighten(.1).get(),vertexes:[{x:t,y:m,z:n},{x:l,y:c,z:r},{x:l,y:c,z:0},{x:t,y:m,z:g}],enabled:a.right.visible&&!a.bottom.visible},
{fill:b.color(a.right.color).brighten(.1).get(),vertexes:[{x:t,y:k,z:g},{x:l,y:d,z:0},{x:l,y:d,z:r},{x:t,y:k,z:n}],enabled:a.right.visible&&!a.top.visible},{fill:b.color(a.right.color).brighten(-.1).get(),vertexes:[{x:l,y:d,z:0},{x:l,y:c,z:0},{x:l,y:c,z:r},{x:l,y:d,z:r}],enabled:a.right.visible},{fill:b.color(a.right.color).brighten(-.1).get(),vertexes:[{x:t,y:m,z:g},{x:t,y:k,z:g},{x:t,y:k,z:n},{x:t,y:m,z:n}],enabled:a.right.visible},{fill:b.color(a.right.color).get(),vertexes:[{x:t,y:k,z:g},{x:t,
y:m,z:g},{x:l,y:c,z:0},{x:l,y:d,z:0}],enabled:a.right.visible&&!a.front.visible},{fill:b.color(a.right.color).get(),vertexes:[{x:t,y:m,z:n},{x:t,y:k,z:n},{x:l,y:d,z:r},{x:l,y:c,z:r}],enabled:a.right.visible&&!a.back.visible}]});this.frameShapes.back[v]({"class":"highcharts-3d-frame highcharts-3d-frame-back",zIndex:a.back.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.back.color).brighten(.1).get(),vertexes:[{x:t,y:m,z:n},{x:h,y:m,z:n},{x:f,y:c,z:r},{x:l,y:c,z:r}],enabled:a.back.visible&&!a.bottom.visible},
{fill:b.color(a.back.color).brighten(.1).get(),vertexes:[{x:h,y:k,z:n},{x:t,y:k,z:n},{x:l,y:d,z:r},{x:f,y:d,z:r}],enabled:a.back.visible&&!a.top.visible},{fill:b.color(a.back.color).brighten(-.1).get(),vertexes:[{x:h,y:m,z:n},{x:h,y:k,z:n},{x:f,y:d,z:r},{x:f,y:c,z:r}],enabled:a.back.visible&&!a.left.visible},{fill:b.color(a.back.color).brighten(-.1).get(),vertexes:[{x:t,y:k,z:n},{x:t,y:m,z:n},{x:l,y:c,z:r},{x:l,y:d,z:r}],enabled:a.back.visible&&!a.right.visible},{fill:b.color(a.back.color).get(),
vertexes:[{x:f,y:d,z:r},{x:l,y:d,z:r},{x:l,y:c,z:r},{x:f,y:c,z:r}],enabled:a.back.visible},{fill:b.color(a.back.color).get(),vertexes:[{x:h,y:m,z:n},{x:t,y:m,z:n},{x:t,y:k,z:n},{x:h,y:k,z:n}],enabled:a.back.visible}]});this.frameShapes.front[v]({"class":"highcharts-3d-frame highcharts-3d-frame-front",zIndex:a.front.frontFacing?-1E3:1E3,faces:[{fill:b.color(a.front.color).brighten(.1).get(),vertexes:[{x:h,y:m,z:g},{x:t,y:m,z:g},{x:l,y:c,z:0},{x:f,y:c,z:0}],enabled:a.front.visible&&!a.bottom.visible},
{fill:b.color(a.front.color).brighten(.1).get(),vertexes:[{x:t,y:k,z:g},{x:h,y:k,z:g},{x:f,y:d,z:0},{x:l,y:d,z:0}],enabled:a.front.visible&&!a.top.visible},{fill:b.color(a.front.color).brighten(-.1).get(),vertexes:[{x:h,y:k,z:g},{x:h,y:m,z:g},{x:f,y:c,z:0},{x:f,y:d,z:0}],enabled:a.front.visible&&!a.left.visible},{fill:b.color(a.front.color).brighten(-.1).get(),vertexes:[{x:t,y:m,z:g},{x:t,y:k,z:g},{x:l,y:d,z:0},{x:l,y:c,z:0}],enabled:a.front.visible&&!a.right.visible},{fill:b.color(a.front.color).get(),
vertexes:[{x:l,y:d,z:0},{x:f,y:d,z:0},{x:f,y:c,z:0},{x:l,y:c,z:0}],enabled:a.front.visible},{fill:b.color(a.front.color).get(),vertexes:[{x:t,y:m,z:g},{x:h,y:m,z:g},{x:h,y:k,z:g},{x:t,y:k,z:g}],enabled:a.front.visible}]})}});m.prototype.retrieveStacks=function(b){var r=this.series,a={},f,l=1;this.series.forEach(function(d){f=z(d.options.stack,b?0:r.length-1-d.index);a[f]?a[f].series.push(d):(a[f]={series:[d],position:l},l++)});a.totalStacks=l+1;return a};m.prototype.get3dFrame=function(){var e=this,
r=e.options.chart.options3d,a=r.frame,f=e.plotLeft,l=e.plotLeft+e.plotWidth,d=e.plotTop,c=e.plotTop+e.plotHeight,h=r.depth,t=function(a){a=b.shapeArea3d(a,e);return.5<a?1:-.5>a?-1:0},k=t([{x:f,y:c,z:h},{x:l,y:c,z:h},{x:l,y:c,z:0},{x:f,y:c,z:0}]),m=t([{x:f,y:d,z:0},{x:l,y:d,z:0},{x:l,y:d,z:h},{x:f,y:d,z:h}]),g=t([{x:f,y:d,z:0},{x:f,y:d,z:h},{x:f,y:c,z:h},{x:f,y:c,z:0}]),n=t([{x:l,y:d,z:h},{x:l,y:d,z:0},{x:l,y:c,z:0},{x:l,y:c,z:h}]),v=t([{x:f,y:c,z:0},{x:l,y:c,z:0},{x:l,y:d,z:0},{x:f,y:d,z:0}]);t=t([{x:f,
y:d,z:h},{x:l,y:d,z:h},{x:l,y:c,z:h},{x:f,y:c,z:h}]);var u=!1,p=!1,q=!1,w=!1;[].concat(e.xAxis,e.yAxis,e.zAxis).forEach(function(a){a&&(a.horiz?a.opposite?p=!0:u=!0:a.opposite?w=!0:q=!0)});var y=function(a,c,d){for(var h=["size","color","visible"],g={},b=0;b<h.length;b++)for(var k=h[b],f=0;f<a.length;f++)if("object"===typeof a[f]){var t=a[f][k];if("undefined"!==typeof t&&null!==t){g[k]=t;break}}a=d;!0===g.visible||!1===g.visible?a=g.visible:"auto"===g.visible&&(a=0<c);return{size:z(g.size,1),color:z(g.color,
"none"),frontFacing:0<c,visible:a}};a={axes:{},bottom:y([a.bottom,a.top,a],k,u),top:y([a.top,a.bottom,a],m,p),left:y([a.left,a.right,a.side,a],g,q),right:y([a.right,a.left,a.side,a],n,w),back:y([a.back,a.front,a],t,!0),front:y([a.front,a.back,a],v,!1)};"auto"===r.axisLabelPosition?(n=function(a,c){return a.visible!==c.visible||a.visible&&c.visible&&a.frontFacing!==c.frontFacing},r=[],n(a.left,a.front)&&r.push({y:(d+c)/2,x:f,z:0,xDir:{x:1,y:0,z:0}}),n(a.left,a.back)&&r.push({y:(d+c)/2,x:f,z:h,xDir:{x:0,
y:0,z:-1}}),n(a.right,a.front)&&r.push({y:(d+c)/2,x:l,z:0,xDir:{x:0,y:0,z:1}}),n(a.right,a.back)&&r.push({y:(d+c)/2,x:l,z:h,xDir:{x:-1,y:0,z:0}}),k=[],n(a.bottom,a.front)&&k.push({x:(f+l)/2,y:c,z:0,xDir:{x:1,y:0,z:0}}),n(a.bottom,a.back)&&k.push({x:(f+l)/2,y:c,z:h,xDir:{x:-1,y:0,z:0}}),m=[],n(a.top,a.front)&&m.push({x:(f+l)/2,y:d,z:0,xDir:{x:1,y:0,z:0}}),n(a.top,a.back)&&m.push({x:(f+l)/2,y:d,z:h,xDir:{x:-1,y:0,z:0}}),g=[],n(a.bottom,a.left)&&g.push({z:(0+h)/2,y:c,x:f,xDir:{x:0,y:0,z:-1}}),n(a.bottom,
a.right)&&g.push({z:(0+h)/2,y:c,x:l,xDir:{x:0,y:0,z:1}}),c=[],n(a.top,a.left)&&c.push({z:(0+h)/2,y:d,x:f,xDir:{x:0,y:0,z:-1}}),n(a.top,a.right)&&c.push({z:(0+h)/2,y:d,x:l,xDir:{x:0,y:0,z:1}}),f=function(a,c,d){if(0===a.length)return null;if(1===a.length)return a[0];for(var h=0,g=x(a,e,!1),b=1;b<g.length;b++)d*g[b][c]>d*g[h][c]?h=b:d*g[b][c]===d*g[h][c]&&g[b].z<g[h].z&&(h=b);return a[h]},a.axes={y:{left:f(r,"x",-1),right:f(r,"x",1)},x:{top:f(m,"y",-1),bottom:f(k,"y",1)},z:{top:f(c,"y",-1),bottom:f(g,
"y",1)}}):a.axes={y:{left:{x:f,z:0,xDir:{x:1,y:0,z:0}},right:{x:l,z:0,xDir:{x:0,y:0,z:1}}},x:{top:{y:d,z:0,xDir:{x:1,y:0,z:0}},bottom:{y:c,z:0,xDir:{x:1,y:0,z:0}}},z:{top:{x:q?l:f,y:d,xDir:q?{x:0,y:0,z:1}:{x:0,y:0,z:-1}},bottom:{x:q?l:f,y:c,xDir:q?{x:0,y:0,z:1}:{x:0,y:0,z:-1}}}};return a};w.prototype.matrixSetter=function(){if(1>this.pos&&(B(this.start)||B(this.end))){var b=this.start||[1,0,0,1,0,0],e=this.end||[1,0,0,1,0,0];var a=[];for(var f=0;6>f;f++)a.push(this.pos*e[f]+(1-this.pos)*b[f])}else a=
this.end;this.elem.attr(this.prop,a,null,!0)};""});C(p,"parts-3d/Axis.js",[p["parts/Globals.js"],p["parts/Tick.js"],p["parts/Utilities.js"]],function(b,e,p){function y(a,c,h){if(!a.chart.is3d()||"colorAxis"===a.coll)return c;var d=a.chart,b=A*d.options.chart.options3d.alpha,l=A*d.options.chart.options3d.beta,g=z(h&&a.options.title.position3d,a.options.labels.position3d);h=z(h&&a.options.title.skew3d,a.options.labels.skew3d);var n=d.frame3d,e=d.plotLeft,m=d.plotWidth+e,p=d.plotTop,v=d.plotHeight+p;
d=!1;var u=0,x=0,q={x:0,y:1,z:0};c=a.swapZ({x:c.x,y:c.y,z:0});if(a.isZAxis)if(a.opposite){if(null===n.axes.z.top)return{};x=c.y-p;c.x=n.axes.z.top.x;c.y=n.axes.z.top.y;e=n.axes.z.top.xDir;d=!n.top.frontFacing}else{if(null===n.axes.z.bottom)return{};x=c.y-v;c.x=n.axes.z.bottom.x;c.y=n.axes.z.bottom.y;e=n.axes.z.bottom.xDir;d=!n.bottom.frontFacing}else if(a.horiz)if(a.opposite){if(null===n.axes.x.top)return{};x=c.y-p;c.y=n.axes.x.top.y;c.z=n.axes.x.top.z;e=n.axes.x.top.xDir;d=!n.top.frontFacing}else{if(null===
n.axes.x.bottom)return{};x=c.y-v;c.y=n.axes.x.bottom.y;c.z=n.axes.x.bottom.z;e=n.axes.x.bottom.xDir;d=!n.bottom.frontFacing}else if(a.opposite){if(null===n.axes.y.right)return{};u=c.x-m;c.x=n.axes.y.right.x;c.z=n.axes.y.right.z;e=n.axes.y.right.xDir;e={x:e.z,y:e.y,z:-e.x}}else{if(null===n.axes.y.left)return{};u=c.x-e;c.x=n.axes.y.left.x;c.z=n.axes.y.left.z;e=n.axes.y.left.xDir}"chart"!==g&&("flap"===g?a.horiz?(l=Math.sin(b),b=Math.cos(b),a.opposite&&(l=-l),d&&(l=-l),q={x:e.z*l,y:b,z:-e.x*l}):e={x:Math.cos(l),
y:0,z:Math.sin(l)}:"ortho"===g?a.horiz?(q=Math.cos(b),g=Math.sin(l)*q,b=-Math.sin(b),l=-q*Math.cos(l),q={x:e.y*l-e.z*b,y:e.z*g-e.x*l,z:e.x*b-e.y*g},b=1/Math.sqrt(q.x*q.x+q.y*q.y+q.z*q.z),d&&(b=-b),q={x:b*q.x,y:b*q.y,z:b*q.z}):e={x:Math.cos(l),y:0,z:Math.sin(l)}:a.horiz?q={x:Math.sin(l)*Math.sin(b),y:Math.cos(b),z:-Math.cos(l)*Math.sin(b)}:e={x:Math.cos(l),y:0,z:Math.sin(l)});c.x+=u*e.x+x*q.x;c.y+=u*e.y+x*q.y;c.z+=u*e.z+x*q.z;d=r([c],a.chart)[0];h&&(0>f(r([c,{x:c.x+e.x,y:c.y+e.y,z:c.z+e.z},{x:c.x+
q.x,y:c.y+q.y,z:c.z+q.z}],a.chart))&&(e={x:-e.x,y:-e.y,z:-e.z}),a=r([{x:c.x,y:c.y,z:c.z},{x:c.x+e.x,y:c.y+e.y,z:c.z+e.z},{x:c.x+q.x,y:c.y+q.y,z:c.z+q.z}],a.chart),d.matrix=[a[1].x-a[0].x,a[1].y-a[0].y,a[2].x-a[0].x,a[2].y-a[0].y,d.x,d.y],d.matrix[4]-=d.x*d.matrix[0]+d.y*d.matrix[2],d.matrix[5]-=d.x*d.matrix[1]+d.y*d.matrix[3]);return d}var w=p.addEvent,q=p.extend,v=p.merge,z=p.pick,m=p.splat;p=p.wrap;var x=b.Axis,u=b.Chart,A=b.deg2rad,r=b.perspective,a=b.perspective3D,f=b.shapeArea;v(!0,x.defaultOptions,
{labels:{position3d:"offset",skew3d:!1},title:{position3d:null,skew3d:null}});w(x,"afterSetOptions",function(){if(this.chart.is3d&&this.chart.is3d()&&"colorAxis"!==this.coll){var a=this.options;a.tickWidth=z(a.tickWidth,0);a.gridLineWidth=z(a.gridLineWidth,1)}});p(x.prototype,"getPlotLinePath",function(a){var c=a.apply(this,[].slice.call(arguments,1));if(!this.chart.is3d()||"colorAxis"===this.coll||null===c)return c;var d=this.chart,b=d.options.chart.options3d;b=this.isZAxis?d.plotWidth:b.depth;d=
d.frame3d;c=[this.swapZ({x:c[1],y:c[2],z:0}),this.swapZ({x:c[1],y:c[2],z:b}),this.swapZ({x:c[4],y:c[5],z:0}),this.swapZ({x:c[4],y:c[5],z:b})];b=[];this.horiz?(this.isZAxis?(d.left.visible&&b.push(c[0],c[2]),d.right.visible&&b.push(c[1],c[3])):(d.front.visible&&b.push(c[0],c[2]),d.back.visible&&b.push(c[1],c[3])),d.top.visible&&b.push(c[0],c[1]),d.bottom.visible&&b.push(c[2],c[3])):(d.front.visible&&b.push(c[0],c[2]),d.back.visible&&b.push(c[1],c[3]),d.left.visible&&b.push(c[0],c[1]),d.right.visible&&
b.push(c[2],c[3]));b=r(b,this.chart,!1);return this.chart.renderer.toLineSegments(b)});p(x.prototype,"getLinePath",function(a){return this.chart.is3d()&&"colorAxis"!==this.coll?[]:a.apply(this,[].slice.call(arguments,1))});p(x.prototype,"getPlotBandPath",function(a){if(!this.chart.is3d()||"colorAxis"===this.coll)return a.apply(this,[].slice.call(arguments,1));var c=arguments,d=c[2],b=[];c=this.getPlotLinePath({value:c[1]});d=this.getPlotLinePath({value:d});if(c&&d)for(var f=0;f<c.length;f+=6)b.push("M",
c[f+1],c[f+2],"L",c[f+4],c[f+5],"L",d[f+4],d[f+5],"L",d[f+1],d[f+2],"Z");return b});p(e.prototype,"getMarkPath",function(a){var c=a.apply(this,[].slice.call(arguments,1));c=[y(this.axis,{x:c[1],y:c[2],z:0}),y(this.axis,{x:c[4],y:c[5],z:0})];return this.axis.chart.renderer.toLineSegments(c)});w(e,"afterGetLabelPosition",function(a){q(a.pos,y(this.axis,a.pos))});p(x.prototype,"getTitlePosition",function(a){var c=a.apply(this,[].slice.call(arguments,1));return y(this,c,!0)});w(x,"drawCrosshair",function(a){this.chart.is3d()&&
"colorAxis"!==this.coll&&a.point&&(a.point.crosshairPos=this.isXAxis?a.point.axisXpos:this.len-a.point.axisYpos)});w(x,"destroy",function(){["backFrame","bottomFrame","sideFrame"].forEach(function(a){this[a]&&(this[a]=this[a].destroy())},this)});u.prototype.addZAxis=function(a){return new l(this,a)};u.prototype.collectionsWithUpdate.push("zAxis");u.prototype.collectionsWithInit.zAxis=[u.prototype.addZAxis];x.prototype.swapZ=function(a,c){return this.isZAxis?(c=c?0:this.chart.plotLeft,{x:c+a.z,y:a.y,
z:a.x-c}):a};var l=b.ZAxis=function(){this.init.apply(this,arguments)};q(l.prototype,x.prototype);q(l.prototype,{isZAxis:!0,setOptions:function(a){a=v({offset:0,lineWidth:0},a);x.prototype.setOptions.call(this,a);this.coll="zAxis"},setAxisSize:function(){x.prototype.setAxisSize.call(this);this.width=this.len=this.chart.options.chart.options3d.depth;this.right=this.chart.chartWidth-this.width-this.left},getSeriesExtremes:function(){var a=this,c=a.chart;a.hasVisibleSeries=!1;a.dataMin=a.dataMax=a.ignoreMinPadding=
a.ignoreMaxPadding=null;a.buildStacks&&a.buildStacks();a.series.forEach(function(d){if(d.visible||!c.options.chart.ignoreHiddenSeries)a.hasVisibleSeries=!0,d=d.zData,d.length&&(a.dataMin=Math.min(z(a.dataMin,d[0]),Math.min.apply(null,d)),a.dataMax=Math.max(z(a.dataMax,d[0]),Math.max.apply(null,d)))})}});w(u,"afterGetAxes",function(){var a=this,c=this.options;c=c.zAxis=m(c.zAxis||{});a.is3d()&&(this.zAxis=[],c.forEach(function(c,d){c.index=d;c.isX=!0;a.addZAxis(c).setScale()}))});p(x.prototype,"getSlotWidth",
function(d,c){if(this.chart.is3d()&&c&&c.label&&this.categories&&this.chart.frameShapes){var b=this.chart,f=this.ticks,e=this.gridGroup.element.childNodes[0].getBBox(),l=b.frameShapes.left.getBBox(),g=b.options.chart.options3d;b={x:b.plotWidth/2,y:b.plotHeight/2,z:g.depth/2,vd:z(g.depth,1)*z(g.viewDistance,0)};var n,r;g=c.pos;var m=f[g-1];f=f[g+1];0!==g&&m&&m.label.xy&&(n=a({x:m.label.xy.x,y:m.label.xy.y,z:null},b,b.vd));f&&f.label.xy&&(r=a({x:f.label.xy.x,y:f.label.xy.y,z:null},b,b.vd));f={x:c.label.xy.x,
y:c.label.xy.y,z:null};f=a(f,b,b.vd);return Math.abs(n?f.x-n.x:r?r.x-f.x:e.x-l.x)}return d.apply(this,[].slice.call(arguments,1))})});C(p,"parts-3d/Series.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(b,e){var p=e.addEvent,y=e.pick,w=b.perspective;p(b.Series,"afterTranslate",function(){this.chart.is3d()&&this.translate3dPoints()});b.Series.prototype.translate3dPoints=function(){var b=this.chart,e=y(this.zAxis,b.options.zAxis[0]),p=[],m;for(m=0;m<this.data.length;m++){var q=this.data[m];
if(e&&e.translate){var u=e.logarithmic&&e.val2lin?e.val2lin(q.z):q.z;q.plotZ=e.translate(u);q.isInside=q.isInside?u>=e.min&&u<=e.max:!1}else q.plotZ=0;q.axisXpos=q.plotX;q.axisYpos=q.plotY;q.axisZpos=q.plotZ;p.push({x:q.plotX,y:q.plotY,z:q.plotZ})}b=w(p,b,!0);for(m=0;m<this.data.length;m++)q=this.data[m],e=b[m],q.plotX=e.x,q.plotY=e.y,q.plotZ=e.z}});C(p,"parts-3d/Column.js",[p["parts/Globals.js"],p["parts/Utilities.js"],p["parts/Stacking.js"]],function(b,e,q){function p(b){var a=b.apply(this,[].slice.call(arguments,
1));this.chart.is3d&&this.chart.is3d()&&(a.stroke=this.options.edgeColor||a.fill,a["stroke-width"]=z(this.options.edgeWidth,1));return a}function w(b,a,f){var e=this.chart.is3d&&this.chart.is3d();e&&(this.options.inactiveOtherPoints=!0);b.call(this,a,f);e&&(this.options.inactiveOtherPoints=!1)}function B(b){for(var a=[],f=1;f<arguments.length;f++)a[f-1]=arguments[f];return this.series.chart.is3d()?this.graphic&&"g"!==this.graphic.element.nodeName:b.apply(this,a)}var v=e.addEvent,z=e.pick;e=e.wrap;
var m=b.perspective,x=b.Series,u=b.seriesTypes,A=b.svg;e(u.column.prototype,"translate",function(b){b.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.translate3dShapes()});e(b.Series.prototype,"justifyDataLabel",function(b){return arguments[2].outside3dPlot?!1:b.apply(this,[].slice.call(arguments,1))});u.column.prototype.translate3dPoints=function(){};u.column.prototype.translate3dShapes=function(){var b=this,a=b.chart,f=b.options,e=f.depth,d=(f.stacking?f.stack||0:b.index)*(e+(f.groupZPadding||
1)),c=b.borderWidth%2?.5:0,h;a.inverted&&!b.yAxis.reversed&&(c*=-1);!1!==f.grouping&&(d=0);d+=f.groupZPadding||1;b.data.forEach(function(f){f.outside3dPlot=null;if(null!==f.y){var k=f.shapeArgs,l=f.tooltipPos,g;[["x","width"],["y","height"]].forEach(function(a){g=k[a[0]]-c;0>g&&(k[a[1]]+=k[a[0]]+c,k[a[0]]=-c,g=0);g+k[a[1]]>b[a[0]+"Axis"].len&&0!==k[a[1]]&&(k[a[1]]=b[a[0]+"Axis"].len-k[a[0]]);if(0!==k[a[1]]&&(k[a[0]]>=b[a[0]+"Axis"].len||k[a[0]]+k[a[1]]<=c)){for(var d in k)k[d]=0;f.outside3dPlot=!0}});
"rect"===f.shapeType&&(f.shapeType="cuboid");k.z=d;k.depth=e;k.insidePlotArea=!0;h={x:k.x+k.width/2,y:k.y,z:d+e/2};a.inverted&&(h.x=k.height,h.y=f.clientX);f.plot3d=m([h],a,!0,!1)[0];l=m([{x:l[0],y:l[1],z:d+e/2}],a,!0,!1)[0];f.tooltipPos=[l.x,l.y]}});b.z=d};e(u.column.prototype,"animate",function(b){if(this.chart.is3d()){var a=arguments[1],f=this.yAxis,e=this,d=this.yAxis.reversed;A&&(a?e.data.forEach(function(a){null!==a.y&&(a.height=a.shapeArgs.height,a.shapey=a.shapeArgs.y,a.shapeArgs.height=1,
d||(a.shapeArgs.y=a.stackY?a.plotY+f.translate(a.stackY):a.plotY+(a.negative?-a.height:a.height)))}):(e.data.forEach(function(a){null!==a.y&&(a.shapeArgs.height=a.height,a.shapeArgs.y=a.shapey,a.graphic&&a.graphic.animate(a.shapeArgs,e.options.animation))}),this.drawDataLabels()))}else b.apply(this,[].slice.call(arguments,1))});e(u.column.prototype,"plotGroup",function(b,a,f,e,d,c){"dataLabelsGroup"!==a&&this.chart.is3d()&&(this[a]&&delete this[a],c&&(this.chart.columnGroup||(this.chart.columnGroup=
this.chart.renderer.g("columnGroup").add(c)),this[a]=this.chart.columnGroup,this.chart.columnGroup.attr(this.getPlotBox()),this[a].survive=!0,"group"===a||"markerGroup"===a))&&(arguments[3]="visible");return b.apply(this,Array.prototype.slice.call(arguments,1))});e(u.column.prototype,"setVisible",function(b,a){var f=this,e;f.chart.is3d()&&f.data.forEach(function(d){e=(d.visible=d.options.visible=a="undefined"===typeof a?!z(f.visible,d.visible):a)?"visible":"hidden";f.options.data[f.data.indexOf(d)]=
d.options;d.graphic&&d.graphic.attr({visibility:e})});b.apply(this,Array.prototype.slice.call(arguments,1))});u.column.prototype.handle3dGrouping=!0;v(x,"afterInit",function(){if(this.chart.is3d()&&this.handle3dGrouping){var b=this.options,a=b.grouping,f=b.stacking,e=z(this.yAxis.options.reversedStacks,!0),d=0;if("undefined"===typeof a||a){a=this.chart.retrieveStacks(f);d=b.stack||0;for(f=0;f<a[d].series.length&&a[d].series[f]!==this;f++);d=10*(a.totalStacks-a[d].position)+(e?f:-f);this.xAxis.reversed||
(d=10*a.totalStacks-d)}b.depth=b.depth||25;this.z=this.z||0;b.zIndex=d}});e(u.column.prototype,"pointAttribs",p);e(u.column.prototype,"setState",w);e(u.column.prototype.pointClass.prototype,"hasNewShapeType",B);u.columnrange&&(e(u.columnrange.prototype,"pointAttribs",p),e(u.columnrange.prototype,"setState",w),e(u.columnrange.prototype.pointClass.prototype,"hasNewShapeType",B),u.columnrange.prototype.plotGroup=u.column.prototype.plotGroup,u.columnrange.prototype.setVisible=u.column.prototype.setVisible);
e(x.prototype,"alignDataLabel",function(b,a,f,e,d){var c=this.chart;e.outside3dPlot=a.outside3dPlot;if(c.is3d()&&this.is("column")){var h=this.options,l=z(e.inside,!!this.options.stacking),k=c.options.chart.options3d,q=a.pointWidth/2||0;h={x:d.x+q,y:d.y,z:this.z+h.depth/2};c.inverted&&(l&&(d.width=0,h.x+=a.shapeArgs.height/2),90<=k.alpha&&270>=k.alpha&&(h.y+=a.shapeArgs.width));h=m([h],c,!0,!1)[0];d.x=h.x-q;d.y=a.outside3dPlot?-9E9:h.y}b.apply(this,[].slice.call(arguments,1))});e(q.prototype,"getStackBox",
function(b,a,f,e,d,c,h,q){var k=b.apply(this,[].slice.call(arguments,1));if(a.is3d()&&f.base){var l=+f.base.split(",")[0],g=a.series[l];l=a.options.chart.options3d;g&&g instanceof u.column&&(g={x:k.x+(a.inverted?h:c/2),y:k.y,z:g.options.depth/2},a.inverted&&(k.width=0,90<=l.alpha&&270>=l.alpha&&(g.y+=c)),g=m([g],a,!0,!1)[0],k.x=g.x-c/2,k.y=g.y)}return k})});C(p,"parts-3d/Pie.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(b,e){var q=e.pick;e=e.wrap;var p=b.deg2rad,w=b.seriesTypes,B=b.svg;
e(w.pie.prototype,"translate",function(b){b.apply(this,[].slice.call(arguments,1));if(this.chart.is3d()){var e=this,m=e.options,q=m.depth||0,u=e.chart.options.chart.options3d,v=u.alpha,r=u.beta,a=m.stacking?(m.stack||0)*q:e._i*q;a+=q/2;!1!==m.grouping&&(a=0);e.data.forEach(function(b){var f=b.shapeArgs;b.shapeType="arc3d";f.z=a;f.depth=.75*q;f.alpha=v;f.beta=r;f.center=e.center;f=(f.end+f.start)/2;b.slicedTranslation={translateX:Math.round(Math.cos(f)*m.slicedOffset*Math.cos(v*p)),translateY:Math.round(Math.sin(f)*
m.slicedOffset*Math.cos(v*p))}})}});e(w.pie.prototype.pointClass.prototype,"haloPath",function(b){var e=arguments;return this.series.chart.is3d()?[]:b.call(this,e[1])});e(w.pie.prototype,"pointAttribs",function(b,e,m){b=b.call(this,e,m);m=this.options;this.chart.is3d()&&!this.chart.styledMode&&(b.stroke=m.edgeColor||e.color||this.color,b["stroke-width"]=q(m.edgeWidth,1));return b});e(w.pie.prototype,"drawDataLabels",function(b){if(this.chart.is3d()){var e=this.chart.options.chart.options3d;this.data.forEach(function(b){var m=
b.shapeArgs,q=m.r,v=(m.start+m.end)/2;b=b.labelPosition;var r=b.connectorPosition,a=-q*(1-Math.cos((m.alpha||e.alpha)*p))*Math.sin(v),f=q*(Math.cos((m.beta||e.beta)*p)-1)*Math.cos(v);[b.natural,r.breakAt,r.touchingSliceAt].forEach(function(b){b.x+=f;b.y+=a})})}b.apply(this,[].slice.call(arguments,1))});e(w.pie.prototype,"addPoint",function(b){b.apply(this,[].slice.call(arguments,1));this.chart.is3d()&&this.update(this.userOptions,!0)});e(w.pie.prototype,"animate",function(b){if(this.chart.is3d()){var e=
arguments[1],m=this.options.animation,p=this.center,u=this.group,v=this.markerGroup;B&&(!0===m&&(m={}),e?(u.oldtranslateX=q(u.oldtranslateX,u.translateX),u.oldtranslateY=q(u.oldtranslateY,u.translateY),e={translateX:p[0],translateY:p[1],scaleX:.001,scaleY:.001},u.attr(e),v&&(v.attrSetters=u.attrSetters,v.attr(e))):(e={translateX:u.oldtranslateX,translateY:u.oldtranslateY,scaleX:1,scaleY:1},u.animate(e,m),v&&v.animate(e,m)))}else b.apply(this,[].slice.call(arguments,1))})});C(p,"parts-3d/Scatter.js",
[p["parts/Globals.js"],p["parts/Point.js"],p["parts/Utilities.js"]],function(b,e,q){q=q.seriesType;var p=b.seriesTypes;q("scatter3d","scatter",{tooltip:{pointFormat:"x: <b>{point.x}</b><br/>y: <b>{point.y}</b><br/>z: <b>{point.z}</b><br/>"}},{pointAttribs:function(e){var q=p.scatter.prototype.pointAttribs.apply(this,arguments);this.chart.is3d()&&e&&(q.zIndex=b.pointCameraDistance(e,this.chart));return q},axisTypes:["xAxis","yAxis","zAxis"],pointArrayMap:["x","y","z"],parallelArrays:["x","y","z"],
directTouch:!0},{applyOptions:function(){e.prototype.applyOptions.apply(this,arguments);"undefined"===typeof this.z&&(this.z=0);return this}});""});C(p,"parts-3d/VMLRenderer.js",[p["parts/Globals.js"],p["parts/Utilities.js"]],function(b,e){e=e.addEvent;var q=b.Axis,p=b.SVGRenderer,w=b.VMLRenderer;w&&(b.setOptions({animate:!1}),w.prototype.face3d=p.prototype.face3d,w.prototype.polyhedron=p.prototype.polyhedron,w.prototype.elements3d=p.prototype.elements3d,w.prototype.element3d=p.prototype.element3d,
w.prototype.cuboid=p.prototype.cuboid,w.prototype.cuboidPath=p.prototype.cuboidPath,w.prototype.toLinePath=p.prototype.toLinePath,w.prototype.toLineSegments=p.prototype.toLineSegments,w.prototype.arc3d=function(b){b=p.prototype.arc3d.call(this,b);b.css({zIndex:b.zIndex});return b},b.VMLRenderer.prototype.arc3dPath=b.SVGRenderer.prototype.arc3dPath,e(q,"render",function(){this.sideFrame&&(this.sideFrame.css({zIndex:0}),this.sideFrame.front.attr({fill:this.sideFrame.color}));this.bottomFrame&&(this.bottomFrame.css({zIndex:1}),
this.bottomFrame.front.attr({fill:this.bottomFrame.color}));this.backFrame&&(this.backFrame.css({zIndex:0}),this.backFrame.front.attr({fill:this.backFrame.color}))}))});C(p,"masters/highcharts-3d.src.js",[],function(){})});
//# sourceMappingURL=highcharts-3d.js.map